jobs:

  autoscaler_prevent_scaledown:
    parameters:
      <<: *cluster-parameter
      <<: *channel-notify-parameter
    executor: self_hosted
    environment:
      <<: *env
    steps:
      - checkout_with_retry
      - setup_nix_self_hosted
      - run_bash_command_in_nix:
          cmd_name: Prevent autoscaler scaledown
          cluster: << parameters.cluster >>
          gce_authenticate: true
          cmd: |
            gcloud container node-pools update --cluster cn-${GCP_CLUSTER_BASENAME}net cn-apps-pool --min-nodes=${GCP_CLUSTER_MAX_NODES}
            gcloud container node-pools update --cluster cn-${GCP_CLUSTER_BASENAME}net cn-infra-pool --min-nodes=${GCP_CLUSTER_MAX_NODES}
          cmd_retry_count: 5

  autoscaler_allow_scaledown:
    parameters:
      <<: *cluster-parameter
      <<: *channel-notify-parameter
    executor: self_hosted
    environment:
      <<: *env
    steps:
      - checkout_with_retry
      - setup_nix_self_hosted
      - run_bash_command_in_nix:
          cmd_name: Allow the autoscaler to scaledown
          cluster: << parameters.cluster >>
          gce_authenticate: true
          cmd: |
            gcloud container node-pools update --cluster cn-${GCP_CLUSTER_BASENAME}net cn-apps-pool --min-nodes=${GCP_CLUSTER_MIN_NODES}
            gcloud container node-pools update --cluster cn-${GCP_CLUSTER_BASENAME}net cn-infra-pool --min-nodes=${GCP_CLUSTER_MIN_NODES}
          cmd_retry_count: 5
