jobs:
  backup_cluster:
    parameters:
      <<: *cluster-parameter
      <<: *channel-notify-parameter
      include_sv:
        type: boolean
        default: true
      include_splitwell:
        type: boolean
        default: true
      include_validator1:
        type: boolean
        default: true
      parallelism:
        type: integer
        default: 3
      internal_stack:
        type: boolean
        default: false
      checkout-branch:
        type: string
        default: "" # Default set to $CIRCLE_SHA1
    executor: self_hosted
    environment:
      <<: *env
    parallelism: << parameters.parallelism >>
    steps:
      - checkout_with_retry:
          checkout-branch: << parameters.checkout-branch >>
      - setup_nix_self_hosted
      - export_migration_id:
          cluster: << parameters.cluster >>
      - run_bash_command_in_nix:
          cmd_name: Listing nodes for backup
          cluster: << parameters.cluster >>
          cmd: |
            nodes=""
            if [[ << parameters.include_sv >> != false ]]; then
              if (env-bool IS_DEVNET); then
                nodes="sv-1 sv-2 sv-3 sv-4"
              else
                nodes="sv-1"
              fi
            fi
            if [[ << parameters.include_validator1 >> != false ]]; then
              nodes="$nodes validator1"
            fi
            if [[ << parameters.include_splitwell >> != false ]]; then
              nodes="$nodes splitwell"
            fi
            echo $nodes > nodes.txt
      - run:
          name: Split backup tasks
          command: |
            nodes=$(cat nodes.txt)
            echo "$nodes" | circleci tests run --command "xargs ./.circleci/grab-tests.sh"
            if [ -e tests-to-run.txt ]; then
              echo "Nodes to backup: $(cat tests-to-run.txt)"
            else
              echo "No nodes to backup, stopping"
              circleci-agent step halt
            fi
      - run_bash_command_in_nix:
          cmd_name: Backup nodes
          cluster: << parameters.cluster >>
          gce_authenticate: true
          no_output_timeout: "20m"
          # Note that this'll also mean duplicate backups for the nodes that did succeed, but not worth the extra complexity to avoid that.
          cmd_retry_count: 3
          additional_nix_args: "--keep ACTIVE_MIGRATION_ID"
          cmd: |
            cncluster activate
            # We use readiness of validator-app as an approximation to the node's readiness
            for ns in $(cat tests-to-run.txt); do
              cncluster wait $ns validator-app ${ACTIVE_MIGRATION_ID}
            done
            cncluster backup_nodes ${ACTIVE_MIGRATION_ID} << parameters.internal_stack >> $(cat tests-to-run.txt)
      - print_gcloud_logs_commands:
          cluster: <<parameters.cluster>>
      - notify-cluster-fail:
          cluster: << parameters.cluster >>
          channel_notify: << parameters.channel_notify >>

  backup_status_cluster:
    parameters:
      <<: *cluster-parameter
      <<: *channel-notify-parameter
      namespace_name:
        type: string
        default: "sv-1"
      alert_threshold:
        type: string
        default: "8 hours ago"
    executor: self_hosted
    environment:
      <<: *env
    steps:
      - checkout_with_retry
      - setup_nix_self_hosted
      - export_migration_id:
          cluster: << parameters.cluster >>
      - run_bash_command_in_nix:
          cmd_name: Check backup status
          cluster: << parameters.cluster >>
          gce_authenticate: true
          no_output_timeout: "10m"
          additional_nix_args: "--keep ACTIVE_MIGRATION_ID"
          cmd: .circleci/cn-scripts/check-backups-status.sh "<< parameters.alert_threshold >>" "${GCP_CLUSTER_BASENAME}" "${ACTIVE_MIGRATION_ID}"
      - run:
          name: Add snapshot_array to env
          command: |
            echo "source tmp-snapshots.sh" >> "$BASH_ENV"
      - run:
          name: Notify if backups are old
          command: |
            if [ ${#snapshot_array[@]} -eq 0 ]; then
              echo "Do not notify."
              exit 0
            else
              echo "Notify."
              exit 1
            fi
      - slack/notify:
          channel: << parameters.channel_notify >>
          event: fail
          custom: |
            { "text": ":fire: No backup found in << parameters.cluster >> that are newer than << parameters.alert_threshold >>:\n${snapshot_array[@]}" }

  restore_node:
    executor: self_hosted
    parameters:
      <<: *cluster-parameter
      <<: *channel-notify-parameter
      namespace_name:
        type: string
      internal_stack:
        type: boolean
        default: false
      silence_deployment_alerts:
        type: boolean
        default: false
      checkout-branch:
        type: string
        default: "" # Default set to $CIRCLE_SHA1
    environment:
      <<: *env
    steps:
      - checkout_with_retry:
          checkout-branch: << parameters.checkout-branch >>
      - setup_nix_self_hosted
      - export_migration_id:
          cluster: << parameters.cluster >>
      - run_bash_command_in_nix:
          cmd_name: Restoring node
          cluster: << parameters.cluster >>
          gce_authenticate: true
          no_output_timeout: "20m"
          additional_nix_args: "--keep ACTIVE_MIGRATION_ID"
          cmd_retry_count: 5
          cmd: |
            cncluster activate

            if [[ << parameters.silence_deployment_alerts >> == true ]]; then
              # silence specific alerts that may fire due to reset downtime
              cncluster silence_grafana_alerts "10 minutes" -f "$SPLICE_ROOT/.circleci/silences/deployment_grafana.json"
            fi

            cncluster restore_node --force << parameters.namespace_name >> ${ACTIVE_MIGRATION_ID} << parameters.internal_stack >>

            case "<< parameters.namespace_name >>" in
              "sv-1"|"sv-2"|"sv-3"|"sv-4")
                cncluster wait << parameters.namespace_name >> scan-app ${ACTIVE_MIGRATION_ID}
                cncluster wait << parameters.namespace_name >> sv-app ${ACTIVE_MIGRATION_ID}
                cncluster wait << parameters.namespace_name >> validator-app ${ACTIVE_MIGRATION_ID}
                ;;
              "validator1")
                cncluster wait << parameters.namespace_name >> validator-app ${ACTIVE_MIGRATION_ID}
                ;;
            esac

      - print_gcloud_logs_commands:
          cluster: <<parameters.cluster>>
      - notify-cluster-fail:
          cluster: << parameters.cluster >>
          channel_notify: << parameters.channel_notify >>

  copy_backup_to_bucket_mainnet:
    executor: self_hosted
    parameters:
      <<: *channel-notify-parameter
    environment:
      <<: *env
    steps:
      - checkout_with_retry
      - setup_nix_self_hosted
      - export_migration_id:
          cluster: mainnet
      - run_bash_command_in_nix:
          cmd_name: Copy backup to bucket
          additional_nix_args: "--keep GCP_DA_CN_BACKUPS_KEY --keep ACTIVE_MIGRATION_ID"
          cmd: |
            echo $GCP_DA_CN_BACKUPS_KEY | gcloud auth activate-service-account --key-file=-
            export GOOGLE_CLOUD_PROJECT=da-cn-backups
            today=$(date +%Y-%m-%d)
            gcloud workflows execute copy-cn-backup-to-bucket --project ${GOOGLE_CLOUD_PROJECT} --location us-central1 --data "{\"migrationId\": ${ACTIVE_MIGRATION_ID}, \"beforeDate\": \"$today\"}"
      - notify-cluster-fail:
          cluster: mainnet
          channel_notify: << parameters.channel_notify >>
