jobs:
  deploy_sv_runbook:
    circleci_ip_ranges: true
    docker:
      - image: cimg/base:2024.01
    environment:
      <<: *env
      CIRCLE_TAG: git-<< pipeline.git.revision >>
    parameters:
      <<: *cluster-parameter
      use_published_artifacts:
        type: boolean
        default: false
      deploy_version:
        type: string
        default: ""
      restore_cluster:
        type: boolean
        default: false
      global_domain_migration_id:
        type: integer
        default: 0
      send_deployment_notification:
        type: boolean
        default: true
    steps:
      - checkout_with_retry
      - when:
          condition: << parameters.deploy_version >>
          steps:
            - run:
                name: Checkout commit << parameters.deploy_version >>
                command: git checkout << parameters.deploy_version >>
      - setup_nix
      - run_bash_command_in_nix:
          cmd_name: Build Helm & Pulumi artifacts
          cluster: << parameters.cluster >>
          cmd: |
            make cluster/build
      - run_bash_command_in_nix:
          cmd_name: Apply SV-runbook Kubernetes manifest to cluster
          cluster: << parameters.cluster >>
          additional_nix_args: "--keep AUTH0_SV_MANAGEMENT_API_CLIENT_ID --keep AUTH0_SV_MANAGEMENT_API_CLIENT_SECRET --keep ARTIFACTORY_USER --keep ARTIFACTORY_PASSWORD --keep CIRCLECI_TOKEN --keep CIRCLE_WORKFLOW_ID"
          gce_authenticate: true
          cmd: |
            export GLOBAL_DOMAIN_ACTIVE_MIGRATION_ID=<< parameters.global_domain_migration_id >>
            if [[ << parameters.restore_cluster >> == true ]]; then
              export RESTORE_CLUSTER=1
            fi
            # Note that we allow for RESTORE_CLUSTER to be false while bootstrapping-config is set. This is important for the combined cidaily/cidaily-testnet deployment which needs to restore cidaily-testnet but not cidaily.
            if (env-bool RESTORE_CLUSTER); then
              if [[ -n '<< pipeline.parameters.bootstrapping-config >>' ]]; then
                export BOOTSTRAPPING_CONFIG='<< pipeline.parameters.bootstrapping-config >>'
              fi
            fi
            cncluster activate
            cncluster ci_pdown_sv
            VERSION=""
            if [[ << parameters.use_published_artifacts >> == true ]]; then
              VERSION=$(get-snapshot-version)
            fi
            cncluster ci_apply_sv $VERSION
      - notify-cluster-fail:
          cluster: << parameters.cluster >>
      - when:
          condition: << parameters.send_deployment_notification >>
          steps:
            - notify-cluster-deployment:
                cluster: << parameters.cluster >>

  deploy_validator_runbook:
    circleci_ip_ranges: true
    docker:
      - image: cimg/base:2024.01
    environment:
      <<: *env
      CIRCLE_TAG: git-<< pipeline.git.revision >>
    parameters:
      <<: *cluster-parameter
      use_published_artifacts:
        type: boolean
        default: false
      deploy_version:
        type: string
        default: ""
      restore_cluster:
        type: boolean
        default: false
    steps:
      - checkout_with_retry
      - when:
          condition: << parameters.deploy_version >>
          steps:
            - run:
                name: Checkout commit << parameters.deploy_version >>
                command: git checkout << parameters.deploy_version >>
      - setup_nix
      - run_bash_command_in_nix:
          cmd_name: Build Helm & Pulumi artifacts
          cluster: << parameters.cluster >>
          cmd: |
            make cluster/build
      - run_bash_command_in_nix:
          cmd_name: Apply Validator runbook Kubernetes manifest to cluster
          cluster: << parameters.cluster >>
          additional_nix_args: "--keep AUTH0_VALIDATOR_MANAGEMENT_API_CLIENT_ID --keep AUTH0_VALIDATOR_MANAGEMENT_API_CLIENT_SECRET --keep ARTIFACTORY_USER --keep ARTIFACTORY_PASSWORD --keep CIRCLECI_TOKEN --keep CIRCLE_WORKFLOW_ID"
          gce_authenticate: true
          cmd: |
            if [[ << parameters.restore_cluster >> == true ]]; then
              export RESTORE_CLUSTER=1
            fi
            # Note that we allow for RESTORE_CLUSTER to be false while bootstrapping-config is set. This is important for the combined cidaily/cidaily-testnet deployment which needs to restore cidaily-testnet but not cidaily.
            if (env-bool RESTORE_CLUSTER); then
              if [[ -n '<< pipeline.parameters.bootstrapping-config >>' ]]; then
                export BOOTSTRAPPING_CONFIG='<< pipeline.parameters.bootstrapping-config >>'
              fi
            fi
            cncluster activate
            VERSION=""
            if [[ << parameters.use_published_artifacts >> == true ]]; then
              VERSION=$(get-snapshot-version)
            fi
            cncluster ci_apply_validator $VERSION
      - notify-cluster-fail:
          cluster: << parameters.cluster >>

  deploy_cluster:
    circleci_ip_ranges: true
    docker:
      - image: cimg/base:2024.01
    resource_class: xlarge
    environment:
      <<: *env
      CIRCLE_TAG: git-<< pipeline.git.revision >>
    parameters:
      <<: *cluster-parameter
      restore_cluster:
        type: boolean
        default: false
      deploy_version:
        type: string
        default: ""
      use_published_artifacts:
        type: boolean
        default: false
      update_deployment_branch:
        type: boolean
        default: true
      send_deployment_notification:
        type: boolean
        default: true
      prepare_global_domain_upgrade:
        type: boolean
        default: false
        description: "If true, it will set the env GLOBAL_DOMAIN_PREPARE_UPGRADE to true, and the deployment will attach the required PVC for the global domain migration dump to the sv app"
      global_domain_active_migration_id:
        type: integer
        default: 0
      global_domain_upgrade_migration_id:
        type: integer
        default: 0
      global_domain_legacy_migration_id:
        type: integer
        default: 0
      cancel_workflow_on_failure:
        type: boolean
        default: false

    steps:
      - checkout_with_retry
      - when:
          condition: << parameters.deploy_version >>
          steps:
            - run:
                name: Checkout commit << parameters.deploy_version >>
                command: git checkout << parameters.deploy_version >>
      - setup_nix
      - run_bash_command_in_nix:
          cmd_name: Build Helm & Pulumi artifacts
          # When nix packages changed, nix will rebuild stuff here, and sometimes go silent for long periods of time
          no_output_timeout: "20m"
          cluster: << parameters.cluster >>
          cmd: |
            make cluster/build
          cmd_retry_count: 2
      - run_bash_command_in_nix:
          cmd_name: Apply Pulumi configuration to cluster
          cluster: << parameters.cluster >>
          additional_nix_args: >
            --keep GITHUB_TOKEN
            --keep AUTH0_MANAGEMENT_API_CLIENT_ID
            --keep AUTH0_CN_MANAGEMENT_API_CLIENT_ID
            --keep AUTH0_MANAGEMENT_API_CLIENT_SECRET
            --keep AUTH0_CN_MANAGEMENT_API_CLIENT_SECRET
            --keep AUTH0_SV_MANAGEMENT_API_CLIENT_ID
            --keep AUTH0_SV_MANAGEMENT_API_CLIENT_SECRET
            --keep AUTH0_VALIDATOR_MANAGEMENT_API_CLIENT_ID
            --keep AUTH0_VALIDATOR_MANAGEMENT_API_CLIENT_SECRET
            --keep CIRCLECI_TOKEN
            --keep CIRCLE_WORKFLOW_ID
            --keep K6_USERS_PASSWORD
            --keep K6_VALIDATOR_ADMIN_USERNAME
            --keep K6_VALIDATOR_ADMIN_PASSWORD
            --keep SLACK_ACCESS_TOKEN
          gce_authenticate: true
          cmd: |
            if [[ << parameters.restore_cluster >> == true ]]; then
              export RESTORE_CLUSTER=1
            fi
            # Note that we allow for RESTORE_CLUSTER to be false while bootstrapping-config is set. This is important for the combined cidaily/cidaily-testnet deployment which needs to restore cidaily-testnet but not cidaily.
            if (env-bool RESTORE_CLUSTER); then
              if [[ -n '<< pipeline.parameters.bootstrapping-config >>' ]]; then
                export BOOTSTRAPPING_CONFIG='<< pipeline.parameters.bootstrapping-config >>'
              fi
            fi
            # All CI-deployed clusters use split postgres instances per app, to support backups.
            export SPLIT_POSTGRES_INSTANCES=1
            cncluster activate
            VERSION=""
            if [[ << parameters.use_published_artifacts >> == true ]]; then
              VERSION=$(get-snapshot-version)
            fi
            export CN_NON_SV_NODES="true"
            if [[ << parameters.prepare_global_domain_upgrade >> == true ]]; then
              export CN_NON_SV_NODES="false"
            export GLOBAL_DOMAIN_PREPARE_UPGRADE="true"
            fi
            export GLOBAL_DOMAIN_ACTIVE_MIGRATION_ID=<< parameters.global_domain_active_migration_id >>
            if [[ << parameters.global_domain_upgrade_migration_id >> -ne 0 ]]; then
              export GLOBAL_DOMAIN_PREPARE_UPGRADE="true"
              export CN_NON_SV_NODES="false"
              export GLOBAL_DOMAIN_UPGRADE_MIGRATION_ID=<< parameters.global_domain_upgrade_migration_id >>
              if [[ << parameters.global_domain_legacy_migration_id >> -ne 0 ]]; then
                export GLOBAL_DOMAIN_LEGACY_MIGRATION_ID=<< parameters.global_domain_legacy_migration_id >>
              fi
              cncluster ci_apply --skip-reset
            elif [[ << parameters.global_domain_active_migration_id >> -ne 0 ]]; then
              cncluster ci_apply --skip-reset
            elif [[ << pipeline.parameters.reset-before-deploy >> == true ]]; then
              cncluster ci_apply
            else
              cncluster ci_apply --skip-reset
            fi
      - when:
          condition: << parameters.update_deployment_branch >>
          steps:
            - run_bash_command_in_nix:
                cmd_name: Update deployment branch for cluster
                cluster: << parameters.cluster >>
                additional_nix_args: "--keep GITHUB_TOKEN"
                cmd: |
                  # deployment/scratch* branches break our deployment, so we guard against accidentally creating those here
                  # This is a safeguard against people manually running e.g. deploy_devnet on a scratchnet.
                  if [[ << parameters.cluster >> != scratch* ]]; then
                    scripts/update-deployment-branch.sh "<< parameters.cluster >>" HEAD
                  else
                    echo "NOTE: skipping deployment branch update for scratchnet cluster << parameters.cluster >>"
                  fi
                cmd_retry_count: 5
      - notify-cluster-fail:
          cluster: << parameters.cluster >>
      - when:
          condition: << parameters.send_deployment_notification >>
          steps:
            - notify-cluster-deployment:
                cluster: << parameters.cluster >>
      - when:
          condition: << parameters.cancel_workflow_on_failure >>
          steps:
            - cancel_entire_workflow_if_this_job_failed

  reset_cluster:
    parameters:
      <<: *cluster-parameter
      channel_notify:
        type: string
        # #team-canton-network-internal-ci
        default: C05DT77QF5M
    machine:
      image: ubuntu-2204:2024.01.1
    environment:
      <<: *env
      VPN_HOST_NAME: vpn-cn-devnet.da-int.net
      VPN_HOST_IP: 34.132.91.75
    steps:
      - checkout_with_retry
      - setup_nix
      - setup_vpn
      - setup_vpn_routes:
          cluster: << parameters.cluster >>
      - run_bash_command_in_nix:
          cmd_name: Reset Cluster and Free Lock (if on scratch*)
          cluster: << parameters.cluster >>
          additional_nix_args: "--keep AUTH0_SV_MANAGEMENT_API_CLIENT_ID --keep AUTH0_SV_MANAGEMENT_API_CLIENT_SECRET \
            --keep VPN_HOST_NAME --keep VPN_USER --keep VPN_PASSWORD --keep VPN_HOST_IP"
          gce_authenticate: true
          cmd: |
            cncluster activate
            cncluster ci_reset_unlock
          cmd_retry_condition: $(if curl --connect-timeout 5 -s ${GCP_CLUSTER_BASENAME}.network.canton.global; then echo "false"; else echo "true"; fi)
          cmd_retry_count: 2
          cmd_before_retry: |-
            echo "VPN connection seems to have died, restarting VPN and retrying..."
            /tmp/vpn-scripts/restart-vpn.sh
            cncluster prefresh
