jobs:
  hard_migration:
    circleci_ip_ranges: true
    docker:
      - image: cimg/base:2024.01
    environment:
      <<: *env
      CIRCLE_TAG: git-<< pipeline.git.revision >>
    parameters:
      <<: *cluster-parameter
      <<: *channel-notify-parameter
      # What to do
      action:
        type: enum
        enum:
          [
            "prepare",
            "migrate"
          ]
      # What to migrate
      scope:
        type: enum
        enum:
          [
            "all",
            "core",
            "sv",
            "validator"
          ]
      # Commit hash that will become the legacy version.
      # If left empty then the latest commit on the branch will be used, with locally-built charts.
      base_version:
        type: string
        default: ""
      # Commit hash that will become the active version.
      # If left empty then the latest commit on the branch will be used, with locally-built charts.
      upgrade_version:
        type: string
        default: ""
      cancel_workflow_on_failure:
        type: boolean
        default: false
    steps:
      - checkout_with_retry
      - when:
          condition: << parameters.upgrade_version >>
          steps:
            - run:
                name: Checkout commit << parameters.upgrade_version >>
                command: |
                  echo "Checking out commit << parameters.upgrade_version >>"
                  git checkout << parameters.upgrade_version >>
      - setup_nix
      - run_bash_command_in_nix:
          cmd_name: Build Helm & Pulumi artifacts for upgrade version
          cluster: << parameters.cluster >>
          cmd: |
            make cluster/build
          cmd_retry_count: 2
      - run_bash_command_in_nix:
          cmd_name: Execute hard domain migration action
          cluster: << parameters.cluster >>
          additional_nix_args: >
            --keep AUTH0_MANAGEMENT_API_CLIENT_ID
            --keep AUTH0_MANAGEMENT_API_CLIENT_SECRET
            --keep AUTH0_CN_MANAGEMENT_API_CLIENT_ID
            --keep AUTH0_CN_MANAGEMENT_API_CLIENT_SECRET
            --keep AUTH0_SV_MANAGEMENT_API_CLIENT_ID
            --keep AUTH0_SV_MANAGEMENT_API_CLIENT_SECRET
            --keep AUTH0_VALIDATOR_MANAGEMENT_API_CLIENT_ID
            --keep AUTH0_VALIDATOR_MANAGEMENT_API_CLIENT_SECRET
            --keep ARTIFACTORY_USER
            --keep ARTIFACTORY_PASSWORD
            --keep CIRCLECI_TOKEN
            --keep CIRCLE_WORKFLOW_ID
            --keep SLACK_ACCESS_TOKEN
          gce_authenticate: true
          cmd: |
            set -eou pipefail
            if [ -z "<< parameters.upgrade_version >>" ]; then
              upgrade_version="local"
            else
              upgrade_version=$(git describe --tags --match "*-snapshot.*" --abbrev=0 "<< parameters.upgrade_version >>")
            fi
            if [ -z "<< parameters.base_version >>" ]; then
              base_version="local"
            else
              base_version=$(git describe --tags --match "*-snapshot.*" --abbrev=0 "<< parameters.base_version >>")
            fi
            # All CI-deployed clusters use split postgres instances per app, to support backups.
            export SPLIT_POSTGRES_INSTANCES=true

            cncluster activate
            cncluster hard_domain_migration_<< parameters.action >> << parameters.scope >> $base_version $upgrade_version --yes --skip-preview
      - notify-cluster-fail:
          channel_notify: << parameters.channel_notify >>
          cluster: << parameters.cluster >>
      - when:
          condition: << parameters.cancel_workflow_on_failure >>
          steps:
            - cancel_entire_workflow_if_this_job_failed

  hard_migration_vpn:
    machine:
      image: ubuntu-2204:2024.01.1
    environment:
      <<: *env
      CIRCLE_TAG: git-<< pipeline.git.revision >>
      VPN_HOST_NAME: vpn-cn-devnet.da-int.net
      VPN_HOST_IP: 34.132.91.75
    parameters:
      <<: *cluster-parameter
      <<: *channel-notify-parameter
      # What to do
      action:
        type: enum
        enum:
          [
            "prepare",
            "migrate"
          ]
      # What to migrate
      scope:
        type: enum
        enum:
          [
            # currently using the _vpn job makes sense only for the sv runbook
            # where VPN is required to resolve Validator1's PartyId
            "sv",
          ]
      # Commit hash that will become the legacy version.
      # If left empty then the latest commit on the branch will be used, with locally-built charts.
      base_version:
        type: string
        default: ""
      # Commit hash that will become the active version.
      # If left empty then the latest commit on the branch will be used, with locally-built charts.
      upgrade_version:
        type: string
        default: ""
      cancel_workflow_on_failure:
        type: boolean
        default: false
    steps:
      - checkout_with_retry
      - when:
          condition: << parameters.upgrade_version >>
          steps:
            - run:
                name: Checkout commit << parameters.upgrade_version >>
                command: |
                  echo "Checking out commit << parameters.upgrade_version >>"
                  git checkout << parameters.upgrade_version >>
      - setup_nix
      - run_bash_command_in_nix:
          cmd_name: Build Helm & Pulumi artifacts for upgrade version
          cluster: << parameters.cluster >>
          cmd: |
            make cluster/build
          cmd_retry_count: 2
      - setup_vpn
      - setup_vpn_routes:
          cluster: << parameters.cluster >>
      - run_bash_command_in_nix:
          cmd_name: Execute hard domain migration action
          cluster: << parameters.cluster >>
          additional_nix_args: >
            --keep AUTH0_MANAGEMENT_API_CLIENT_ID
            --keep AUTH0_MANAGEMENT_API_CLIENT_SECRET
            --keep AUTH0_CN_MANAGEMENT_API_CLIENT_ID
            --keep AUTH0_CN_MANAGEMENT_API_CLIENT_SECRET
            --keep AUTH0_SV_MANAGEMENT_API_CLIENT_ID
            --keep AUTH0_SV_MANAGEMENT_API_CLIENT_SECRET
            --keep AUTH0_VALIDATOR_MANAGEMENT_API_CLIENT_ID
            --keep AUTH0_VALIDATOR_MANAGEMENT_API_CLIENT_SECRET
            --keep ARTIFACTORY_USER
            --keep ARTIFACTORY_PASSWORD
            --keep CIRCLECI_TOKEN
            --keep CIRCLE_WORKFLOW_ID
            --keep SLACK_ACCESS_TOKEN
          gce_authenticate: true
          cmd: |
            set -eou pipefail
            if [ -z "<< parameters.upgrade_version >>" ]; then
              upgrade_version="local"
            else
              # gives us the latest tag that looks like a release tag (e.g. 1.2.3)
              upgrade_version=$(git describe --tags --match "[0-9][0-9\.][0-9\.]*" --abbrev=0 "<< parameters.upgrade_version >>")
            fi
            if [ -z "<< parameters.base_version >>" ]; then
              base_version="local"
            else
              # gives us the latest tag that looks like a release tag (e.g. 1.2.3)
              base_version=$(git describe --tags --match "[0-9][0-9\.][0-9\.]*" --abbrev=0 "<< parameters.base_version >>")
            fi
            # All CI-deployed clusters use split postgres instances per app, to support backups.
            export SPLIT_POSTGRES_INSTANCES=true

            cncluster activate
            cncluster hard_domain_migration_<< parameters.action >> << parameters.scope >> $base_version $upgrade_version --yes --skip-preview
      - notify-cluster-fail:
          channel_notify: << parameters.channel_notify >>
          cluster: << parameters.cluster >>
      - when:
          condition: << parameters.cancel_workflow_on_failure >>
          steps:
            - cancel_entire_workflow_if_this_job_failed
