jobs:
  deploy_operator:
    executor: self_hosted
    environment:
      <<: *env
      CIRCLE_TAG: git-<< pipeline.git.revision >>
    parameters:
      <<: *cluster-parameter
      deploy_retry_count:
        type: integer
        default: 2
    steps:
      - checkout_with_retry
      - setup_nix_self_hosted
      - deploy_operator:
          cluster: << parameters.cluster >>
          deploy_retry_count: << parameters.deploy_retry_count >>
