jobs:
  preview_pulumi_changes:
    parameters:
      <<: *cluster-parameter
      deployment_only:
        type: boolean
    executor: self_hosted
    environment:
      <<: *env
    steps:
      - checkout_with_retry
      - setup_nix_self_hosted
      - set_pr_target_branch
      - run_bash_command_in_nix:
          cmd_name: Install pulumi dependencies
          cluster: << parameters.cluster >>
          cmd: |
            make -j cluster/pulumi/build
          cmd_retry_count: 2
      - when:
          condition:
            not: << parameters.deployment_only >>
          steps:
            - preview_pulumi:
                cluster: << parameters.cluster >>
                project: "canton-network"
            - preview_pulumi:
                cluster: << parameters.cluster >>
                project: "infra"
            - preview_pulumi:
                cluster: << parameters.cluster >>
                project: "sv-canton"
            - preview_pulumi:
                cluster: << parameters.cluster >>
                project: "sv-runbook"
                when_env: "SPLICE_DEPLOY_SV_RUNBOOK"
            - preview_pulumi:
                cluster: << parameters.cluster >>
                project: "multi-validator"
                when_env: "SPLICE_DEPLOY_MULTI_VALIDATOR"
            - preview_pulumi:
                cluster: << parameters.cluster >>
                project: "validator-runbook"
                when_env: "SPLICE_DEPLOY_VALIDATOR_RUNBOOK"
      - when:
          condition: << parameters.deployment_only >>
          steps:
            - preview_pulumi:
                cluster: << parameters.cluster >>
                project: "deployment"
