jobs:
  reset_cluster:
    executor: self_hosted
    parameters:
      <<: *cluster-parameter
      <<: *channel-notify-parameter
      unlock_shared_cluster:
        type: boolean
        default: true
      silence_deployment_alerts:
        type: boolean
        default: false
      extra_migrations_reset:
        type: string
        default: ""
    environment:
      <<: *env
    steps:
      - checkout_with_retry
      - setup_nix_self_hosted
      - run_bash_command_in_nix:
          cmd_name: "Install pulumi packages" #required for ts-node to reset sv-canton stacks
          # When nix packages changed, nix will rebuild stuff here, and sometimes go silent for long periods of time
          no_output_timeout: "20m"
          cluster: << parameters.cluster >>
          cmd: |
            make -j cluster/pulumi/build
          cmd_retry_count: 2
      - run_bash_command_in_nix:
          cmd_name: Reset Cluster and Free Lock (if on scratch*)
          cluster: << parameters.cluster >>
          additional_nix_args: "--keep AUTH0_SV_MANAGEMENT_API_CLIENT_ID --keep AUTH0_SV_MANAGEMENT_API_CLIENT_SECRET \
            --keep VPN_HOST_NAME --keep VPN_USER --keep VPN_PASSWORD --keep VPN_HOST_IP --keep CIRCLECI_TOKEN --keep CIRCLE_WORKFLOW_ID --keep CIRCLE_BUILD_URL --keep SLACK_ACCESS_TOKEN"
          gce_authenticate: true
          cmd: |
            cncluster activate

            if [ -n "<< parameters.extra_migrations_reset >>" ]; then
              export GLOBAL_DOMAIN_SV_CANTON_EXTRA_MIGRATIONS_RESET='<< parameters.extra_migrations_reset >>'
            fi

            if [[ << parameters.silence_deployment_alerts >> == true ]]; then
              # silence specific alerts that may fire due to reset downtime
              cncluster silence_grafana_alerts "10 minutes" -f "$REPO_ROOT/.circleci/silences/deployment_grafana.json"
            fi

            if [[ << parameters.cluster >> =~ scratch* ]] && [[ << parameters.unlock_shared_cluster >> == true ]]; then
              cncluster ci_reset_unlock
            else
              cncluster reset
            fi
          cmd_retry_count: 3
          cmd_before_retry: .circleci/post-slack-message.sh "Reset of cluster << parameters.cluster >> failed. Retrying... ( <${CIRCLE_BUILD_URL}|CI Build> )"
      - notify-cluster-fail:
          channel_notify: << parameters.channel_notify >>
          cluster: << parameters.cluster >>

  reset_sv_runbook:
    executor: self_hosted
    environment:
      <<: *env
      CIRCLE_TAG: git-<< pipeline.git.revision >>
    parameters:
      <<: *cluster-parameter
      <<: *channel-notify-parameter
      unprotect_dbs:
        type: boolean
        default: false
      silence_deployment_alerts:
        type: boolean
        default: false
      extra_migrations_reset:
        type: string
        default: ""
    steps:
      - checkout_with_retry
      - setup_nix_self_hosted
      - run_bash_command_in_nix:
          cmd_name: Build Helm & Pulumi artifacts
          cluster: << parameters.cluster >>
          cmd: |
            make -j cluster/build
          cmd_retry_count: 2
      - run_bash_command_in_nix:
          cmd_name: Reset SV runbook
          cluster: << parameters.cluster >>
          gce_authenticate: true
          cmd: |
            cncluster activate
            if [[ << parameters.unprotect_dbs >> == true ]]; then
              cncluster unprotect_dbs sv
            fi

            if [ -n "<< parameters.extra_migrations_reset >>" ]; then
              export GLOBAL_DOMAIN_SV_CANTON_EXTRA_MIGRATIONS_RESET='<< parameters.extra_migrations_reset >>'
            fi

            if [[ << parameters.silence_deployment_alerts >> == true ]]; then
              # silence specific alerts that may fire due to reset downtime
              cncluster silence_grafana_alerts "20 minutes" -f "$REPO_ROOT/.circleci/silences/deployment_grafana.json"
            fi

            cncluster ci_pdown_sv
          cmd_retry_count: 3
      - notify-cluster-fail:
          channel_notify: << parameters.channel_notify >>
          cluster: << parameters.cluster >>

  reset_validator_runbook:
    executor: self_hosted
    environment:
      <<: *env
      CIRCLE_TAG: git-<< pipeline.git.revision >>
    parameters:
      <<: *cluster-parameter
      <<: *channel-notify-parameter
      silence_deployment_alerts:
        type: boolean
        default: false
    steps:
      - checkout_with_retry
      - setup_nix_self_hosted
      - run_bash_command_in_nix:
          cmd_name: Build Helm & Pulumi artifacts
          cluster: << parameters.cluster >>
          cmd: |
            make -j cluster/build
          cmd_retry_count: 2
      - run_bash_command_in_nix:
          cmd_name: Reset validator runbook
          cluster: << parameters.cluster >>
          gce_authenticate: true
          cmd: |
            cncluster activate
            if [[ << parameters.silence_deployment_alerts >> == true ]]; then
              # silence specific alerts that may fire due to reset downtime
              cncluster silence_grafana_alerts "20 minutes" -f "$REPO_ROOT/.circleci/silences/deployment_grafana.json"
            fi
            cncluster ci_pdown_validator
          cmd_retry_count: 3
      - notify-cluster-fail:
          channel_notify: << parameters.channel_notify >>
          cluster: << parameters.cluster >>
