jobs:
  reset_sv_runbook:
    machine:
      image: ubuntu-2204:2024.01.1
    environment:
      <<: *env
      CIRCLE_TAG: git-<< pipeline.git.revision >>
      VPN_HOST_NAME: vpn-cn-devnet.da-int.net
      VPN_HOST_IP: 34.132.91.75
    parameters:
      <<: *cluster-parameter
      <<: *channel-notify-parameter
      send_deployment_notification:
        type: boolean
        default: true
    steps:
      - checkout_with_retry
      - setup_nix
      - run_bash_command_in_nix:
          cmd_name: Build Helm & Pulumi artifacts
          cluster: << parameters.cluster >>
          cmd: |
            make -j cluster/build
          cmd_retry_count: 2
      - run_bash_command_in_nix:
          cmd_name: Reset SV runbook
          cluster: << parameters.cluster >>
          gce_authenticate: true
          cmd: |
            cncluster activate
            cncluster ci_pdown_sv
      - notify-cluster-fail:
          channel_notify: << parameters.channel_notify >>
          cluster: << parameters.cluster >>
      - when:
          condition: << parameters.send_deployment_notification >>
          steps:
            - notify-cluster-reset:
                channel_notify: << parameters.channel_notify >>
                cluster: << parameters.cluster >>
