jobs:

  reset_cluster:
    parameters:
      <<: *cluster-parameter
      <<: *channel-notify-parameter
      is_shared_cluster:
        type: boolean
        default: true
      silence_deployment_alerts:
        type: boolean
        default: false
    machine:
      image: ubuntu-2204:2024.01.1
    environment:
      <<: *env
      VPN_HOST_NAME: vpn-cn-devnet.da-int.net
      VPN_HOST_IP: 34.132.91.75
    steps:
      - checkout_with_retry
      - setup_nix
      - setup_vpn
      - setup_vpn_routes:
          cluster: << parameters.cluster >>
      - run_bash_command_in_nix:
          cmd_name: Reset Cluster and Free Lock (if on scratch*)
          cluster: << parameters.cluster >>
          additional_nix_args: "--keep AUTH0_SV_MANAGEMENT_API_CLIENT_ID --keep AUTH0_SV_MANAGEMENT_API_CLIENT_SECRET \
            --keep VPN_HOST_NAME --keep VPN_USER --keep VPN_PASSWORD --keep VPN_HOST_IP"
          gce_authenticate: true
          cmd: |
            cncluster activate

            if [[ << parameters.silence_deployment_alerts >> == true ]]; then
              # silence specific alerts that may fire due to reset downtime
              cncluster silence_grafana_alerts "10 minutes" -f "$REPO_ROOT/.circleci/silences/deployment_grafana.json"
            fi

            if [[ << parameters.is_shared_cluster >> == true ]]; then
              cncluster ci_reset_unlock
            else
              cncluster reset
            fi
          cmd_retry_condition: $(if curl --connect-timeout 5 -s ${GCP_CLUSTER_HOSTNAME}; then echo "false"; else echo "true"; fi)
          cmd_retry_count: 2
          cmd_before_retry: |-
            echo "VPN connection seems to have died, restarting VPN and retrying..."
            /tmp/vpn-scripts/restart-vpn.sh
            cncluster prefresh

  reset_sv_runbook:
    machine:
      image: ubuntu-2204:2024.01.1
    environment:
      <<: *env
      CIRCLE_TAG: git-<< pipeline.git.revision >>
      VPN_HOST_NAME: vpn-cn-devnet.da-int.net
      VPN_HOST_IP: 34.132.91.75
    parameters:
      <<: *cluster-parameter
      <<: *channel-notify-parameter
    steps:
      - checkout_with_retry
      - setup_nix
      - setup_vpn
      - setup_vpn_routes:
          cluster: << parameters.cluster >>
      - run_bash_command_in_nix:
          cmd_name: Build Helm & Pulumi artifacts
          cluster: << parameters.cluster >>
          cmd: |
            make -j cluster/build
          cmd_retry_count: 2
      - run_bash_command_in_nix:
          cmd_name: Reset SV runbook
          cluster: << parameters.cluster >>
          gce_authenticate: true
          cmd: |
            cncluster activate
            cncluster ci_pdown_sv
          cmd_retry_count: 3
      - notify-cluster-fail:
          channel_notify: << parameters.channel_notify >>
          cluster: << parameters.cluster >>

  reset_validator_runbook:
    machine:
      image: ubuntu-2204:2024.01.1
    environment:
      <<: *env
      CIRCLE_TAG: git-<< pipeline.git.revision >>
      VPN_HOST_NAME: vpn-cn-devnet.da-int.net
      VPN_HOST_IP: 34.132.91.75
    parameters:
      <<: *cluster-parameter
      <<: *channel-notify-parameter
    steps:
      - checkout_with_retry
      - setup_nix
      - setup_vpn
      - setup_vpn_routes:
          cluster: << parameters.cluster >>
      - run_bash_command_in_nix:
          cmd_name: Build Helm & Pulumi artifacts
          cluster: << parameters.cluster >>
          cmd: |
            make -j cluster/build
          cmd_retry_count: 2
      - run_bash_command_in_nix:
          cmd_name: Reset validator runbook
          cluster: << parameters.cluster >>
          gce_authenticate: true
          cmd: |
            cncluster activate
            cncluster ci_pdown_validator
          cmd_retry_count: 3
      - notify-cluster-fail:
          channel_notify: << parameters.channel_notify >>
          cluster: << parameters.cluster >>
