jobs:
  deploy_validator_to_recover_sv_amulets:
    executor: self_hosted
    environment:
      <<: *env
      CIRCLE_TAG: git-<< pipeline.git.revision >>
    parameters:
      <<: *cluster-parameter
      <<: *channel-notify-parameter
      use_published_artifacts:
        type: boolean
        default: false
      restore_cluster:
        type: boolean
        default: false
      reset_cluster:
        type: boolean
        default: true
      validator_party_hint:
        type: string
        default: ""
      validator_new_participant_id:
        type: string
        default: ""
      restore_identity_from_sv_runbook:
        type: boolean
        default: false
      deploy_retry_count:
        type: integer
        default: 2
    steps:
      - checkout_with_retry
      - setup_nix_self_hosted
      - run_bash_command_in_nix:
          cmd_name: Build Helm & Pulumi artifacts
          cluster: << parameters.cluster >>
          cmd: |
            make -j cluster/build
          cmd_retry_count: 2
      - when:
          condition:
            and:
              - equal: [ true, <<pipeline.parameters.reset-before-deploy>> ]
              - equal: [ true, <<parameters.reset_cluster>> ]
          steps:
            - run_bash_command_in_nix:
                cmd_name: Reset Validator runbook
                cluster: << parameters.cluster >>
                gce_authenticate: true
                cmd: |
                  cncluster activate
                  cncluster ci_pdown_validator
      - run_bash_command_in_nix:
          cmd_name: Apply Validator runbook Kubernetes manifest to cluster
          cluster: << parameters.cluster >>
          additional_nix_args: "--keep AUTH0_VALIDATOR_MANAGEMENT_API_CLIENT_ID \
            --keep AUTH0_VALIDATOR_MANAGEMENT_API_CLIENT_SECRET \
            --keep AUTH0_SV_MANAGEMENT_API_CLIENT_ID \
            --keep AUTH0_SV_MANAGEMENT_API_CLIENT_SECRET \
            --keep ARTIFACTORY_USER \
            --keep ARTIFACTORY_PASSWORD
            --keep CIRCLECI_TOKEN \
            --keep CIRCLE_WORKFLOW_ID \
            --keep SLACK_ACCESS_TOKEN \
            --keep CIRCLE_BUILD_URL"
          gce_authenticate: true
          cmd_retry_count: << parameters.deploy_retry_count >>

          cmd: |
            VERSION=""
            if [[ << parameters.use_published_artifacts >> == true ]]; then
              VERSION=$(get-snapshot-version)
            fi

            if [[ -n '<< parameters.validator_party_hint >>' ]]; then
              echo "setting validator party hint << parameters.validator_party_hint >>"
              export VALIDATOR_PARTY_HINT='<< parameters.validator_party_hint >>'
            fi
            if [[ -n '<< parameters.validator_new_participant_id >>' ]]; then
              echo "using validator new participant id << parameters.validator_new_participant_id >>"
              export VALIDATOR_NEW_PARTICIPANT_ID='<< parameters.validator_new_participant_id >>'
              export VALIDATOR_MIGRATE_PARTY='true'
            fi
            if [[ << parameters.restore_identity_from_sv_runbook >> == true ]]; then
              echo "restoring identity from sv runbook"
              token=$(cncluster get_token sv validator)
              id=$(curl -s "https://wallet.sv.${GCP_CLUSTER_HOSTNAME}/api/validator/v0/admin/participant/identities" -H "authorization: Bearer ${token}")
              echo "$id" > id.json
              export PARTICIPANT_IDENTITIES_FILE=$(readlink -f id.json)
            fi

            cncluster activate

            # TODO(#12776): remove this once the flow is more robust to ACS changes
            # TODO(#11769): if we activate alerting on ciperiodic we might want to add a silencing here
            echo "scaling down validator1 to prevent it from tainting the SV party's ACS"
            kubectl scale deployment --replicas=0 -n validator1 validator-app

            cncluster ci_apply_validator $VERSION

            echo "scaling validator1 back up"
            kubectl scale deployment --replicas=1 -n validator1 validator-app
      - notify-cluster-fail:
          channel_notify: << parameters.channel_notify >>
          cluster: << parameters.cluster >>
