jobs:
  deploy_validator_to_recover_sv_amulets:
    machine:
      image: ubuntu-2204:2024.01.1
    environment:
      <<: *env
      CIRCLE_TAG: git-<< pipeline.git.revision >>
      VPN_HOST_NAME: vpn-cn-devnet.da-int.net
      VPN_HOST_IP: 34.132.91.75
    parameters:
      <<: *cluster-parameter
      <<: *channel-notify-parameter
      use_published_artifacts:
        type: boolean
        default: false
      restore_cluster:
        type: boolean
        default: false
      reset_cluster:
        type: boolean
        default: true
      validator_party_hint:
        type: string
        default: ""
      validator_new_participant_id:
        type: string
        default: ""
      restore_identity_from_sv_runbook:
        type: boolean
        default: false
    steps:
      - checkout_with_retry
      - setup_nix
      - run_bash_command_in_nix:
          cmd_name: Build Helm & Pulumi artifacts
          cluster: << parameters.cluster >>
          cmd: |
            make -j cluster/build
          cmd_retry_count: 2
      - setup_vpn # VPN is required to get sv runbook identities
      - setup_vpn_routes:
          cluster: << parameters.cluster >>
      - when:
          condition:
            and:
              - equal: [ true, <<pipeline.parameters.reset-before-deploy>> ]
              - equal: [ true, <<parameters.reset_cluster>> ]
          steps:
            - run_bash_command_in_nix:
                cmd_name: Reset Validator runbook
                cluster: << parameters.cluster >>
                gce_authenticate: true
                cmd: |
                  cncluster activate
                  cncluster ci_pdown_validator
      - run_bash_command_in_nix:
          cmd_name: Apply Validator runbook Kubernetes manifest to cluster
          cluster: << parameters.cluster >>
          additional_nix_args: "--keep AUTH0_VALIDATOR_MANAGEMENT_API_CLIENT_ID --keep AUTH0_VALIDATOR_MANAGEMENT_API_CLIENT_SECRET --keep ARTIFACTORY_USER --keep ARTIFACTORY_PASSWORD --keep CIRCLECI_TOKEN --keep CIRCLE_WORKFLOW_ID"
          gce_authenticate: true
          cmd: |
            if [[ << parameters.restore_cluster >> == true ]]; then
              export RESTORE_CLUSTER=1
            fi
            # Note that we allow for RESTORE_CLUSTER to be false while bootstrapping-config is set. This is important for the combined cidaily/cidaily-testnet deployment which needs to restore cidaily-testnet but not cidaily.
            if (env-bool RESTORE_CLUSTER); then
              if [[ -n '<< pipeline.parameters.bootstrapping-config >>' ]]; then
                export BOOTSTRAPPING_CONFIG='<< pipeline.parameters.bootstrapping-config >>'
              fi
            fi

            VERSION=""
            if [[ << parameters.use_published_artifacts >> == true ]]; then
              VERSION=$(get-snapshot-version)
            fi

            if [[ -n '<< parameters.validator_party_hint >>' ]]; then
              echo "setting validator party hint << parameters.validator_party_hint >>"
              export VALIDATOR_PARTY_HINT='<< parameters.validator_party_hint >>'
            fi
            if [[ -n '<< parameters.validator_new_participant_id >>' ]]; then
              echo "using validator new participant id << parameters.validator_new_participant_id >>"
              export VALIDATOR_NEW_PARTICIPANT_ID='<< parameters.validator_new_participant_id >>'
              export VALIDATOR_MIGRATE_PARTY='true'
            fi
            if [[ << parameters.restore_identity_from_sv_runbook >> == true ]]; then
              echo "restoring identity from sv runbook"
              token=$(cncluster get_token sv)
              id=$(curl -s "https://wallet.sv.${GCP_CLUSTER_HOSTNAME}/api/validator/v0/admin/participant/identities" -H "authorization: Bearer ${token}")
              echo "$id" > id.json
              export PARTICIPANT_IDENTITIES_FILE=$(readlink -f id.json)
            fi

            cncluster activate

            # TODO(#12776): remove this once the flow is more robust to ACS changes
            # TODO(#11769): if we activate alerting on ciperiodic we might want to add a silencing here
            echo "scaling down validator1 to prevent it from tainting the SV party's ACS"
            kubectl scale deployment --replicas=0 -n validator1 validator-app

            cncluster ci_apply_validator $VERSION

            echo "scaling validator1 back up"
            kubectl scale deployment --replicas=1 -n validator1 validator-app
      - notify-cluster-fail:
          channel_notify: << parameters.channel_notify >>
          cluster: << parameters.cluster >>
