// Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

package org.lfdecentralizedtrust.splice.validator.store.db

/** Defines the table and row data model for storing the Scan node configuration.
  * This is an internal store, separate from the main ACS tables.
  */

object ScanConfigTables {

  /** The name of the table created by V050__validator_local.sql. */
  val tableName: String = "validator_scan_config"

  /** Represents a row in the validator_scan_config table.
    * We omit the 'id' (SERIAL PRIMARY KEY) in this case class as it is auto-generated by the DB
    * @param svName The Synchronizer Vendor (SV) name of the scan node.
    * @param scanUrl The public URL where the scan node can be reached.
    */
  case class ScanConfigRow(
      svName: String,
      scanUrl: String,
  )
}
