cluster:
  imageTag: IMAGE_TAG
imageRepo: "digitalasset-canton-network-docker.jfrog.io/digitalasset"
resources:
  limits:
    cpu: "2"
    memory: 8Gi
  requests:
    cpu: "2"
    memory: 8Gi

db:
  volumeSize: 240Gi
  volumeStorageClass: standard-rwo
  pvcTemplateName: pg-data

postgresSecretName: "postgres-secrets"
