_client_credentials_auth_config {
  type = "client-credentials"
  well-known-config-url = ${?CN_APP_WALLET_LEDGER_API_AUTH_URL}
  client-id = ${?CN_APP_WALLET_LEDGER_API_AUTH_CLIENT_ID}
  client-secret = ${?CN_APP_WALLET_LEDGER_API_AUTH_CLIENT_SECRET}
  # TODO(#1837) use actual audience of the target participant
  audience = "https://canton.network.global"
}

_participant_remote {
  admin-api = {
    address = "validator1-participant"
    port = 5002
  }

  ledger-api = {
    client-config = {
      address = "validator1-participant"
      port = 5001
    }
    auth-config = ${_client_credentials_auth_config}
  }
}

_validator_remote {
  admin-api.port = 5103
  admin-api.address = "validator1-validator-app"
}

_scan_remote {
  admin-api.port = 5012
  admin-api.address = "scan-app"
}

canton {
  wallet-app-backends {
    validator1_wallet_backend {
      storage.type = memory
      admin-api = {
        address = "0.0.0.0"
        port = 5104
      }
      remote-participant = ${_participant_remote}
      remote-scan = ${_scan_remote}
      validator = ${_validator_remote}
      service-user = ${?CN_APP_WALLET_LEDGER_API_AUTH_USER_NAME}
      validator-auth = ${_client_credentials_auth_config}
      auth {
        algorithm = "rs-256"
        audience = "https://canton.network.global"
        jwks-url = "https://canton-network-dev.us.auth0.com/.well-known/jwks.json"
      }
    }
  }
  features.enable-testing-commands = yes
}
