_participant_remote {
  admin-api = {
    address = "validator1-participant"
    port = 5102
  }

  ledger-api = {
    address = "validator1-participant"
    port = 5101
  }
}

_validator_remote {
  admin-api.port = 5103
  admin-api.address = "validator1-validator-app"
}

_scan_remote {
  admin-api.port = 5012
  admin-api.address = "scan-app"
}

canton {
  wallet-apps {
    validator1_wallet_backend {
      storage.type = memory
      admin-api = {
        address = "0.0.0.0"
        port = 5104
      }
      remote-participant = ${_participant_remote}
      remote-scan = ${_scan_remote}
      validator = ${_validator_remote}
      service-user = "validator1_wallet_service_user"
    }
    auth {
      algorithm = "hs-256-unsafe"
      secret = "test"
      enable-auth = false
    }
  }
  features.enable-testing-commands = yes
}
