_client_credentials_auth_config {
  type = "client-credentials"
  well-known-config-url = ${?CN_APP_DIRECTORY_LEDGER_API_AUTH_URL}
  client-id = ${?CN_APP_DIRECTORY_LEDGER_API_AUTH_CLIENT_ID}
  client-secret = ${?CN_APP_DIRECTORY_LEDGER_API_AUTH_CLIENT_SECRET}
  # TODO(#1837) use actual audience of the target participant
  audience = "https://canton.network.global"
}

_participant_remote {
  admin-api = {
    address = "participant"
    port = 5002
  }

  ledger-api = {
    client-config = {
      address = "participant"
      port = 5001
    }
    auth-config = ${_client_credentials_auth_config}
  }
}

_scan_remote {
  admin-api.port = 5012
  admin-api.address = "http://scan-app"
}

canton {
  directory-app {
    storage.type = memory
    admin-api = {
      address = "0.0.0.0"
      port = 5010
    }
    remote-participant = ${_participant_remote}
    remote-scan = ${_scan_remote}
    ledger-api-user = ${?CN_APP_DIRECTORY_LEDGER_API_AUTH_USER_NAME}
    domains {
      global = "global"
    }
  }
}
canton.features.enable-testing-commands = yes
