_participant_remote {
  admin-api = {
    address = "canton-participant"
    port = 5002
  }

  ledger-api = {
    address = "canton-participant"
    port = 5001
  }
}

_scan_remote {
  admin-api.port = 5012
  admin-api.address = "scan-app"
}

canton {
  directory-app {
    storage.type = memory
    admin-api = {
      address = "0.0.0.0"
      port = 5010
    }
    remote-participant = ${_participant_remote}
    remote-scan = ${_scan_remote}
    # TODO(#766) Consider separating users & participants from the SVC
    daml-user = "svc"
  }
}
canton.features.enable-testing-commands = yes
