cluster:
  imageTag: IMAGE_TAG
imageRepo: "digitalasset-canton-network-docker.jfrog.io/digitalasset"

defaultJvmOptions: -Xms1152M -Xmx1152M -Dscala.concurrent.context.minThreads=4
resources:
  limits:
    memory: 1536Mi
  requests:
    cpu: "1"
    memory: 1536Mi

metrics:
  enable: false
  release: prometheus-grafana-monitoring
  interval: 30s

persistence:
  databaseName: cantonnet_scan
  schema: scan
  host: postgres
  port: 5432
  user: cnadmin
  secretName: "postgres-secrets"

# k8s affinity for all deployed pods (optional)
# affinity:

# k8s nodeSelector for all deployed pods (optional)
# nodeSelector:
