# Configurations here will be applied after app.conf, and before any ADDITIONAL_CONFIG env vars
# Please use this file for temporary changes that require quick iterations. Once made permanent,
# please upstream the change to the Canton repo.

canton.participants.participant {
    parameters {
      commitment-asynchronous-initialization = true
      caching {
        # TODO(#3882) upstream and then remove here
        session-encryption-key-cache {
          sender-cache {
            maximum-size = 100000 # default is 10000
            expire-after-timeout = 3600s # default is 10s
          }
          receiver-cache {
            maximum-size = 100000 # default is 10000
            expire-after-timeout = 3600s # default is 10s
          }
        }
      }
    }
    topology {
        enable-topology-state-cache-consistency-checks = false
        use-new-processor = true
        use-new-client = true
    }
}
