canton {
  features {
    enable-preview-commands = yes
    enable-testing-commands = yes
  }
  parameters {
    manual-start = no
    non-standard-config = yes
    dev-version-support = yes
    # Bumping because our topology state can get very large due to
    # a large number of participants.
    timeouts.processing.verify-active = 40.seconds
  }

  # Bumping because our topology state can get very large due to
  # a large number of participants.
  monitoring.delay-logging-threshold = 40.seconds

  monitoring.metrics.reporters = [{
    type = prometheus
    address = "0.0.0.0"
    port = 10013
  }]

  participants-x {
    participant {

      init.auto-init=${?CANTON_PARTICIPANT_AUTO_INIT}

      monitoring.grpc-health-server {
        address = "0.0.0.0"
        port = 5061
      }

      storage {
        type = postgres
        config {
           dataSourceClass = "org.postgresql.ds.PGSimpleDataSource"
           properties = {
             serverName = ${CANTON_PARTICIPANT_POSTGRES_SERVER}
             portNumber = "5432"
             databaseName = "cantonnet"
             currentSchema = ${CANTON_PARTICIPANT_POSTGRES_SCHEMA}
             user = "cnadmin"
             password = "cnadmin"
             user = ${?CANTON_PARTICIPANT_POSTGRES_USER}
             password = ${?CANTON_PARTICIPANT_POSTGRES_PASSWORD}
           }
         }
         parameters {
           max-connections = 32
         }
       }

      admin-api {
        address = "0.0.0.0"
        port = 5002
      }

      init {
        ledger-api.max-deduplication-duration = 30s
      }

      ledger-api {
        address = "0.0.0.0"
        port = 5001
        user-management-service.additional-admin-user-id = ${CANTON_PARTICIPANT_ADMIN_USER_NAME}
        auth-services = [{
          type = jwt-rs-256-jwks
          url = "https://canton-network-dev.us.auth0.com/.well-known/jwks.json"
          url = ${?AUTH_JWKS_URL}

          # TODO(#2052) Use different audiences per participant.
          target-audience = "https://canton.network.global"
          target-audience = ${?AUTH_TARGET_AUDIENCE}
        }]
        # TODO(M3-55) Consider lowering this once we switched to postgres
        rate-limit.max-api-services-queue-size = 40000
        explicit-disclosure-unsafe = true
      }
      parameters {
        dev-version-support = yes
        initial-protocol-version = dev
        unique-contract-keys = false
      }
    }
  }
}
