canton {
  features {
    enable-testing-commands = yes
  }
  parameters {
    manual-start = no
    non-standard-config = yes
  }

  monitoring.metrics.reporters = [{
    type = prometheus
    address = "0.0.0.0"
    port = 10013
  }]

  participants {
    participant {
      storage {
        type = postgres
        config {
           dataSourceClass = "org.postgresql.ds.PGSimpleDataSource"
           properties = {
             serverName = ${CANTON_PARTICIPANT_POSTGRES_SERVER}
             portNumber = "5432"
             databaseName = "cantonnet"
             currentSchema = ${CANTON_PARTICIPANT_POSTGRES_SCHEMA}
             user = "cnadmin"
             password = "cnadmin"
           }
         }
       }

      admin-api {
        address = "0.0.0.0"
        port = 5002
      }

      ledger-api {
        address = "0.0.0.0"
        port = 5001
        max-deduplication-duration = 30s
        auth-services = [{
          type = jwt-rs-256-jwks
          url = "https://canton-network-dev.us.auth0.com/.well-known/jwks.json"
        }]
        # TODO(M3-55) Consider lowering this once we switched to postgres
        rate-limit.max-api-services-queue-size = 40000
        explicit-disclosure-unsafe = true
      }
      parameters {
        dev-version-support = yes
        unique-contract-keys = false
      }
    }
  }
}
