_participant_remote {
  admin-api = {
    address = "splitwise-participant"
    port = 5202
  }

  ledger-api = {
    address = "splitwise-participant"
    port = 5201
  }
}

_validator_remote {
  admin-api.port = 5203
  admin-api.address = "splitwise-validator-app"
}

_scan_remote {
  admin-api.port = 5012
  admin-api.address = "scan-app"
}

canton {
  splitwise-apps {
    splitwise_backend {
      storage.type = memory
      admin-api = {
        address = "0.0.0.0"
        port = 5213
      }
      remote-participant = ${_participant_remote}
      remote-scan = ${_scan_remote}
      provider-user = "splitwise_service_user"
    }
  }
  features.enable-testing-commands = yes
}
