{
 "title": "Automations",
 "description": "Track the trigger automations being run by Splice Apps",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(splice_trigger_completed_total,namespace)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(splice_trigger_completed_total{namespace=~\"$namespace\"},node_type)"
    }
   },
   {
    "name": "trigger_name",
    "label": "Trigger Name",
    "query": {
     "query": "label_values(splice_trigger_completed_total{namespace=~\"$namespace\", node_type=~\"$app\"},trigger_name)"
    }
   },
   { "name": "trigger_type", "query": "taskbased, polling" },
   {
    "name": "isDsoDelegateTrigger",
    "label": "isDsoDelegateTrigger",
    "query": {
     "query": "label_values(splice_trigger_attempted_total,isDsoDelegateTrigger)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Runs",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "runs / second" } },
   "targets": [
    {
     "expr": "rate(splice_trigger_completed_total{namespace=~\"$namespace\", node_type=~\"$app\", trigger_name=~\"$trigger_name\", outcome=~\"success|failure\"}[$__rate_interval])",
     "legendFormat": "{{node_name}} {{trigger_name}} {{outcome}} "
    }
   ]
  },
  {
   "title": "Triggers $trigger_type",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "trigger_type",
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic",
     "type": "stat",
     "description": "The rate of successful iterations completed",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(histogram_sum(rate(splice_trigger_latency_duration_seconds{namespace=~\"$namespace\", node_type=~\"$app\", trigger_name=~\"$trigger_name\", trigger_type=\"$trigger_type\"}[$__rate_interval])))"
      }
     ]
    },
    {
     "title": "Retries",
     "type": "stat",
     "description": "The rate at which the trigger(s) are failing with retryable errors",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(splice_retries_failures{namespace=~\"$namespace\", node_type=~\"$app\", trigger_name=~\"$trigger_name\", trigger_type=\"$trigger_type\", error_kind=\"transient\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "stat",
     "description": "The rate at which trigger(s) are failing with fatal/non-retryable errors",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(splice_retries_failures{namespace=~\"$namespace\", node_type=~\"$app\", trigger_name=~\"$trigger_name\", trigger_type=\"$trigger_type\", error_kind=\"fatal\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "description": "The time it took to perform an iteration",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(splice_trigger_latency_duration_seconds{namespace=~\"$namespace\", node_type=~\"$app\", trigger_name=~\"$trigger_name\", trigger_type=\"$trigger_type\"}[$__rate_interval]))",
       "legendFormat": "{{namespace}} {{node_type}} {{service}} {{trigger_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Active Triggers",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum by(trigger_name) (histogram_count(rate(splice_trigger_latency_duration_seconds{namespace=~\"$namespace\", node_type=~\"$app\", trigger_type=\"$trigger_type\"}[$__rate_interval])))"
      }
     ]
    },
    {
     "title": "Saturation",
     "type": "timeseries",
     "description": "How busy triggers are within a certain time window",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(trigger_name, instance, node_type, trigger_type) (histogram_sum(rate(splice_trigger_latency_duration_seconds{namespace=~\"$namespace\", node_type=~\"$app\", trigger_name=~\"$trigger_name\", trigger_type=\"$trigger_type\"}[$__rate_interval])))",
       "legendFormat": "{{node_type}} {{instance}} {{trigger_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Trigger attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(splice_trigger_attempted_total{statusCode=\"OK\", isDsoDelegateTrigger=\"$isDsoDelegateTrigger\", trigger_name=~\"$trigger_name\", namespace=~\"$namespace\", node_type=~\"$app\"}[$__rate_interval]))",
     "legendFormat": "total attempts"
    },
    {
     "expr": "sum(rate(splice_trigger_attempted_total{statusCode!~\"OK\", isDsoDelegateTrigger=\"$isDsoDelegateTrigger\", namespace=~\"$namespace\", node_type=~\"$app\", trigger_name=~\"$trigger_name\"}[$__rate_interval]))",
     "legendFormat": "total contentions"
    }
   ]
  },
  {
   "title": "Failed trigger attempts with contention errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(errorCodeId, namespace, node_type, trigger_name) (rate(splice_trigger_attempted_total{namespace=~\"$namespace\", node_type=~\"$app\", trigger_name=~\"$trigger_name\", isDsoDelegateTrigger=~\"$isDsoDelegateTrigger\", errorCodeId=~\"CONTRACT_NOT_FOUND|LOCAL_VERDICT_LOCKED_CONTRACTS|LOCAL_VERDICT_INACTIVE_CONTRACTS\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed trigger attempts with non-contention errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by (errorCodeId, namespace, node_type, trigger_name) (rate(splice_trigger_attempted_total{namespace=~\"$namespace\",node_type=~\"$app\",trigger_name=~\"$trigger_name\",isDsoDelegateTrigger=~\"$isDsoDelegateTrigger\", errorCodeId!~\"CONTRACT_NOT_FOUND|LOCAL_VERDICT_INACTIVE_CONTRACTS|LOCAL_VERDICT_LOCKED_CONTRACTS\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}