{
 "title": "Global Domain Catchup",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(daml_sequencer_client_handler_delay,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Canton", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sequencer Client Delay",
   "type": "timeseries",
   "description": "Delay on event processing of a sequencer, compared to the collective",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "daml_sequencer_client_handler_delay{namespace=~\"$namespace\", component=\"sequencer\"}",
     "legendFormat": "{{namespace}} {{service}}"
    }
   ]
  },
  {
   "title": "Participant Client Delay",
   "type": "timeseries",
   "description": "Delay on event processing of the participant, compared to the sequencers it is connected to.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "daml_sequencer_client_handler_delay{namespace=~\"$namespace\",component=\"participant\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Mediator Client Delay",
   "type": "timeseries",
   "description": "Delay on event processing of a mediator, compared to its corresponding sequencer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "daml_sequencer_client_handler_delay{namespace=~\"$namespace\", component=\"mediator\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "CometBFT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Sequencer processing Block Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(daml_block_height{namespace=~\"$namespace\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Cometbft producing Block Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(cometbft_consensus_height{namespace=~\"$namespace\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Sequencer Cometbft height ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "daml_block_height{namespace=~\"$namespace\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CometBFT Block Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "cometbft_consensus_latest_block_height{namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CometBFT Block Syncing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "cometbft_consensus_block_syncing{namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}