{
 "title": "Pulumi Operator Stacks Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "stack", "query": { "query": "label_values(stack_info,stack)" } }
  ]
 },
 "panels": [
  {
   "title": "Stacks being updated",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by() (controller_runtime_active_workers)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State",
   "type": "state-timeline",
   "gridPos": { "h": 14, "w": 18, "x": 6, "y": 0 },
   "targets": [
    { "expr": "sum by(name) (stacks_failing)", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "$stack",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "repeat": "stack",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stacks_failing{name=\"$stack\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Stacks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "targets": [
    { "expr": "stacks_active\n", "legendFormat": "stacks_active" },
    { "legendFormat": "stacks_failing" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_time_seconds_bucket{controller=\"stack-controller\"}[10m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Concurrent Reconciles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "controller_runtime_active_workers{controller=\"stack-controller\"}",
     "legendFormat": "Running reconciles"
    },
    {
     "expr": "controller_runtime_max_concurrent_reconciles{controller=\"stack-controller\"}",
     "legendFormat": "max_concurrent_reconciles"
    }
   ]
  },
  {
   "title": "Reconcile Results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "controller_runtime_reconcile_total{controller=\"stack-controller\"}",
     "legendFormat": "{{result}}"
    },
    {
     "expr": "controller_runtime_reconcile_errors_total{controller=\"stack-controller\"}",
     "legendFormat": "total errors"
    }
   ]
  }
 ]
}