{
 "title": "History backfiling",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(splice_history_backfilling_latest_record_time,namespace)"
    }
   },
   {
    "name": "migration",
    "query": {
     "query": "label_values(splice_history_backfilling_latest_record_time,migration)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Updates (scan)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backfilled transactions count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by(namespace)(splice_history_backfilling_transaction_count{namespace=~\"$namespace\", migration=~\"$migration\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate backfilled transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "max by (namespace)(rate(splice_history_backfilling_transaction_count{namespace=~\"$namespace\", migration=~\"$migration\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backfilled events count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max by(namespace)(splice_history_backfilling_event_count{namespace=~\"$namespace\", migration=~\"$migration\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate backfilled events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "max by(namespace)(rate(splice_history_backfilling_event_count{namespace=~\"$namespace\", migration=~\"$migration\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backfilling completed",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "max by(namespace)(splice_history_backfilling_completed{namespace=~\"$namespace\", migration=~\"$migration\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last record time backfilled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "min by(namespace)((splice_history_backfilling_latest_record_time{namespace=~\"$namespace\", migration=~\"$migration\"}>-62135596800000)/1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TxLog entries (all apps)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Processed transactions count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "max by(namespace)(splice_history_txlog_backfilling_transaction_count{namespace=~\"$namespace\", migration=~\"$migration\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate processed transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "max by (namespace)(rate(splice_history_txlog_backfilling_transaction_count{namespace=~\"$namespace\", migration=~\"$migration\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed events count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "max by(namespace)(splice_history_txlog_backfilling_event_count{namespace=~\"$namespace\", migration=~\"$migration\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate processed events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "max by(namespace)(rate(splice_history_txlog_backfilling_event_count{namespace=~\"$namespace\", migration=~\"$migration\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backfilling completed",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "max by(namespace)(splice_history_txlog_backfilling_completed{namespace=~\"$namespace\", migration=~\"$migration\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last record time backfilled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "min by(namespace)((splice_history_txlog_backfilling_latest_record_time{namespace=~\"$namespace\", migration=~\"$migration\"}>-62135596800000)/1000)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}