{
 "title": "Mediator Verdicts Ingestion",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(splice_scan_verdict_ingestion_last_record_time_us,namespace)"
    }
   },
   {
    "name": "node_name",
    "query": {
     "query": "label_values(splice_scan_verdict_ingestion_last_record_time_us,node_name)"
    }
   },
   {
    "name": "pod_name",
    "query": {
     "query": "label_values(splice_scan_verdict_ingestion_last_record_time_us,pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Verdicts Ingestion Rate",
   "type": "timeseries",
   "description": "Rate of ingestion of mediator verdicts per second based on ingestion_count_total",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(splice_scan_verdict_ingestion_count_total{namespace=~\"$namespace\", node_name=~\"$node_name\", pod=~\"$pod_name\"}[$__rate_interval])",
     "legendFormat": "{{namespace}} {{job}} {{pod}}"
    }
   ]
  },
  {
   "title": "Last Ingested Verdict Time Lag",
   "type": "timeseries",
   "description": "The time difference between the last ingested verdict record time and the current wall clock time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(time() * 1000) - (splice_scan_verdict_ingestion_last_record_time_us{namespace=~\"$namespace\",node_name=~\"$node_name\", pod_name=~\"$pod_name\"} / 1000) unless (splice_scan_verdict_ingestion_last_record_time_us{namespace=~\"$namespace\",node_name=~\"$node_name\", pod_name=~\"$pod_name\"} / 1000 == 0)",
     "legendFormat": "{{namespace}} {{job}} {{pod}}"
    }
   ]
  },
  {
   "title": "Last Ingested Verdict Record Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "splice_scan_verdict_ingestion_last_record_time_us{namespace=~\"$namespace\",node_name=~\"$node_name\", pod_name=~\"$pod_name\"} / 1000 unless (splice_scan_verdict_ingestion_last_record_time_us{namespace=~\"$namespace\",node_name=~\"$node_name\", pod_name=~\"$pod_name\"} / 1000 == 0)",
     "legendFormat": "{{namespace}} {{job}} {{pod}}"
    }
   ]
  }
 ]
}