{
 "title": "Sequencer Traffic",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(daml_block_events_total,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sequencer Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(daml_block_events_total{namespace=\"sv-1\", job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(type) (rate(daml_block_events_total{namespace=\"sv-1\", job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Confirmation Requests Rate by Sender",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(sender) (rate(daml_block_events_total{namespace=\"sv-1\", job=\"$job\", type=\"send-confirmation-request\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Confirmation Requests by Sender in the last Hour",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 12 },
   "targets": [
    {
     "expr": "sort_desc(sum(delta(daml_block_events_total{namespace=\"sv-1\",job=\"$job\",type=\"send-confirmation-request\"}[1h])) by (sender))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequencer Message Rate by Participant",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(daml_block_events_total{namespace=\"sv-1\", job=\"$job\",sender=~\"PAR::.*\"}[$__rate_interval])) by (sender)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequencer Message Rate by Mediator",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(rate(daml_block_events_total{namespace=\"sv-1\", job=\"$job\",sender=~\"MED::.*\"}[$__rate_interval])) by (sender)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequencer Message Rate by Member excluding Mediator/Participant",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum by(sender) (rate(daml_block_events_total{namespace=\"sv-1\", job=\"$job\", sender!~\"(MED|PAR)::.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}