{
 "title": "SV Status Reports",
 "description": "Show the DSO health based on the SV status reports.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(cn_sv_status_report_creation_time_us,namespace)"
    }
   },
   {
    "name": "sv_party",
    "label": "report publisher",
    "query": {
     "query": "label_values(cn_sv_status_report_creation_time_us,report_publisher)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(cn_sv_status_report_creation_time_us,canton_version)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Progress Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Domain Time Progress",
   "type": "timeseries",
   "description": "How many seconds of progress on the reported participant domain time is observed every second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (namespace, report_publisher, target_node) (rate(cn_sv_status_report_domain_time_us{namespace=~\"$namespace\", report_publisher=~\"$sv_party\", canton_version=~\"$version\"}[10m])) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Domain Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "cn_sv_status_report_domain_time_us{namespace=~\"$namespace\", report_publisher=~\"$sv_party\", canton_version=~\"$version\"} / 1000",
     "legendFormat": "{{target_node}} - {{ report_publisher }}  {{ report_publisher_party }}"
    }
   ]
  },
  {
   "title": "Reporting Frequency",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "recpm" } },
   "targets": [
    {
     "expr": "max by(namespace, report_publisher) (rate(cn_sv_status_report_number{namespace=~\"$namespace\", report_publisher=~\"$sv_party\", canton_version=~\"$version\"}[5m]) * 60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CometBFT Height Lag",
   "type": "timeseries",
   "description": "Maximal minus minimal CometBFT height reported by the SV status reports seen from one SV's perspective",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "max by (namespace) (max by (report_publisher, namespace) (cn_sv_status_report_cometbft_height{namespace=~\"$namespace\", report_publisher=~\"$sv_party\", canton_version=~\"$version\"}) ) - min by (namespace) (max by (report_publisher, namespace) (cn_sv_status_report_cometbft_height{namespace=~\"$namespace\", report_publisher=~\"$sv_party\", canton_version=~\"$version\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Open Mining Round Lag",
   "type": "timeseries",
   "description": "Should not go above 1 when all SVs are healthy, serves as a basic safeguard to see that the round structure makes progress from all SVs' point of view.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "max by (namespace) (max by (report_publisher, namespace) (cn_sv_status_report_latest_open_round{namespace=~\"$namespace\", report_publisher=~\"$sv_party\", canton_version=~\"$version\"}) ) - min by (namespace) (max by (report_publisher, namespace) (cn_sv_status_report_latest_open_round{namespace=~\"$namespace\", report_publisher=~\"$sv_party\", canton_version=~\"$version\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Additional Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Report Creation Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "max by (namespace, report_publisher) (cn_sv_status_report_creation_time_us{namespace=~\"$namespace\", report_publisher=~\"$sv_party\", canton_version=~\"$version\"}) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CometBFT Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (namespace, report_publisher) (cn_sv_status_report_cometbft_height{namespace=~\"$namespace\", report_publisher=~\"$sv_party\", canton_version=~\"$version\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Open Mining Round",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (namespace, report_publisher) (cn_sv_status_report_latest_open_round{namespace=~\"$namespace\", report_publisher=~\"$sv_party\", canton_version=~\"$version\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}