{
 "title": "Synchronizer Traffic",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(daml_traffic_control_event_delivered_cost_total,namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(daml_traffic_control_event_delivered_cost_total,job)"
    }
   },
   {
    "name": "member",
    "label": "Member",
    "query": {
     "query": "label_values(daml_traffic_control_event_delivered_cost_total,member)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Delivered Event Traffic Rate By Event Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(type) (rate(daml_traffic_control_event_delivered_cost_total{namespace=\"$namespace\", job=\"$job\", member=~\"$member\", type=~\".+\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rejected Event Traffic Rate By Event Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(type) (rate(daml_traffic_control_event_rejected_cost_total{namespace=\"$namespace\", job=\"$job\", member=~\"$member\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Tier Traffic Available By Participant/Mediator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(member) (daml_traffic_control_base_traffic_remainder{namespace=\"$namespace\", job=\"$job\", member=~\"$member\", member=~\"(PAR|MED)::.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Extra Traffic Available By Participant",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expression": "$extra_traffic_limit - $extra_traffic_consumed",
     "type": "math"
    }
   ]
  }
 ]
}