{
 "title": "Update History",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(splice_store_last_ingested_record_time_ms,namespace)"
    }
   },
   {
    "name": "node_name",
    "query": {
     "query": "label_values(splice_store_last_ingested_record_time_ms,node_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ingestion timing",
   "type": "timeseries",
   "description": "How long it takes to ingest a single update history entry (including all children events)",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, namespace, job, update_type) (rate(splice_history_updates_latency_duration_seconds{namespace=~\"$namespace\", node_name=~\"$node_name\"}[$__rate_interval])))",
     "legendFormat": "95% - {{namespace}} {{job}} {{update_type}}"
    },
    {
     "expr": "histogram_avg(rate(splice_history_updates_latency_duration_seconds{namespace=~\"$namespace\", node_name=~\"$node_name\"}[$__rate_interval]))",
     "legendFormat": "avg - {{namespace}} {{job}} {{update_type}}"
    }
   ]
  },
  {
   "title": "Ingestion rate",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_count(rate(splice_history_updates_latency_duration_seconds{namespace=~\"$namespace\",node_name=~\"$node_name\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{job}} {{update_type}}"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Ingestion rate events",
   "type": "timeseries",
   "description": "How many events (created / archived) were ingested per $rate_interval",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(splice_history_updates_event_count{namespace=~\"$namespace\", node_name=~\"$node_name\", event_type=\"exercised\"}[$__rate_interval])",
     "legendFormat": "exercised {{namespace}} {{node_name}}"
    },
    {
     "expr": "rate(splice_history_updates_event_count{namespace=~\"$namespace\", node_name=~\"$node_name\", event_type=\"created\"}[$__rate_interval])",
     "legendFormat": "created {{namespace}} {{node_name}}"
    }
   ]
  },
  { "title": "Record time metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Last Ingested Record Time Lag",
   "type": "timeseries",
   "description": "The time difference between the last ingested record time and the current wallclock time.\n\nNote that the last ingested record time metric only updates when the store ingests a new transaction so if there is no activity, the last ingested record time will not advance. For a party performing reward collection, e.g., the validator operator party you expect at least one transaction every round so the lag should not go above 20min.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": " time() * 1000.0 - splice_history_updates_latest_record_time{namespace=~\"$namespace\",node_name=~\"$node_name\"} / 1000",
     "legendFormat": "{{namespace}} {{job}} {{store_name}} {{store_party}} {{synchronizer_id}}"
    }
   ]
  },
  {
   "title": "Last Ingested Record Time",
   "type": "timeseries",
   "description": "The last ingested record time for the update history.\n\nNote that the last ingested record time metric only updates when the update history ingests a new transaction so if no transaction is ingested the last ingested time will not advance. For a party performing reward collection, e.g., the validator operator party you expect at least one transaction every round so the last ingested time should be at most 20min ago.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "splice_history_updates_latest_record_time{namespace=~\"$namespace\",node_name=~\"$node_name\"} / 1000",
     "legendFormat": "{{namespace}} {{job}}"
    }
   ]
  }
 ]
}