# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

FROM ubuntu:latest
RUN apt-get update && apt-get install -y postgresql-client
