imageRepo: digitalasset-canton-network-docker.jfrog.io/digitalasset
imageName: cometbft
cluster:
  imageTag: IMAGE_TAG

# Node names use as a moniker to identify the node in the CometBFT network
nodeName: ""

stateSync:
  # state sync speeds up initialization considerably for large chains.
  enable: true
  # at least 2 not necessarily unique comma-separated entries must be provided for rpc_servers if enable is true
  rpcServers: ""
  # trust all snapshots from the trust height onwards for a period of 1 week
  trustPeriod: "168h0m0s"

founder:
  # The CometBFT node ID of the founding node
  nodeId: "5af57aa83abcec085c949323ed8538108757be9c"
  # The public key of the CometBFT founding node
  publicKey: "gpkwc1WCttL8ZATBIPWIBRCrb0eV4JwMCnjRa56REPw="
  keyAddress: "8A931AB5F957B8331BDEF3A0A081BD9F017A777F"
  # External address, in the format <host>:<port> that can be used to access the p2p port of the founding node
  externalAddress:
peers:
  # Permanent peers to add alongside the founder
  # The CometBFT node ID of the peer node
  #- nodeId:
  # External address, in the format <host>:<port> that can be used to access the p2p port of the peer
  #  externalAddress:
node:
  # The CometBFT node ID
  id:
  # The p2p port exposed by the CometBFT container
  p2pPort: 26656
  # The rpc port exposed by the CometBFT container
  rpcPort: 26657
  # Identifier used to prefix created resources and as part of the optional Istio ingress
  identifier:
  # Number of blocks to keep, used for pruning. 0 -> keep all blocks.
  # Number of blocks to keep for 7 days. 700k -> at least 7 days pruning
  retainBlocks: 700000
  # Interval in which a new snapshot should be generated, in order to assist new peers to sync quickly.
  # A value below 1000 is not recommended.
  snapshotHeightDelta: 1000
  # URL that can be used by other nodes to access the p2p port of the node.
  # Must be set in the format <host>:<port>
  externalAddress: ""
  # Either keysSecret or privateKey and validator values must be provided
  keysSecret: ""
  # The node private key
  privateKey: ""
  validator:
    keyAddress: ""
    privateKey: ""
    publicKey: ""

istioVirtualService:
  enabled: false
  gateway: ""
  port: 26656

genesis:
  chainId: ""

db:
  volumeSize: 240Gi
  volumeStorageClass: standard-rwo

resources:
  limits:
    cpu: 4
    memory: 4Gi
  requests:
    cpu: 1
    memory: 1Gi

metrics:
  enable: false
  release: prometheus-grafana-monitoring
  interval: 30s
