# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

ARG base_version

FROM --platform=linux/amd64 canton:${base_version}

COPY pre-bootstrap.sh app.conf /app/
