{
 "title": "Participant",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_participant_api_commands_max_in_flight_length,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(daml_participant_api_commands_max_in_flight_length{namespace=~\"$namespace\"},job)"
    }
   },
   {
    "name": "participant",
    "query": {
     "query": "label_values(daml_participant_api_commands_max_in_flight_length{namespace=~\"$namespace\", job=~\"$job\"},node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Sequencer Connection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Participant Client Delay",
   "type": "timeseries",
   "description": "Delay on event processing of the participant, compared to the sequencers it is connected to.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "daml_sequencer_client_handler_delay{namespace=~\"$namespace\",component=\"participant\",job=~\"$job\", node=~\"$participant\"}",
     "legendFormat": "_ overall - {{namespace}} {{job}} {{node}}"
    },
    {
     "expr": "daml_sequencer_client_handler_delay_per_connection{namespace=~\"$namespace\",component=\"participant\",job=~\"$job\", node=~\"$participant\"}",
     "legendFormat": "{{namespace}} {{job}} {{node}} {{sequencer}}"
    }
   ]
  },
  {
   "title": "In Flight submissions",
   "type": "timeseries",
   "description": "Sequencer submissions currently running. Note this is at the level of a sequencer submission not a Daml transaction.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "submissions" } },
   "targets": [
    {
     "expr": "sum by(synchronizer, type, namespace, job, node) (daml_sequencer_client_submissions_in_flight{namespace=~\"$namespace\", component=\"participant\", job=~\"$job\", node=~\"$participant\"})",
     "legendFormat": "{{namespace}} {{job}} {{node}} {{sync}} {{type}}"
    }
   ]
  },
  {
   "title": "Dropped Submissiones",
   "type": "timeseries",
   "description": "Submissions that were not sequenced",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "epm" } },
   "targets": [
    {
     "expr": "increase(daml_sequencer_client_submissions_dropped{namespace=~\"$namespace\",component=\"participant\",job=~\"$job\", node=~\"$participant\"}[1m])",
     "legendFormat": "{{namespace}} {{job}} {{node}}"
    }
   ]
  },
  {
   "title": "Sequencer Client Batches ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "daml_sequencer_client_handler_max_in_flight_event_batches{namespace=~\"$namespace\",component=\"participant\",job=~\"$job\", node=~\"$participant\"}",
     "legendFormat": "max {{namespace}} {{job}}"
    },
    {
     "expr": "daml_sequencer_client_handler_actual_in_flight_event_batches{namespace=~\"$namespace\",component=\"participant\",job=~\"$job\", node=~\"$participant\"}",
     "legendFormat": "actual {{namespace}} {{job}}"
    }
   ]
  },
  {
   "title": "Events received",
   "type": "timeseries",
   "description": "Events received from the sequencer",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "epm" } },
   "targets": [
    {
     "expr": "rate(daml_sequencer_client_handler_sequencer_events{namespace=~\"$namespace\",component=\"participant\",job=~\"$job\", node=~\"$participant\"}[$__rate_interval])",
     "legendFormat": "{{namespace}} {{job}} {{node}}"
    }
   ]
  },
  { "title": "Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "In Flight Commands",
   "type": "timeseries",
   "description": "Daml commands through the synchronous CommandService currently in flight",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "submissions" } },
   "targets": [
    {
     "expr": "daml_participant_api_commands_max_in_flight_length{namespace=~\"$namespace\",component=\"participant\",job=~\"$job\", node=~\"$participant\"}",
     "legendFormat": "{{namespace}} {{job}} {{node}}"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Health Status",
   "type": "state-timeline",
   "description": "Status of the participant (healthy or not)",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Alive" } },
   "targets": [
    {
     "expr": "daml_health_status{namespace=~\"$namespace\",job=~\"$job\", node=~\"$participant\"}",
     "legendFormat": "{{namespace}} {{job}} {{node}} {{component}}"
    }
   ]
  }
 ]
}