{
 "title": "Unresponsive Parties",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_mediator_timeout_non_responsive_participants_total,namespace)"
    }
   },
   {
    "name": "party",
    "query": {
     "query": "label_values(daml_mediator_timeout_non_responsive_participants_total,party)"
    }
   },
   {
    "name": "participant",
    "query": {
     "query": "label_values(daml_mediator_timeout_non_responsive_participants_total,participant)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of missed confirmations by party in the last hour",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(max by (party) (increase(daml_mediator_timeout_non_responsive_participants_total{namespace=~\"$namespace\",party=~\"$party\",participant=~\"$participant\"}[1h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of missed confirmations by participant in the last hour",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(max by (participant) (increase(daml_mediator_timeout_non_responsive_participants_total{namespace=~\"$namespace\",party=~\"$party\",participant=~\"$participant\"}[1h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of missed confirmations",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "max by (party, participant) (rate(daml_mediator_timeout_non_responsive_participants_total{namespace=~\"$namespace\",party=~\"$party\",participant=~\"$participant\"}[$__rate_interval]))",
     "legendFormat": "{{party}}@{{participant}}"
    }
   ]
  }
 ]
}