# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: local
    hooks:
      - id: scalafmt
        name: scalafmt
        language: system
        require_serial: true
        entry: "bash -c 'sbt --client \"scalafmtOnly $@\"' bash"
        types: [scala]
      - id: dars_lock
        name: dars_lock
        language: system
        pass_filenames: false
        require_serial: true
        entry: "bash -c 'sbt --client \"damlDarsLockFileUpdate $@\"' bash"
        files: '(daml\.yaml|.*\.daml)'
      - id: shellcheck
        name: shellcheck
        language: system
        entry: "shellcheck"
        # ignore external sources
        args: [-e, SC1091]
        types: [shell]
        exclude: '^canton/'
      - id: typescriptfmt
        name: typescriptfmt
        language: system
        entry: "scripts/fix-ts.py"
        types_or: [javascript, jsx, ts, tsx]
        exclude: "/[.]prettierrc[.]cjs$"
      - id: pulumi_infra
        name: check pulumi infra config
        language: system
        entry: "make cluster/pulumi/infra/test"
        files: '^cluster/pulumi/infra/.*[.]ts$'
        pass_filenames: false
      - id: pulumi_cn
        name: check pulumi canton-network config
        language: system
        entry: "make cluster/pulumi/canton-network/test"
        files: '^cluster/pulumi/canton-network/.*[.]ts$'
        pass_filenames: false
      - id: pulumi_sv
        name: check pulumi sv-runbook config
        language: system
        entry: "make cluster/pulumi/sv-runbook/test"
        files: '^cluster/pulumi/sv-runbook/.*[.]ts$'
      - id: pulumi_validator
        name: check pulumi validator-runbook config
        language: system
        entry: "make cluster/pulumi/validator-runbook/test"
        files: '^cluster/pulumi/validator-runbook/.*[.]ts$'
        pass_filenames: false
      - id: circleci_config
        name: check circleci config is updated
        language: system
        entry: ".circleci/build-config.sh --check"
        files: '^.circleci/config/.*[.]yml$'
