# Enable this config for region migration
#svs:
#  sv-1:
#    cometbft:
#      snapshotName: "nicu-test-cometbft-cloning"
synchronizerMigration:
  active:
    id: 1
    provider: internal
    version: 0.2.8
    releaseReference: "refs/heads/release-line-0.2.8"
pulumiProjectConfig:
  default:
    installDataOnly: true
  infra:
    installDataOnly: false
