apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-mediator
  name: {{ .Release.Name }}-mediator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mediator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mediator
    spec:
      containers:
      - name: {{ .Release.Name }}-mediator
        image: "{{ .Values.imageRepo }}/canton-mediator:{{ .Values.cluster.imageTag }}"
        env:
        - name: JAVA_TOOL_OPTIONS
          value: {{ .Values.defaultJvmOptions }} {{ .Values.additionalJvmOptions }}
        - name: CANTON_DOMAIN_POSTGRES_SERVER
          value: {{ .Values.mediatorPostgres }}
        - name: CANTON_DOMAIN_POSTGRES_PASSWORD
          valueFrom:
           secretKeyRef:
              name: {{ .Values.mediatorPostgresSecretName }}
              key: postgresPassword
        {{- if .Values.postgresMediatorDb }}
        - name: CANTON_MEDIATOR_POSTGRES_DB
          value: {{ .Values.postgresMediatorDb }}
        {{- end }}
        # Use the same way to disable auto-init as we do in the sequencer and participant once https://github.com/DACH-NY/canton/issues/16179 is fixed
        {{- if .Values.disableAutoInit }}
        - name: ADDITIONAL_CONFIG_MEDIATOR_AUTO_INIT
          value: |
            canton {
              mediators-x {
                mediator {
                    init.auto-init = false
                }
              }
            }
        {{- end }}
        imagePullPolicy: Always
        ports:
        - containerPort: 5007
          name: cm-adm-api
          protocol: TCP
        - containerPort: 10013
          name: cm-metrics
          protocol: TCP
        {{- with .Values.resources }}
        resources: {{- toYaml . | nindent 10 }}
        {{- end }}
      restartPolicy: Always
      {{- if .Values.init }}
      initContainers:
        - name: {{ .Release.Name }}-init
          image: postgres:14
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgresPassword
                  name: {{ .Values.mediatorPostgresSecretName }}
          command:
            - 'sh'
            - '-c'
            - |
              until errmsg=$(psql -h {{ .Values.mediatorPostgres }} --username=cnadmin --dbname={{ .Values.init.initDb }} -c 'create database {{ .Values.postgresMediatorDb }}' 2>&1); do
                if [[ $errmsg == *"already exists"* ]]; then
                  echo "Database {{ .Values.postgresMediatorDb }} already exists. Done."
                  break
                fi

                echo "trying to create postgres database {{ .Values.postgresMediatorDb }}, last error: $errmsg";
                sleep 2;
              done
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mediator
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-mediator
spec:
  selector:
    app: {{ .Release.Name }}-mediator
  ports:
  - name: cm-adm-api
    port: 5007
    protocol: TCP
  - name: cm-metrics
    port: 10013
    protocol: TCP
