---

apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secrets"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  cantonDomainPostgresPassword: {{ .Values.postgresPassword | trim |  b64enc }}
  {{ if eq .Values.sequencerDriver.type "postgres" }}
  sequencerDriverPostgresPassword: {{ .Values.sequencerDriver.password | trim | b64enc }}
  {{ end }}
