apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-sequencer
  name: {{ .Release.Name }}-sequencer
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-sequencer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-sequencer
    spec:
      containers:
        - name: {{ .Release.Name }}-sequencer
        {{- if eq .Values.sequencerDriver.type "cometbft"}}
          image: "{{ .Values.imageRepo }}/canton-cometbft-sequencer:{{ .Values.cluster.imageTag }}"
        {{- else}}
          image: "{{ .Values.imageRepo }}/canton-sequencer:{{ .Values.cluster.imageTag }}"
        {{- end}}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.defaultJvmOptions }} {{ .Values.additionalJvmOptions }}
            - name: CANTON_DOMAIN_POSTGRES_SERVER
              value: {{ .Values.sequencerPostgres }}
            - name: CANTON_DOMAIN_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sequencerPostgresSecretName }}
                  key: postgresPassword
        {{- if .Values.postgresSequencerDb }}
            - name: CANTON_SEQUENCER_POSTGRES_DB
              value: {{ .Values.postgresSequencerDb }}
        {{- end }}
        {{- if eq .Values.sequencerDriver.type "postgres"}}
            - name: SEQUENCER_DRIVER_DATABASE_ADDRESS
              value: {{ .Values.sequencerDriver.address }}
            - name: SEQUENCER_DRIVER_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresSecretName }}
                  key: postgresPassword
        {{- else if eq .Values.sequencerDriver.type "cometbft"}}
            - name: SEQUENCER_DRIVER_COMETBFT_HOST
              value: {{ .Values.sequencerDriver.host }}
            - name: SEQUENCER_DRIVER_COMETBFT_PORT
              value: "{{ .Values.sequencerDriver.port }}"
        {{- end}}
          imagePullPolicy: Always
          ports:
            - containerPort: 5008
              name: cs-pub-api
              protocol: TCP
            - containerPort: 5009
              name: cs-adm-api
              protocol: TCP
        {{- with .Values.resources }}
          resources: {{- toYaml . | nindent 12 }}
        {{- end }}
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: cs-pub-api
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: cs-pub-api
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 20
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: cs-pub-api
            timeoutSeconds: 1
      restartPolicy: Always
      {{- if .Values.init }}
      initContainers:
        - name: {{ .Release.Name }}-init
          image: postgres:14
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgresPassword
                  name: {{ .Values.sequencerPostgresSecretName }}
          command:
            - 'sh'
            - '-c'
            - |
              until errmsg=$(psql -h {{ .Values.sequencerPostgres }} --username=cnadmin --dbname={{ .Values.init.initDb }} -c 'create database {{ .Values.postgresSequencerDb }}' 2>&1); do
                if [[ $errmsg == *"already exists"* ]]; then
                  echo "Database {{ .Values.postgresSequencerDb }} already exists. Done."
                  break
                fi

                echo "trying to create postgres database {{ .Values.postgresSequencerDb }}, last error: $errmsg";
                sleep 2;
              done
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sequencer
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-sequencer
spec:
  selector:
    app: {{ .Release.Name }}-sequencer
  ports:
    - name: grpc-cs-pub-api
      port: 5008
      protocol: TCP
    - name: grpc-cs-adm-api
      port: 5009
      protocol: TCP
    - name: cs-metrics
      port: 10013
      protocol: TCP
