_validator_participant_remote {
  admin-api.port = 5002
  ledger-api.port = 5001
}

_scan_remote {
  admin-api.port = 5012
  admin-api.address = dev.network.canton.global
  admin-api.address = ${?NETWORK_APPS_ADDRESS}
}

canton {
  splitwise-apps {
    splitwiseBackend {
      admin-api.address = 0.0.0.0
      admin-api.port = 5013
      provider-user = "splitwise-service-user"
      remote-participant = ${_validator_participant_remote}
      remote-scan = ${_scan_remote}
    }
  }
}
