canton {
  participants {
    validatorParticipant {
      storage.type = memory
      admin-api.port = 5012
      ledger-api.port = 5011
      parameters.unsafe-enable-daml-lf-dev-version = true
    }
  }
}
canton.features.enable-testing-commands = yes
