canton {
  parameters.non-standard-config = yes
  participants {
    validatorParticipant {
      storage.type = memory
      admin-api.port = 5002
      ledger-api.port = 5001
      ledger-api.auth-services = [{
        type = jwt-rs-256-jwks
        url = ${?NETWORK_AUTH_JWKS_URL}
        target-audience = "https://ledger_api.example.com"
      }]
      ledger-api.explicit-disclosure-unsafe = true
      parameters {
        dev-version-support = yes
      }
      init.parameters.unique-contract-keys = false
    }
  }
}
canton.features.enable-testing-commands = yes
