_validator_participant_remote {
  admin-api.port = 5002
  ledger-api.client-config.port = 5001
}

_scan_remote {
  admin-api.port = 5012
  admin-api.address = ${NETWORK_APPS_ADDRESS}
  admin-api.url = ${NETWORK_APPS_ADDRESS_PROTOCOL}"://"${NETWORK_APPS_ADDRESS}":5012"
}

canton {
  validator-apps {
    validatorApp {
      storage.type = memory
      admin-api.port = 5003
      remote-participant = ${_validator_participant_remote}
      remote-participant.ledger-api.auth-config = {
        type = "client-credentials"
        well-known-config-url = ${NETWORK_AUTH_WELLKNOWN_URL}
        client-id = ${NETWORK_AUTH_VALIDATOR_CLIENT_ID}
        client-secret = ${NETWORK_AUTH_VALIDATOR_CLIENT_SECRET}
        audience = "https://ledger_api.example.com"
      }
      ledger-api-user = ${NETWORK_AUTH_VALIDATOR_USER_NAME}
      # validator-wallet-user = ${NETWORK_AUTH_VALIDATOR_WALLET_USER_NAME}
      remote-scan = ${_scan_remote}
      app-instances {
      }
      auth {
        algorithm = "rs-256"
        audience = "https://cn_api.example.com"
        jwks-url = ${NETWORK_AUTH_JWKS_URL}
      }
      domains {
        global = "global"
      }
    }
  }

  # Wallet app clients do not support real auth, need to interact via web UI
  wallet-app-clients {}
}
canton.features.enable-testing-commands = yes
