canton {
  validator-apps {
    validatorApp {
      onboarding = {
        # our onboarding sponsor is SV1
        remote-sv.admin-api.port = 5014
        remote-sv.admin-api.address = ${NETWORK_APPS_ADDRESS_PROTOCOL}"://"${NETWORK_APPS_ADDRESS}
        # secret must be obtained from SV1 first
        secret = "PLACEHOLDER"
      }
    }
  }
}
