_validator_participant_remote {
  admin-api.port = 5002
  ledger-api.client-config.port = 5001
  ledger-api.auth-config.type = "none"
}

_scan_remote {
  admin-api.port = 5012
  admin-api.address = ${NETWORK_APPS_ADDRESS}
  admin-api.url = ${NETWORK_APPS_ADDRESS_PROTOCOL}"://"${NETWORK_APPS_ADDRESS}":5012"
}

canton {
  validator-apps {
    validatorApp {
      storage.type = memory
      admin-api.port = 5003
      remote-participant = ${_validator_participant_remote}
      ledger-api-user = "validator_user"
      validator-wallet-user = "validator_user"
      remote-scan = ${_scan_remote}
      wallet-service-user = ${canton.wallet-app-backends.walletApp.service-user}
      auth {
        algorithm = "hs-256-unsafe"
        audience = "https://canton.network.global"
        secret = "test"
      }
      app-instances {
      }
      domains {
        global = "global"
      }
    }
  }

  wallet-app-backends {
    walletApp {
      storage.type = memory
      admin-api.port = 5004
      service-user = "wallet_service_user"
      remote-participant = ${_validator_participant_remote}
      remote-scan = ${_scan_remote}
      validator.admin-api = {
        port = 5003
        url = "http://127.0.0.1:5003"
      }
      validator-auth {
        type = "self-signed"
        audience = ${canton.validator-apps.validatorApp.auth.audience}
        user = ${canton.wallet-app-backends.walletApp.service-user}
        secret = ${canton.validator-apps.validatorApp.auth.secret}
      }
      auth {
        algorithm = "hs-256-unsafe"
        audience = "https://canton.network.global"
        secret = "test"
      }
      domains {
        global = "global"
      }
    }
  }

  wallet-app-clients {
    aliceWallet {
      ledger-api-user = "alice"
      admin-api {
        port = 5004
        url = "http://127.0.0.1:5004"
      }
    }

    bobWallet {
      ledger-api-user = "bob"
      admin-api {
        port = 5004
        url = "http://127.0.0.1:5004"
      }
    }
  }
}
canton.features.enable-testing-commands = yes
