_validator_remote {
  admin-api.port = 5012
  ledger-api.port = 5011
}

canton {
  participants {
    validatorParticipant {
      storage.type = memory
      admin-api.port = 5012
      ledger-api.port = 5011
      parameters.minimum-protocol-version = 2.0.0 # TODO(M1-90 Backlog) remove once we have our own transaction domain
    }
  }

  validator-apps {
    validatorApp {
      storage.type = memory
      admin-api.port = 5003
      remote-participant = ${_validator_remote}
    }
  }

  wallet-apps {
    wallet {
      storage.type = memory
      admin-api.port = 5004
      remote-participant = ${_validator_remote}
      daml-user = "wallet"
    }
  }
}
canton.participants.validatorParticipant.parameters.unsafe-enable-daml-lf-dev-version = true
canton.features.enable-testing-commands = yes

