canton {
  participants {
    validator1 { # TODO(https://github.com/DACH-NY/canton/issues/9731) the 1 suffix required due to  bug
      storage.type = memory
      admin-api.port = 5022
      ledger-api.port = 5021
      parameters.minimum-protocol-version =  2.0.0 # TODO(M1-90 Backlog) remove once we have our own transaction domain
    }
  }
}
