#!/bin/bash

set -euo pipefail

# This script is used in CircleCI to determine whether there's been changes in the selected file path since the latest base version.

file_path="${1:-}"
if [ -z "$file_path" ]; then
  echo "Error: Path where to check changes not set."
  echo "USAGE: $0 <path>"
  exit 1
fi

# Find latest commit where those were modified
changed_files_hash=$(git log -n 1 --format="%H" -- "${file_path}")

latest_base_version=$(build-tools/find_latest_base_version.sh)

if git merge-base --is-ancestor "$latest_base_version" "$changed_files_hash"; then
    echo "There's been changes in $file_path ($changed_files_hash) since the latest base version ($latest_base_version)."
    exit 1
else
    echo "There's been no changes in $file_path since the latest base version ($latest_base_version)."
    exit 0
fi
