#!/usr/bin/env bash
set -euo pipefail

source ${TOOLS_LIB}/libcli.source
source ${TOOLS_LIB}/gcloud.source
source ${TOOLS_LIB}/k8s.source
source ${TOOLS_LIB}/minikube.source

set_k8s_context

if [ "$K8S_CONTEXT" == "gcloud" ]; then
    echo "Deleting gcloud cluster..."
    gcloud_setup
    gcloud_delete
elif [ "$K8S_CONTEXT" == "minikube" ]; then
    echo "Deleting minikube cluster..."
    minikube_delete
fi

echo "Cluster deleted."
