#!/usr/bin/env bash
set -euo pipefail

if [ "$K8S_CONTEXT" == "gcloud" ]; then
    echo "Creating gcloud cluster..."
    source ${TOOLS_LIB}/gcloud-setup
    source ${TOOLS_LIB}/gcloud-create
    source ${TOOLS_LIB}/gcloud-connect
elif [ "$K8S_CONTEXT" == "minikube" ]; then
    echo "Creating minikube cluster..."
    source ${TOOLS_LIB}/minikube-create
else
    echo "Unknown cluster type: ${K8S_CONTEXT}"
    exit 1
fi

source ${TOOLS_LIB}/k8s-apply
