# This config file contains all nodes of our deployed Canton Network cluster
# Use it to interact with a deployed cluster through a locally running coin binary, e.g., using
# CLUSTER_ADDR=scratch.network.canton.global coin -v -c ./build-tools/cluster.conf

canton {
  remote-participants {

    # SVC node: canton participant
    svc_participant {
      admin-api {
        port = 5002
        address = ${CLUSTER_ADDR}
      }
      ledger-api {
        port = 5001
        address = ${CLUSTER_ADDR}
      }
    }

    # Validator1 node: canton participant
    validator1_participant {
      admin-api {
        port = 5102
        address = ${CLUSTER_ADDR}
      }
      ledger-api {
        port = 5101
        address = ${CLUSTER_ADDR}
      }
    }

    # Splitwell provider node: canton participant
    splitwell_participant {
      admin-api {
        port = 5202
        address = ${CLUSTER_ADDR}
      }
      ledger-api {
        port = 5201
        address = ${CLUSTER_ADDR}
      }
    }
  }

  # SVC node: SVC app backend
  # Note: hardcoded to have the instance name `svc-app-client`
  svc-app-client {
    admin-api.port = 5005
    admin-api.address = ${CLUSTER_ADDR}
  }

  # SVC node: scan app backend
  scan-app-clients {
    svc_scan {
      admin-api.port = 5012
      admin-api.address = ${CLUSTER_ADDR}
      admin-api.url = "http://"${CLUSTER_ADDR}":7012"
    }
  }

  # Validator1 node: validator app backend
  validator-app-clients {
    validator1_validator {
      admin-api.port = 5103
      admin-api.address = ${CLUSTER_ADDR}
    }

    splitwell_validator {
      admin-api.port = 5203
      admin-api.address = ${CLUSTER_ADDR}
    }
  }

  # Validator1 node: wallet app backend
  # Note: user is hardcoded in the app config, this will be replaced by auth in the future
  wallet-app-clients {
    validator1_wallet_as_alice {
      admin-api.port = 5104
      admin-api.address = ${CLUSTER_ADDR}
      admin-api.url = "http://"${CLUSTER_ADDR}":7104"
      ledger-api-user = "alice"
    }
    validator1_wallet_as_bob {
      admin-api.port = 5104
      admin-api.address = ${CLUSTER_ADDR}
      admin-api.url = "http://"${CLUSTER_ADDR}":7104"
      ledger-api-user = "bob"
    }
    validator1_wallet_as_charlie {
      admin-api.port = 5104
      admin-api.address = ${CLUSTER_ADDR}
      admin-api.url = "http://"${CLUSTER_ADDR}":7104"
      ledger-api-user = "charlie"
    }
  }

  splitwell-app-clients {
    aliceSplitwell {
        admin-api.port = 5213
        admin-api.address = ${CLUSTER_ADDR}
        ledger-api = ${canton.remote-participants.validator1_participant.ledger-api}
        remote-scan.admin-api = ${canton.remote-scan-apps.svc_scan.admin-api}
        ledger-api-user = "alice"
    }
  }

  features.enable-testing-commands = yes
}
