canton {
  remote-participants {
    clusterParticipant1 {
      admin-api {
        port = 5002
        address = ${CLUSTER_ADDR}
      }
      ledger-api {
        port = 5001
        address = ${CLUSTER_ADDR}
      }
    }
  }
  participants {
    localParticipant1 {
      storage.type = memory
      admin-api.port = 5012
      ledger-api.port = 5011
      parameters {
        unsafe-enable-daml-lf-dev-version = yes
        will-corrupt-your-system-dev-version-support = yes
      }
    }
 }
}
