#!/usr/bin/env bash
set -euo pipefail

source ${TOOLS_LIB}/libcli.source
source ${TOOLS_LIB}/set-k8s-context

if [ "$K8S_CONTEXT" == "gcloud" ]; then
    echo "Deleting gcloud cluster..."
    source ${TOOLS_LIB}/gcloud-setup
    source ${TOOLS_LIB}/gcloud-delete
elif [ "$K8S_CONTEXT" == "minikube" ]; then
    echo "Deleting minikube cluster..."
    source ${TOOLS_LIB}/minikube-delete
fi

echo "Cluster deleted."
