#!/usr/bin/env bash
set -euo pipefail

source ${TOOLS_LIB}/libcli.source
source ${TOOLS_LIB}/set-k8s-context

if [ "$K8S_CONTEXT" == "gcloud" ]; then
    source ${TOOLS_LIB}/gcloud-setup
    source ${TOOLS_LIB}/gcloud-connect
elif [ "$K8S_CONTEXT" == "minikube" ]
    echo "Warning: running in minikube mode: 'cluster-connect' is a no-op."
fi
