#!/usr/bin/env bash

SUBCOMMAND_NAME="$1"
shift

set -euo pipefail

# shellcheck disable=SC1091
source "${TOOLS_LIB}/libcli.source"

SCRIPTNAME=${0##*/}

# Ensure we're running in a cluster deployment context

if [ -z "${GCP_CLUSTER_BASENAME-}" ]; then
    _error "GCP_CLUSTER_BASENAME is undefined, this script must be run in a deployment/ directory."
fi

##

SOURCE_IMAGE_TAG=$(get-snapshot-version)
GCP_CLUSTER_NAME="cn-${GCP_CLUSTER_BASENAME}net"
CLUSTER_DNS_NAME="${GCP_CLUSTER_BASENAME}.network.canton.global"

################################
### Utilities
################################

function _cluster_exists() {
  CLUSTER=$(gcloud container clusters list --filter "name:${GCP_CLUSTER_NAME}"  --format 'value(name)')

  if [ -z "${CLUSTER}" ]; then
      return 1
  else
      return 0
  fi
}

function _cluster_must_exist() {
    if ! _cluster_exists; then
        _error "Cluster does not exist, cannot continue."
    fi
}

function _docker_must_be_running() {
    if ! docker ps  > /dev/null 2>&1; then
        _error "Docker Daemon not found to be running."
    fi
}

function _production_gate() {
    if [ -n "${GCP_CLUSTER_PROD_LIKE-}" ] && [ -z "${CI-}" ]; then
        _error "Please deploy to this cluster only via CircleCI (https://github.com/DACH-NY/canton-network-node/tree/main/cluster#manually-deploying-via-ci)"
    fi
}

function _cluster_ip() {
    gcloud compute addresses list \
           --regions="${CLOUDSDK_COMPUTE_REGION}" \
           --filter "name:${GCP_CLUSTER_NAME}-ip" \
           --format 'value(address)'
}

function _needs_auth0_management_api_creds() {
    if [ -z "${AUTH0_MANAGEMENT_API_CLIENT_ID-}" ]; then
        _error "Environment variable AUTH0_MANAGEMENT_API_CLIENT_ID undefined.\nPlease see https://github.com/DACH-NY/canton-network-node#configure-auth0-environment"
      exit 1
    fi

    if [ -z "${AUTH0_MANAGEMENT_API_CLIENT_SECRET-}" ]; then
      _error "Environment variable AUTH0_MANAGEMENT_API_CLIENT_SECRET is undefined.\nPlease see https://github.com/DACH-NY/canton-network-node#configure-auth0-environment"
      exit 1
    fi
}

function _cluster_install_network_gateway() {
    # TODO(#4560): Use an empty passphrase until we manage secrets
    local -x PULUMI_CONFIG_PASSPHRASE=''

    _info "Creating a pulumi stack if it does not yet exist"

    _uses_pulumi_stack canton-network-gateway

    _info "Installing canton-network-gateway stack"

    # Spin up the canton-network-gateway pulumi stack
    _pulumi --stack "canton-network-gateway.${GCP_CLUSTER_BASENAME}" \
           --cwd "${REPO_ROOT}/cluster/pulumi/canton-network-gateway" \
           up -y
}

function _cluster_apply() {
    IMAGE_TAG=$1

    TOKEN_ARG=fixedTokens=false

    if [ -n "${CNCLUSTER_FIXED_TOKENS:-}" ]; then
        TOKEN_ARG=fixedTokens=true
    fi

    TICK_DURATION_ARG="tickDuration=null"

    if [ -n "${CNCLUSTER_TICK_DURATION:-}" ]; then
        TICK_DURATION_ARG="tickDuration=\"${CNCLUSTER_TICK_DURATION}\""
    fi

    _cluster_install_network_gateway

    _info "Applying jsonnet manifest"

    # Apply base cluster config
    jsonnet --tla-str gcpRegion="${CLOUDSDK_COMPUTE_REGION}" \
            --tla-str gcpRepoName="${GCP_REPO_NAME}" \
            --tla-str gcpDnsProject="${GCP_DNS_PROJECT}" \
            --tla-str gcpDnsSASecret="${GCP_DNS_SA_SECRET}" \
            --tla-str imageTag="${IMAGE_TAG}" \
            --tla-str ipAddr="$(_cluster_ip)" \
            --tla-str clusterName="${GCP_CLUSTER_NAME}" \
            --tla-str clusterDnsName="${CLUSTER_DNS_NAME}" \
            --tla-code $TOKEN_ARG \
            --tla-code "$TICK_DURATION_ARG" \
            "$REPO_ROOT/cluster/manifest/canton-network-config.jsonnet" \
        | kubectl apply -f -
}

function _cluster_papply() {
    IMAGE_TAG=$1

    VERSION_NUMBER=$(get-snapshot-version)

    args=(-c "VERSION_NUMBER=${VERSION_NUMBER}"
          -c "CLUSTER_BASENAME=${GCP_CLUSTER_BASENAME}")

    if [ -n "${IMAGE_TAG:-}" ]; then
        args+=(-c "IMAGE_TAG=${IMAGE_TAG}")
    fi

    if [ -n "${CNCLUSTER_FIXED_TOKENS:-}" ]; then
        args+=(-c "FIXED_TOKENS=${CNCLUSTER_FIXED_TOKENS}")
    else
        args+=(-c "FIXED_TOKENS=0")
    fi

    if [ -n "${CNCLUSTER_X_NODES:-}" ]; then
        args+=(-c "X_NODES=${CNCLUSTER_X_NODES}")
    else
        args+=(-c "X_NODES=0")
    fi

    _cluster_install_network_gateway

    _info "Applying Pulumi Stack"

    subcmd_pulumi canton-network up --yes --show-sames "${args[@]}"
}

function _cluster_update_module() {
    module=$1

    _log "Pushing module: ${module}"

    pushStateFile="${REPO_ROOT}/cluster/images/${module}/target/docker.push"

    if [ ! -f "${pushStateFile}" ]; then
        _error "Module not available for deployment (failure during either push or build): $1"
    fi

    imageTag=$(gawk -F '::' '{ print $2; }' < "${pushStateFile}")

    dnames=$(kubectl get deployment --all-namespaces -l moduleName="${module}" -o jsonpath='{.items[*].metadata}' \
                 | jq -r '.name + if has("namespace") then "@" + .namespace else "" end')

    if [ -z "$dnames" ]; then
        _warning "No deployment found for module: ${module}"
    else
        for dname in $dnames; do
            _log "Setting module for deployment: ${dname}"
            IFS='@' read -ra NAME_NS <<<"$dname"
            kubectl set image --namespace "${NAME_NS[1]-default}" "deployment/${NAME_NS[0]}" "${NAME_NS[0]}=${imageTag}"
        done

        _log "Deleting module pods to force restart: ${module}"

        # Delete the pods to force recreation. This forces a reload of
        # the docker image, even if the tag has not changed, due to
        # the imagePullPolicy setting of "Always".
        kubectl delete pods --all-namespaces -l "moduleName=${module}"
    fi
}

function _cluster_show() {
    _log "CLOUDSDK_COMPUTE_REGION : ${CLOUDSDK_COMPUTE_REGION}"
    _log "CLOUDSDK_CORE_PROJECT   : ${CLOUDSDK_CORE_PROJECT}"
    _log "GCP_REPO_NAME           : ${GCP_REPO_NAME}"

    _log "GCP_MASTER_IPV4_CIDR    : ${GCP_MASTER_IPV4_CIDR}"
    _log "GCP_CLUSTER_BASENAME    : ${GCP_CLUSTER_BASENAME}"
    _log "GCP_CLUSTER_NAME        : ${GCP_CLUSTER_NAME}"
    _log "CLUSTER_DNS_NAME        : ${CLUSTER_DNS_NAME}"

    _log ""
}

function _pulumi() {
    if ! [ -v PULUMI_BACKEND_URL ]; then
        # shellcheck disable=SC2016
      	_error 'The `PULUMI_BACKEND_URL` variable is not set. It should point to a GCP bucket, e.g. `gs://a-bucket-name`.'
    fi

    pulumi "$@"
}

# Create a pulumi stack for a given project (for the current cluster) if one does not yet exist
# Use cases:
# - unfortunately `pulumi up -y` still asks for confirmation of stack creation despite the `-y` flag
# - to bring a stack down if it exists - call this before calling refresh&down
function _uses_pulumi_stack() {

    pulumi_project=$1

    _pulumi --stack "${pulumi_project}.${GCP_CLUSTER_BASENAME}" \
           --cwd "${REPO_ROOT}/cluster/pulumi/${pulumi_project}" \
            stack init 2> /dev/null || true
}

### Cluster manageent


function _current_lockholder() {
    kubectl get secret cluster-lock -o jsonpath='{.data.lockholder}' 2>/dev/null | base64 --decode
}

function _current_lock_age() {
    lock_timestamp=$(kubectl get secret cluster-lock -o jsonpath='{.metadata.creationTimestamp}' 2>/dev/null | xargs -0 -I X date -d X +%s)
    current_timestamp=$(date +%s)
    echo "$((current_timestamp-lock_timestamp))"
}


function _current_lock_age_formatted() {
    age_secs="$(_current_lock_age)"
    echo "$((age_secs / 86400)) days(s), $(((age_secs % 86400) / 3600)) hour(s), $(((age_secs % 3600) / 60)) minute(s)"
}

function _assert_lock() {
    if [ -z "${SHARED_CLUSTER:-}" ]; then
        return
    fi

    if lockholder=$(_current_lockholder); then
        # CI asserts lock in shared cluster with a reduced strength
        # compared to the lock assert on developer workstations. The
        # cluster lock must be held, but we do not check user ID
        # (because we don't have a reliable way of finding the user ID
        # of the requesting user in CI.)
        if [ "${1-}" != "--for-ci" ]; then
            if [ "${lockholder}" != "$(whoami)" ]; then
                _error "Cluster already locked by: ${lockholder}"
            fi
        else
            _info "CI running with cluster lock held by: ${lockholder}"
        fi
    else
        _error "Cluster not locked. (See: https://github.com/DACH-NY/canton-network-node#deploy-a-build-to-a-cluster))"
    fi
}

################################
### Commands
################################

## Subcommand dictionary
##
##    This is a map from subcommand name to help text. The definition of the
##    sumcommand's functionality itself is in a shell function named
##    cluster_${subcommand_name}. The subcommand must be defined in the
##    whitelist dictionary to be invoked.

declare -A subcommand_whitelist

function _prompt_to_confirm() {
    _cluster_show

    if [ "${1-}" != "--no-lock" ]; then
        _assert_lock
    fi

    if [ -z "${GCP_CLUSTER_PROD_LIKE-}" ] ; then
        if [ -n "${CNCLUSTER_AUTOCONFIRM-}" ] ; then
            _warning "Automatically confirmed (via environment variable): ${subcommand_whitelist[${SUBCOMMAND_NAME}]}"
            return
        fi
    fi

    _confirm "Confirm: ${subcommand_whitelist[${SUBCOMMAND_NAME}]}"
}

###

subcommand_whitelist[activate]='Ensure cncluster is correctly authenticated to administer the cluster.'

function subcmd_activate() {
    _cluster_must_exist

    gcloud container clusters get-credentials "${GCP_CLUSTER_NAME}"
}

###

subcommand_whitelist[apply]='Apply the current manifest to the cluster. Accepts an optional tag for images.'

function subcmd_apply() {
    _production_gate
    _prompt_to_confirm

    IMAGE_TAG=${SOURCE_IMAGE_TAG}

    if [ -z "${1-}" ]; then
        if [ -z "${CNCLUSTER_SKIP_DOCKER_CHECK-}" ]; then
            _docker_must_be_running
            if ! make -C "${REPO_ROOT}" docker-check -j; then
                _error "Images missing from artifact registry, cannot apply."
            fi
        else
            _warning "docker-check bypassed with CNCLUSTER_SKIP_DOCKER_CHECK."
        fi
    else
        IMAGE_TAG=$1
        _warning "Overriding image tag (no docker-check): ${IMAGE_TAG} (was: ${SOURCE_IMAGE_TAG})"
    fi

    _cluster_apply "${IMAGE_TAG}"
}

###

subcommand_whitelist[deploy]='Rebuild local working copy and deploy to cluster.'

function subcmd_deploy() {
    _production_gate
    _prompt_to_confirm
    _docker_must_be_running

    make -C "${REPO_ROOT}" clean -j

    if ! make -C "${REPO_ROOT}" docker-build -j; then
        _error "Error building images, cannot apply."
    fi

    if ! make -C "${REPO_ROOT}" docker-push -j; then
        _error "Error pushing images, cannot apply."
    fi

    _cluster_apply "${SOURCE_IMAGE_TAG}"
}

###

subcommand_whitelist[push]='Update one or more modules running on a cluster'

function subcmd_push() {
    _production_gate
    _prompt_to_confirm
    _cluster_must_exist
    _docker_must_be_running

    # Assemble target lists for parallel clean and then build.
    clean_targets=""
    db_targets=""
    dpf_targets=""
    for module in "$@"
    do
        if [ ! -d "${REPO_ROOT}/cluster/images/${module}" ]; then
            _error "Unknown module: $module"
        fi

        clean_targets="${clean_targets} cluster/images/${module}/clean"
        db_targets="${db_targets} cluster/images/${module}/docker-build"
        dpf_targets="${dpf_targets} cluster/images/${module}/docker-push"
    done

    if [ -z "${db_targets}" ]; then
        _error "No modules specified."
    fi

    # Clean and build in parallel
    # shellcheck disable=SC2086
    make -C "${REPO_ROOT}" ${clean_targets} -j
    # shellcheck disable=SC2086
    make -C "${REPO_ROOT}" ${db_targets} -j

    # Run the push serially (since the push is ultimately serialized across
    # the shared upload link anyway, and adding contention won't help speed
    # things up).
    # shellcheck disable=SC2086
    make -C "${REPO_ROOT}" ${dpf_targets}

    # Update all the modules in cluster
    for module in "$@"; do
        _cluster_update_module "${module}"
    done
}

###

subcommand_whitelist[rlogs]='Stream a running application log stream to standard output'

function _json_log_format() {
    jq -R 'fromjson? | select(type == "object")' \
        | jq -r '"\(.["@timestamp"]) \(.level) [\(.logger_name)] - \(.message)"'
}

function subcmd_rlogs() {
    if [ "${1-}" = "--raw" ]; then
        raw=yes
        shift
    fi

    if [ -z "${1-}" ]; then
        _error "No namespace specified"
    fi

    if [ -z "${2-}" ]; then
        _error "No app specified"
    fi

    namespace=$1
    app=$2

    _cluster_must_exist

    if POD_SPEC=$(kubectl get pod \
                          -n "${namespace}" \
                          -l app="${app}" \
                          -o jsonpath='{range .items[0].metadata}{"-n "}{@.namespace}{" "}{@.name}{"\n"}{end}'  \
                          2> /dev/null); then


        if [ -n "${raw-}" ] ; then
            # shellcheck disable=SC2086
            kubectl logs ${POD_SPEC} "${app}" -f
        else
            # shellcheck disable=SC2086
            kubectl logs ${POD_SPEC} "${app}" -f | _json_log_format
        fi
    else
        _error "No pod for app found: ${app}"
    fi
}

###

subcommand_whitelist[logs]='View an running application log stream in lnav'

function subcmd_logs() {
    if [ -z "${1-}" ]; then
        _error "No namespace specified"
    fi

    if [ -z "${2-}" ]; then
        _error "No app specified"
    fi

    namespace=$1
    app=$2

    _cluster_must_exist

    if POD_SPEC=$(kubectl get pod \
                          -n "${namespace}" \
                          -l app="${app}" \
                          -o jsonpath='{range .items[0].metadata}{"-n "}{@.namespace}{" "}{@.name}{"\n"}{end}'  \
                          2> /dev/null); then

        LOGFILE=$(mktemp cnlogXXXXXXX.clog)
        # shellcheck disable=SC2086
        (kubectl logs ${POD_SPEC} "${app}" -f >> "${LOGFILE}" & lnav "${LOGFILE}")
        rm "${LOGFILE}"
    else
        _error "No pod for app found: ${app}"
    fi
}

subcommand_whitelist[gcloud_logs]='View the logs of an application through gcloud. This allows viewing historical logs'

function subcmd_gcloud_logs() {
    if [ "${1-}" = "--download-only" ]; then
        download_only=yes
        shift
    fi

    if [ -z "${1-}" ]; then
        _error "No namespace specified"
    fi

    if [ -z "${2-}" ]; then
        _error "No app specified"
    fi

    if [ -z "${3-}" ]; then
        _error "No filter specified. See https://cloud.google.com/logging/docs/view/logging-query-language for docs on the query language."
    fi

    namespace="$1"
    app="$2"
    filter="$3"

    _cluster_must_exist

    LOGFILE=$(mktemp "$namespace"-"$app"-XXXX.clog)
    _info "Writing log to $LOGFILE"

    function gcloud_read() {
        gcloud logging read --order asc --format 'json(jsonPayload)' "resource.labels.cluster_name=$GCP_CLUSTER_NAME AND resource.labels.namespace_name=$namespace AND resource.labels.container_name=$app AND $filter"
    }
    function jq_parse() {
        jq --stream -cn 'fromstream(1 | truncate_stream(inputs) | select(.[0][0] == "jsonPayload")) | .jsonPayload'
    }


    if [ -z "${download_only-}" ]
    then
        gcloud_read | jq_parse > "$LOGFILE" &
        lnav "$LOGFILE"
    else
        gcloud_read | jq_parse > "$LOGFILE"
    fi
}

###

subcommand_whitelist[set_machine_type]='Rebuilds the default node pool with current cluster machine type and count'

function subcmd_set_machine_type() {
    _prompt_to_confirm
    _cluster_must_exist

    _info "Creating temporary node pool..."
    gcloud container node-pools create temp-pool --cluster "cn-${GCP_CLUSTER_BASENAME}net" \
           --machine-type "${GCP_CLUSTER_NODE_TYPE}" --num-nodes 1 \
           || _error "Could not create node pool with machine type: ${GCP_CLUSTER_NODE_TYPE}"

    _info "Deleting default node pool..."
    gcloud container node-pools delete default-pool --quiet --cluster "cn-${GCP_CLUSTER_BASENAME}net" \
           || _error "Could not delete default node pool. Terminating early."

    _info "Recreating default node pool..."
    gcloud container node-pools create default-pool --cluster "cn-${GCP_CLUSTER_BASENAME}net" \
           --machine-type "${GCP_CLUSTER_NODE_TYPE}" \
           --num-nodes 2 \
           --enable-autoscaling \
           --min-nodes 2 \
           --max-nodes "${GCP_CLUSTER_MAX_NODES}" \
           || _error "Could not recreate default node pool. Terminating early."

    _info "Deleting temporary node pool..."
    gcloud container node-pools delete temp-pool --quiet --cluster "cn-${GCP_CLUSTER_BASENAME}net" \
           || _error "Could not delete temporary node pool."
}

###

subcommand_whitelist[get_dns01_key_id]='Get the gcloud service account key id used for dns challenges.'

function subcmd_get_dns01_key_id() {
    subcmd_pulumi infra stack output --show-secrets dnsPrivateKey | base64 -d | jq -r '.private_key_id'
}

subcommand_whitelist[update_dns01_secret]='Update the gcloud service account key used for letsencrypt dns challenges.'

function subcmd_update_dns01_secret() {
    if kubectl get secret "$GCP_DNS_SA_SECRET" > /dev/null 2>&1; then
      kubectl delete secret "$GCP_DNS_SA_SECRET"
    fi
    subcmd_pulumi infra stack output --show-secrets dnsPrivateKey | base64 --decode > /tmp/key.json
    kubectl create secret generic "$GCP_DNS_SA_SECRET" \
            --from-file=key.json=/tmp/key.json
    rm /tmp/key.json
}

subcommand_whitelist[create]='Create a cluster from scratch.'

function subcmd_create() {
    _prompt_to_confirm --no-lock

    if _cluster_exists; then
        _error "Cluster already exists."
    else
        #### Cluster can be resized from deployment directories with the following command:
        ####   gcloud container clusters resize "cn-${GCP_CLUSTER_BASENAME}net" --num-nodes 4
        gcloud container clusters create "${GCP_CLUSTER_NAME}" \
               --create-subnetwork name="${GCP_CLUSTER_NAME}-subnet" \
               --enable-master-authorized-networks \
               --enable-ip-alias \
               --enable-private-nodes \
               --machine-type "${GCP_CLUSTER_NODE_TYPE}" \
               --num-nodes 2 \
               --master-ipv4-cidr "${GCP_MASTER_IPV4_CIDR}" \
               --node-locations "${CLOUDSDK_COMPUTE_REGION}-a" \
               --node-labels digitalasset.com/cluster-name="${GCP_CLUSTER_NAME}" \
               --addons=GcePersistentDiskCsiDriver \
               --enable-autoscaling \
               --min-nodes 2 \
               --max-nodes "${GCP_CLUSTER_MAX_NODES}"

        #### Enable Firewall Access
        gcloud container clusters update "${GCP_CLUSTER_NAME}" \
               --enable-master-authorized-networks \
               --master-authorized-networks "${GCP_VPN_NETS}"

        #### Delete default firewall rules, if they exist.
        if (gcloud compute firewall-rules delete\
                         default-allow-rdp \
                         default-allow-icmp \
                         default-allow-ssh \
                         --quiet 2> /dev/null); then
            _warning "Deleted default firewall rules."
        else
            _log "Default firewalls already removed and do not need to be deleted."
        fi
    fi

    _log "Authenticating to newly created cluster."
    subcmd_activate

    #### Open port 15017 in GKE firewall, see https://istio.io/latest/docs/setup/platform-setup/gke/
    _log "Opening port 15017 in GKE firewall"
    FW_NAME=$(gcloud compute firewall-rules list --filter="name~gke-cn-${GCP_CLUSTER_BASENAME}net-[0-9a-z]*-master" --format=json | jq -r '.[].name')
    gcloud compute firewall-rules update "${FW_NAME}" --allow tcp:10250,tcp:443,tcp:15017

    _log "Activating infrastructure Pulumi stack"
    subcmd_pulumi infra up --yes

    _log "Updating DNS01 secret"
    #### Store DNS service account secret for cert-manager DNS-01 authorizer to use
    #### TODO(#1447)
    subcmd_update_dns01_secret

    _log "Determining cluster ingress IP address"
    IPADDR=$(_cluster_ip)

    if [ -z "${IPADDR}" ]; then
        _error "Could not determine cluster IP address."
    fi

    _log "Cluster at IP ${IPADDR}, updating cluster secrets..."
    subcmd_update_secrets

    _log "Cluster ready."
}

###

subcommand_whitelist[reset]='Reset the state of the cluster to a fully blank state. Clears all data.'

function _cluster_reset() {
    _info "Deleting all stateful sets..."
    kubectl delete StatefulSet --all-namespaces -l clusterName="${GCP_CLUSTER_NAME}"

    _info "Deleting all deployments..."
    kubectl delete Deployment --all-namespaces -l clusterName="${GCP_CLUSTER_NAME}"

    _info "Deleting all pods..."
    kubectl delete Pods --all-namespaces -l clusterName="${GCP_CLUSTER_NAME}"

    _info "Deleting all services..."
    kubectl delete Service --all-namespaces -l clusterName="${GCP_CLUSTER_NAME}"

    _info "Deleting all persistent volume claims..."
    kubectl delete PersistentVolumeClaim --all-namespaces -l clusterName="${GCP_CLUSTER_NAME}"

    _info "Uninstalling Pulumi canton-network-gateway stack"
    # TODO(#4560): Use an empty passphrase until we manage secrets
    local -x PULUMI_CONFIG_PASSPHRASE=''
    _uses_pulumi_stack canton-network-gateway
    subcmd_pulumi canton-network-gateway refresh --yes
    subcmd_pulumi canton-network-gateway down --yes

    _info "Uninstalling Pulumi canton-network stack"
    _uses_pulumi_stack canton-network
    subcmd_pulumi canton-network refresh --yes
    subcmd_pulumi canton-network down --yes

    _info "Uninstalling Pulumi sv-runbook stack"
    _uses_pulumi_stack sv-runbook
    subcmd_pulumi sv-runbook refresh --yes
    subcmd_pulumi sv-runbook down --yes

    _info "Cluster in reset/idle state."
}

function subcmd_reset() {
    _prompt_to_confirm

    _cluster_reset "$@"
}

###

subcommand_whitelist[obliterate_state]='Delete ALL CANTON NETWORK RESOURCES from the cluster.'

function subcmd_obliterate_state() {
    _production_gate
    _prompt_to_confirm
    _cluster_must_exist

    _info "Deleting all Canton Network Namespaces..."
    kubectl delete Namespace -l cnjClusterName="${GCP_CLUSTER_NAME}"

    _info "Full delete... deleting default namespace deployments..."
    kubectl delete Deployment -l cnjClusterName="${GCP_CLUSTER_NAME}"

    _info "Full delete... deleting default namespace services..."
    kubectl delete Service -l cnjClusterName="${GCP_CLUSTER_NAME}"

    # Delete the external service manually, since it does not have
    # the CNJ prefix cluster name label.
    kubectl delete Service external --ignore-not-found=true

    _info "Cluster state obliterated"
}

###

subcommand_whitelist[ci_papply]='Run only by CircleCI'

function subcmd_ci_papply() {
    _assert_lock --for-ci

    # A CI-specific variant of 'cncluster apply' that removes the need
    # for manual confirmation and ensures that all pods are deleted
    # and recreated during the apply. With current (September 2022)
    # DevNet, the ledger is stored in memory and the pod reset
    # has the effect of clearing out all ledger state.

    if [ -z "${CI-}" ]; then
        _error "This subcommand is available to CI jobs only."
    fi

    _cluster_show

    _cluster_reset
    _cluster_papply "${SOURCE_IMAGE_TAG}"
}

###

subcommand_whitelist[ci_apply]='Run only by CircleCI'

function subcmd_ci_apply() {
    _assert_lock --for-ci

    # A CI-specific variant of 'cncluster apply' that removes the need
    # for manual confirmation and ensures that all pods are deleted
    # and recreated during the apply. With current (September 2022)
    # DevNet, the ledger is stored in memory and the pod reset
    # has the effect of clearing out all ledger state.

    if [ -z "${CI-}" ]; then
        _error "This subcommand is available to CI jobs only."
    fi

    _cluster_show

    _cluster_reset
    _cluster_apply "${SOURCE_IMAGE_TAG}"
}

###

subcommand_whitelist[ci_assert_fresh_lock]='Run only by CircleCI'

function subcmd_ci_assert_fresh_lock() {
    if [ -z "${SHARED_CLUSTER:-}" ]; then
        _info "Cluster not marked as shared. No lock to check."
        exit 0
    fi

    if lockholder=$(_current_lockholder); then
        age_secs="$(_current_lock_age)"

        if (( age_secs > 21600 )); then
            _error "Cluster lock held by ${lockholder} is stale. Lock age: $(_current_lock_age_formatted)"
        else
            _info "Cluster lock held by ${lockholder} is fresh. Lock age: $(_current_lock_age_formatted)"
        fi
    else
        _info "Cluster sharable but not locked. No lock to check."
    fi
}

###

subcommand_whitelist[ci_reset_unlock]='Run only by CircleCI'

function subcmd_ci_reset_unlock() {
    # A CI-specific variant of 'cncluster reset' and 'cncluster unlock' that
    # removes the need for manual confirmation and is executed only on shared
    # clusters (like scratchnet).

    if [ -z "${CI-}" ]; then
        _error "This subcommand is available to CI jobs only."
    fi

    if [ -z "${SHARED_CLUSTER:-}" ]; then
        _info "Not resetting and unlocking because not on a shared cluster (like scratchnet)."
        return
    fi

    _cluster_reset
    if lockholder=$(_current_lockholder); then
        _unlock
        _info "Cluster unlocked. Former lockholder was: ${lockholder}"
    else
        _info "Cluster was not locked."
    fi
}

###

subcommand_whitelist[delete]='Delete all cluster resources.'

function subcmd_delete() {
    _prompt_to_confirm
    _cluster_must_exist

    _info "Taking down pulumi infrastructure stack."
    subcmd_pulumi infra down --yes

    _info "Deleting GKE cluster."
    gcloud container clusters delete --quiet "${GCP_CLUSTER_NAME}"

    _info "Cluster deleted."
}

###

subcommand_whitelist[ipaddr]='Display the cluster\s main IP address.'

function subcmd_ipaddr() {
    _cluster_must_exist
    _cluster_ip
}

###

subcommand_whitelist[eipaddr]='Display the cluster\s Egress IP address. (May not be comprehensive)'

function subcmd_eipaddr() {
    _cluster_must_exist

    kubectl exec -n docs "$(kubectl get pods -n docs -lapp=docs -o name)" -- \
            curl -s http://checkip.amazonaws.com
}

###

subcommand_whitelist[start_frontends]='Run the self-hosted frontends for the preflight test'

function subcmd_start_frontends() {
    _log "Starting frontends needed for preflight check..."

    (cd "${REPO_ROOT}" && \
         NETWORK_APPS_ADDRESS=${GCP_CLUSTER_BASENAME}.network.canton.global ./start-frontends.sh -d -p)
}

###

subcommand_whitelist[preflight]='Run the runbook preflight test against the cluster'

function subcmd_preflight() {
    _log "Starting preflight"

    set +e
    tmux has-session -t cn-frontends
    local tmux_session_check=$?
    set -e

    if [ $tmux_session_check -eq 0 ]; then
        _error "CN Frontends are already running. Please run \`stop-frontends.sh\` from the root and try again."
    fi;

    postgres=$(docker ps -q -f name=postgres-for-canton-coin)

    if [ -n "$postgres" ]; then
        _error "postgres container is already running. Please run \`stop-canton.sh\` from the root and try again."
    fi;

    subcmd_start_frontends
    cd "${REPO_ROOT}" && scripts/start-postgres-for-preflight.sh

    set +e
    subcmd_sbt_for_preflight "apps-app/testOnly *PreflightIntegrationTest"
    local test_result=$?
    set -e

    _log "Stopping postgres..."
    cd "${REPO_ROOT}" && scripts/stop-postgres-for-preflight.sh

    _log "Stopping frontends..."
    cd "${REPO_ROOT}" && ./stop-frontends.sh

    return $test_result
}

###

subcommand_whitelist[sbt_for_preflight]='Runs Sbt, as if for the runbook preflight test.'

function subcmd_sbt_for_preflight() {
    _needs_auth0_management_api_creds

    (cd "${REPO_ROOT}" && \
         DOMAIN_URL=http://${GCP_CLUSTER_BASENAME}.network.canton.global:5008 \
         NETWORK_APPS_ADDRESS=${GCP_CLUSTER_BASENAME}.network.canton.global \
         NETWORK_APPS_ADDRESS_PROTOCOL=https \
         VALIDATOR_USER_NAME=manual_preflight \
             sbt -DAUTH0_TENANT=dev "$@")
}

###

subcommand_whitelist[preflight_sv]='Run the SV runbook preflight test against the cluster'

function subcmd_preflight_sv() {
    _log "Starting SV preflight"

    cd "${REPO_ROOT}" && \
        NETWORK_APPS_ADDRESS="${GCP_CLUSTER_BASENAME}.network.canton.global" \
        sbt "apps-app/testOnly *PreflightSvIntegrationTest"
}

###

subcommand_whitelist[info]='Display information on current cluster configuration, including image tags'

function subcmd_info() {
    _cluster_show
    _cluster_must_exist

    kubectl get po -o json \
            --all-namespaces \
            -l clusterName="${GCP_CLUSTER_NAME}" \
        | jq -r '(["NAMESPACE", "POD-NAME", "CONTAINER", "IMAGE", "MEM-LIMIT", "CPU-REQ", "CPU-LIMIT"],(.items[] | .metadata as $pod | .spec.containers[] as $c | $c.resources as $r | [$pod.namespace, $pod.name, $c.name, ($c.image | split(":")[1]), $r.limits.memory, $r.requests.cpu, $r.limits.cpu]))|@tsv' \
        | sort \
        | column -t

}

###

subcommand_whitelist[show]='Display information on current cluster configuration'

function subcmd_show() {
    _cluster_show
    _cluster_must_exist
}

###

subcommand_whitelist[top]='Display current CPU and memory usage by both node and pod'

function subcmd_top() {
    _cluster_show
    _cluster_must_exist

	_log "Node Usage:"
    kubectl top node

    _log ""
	_log "Pod Usage:"
    kubectl top pod --all-namespaces -l clusterName="${GCP_CLUSTER_NAME}"
}

###

subcommand_whitelist[pods]='Display a list of cluster pods'

function subcmd_pods() {
    _cluster_show

    kubectl top node

    _log ""
    kubectl get pods -A | grep -v kube-system
}

###

subcommand_whitelist[wait]='Wait for the cluster to reach a fully ready state'

function subcmd_wait() {
    _cluster_show

    _log "Waiting for all pods to become ready"
    kubectl wait --for=condition=Ready --all pod --timeout=5m --all-namespaces
}

###

subcommand_whitelist[update_secrets]='Update Auth0 Kubernetes Secrets'

AUTH_BASE_URL='https://canton-network-dev.us.auth0.com'

function _set_auth0_ui_secret() {
    SECRET_NAME=$1
    CLIENT_ID=$2
    NAMESPACE=$3

    # Delete secret if it exists, easier than editing existing secrets
    if kubectl get --namespace "$NAMESPACE" secret "${SECRET_NAME}" > /dev/null 2>&1; then
        kubectl delete --namespace "$NAMESPACE" secret "${SECRET_NAME}"
    fi

    kubectl create --namespace "$NAMESPACE" secret generic "${SECRET_NAME}" \
      --from-literal=url="${AUTH_BASE_URL}" \
      --from-literal=client-id="${CLIENT_ID}"
}

function _set_auth0_secret() {
  SECRET_NAME=$1
  CLIENT_ID=$2
  CLIENT_SECRET=$3
  NAMESPACE=$4

  _log "Setting secret $SECRET_NAME ($NAMESPACE)"

  USER_NAME="${CLIENT_ID}@clients"
  WELL_KNOWN_URL="${AUTH_BASE_URL}/.well-known/openid-configuration"

  # Delete secret if it exists, easier than editing existing secrets
  if kubectl get --namespace "$NAMESPACE" secret "${SECRET_NAME}" > /dev/null 2>&1; then
      kubectl delete --namespace "$NAMESPACE" secret "${SECRET_NAME}"
  fi

  # Create the namespace if it does not exist (no harm should be caused if it does)
  kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -

  if [ -n "${CNCLUSTER_FIXED_TOKENS:-}" ]; then
    TOKEN_RESPONSE=$(curl -s --show-error --fail --request POST \
      --url https://canton-network-dev.us.auth0.com/oauth/token \
      --header 'content-type: application/json' \
      --data "{\"client_id\":\"$CLIENT_ID\",\"client_secret\":\"$CLIENT_SECRET\",\"audience\":\"https://canton.network.global\",\"grant_type\":\"client_credentials\"}")

    ACCESS_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r ".access_token")

    kubectl create --namespace "$NAMESPACE" secret generic "${SECRET_NAME}" \
      --from-literal=ledger-api-user="${USER_NAME}" \
      --from-literal=token="${ACCESS_TOKEN}"
  else
    kubectl create --namespace "$NAMESPACE" secret generic "${SECRET_NAME}" \
      --from-literal=url="${WELL_KNOWN_URL}" \
      --from-literal=client-id="${CLIENT_ID}" \
      --from-literal=client-secret="${CLIENT_SECRET}" \
      --from-literal=ledger-api-user="${USER_NAME}"
  fi
}

function _set_auth0_api_user() {
    # Add/update secret only containing the `ledger-api-user` field
    local -r APP_NAME="$1"
    local -r NAMESPACE="$2"
    local -r CLIENT_ID="$3"
    local SECRET_NAME="cn-app-${APP_NAME,,}-ledger-api-auth"
    SECRET_NAME="${SECRET_NAME//_/-}"

    _log "Setting user-only secret $SECRET_NAME ($NAMESPACE)"

    # Delete secret if it exists, easier than editing existing secrets
    if kubectl get --namespace "$NAMESPACE" secret "${SECRET_NAME}" &> /dev/null; then
       kubectl delete --namespace "$NAMESPACE" secret "${SECRET_NAME}"
    fi

    kubectl create --namespace "$NAMESPACE" secret generic "${SECRET_NAME}" \
            "--from-literal=ledger-api-user=${CLIENT_ID}@clients"
}

function _set_sv_key_secret() {
    NAMESPACE=$1
    PUBLIC_KEY=$2
    PRIVATE_KEY=$3

    SECRET_NAME="cn-app-sv-key"

    _log "Setting secret $SECRET_NAME ($NAMESPACE)"

    # Delete secret if it exists, easier than editing existing secrets
    if kubectl get --namespace "$NAMESPACE" secret "${SECRET_NAME}" > /dev/null 2>&1; then
        kubectl delete --namespace "$NAMESPACE" secret "${SECRET_NAME}"
    fi

    kubectl create --namespace "$NAMESPACE" secret generic "${SECRET_NAME}" \
      --from-literal=public="${PUBLIC_KEY}" \
      --from-literal=private="${PRIVATE_KEY}"
}

function subcmd_update_secrets() {
  _needs_auth0_management_api_creds

  _log "Fetching token for management API from auth0"

  AUTH0_MANAGEMENT_API_URL="https://canton-network-dev.us.auth0.com/api/v2"

    TOKEN=$(curl -sSLf \
         --url https://canton-network-dev.us.auth0.com/oauth/token \
         --header 'content-type: application/json' \
         --data "{\"client_id\": \"$AUTH0_MANAGEMENT_API_CLIENT_ID\",\"client_secret\": \"$AUTH0_MANAGEMENT_API_CLIENT_SECRET\",\"audience\": \"$AUTH0_MANAGEMENT_API_URL/\",\"grant_type\":\"client_credentials\"}" | jq -r '.access_token')

  _log "Fetching secrets from auth0"
  all=$(curl -s --show-error --fail -H "Authorization: Bearer $TOKEN" ${AUTH0_MANAGEMENT_API_URL}/clients)

  local -Ar appToClientId=(
      [validator]='cf0cZaTagQUN59C1HBL2udiIBdFh2CWq'
      [splitwell]='ekPlYxilradhEnpWdS80WfW63z1nHvKy'
      [splitwell_validator]='hqpZ6TP0wGyG2yYwhH6NLpuo0MpJMQZW'
      [sv1]='OBpJ9oTyOLuAKF0H2hhzdSFUICt0diIn'
      [sv2]='rv4bllgKWAiW9tBtdvURMdHW42MAXghz'
      [sv3]='SeG68w0ubtLQ1dEMDOs4YKPRTyMMdDLk'
      [sv4]='CqKgSbH54dqBT7V1JbnCxb6TfMN8I1cN'
      [sv1_validator]='7YEiu1ty0N6uWAjL8tCAWTNi7phr7tov'
      [sv2_validator]='5N2kwYLOqrHtnnikBqw8A7foa01kui7h'
      [sv3_validator]='V0RjcwPCsIXqYTslkF5mjcJn70AiD0dh'
      [sv4_validator]='FqRozyrmu2d6dFQYC4J9uK8Y6SXCVrhL'
  )

  local -Ar namespaceToUiClientId=(
    [validator1]='5RJeTm41IwUs8VbbnZHxFEPjCX5ojfaK'
    [splitwell]='eeMLQ6qljnUcg9o1sJRbt4suCn2CYbSL'
    [sv-1]='Ez65bly75dMqcKxQiJDF8rIP9xxkxV3J'
    [sv-2]='G6Y5KYuiyOb0bnllGyQ2JKwjpwZM0Ai6'
    [sv-3]='cgxHguMv32JLeew9S6wBDgNPHmPCIKaP'
    [sv-4]='VoSuAamXhvwISHGgaCtULYmbRIWbQeTb'
  )

  for i in \
    "cn-app-validator-ledger-api-auth validator validator1" \
    "cn-app-sv-ledger-api-auth sv1 svc" \
    "cn-app-sv-ledger-api-auth sv1 sv-1" \
    "cn-app-validator-ledger-api-auth sv1_validator sv-1" \
    "cn-app-sv-ledger-api-auth sv2 sv-2" \
    "cn-app-validator-ledger-api-auth sv2_validator sv-2" \
    "cn-app-sv-ledger-api-auth sv3 sv-3" \
    "cn-app-validator-ledger-api-auth sv3_validator sv-3" \
    "cn-app-sv-ledger-api-auth sv4 sv-4" \
    "cn-app-validator-ledger-api-auth sv4_validator sv-4" \
    "cn-app-splitwell-ledger-api-auth splitwell splitwell" \
    "cn-app-validator-ledger-api-auth splitwell_validator splitwell"
  do
    # shellcheck disable=SC2086
    set -- $i

    client_id="${appToClientId[$2]}"
    secret=$(echo "$all" | jq -r ".[] | select(.client_id==\"$client_id\") | .client_secret")

    # SECRET_NAME, CLIENT_ID,  CLIENT_SECRET, NAMESPACE=$4

    _set_auth0_secret "$1" "$client_id" "$secret" "$3"
  done

  for i in sv1 sv1_validator
  do
      client_id="${appToClientId[$i]}"
      _set_auth0_api_user "$i" svc "$client_id"
  done

  for i in \
    "cn-app-wallet-ui-auth validator1" \
    "cn-app-directory-ui-auth validator1" \
    "cn-app-splitwell-ui-auth validator1" \
    "cn-app-wallet-ui-auth splitwell" \
    "cn-app-wallet-ui-auth sv-1" \
    "cn-app-wallet-ui-auth sv-2" \
    "cn-app-wallet-ui-auth sv-3" \
    "cn-app-wallet-ui-auth sv-4" \
    "cn-app-sv-ui-auth sv-1" \
    "cn-app-sv-ui-auth sv-2" \
    "cn-app-sv-ui-auth sv-3" \
    "cn-app-sv-ui-auth sv-4"
  do
    # shellcheck disable=SC2086
    set -- $i
    client_id="${namespaceToUiClientId[$2]}"
    _set_auth0_ui_secret "$1" "$client_id" "$2"
  done

  local -Ar svPublicKeys=(
      [sv-2]='MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEsRRntNkOLF2Wh7JxV0rBQPgT+SendIjFLXKUXCrLbVHqomkypHQiZP8OgFMSlByOnr81fqiUt3G36LUpg/fmgA=='
      [sv-3]='MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE0fnbBQiM7UiSNaV6tjPq5lK2buIx5L5nzUuhYWxBk341nFChcbK9pDEO4O6gdxexb/OQP6RhQkDOTDdTCr77CA=='
      [sv-4]='MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEa76d2OWmkpCQ2dTWsWyhofV3tOGdlkhoCnPpY7BbQhCb0s3laR1vp57JYu/d5Cf+332PF2XrgjC0yBWUqM4syQ=='
  )

  local -Ar svPrivateKeys=(
      [sv-2]='MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgOouqxvUir3C9+2apEdOUC40XrbLTdkbBIK78o2m3lOKhRANCAASxFGe02Q4sXZaHsnFXSsFA+BP5J6d0iMUtcpRcKsttUeqiaTKkdCJk/w6AUxKUHI6evzV+qJS3cbfotSmD9+aA'
      [sv-3]='MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg+8jKTfry5rkitnvy9Dyh5uPVKTzcKu3rrPZyrVW9e/KhRANCAATR+dsFCIztSJI1pXq2M+rmUrZu4jHkvmfNS6FhbEGTfjWcUKFxsr2kMQ7g7qB3F7Fv85A/pGFCQM5MN1MKvvsI'
      [sv-4]='MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgE5r1MpzeTmvYjtiVLDASw63VA2pfQm4psX7XlUJU8fGhRANCAARrvp3Y5aaSkJDZ1NaxbKGh9Xe04Z2WSGgKc+ljsFtCEJvSzeVpHW+nnsli793kJ/7ffY8XZeuCMLTIFZSozizJ'
  )

  for i in sv-2 sv-3 sv-4
  do
      _set_sv_key_secret $i "${svPublicKeys[$i]}" "${svPrivateKeys[$i]}"
  done
}

###

subcommand_whitelist[help]='Display this help message.'

function subcmd_help() {
    _info "Usage: $SCRIPTNAME {subcommand} [options...]"

    _info "Valid subcommands: "
    readarray -t sorted < <(printf '%s\n' "${!subcommand_whitelist[@]}" | sort)

    for ii in "${sorted[@]}";
    do
        if [[ "$ii" != ci_* && "$ii" != _* ]]; then
            printf '%s\t%s\n' "${ii}" "${subcommand_whitelist[${ii}]}"
        fi
    done | column -ts $'\t'
}

###

subcommand_whitelist[_autocomplete]='Utility for autocomplete.'

function subcmd__autocomplete() {
    readarray -t sorted < <(printf '%s\n' "${!subcommand_whitelist[@]}" | sort)

    for ii in "${sorted[@]}";
    do
        if [[ "$ii" != ci_* && "$ii" != _* ]]; then
            echo "${ii}"
        fi
    done

}


###

subcommand_whitelist[pulumi]="Execute a Pulumi command in the context of the current cluster"

function subcmd_pulumi() {
    _production_gate

    pulumi_project="${1-}"
    pulumi_cmd="${2-}"
    if [ -z "${pulumi_cmd}" ] || [ -z "${pulumi_project}" ]; then
        _error "Usage: $SCRIPTNAME pulumi <pulumi-project> <pulumi-cmd> [options...]"
    fi

    shift 2

    # TODO(#4560): Use an empty passphrase until we manage secrets
    local -x PULUMI_CONFIG_PASSPHRASE=''

    _pulumi --stack "${pulumi_project}.${GCP_CLUSTER_BASENAME}" \
           --cwd "${REPO_ROOT}/cluster/pulumi/${pulumi_project}" \
            "$pulumi_cmd" "$@"
}

###

subcommand_whitelist[papply]="Apply the current Pulumi configuration (--preview to preview only)"

function subcmd_papply() {
    _production_gate
    _cluster_must_exist

    POSITIONAL_ARGS=()
    while [[ $# -gt 0 ]]; do
        case $1 in
            --preview)
                preview="yes"
                shift
                ;;
            -*)
                _error "Unknown option $1"
                ;;
            *)
                POSITIONAL_ARGS+=("$1")
                shift
                ;;
        esac
    done
    set -- "${POSITIONAL_ARGS[@]}"

    VERSION_NUMBER=$(get-snapshot-version)

    if [ -n "${1-}" ]; then
        IMAGE_TAG=$1
        _warning "Overriding image tag: ${IMAGE_TAG} (was: ${SOURCE_IMAGE_TAG})"
    fi

    args=(-c "VERSION_NUMBER=${VERSION_NUMBER}"
          -c "CLUSTER_BASENAME=${GCP_CLUSTER_BASENAME}")

    if [ -n "${IMAGE_TAG:-}" ]; then
        args+=(-c "IMAGE_TAG=${IMAGE_TAG}")
    fi

    if [ -n "${CNCLUSTER_FIXED_TOKENS:-}" ]; then
        args+=(-c "FIXED_TOKENS=${CNCLUSTER_FIXED_TOKENS}")
    else
        args+=(-c "FIXED_TOKENS=0")
    fi

    if [ -n "${CNCLUSTER_X_NODES:-}" ]; then
        args+=(-c "X_NODES=${CNCLUSTER_X_NODES}")
    else
        args+=(-c "X_NODES=0")
    fi

    if [ -n "${preview:-}" ]; then
        _info "Previewing apply."
        make -C "${REPO_ROOT}" cluster/helm/build -j
        subcmd_pulumi canton-network preview --show-sames --json "${args[@]}"
    else
        _prompt_to_confirm
        make -C "${REPO_ROOT}" cluster/build -j

        if [ -z "${IMAGE_TAG:-}" ]; then
            if [ -z "${CNCLUSTER_SKIP_DOCKER_CHECK-}" ]; then
                _docker_must_be_running
                if ! make -C "${REPO_ROOT}" docker-check -j; then
                    _error "Images missing from artifact registry, cannot apply."
                fi
            else
                _warning "docker-check bypassed with CNCLUSTER_SKIP_DOCKER_CHECK."
            fi
        fi

        _cluster_install_network_gateway
        subcmd_pulumi canton-network up --yes --skip-preview "${args[@]}"
    fi
}

###

subcommand_whitelist[pdown]="Take the current Pulumi configuration down"

function subcmd_pdown() {
    _production_gate
    _prompt_to_confirm
    _cluster_must_exist

    subcmd_pulumi canton-network down --yes
}

###

subcommand_whitelist[prefresh]="Refresh the Pulumi resources in the stack"

function subcmd_prefresh() {
    _production_gate
    _prompt_to_confirm
    _cluster_must_exist

    subcmd_pulumi canton-network refresh --yes
}

###

subcommand_whitelist[papply_sv]="Apply the sv-runbook Pulumi stack"

function subcmd_papply_sv(){
    local -x TARGET_CLUSTER="${1-}"
    if [ -z "$TARGET_CLUSTER" ]; then
        _error "Usage: $SCRIPTNAME papply_sv <target-domain-cluster> [<charts-version>]"
    fi

    _production_gate
    _prompt_to_confirm
    _cluster_must_exist

    local -x CHARTS_VERSION="${2-}"

    subcmd_pulumi sv-runbook up --yes
}

###

subcommand_whitelist[ci_papply_sv]='Run only by CircleCI'

function subcmd_ci_papply_sv() {
    _assert_lock --for-ci

    # A CI-specific variant of 'cncluster papply_sv' that removes the need
    # for manual confirmation, and also always uses the same target cluster
    # as the one the sv is deployed on.

    if [ -z "${CI-}" ]; then
        _error "This subcommand is available to CI jobs only."
    fi

    _cluster_show

    local -x TARGET_CLUSTER="${GCP_CLUSTER_BASENAME}"

    subcmd_pulumi sv-runbook up --yes
}

###

subcommand_whitelist[pdown_sv]="Take the current sv-runbook Pulumi configuration down"

function subcmd_pdown_sv(){
    _production_gate
    _prompt_to_confirm
    _cluster_must_exist

    subcmd_pulumi sv-runbook down --yes
}

###

subcommand_whitelist[lock]="Attempt to claim the lock on a cluster."

function subcmd_lock() {
    if lockholder=$(_current_lockholder); then
        if [ "${lockholder}" = "$(whoami)" ]; then
            _info "Cluster is already locked to you. Lock age: $(_current_lock_age_formatted)."
        else
            _error "Cluster already locked by: ${lockholder}. Lock age: $(_current_lock_age_formatted)."
        fi
    else
        kubectl create secret generic cluster-lock --from-literal=lockholder="$(whoami)" > /dev/null
        _info "Cluster lock claimed successfully."
    fi
}

###

subcommand_whitelist[lockholder]="Print the current lockholder, if any, for the cluster."

function subcmd_lockholder() {
    _current_lockholder
}

###

subcommand_whitelist[unlock]="Release the lock on a cluster"

function _unlock() {
  kubectl delete secret cluster-lock > /dev/null
}

function _check_reset_and_unlock() {
    s=$(kubectl get StatefulSets -A --no-headers 2>/dev/null)
    if [ -n "$s" ]; then
        echo -e "Cluster not reset, it is recommended to reset it before unlocking. Reset now?"
        read -r -p '[y/n]: '
        if [ "${REPLY}" != 'n' ]; then
            _cluster_reset
            echo "Done resetting, unlocking.."
        fi
    fi
    _unlock
}

function subcmd_unlock() {
    _assert_lock

    if lockholder=$(_current_lockholder); then
        if [ "${lockholder}" = "$(whoami)" ]; then
            _check_reset_and_unlock
            _info "Cluster lock successfully released."
        else
            _error "You cannot unlock cluster locked by: ${lockholder}"
        fi
    else
        _info "Cluster not locked."
    fi
}

###

subcommand_whitelist[unlock_force]="Forcibly release the lock on a cluster."

function subcmd_unlock_force() {
    _prompt_to_confirm --no-lock

    if lockholder=$(_current_lockholder); then
        _check_reset_and_unlock
        _warning "Cluster forcibly unlocked, please let former lockholder know: ${lockholder}"
    else
        _info "Cluster was not locked."
    fi
}

###

subcommand_whitelist[kill_sv_app]='Spin down sv-app to zero replicas for the specified namespace'

function subcmd_kill_sv_app() {
    _cluster_must_exist

    _assert_lock

    if lockholder=$(_current_lockholder); then
        if [ "${lockholder}" = "$(whoami)" ]; then
            _info "Killing sv-app for $1"
            kubectl patch deployment sv-app --namespace "$1" -p '{"spec":{"replicas":0}}'
        else
            _error "You cannot edit a cluster locked by: ${lockholder}"
        fi
    else
        _error "Cluster not locked."
    fi
}

###

subcommand_whitelist[revive_sv_app]='Spin up sv-app to one replica for the specified namespace'

function subcmd_revive_sv_app() {
    _cluster_must_exist

    _assert_lock

    if lockholder=$(_current_lockholder); then
        if [ "${lockholder}" = "$(whoami)" ]; then
            _info "Reviving sv-app for $1"
            kubectl patch deployment sv-app --namespace "$1" -p '{"spec":{"replicas":1}}'
        else
            _error "You cannot edit a cluster locked by: ${lockholder}"
        fi
    else
        _error "Cluster not locked."
    fi
}

################################
### Main
################################

if [ -z "${SUBCOMMAND_NAME-}" ]; then
    subcmd_help

    _error  "Missing subcommand"
fi


if [ ! ${subcommand_whitelist[${SUBCOMMAND_NAME}]+_} ]; then
    subcmd_help

    _error  "Unknown subcommand: ${SUBCOMMAND_NAME}"
fi

"subcmd_${SUBCOMMAND_NAME}" "$@"
