#!/usr/bin/env bash

SUBCOMMAND_NAME="$1"
shift

set -euo pipefail

# shellcheck disable=SC1091
source "${TOOLS_LIB}/libcli.source"

SCRIPTNAME=${0##*/}

# Ensure we're running in a cluster deployment context

if [ -z "${GCP_CLUSTER_BASENAME-}" ]; then
    _error "GCP_CLUSTER_BASENAME is undefined, this script must be run in a deployment/ directory."
fi

##

GCP_CLUSTER_NAME="cn-${GCP_CLUSTER_BASENAME}net"
CLUSTER_DNS_NAME="${GCP_CLUSTER_BASENAME}.network.canton.global"

################################
### Utilities
################################

function _contained() {
    local needle="$1" item
    shift
    for item; do
        if [[ "$item" == "$needle" ]]; then
            return 0
        fi
    done
    return 1
}

function _cluster_exists() {
  CLUSTER=$(gcloud container clusters list --filter "name:${GCP_CLUSTER_NAME}"  --format 'value(name)')

  if [ -z "${CLUSTER}" ]; then
      return 1
  else
      return 0
  fi
}

function _cluster_must_exist() {
    if ! _cluster_exists; then
        _error "Cluster does not exist, cannot continue."
    fi
}

function _docker_must_be_running() {
    if ! docker ps  > /dev/null 2>&1; then
        _error "Docker Daemon not found to be running."
    fi
}

function _production_gate() {
    if [ -n "${GCP_CLUSTER_PROD_LIKE-}" ] && [ -z "${CI-}" ]; then
        _error "Please deploy to this cluster only via CircleCI (https://github.com/DACH-NY/canton-network-node/tree/main/cluster#manually-deploying-via-ci)"
    fi
}

function _cluster_ip() {
    gcloud compute addresses list \
           --regions="${CLOUDSDK_COMPUTE_REGION}" \
           --filter "name:${GCP_CLUSTER_NAME}-ip" \
           --format 'value(address)'
}

function _needs_auth0_management_api_creds() {
    if [ -z "${AUTH0_CN_MANAGEMENT_API_CLIENT_ID-}" ]; then
        _error "Environment variable AUTH0_CN_MANAGEMENT_API_CLIENT_ID undefined.\nPlease see https://github.com/DACH-NY/canton-network-node#configure-auth0-environment"
      exit 1
    fi

    if [ -z "${AUTH0_CN_MANAGEMENT_API_CLIENT_SECRET-}" ]; then
      _error "Environment variable AUTH0_CN_MANAGEMENT_API_CLIENT_SECRET is undefined.\nPlease see https://github.com/DACH-NY/canton-network-node#configure-auth0-environment"
      exit 1
    fi
}


function _needs_auth0_sv_management_api_creds() {
    if [ -z "${AUTH0_SV_MANAGEMENT_API_CLIENT_ID-}" ]; then
        _error "Environment variable AUTH0_SV_MANAGEMENT_API_CLIENT_ID undefined.\nPlease see https://github.com/DACH-NY/canton-network-node#configure-auth0-environment"
        exit 1
    fi

    if [ -z "${AUTH0_SV_MANAGEMENT_API_CLIENT_SECRET-}" ]; then
        _error "Environment variable AUTH0_SV_MANAGEMENT_API_CLIENT_SECRET is undefined.\nPlease see https://github.com/DACH-NY/canton-network-node#configure-auth0-environment"
        exit 1
    fi
}

function _needs_auth0_validator_management_api_creds() {
    if [ -z "${AUTH0_VALIDATOR_MANAGEMENT_API_CLIENT_ID-}" ]; then
        _error "Environment variable AUTH0_VALIDATOR_MANAGEMENT_API_CLIENT_ID undefined.\nPlease see https://github.com/DACH-NY/canton-network-node#configure-auth0-environment"
        exit 1
    fi

    if [ -z "${AUTH0_VALIDATOR_MANAGEMENT_API_CLIENT_SECRET-}" ]; then
        _error "Environment variable AUTH0_VALIDATOR_MANAGEMENT_API_CLIENT_SECRET is undefined.\nPlease see https://github.com/DACH-NY/canton-network-node#configure-auth0-environment"
        exit 1
    fi
}

function _cluster_apply() {
    IMAGE_TAG=$1

    if [ -n "${IMAGE_TAG:-}" ]; then
        local -x IMAGE_TAG=${IMAGE_TAG}
    fi

    _info "Applying Pulumi Infra Stack"
    subcmd_infra_up

    _info "Applying Pulumi Stack"

    subcmd_install_data_export_bucket_key
    subcmd_pulumi canton-network up --yes --skip-preview --show-sames "${args[@]}"
}

function _cluster_show() {
    _log "CLOUDSDK_COMPUTE_REGION : ${CLOUDSDK_COMPUTE_REGION}"
    _log "CLOUDSDK_CORE_PROJECT   : ${CLOUDSDK_CORE_PROJECT}"
    _log "GCP_REPO_NAME           : ${GCP_REPO_NAME}"

    _log "GCP_MASTER_IPV4_CIDR    : ${GCP_MASTER_IPV4_CIDR}"
    _log "GCP_CLUSTER_BASENAME    : ${GCP_CLUSTER_BASENAME}"
    _log "GCP_CLUSTER_NAME        : ${GCP_CLUSTER_NAME}"
    _log "CLUSTER_DNS_NAME        : ${CLUSTER_DNS_NAME}"
    _log "PULUMI_BACKEND_URL      : ${PULUMI_BACKEND_URL}"

    _log ""
}

function _pulumi() {
    if ! [ -v PULUMI_BACKEND_URL ]; then
        # shellcheck disable=SC2016
      	_error 'The `PULUMI_BACKEND_URL` variable is not set. It should point to a GCP bucket, e.g. `gs://a-bucket-name`.'
    fi

    # shellcheck disable=SC2145
    _log "Running Pulumi Command : pulumi $@"

    pulumi "$@"
}

# Create a pulumi stack for a given project (for the current cluster) if one does not yet exist.
# While `pulumi up` can create a stack implicitly if one does not exist, we want to also configure
# it to use gcpkms, so we explicitly initialize it first here.
# We also call this before `pulumi down`, otherwise that command will fail if the stack happens not to exist yet,
# which we typically don't want.
function _uses_pulumi_stack() {

    pulumi_project=$1

    _pulumi --stack "organization/${pulumi_project}/${pulumi_project}.${GCP_CLUSTER_BASENAME}" \
            --cwd "${REPO_ROOT}/cluster/pulumi/${pulumi_project}" \
            stack init \
            --secrets-provider="gcpkms://projects/${CLOUDSDK_CORE_PROJECT}/locations/${CLOUDSDK_COMPUTE_REGION}/keyRings/pulumi/cryptoKeys/${GCP_CLUSTER_BASENAME}" \
            2> /dev/null || true

    if [ ! -f "${REPO_ROOT}/cluster/pulumi/${pulumi_project}/Pulumi.${pulumi_project}.${GCP_CLUSTER_BASENAME}.yaml" ]; then
        # Even though we do not use pulumi configs, pulumi insists on creating a local settings file, and on having a secrets-provider for it. We therefore create it here if it doesn't exist.
        _info "Creating Pulumi stack for ${pulumi_project} project (file ${REPO_ROOT}/cluster/pulumi/${pulumi_project}/Pulumi.${pulumi_project}.${GCP_CLUSTER_BASENAME}.yaml does not exist)"
        local -x PULUMI_CONFIG_PASSPHRASE=''
        _pulumi --stack "organization/${pulumi_project}/${pulumi_project}.${GCP_CLUSTER_BASENAME}" \
                --cwd "${REPO_ROOT}/cluster/pulumi/${pulumi_project}" \
                stack change-secrets-provider "gcpkms://projects/${CLOUDSDK_CORE_PROJECT}/locations/${CLOUDSDK_COMPUTE_REGION}/keyRings/pulumi/cryptoKeys/${GCP_CLUSTER_BASENAME}"
    fi
}

function _retry_until_success() {
    local -r cmd="${1-}"
    local -r msg="${2-}"

    if [ -z "$cmd" ]; then
        _error "Missing command in _retry_until_success"
        exit 1
    fi

    # with 5 second sleep + 1 second kubectl timeout, this is roughly 10 minutes
    # See also max_wait which caps the overall wait time
    local -i -r max_retries=$((100))
    local -i num_retries=0
    local -i -r max_wait=$((60*60)) # do not wait longer than 60m in any case
    local -i -r start_time=$(date +%s)

    _log "Running command with retry: $cmd"

    set +e
    until $cmd; do
        ((++num_retries))
        if ((num_retries>max_retries)); then
            echo "Too many attempts, exiting"
            exit 1
        fi
        if (($(date +%s) > (start_time+max_wait))); then
            echo "Timed out after $max_wait seconds, exiting"
            exit 1
        fi
        sleep 5
    done
    set -e
}

function _retry_until_value() {
    local -r cmd="${1-}"
    local -r msg="${2-}"
    local -r expected="${3-}"
    local -r is_regex="${4-}"

    if [ -z "$cmd" ] || [ -z "$expected" ]; then
        _error "Missing command or expected value in _retry_until_value"
        exit 1
    fi

    # with 5 second sleep, this takes roughly 30 minutes + 360*N, where N is time it takes to run `cmd` in minutes.
    # Usually this is negligible, but beware if `cmd` is resource heavy or does retries of its own.
    # See also max_wait which caps the overall wait time
    local -i -r max_retries=$((12*30))
    local -i num_retries=0
    local -i -r max_wait=$((60*60)) # do not wait longer than 60m in any case
    local -i -r start_time=$(date +%s)

    _log "Running command with retry (until $expected): $cmd"

    function is_expected() {
        local -r found="${1-}"
        if [ -z "$is_regex" ]; then
            if [ "$found" == "$expected" ]; then
                true
            else
                _log "Waiting for $msg (found: \"$found\", expecting: \"$expected\")"
                false
            fi
        else
            if [[ "$found" =~ $expected ]]; then
                true
            else
                _log "Waiting for $msg (found: \"$found\", expecting regex: \"$expected\")"
                false
            fi
        fi
    }

    until found=$($cmd 2>&1 || true) && (is_expected "$found"); do
        ((++num_retries))
        if ((num_retries>max_retries)); then
            echo "Too many attempts, exiting"
            exit 1
        fi
        if (($(date +%s) > (start_time+max_wait))); then
            echo "Timed out after $max_wait seconds, exiting"
            exit 1
        fi
        sleep 5
    done

    ret=$found
}


### Cluster management


function _current_lockholder() {
    local secret
    local errorcode
    errorcode=0
    secret=$(kubectl get secret cluster-lock -o jsonpath='{.data.lockholder}' 2>&1) || errorcode=$?
    if [ $errorcode != 0 ]; then
        if [[ $secret == "Unable to connect to the server"* ]]; then
            _error "Failed to get secret cluster-lock from the cluster. Please check that you are on VPN, and if so, try running \`cncluster activate\`"
        elif [[ $secret == "Error from server (NotFound)"* ]]; then
            echo ""
        else
            _error "Unknown error when fetching lock secret: $secret"
        fi
    else
        echo "$secret" | base64 --decode
    fi
}

function _current_lock_age() {
    lock_timestamp=$(kubectl get secret cluster-lock -o jsonpath='{.metadata.creationTimestamp}' 2>/dev/null | xargs -0 -I X date -d X +%s)
    current_timestamp=$(date +%s)
    echo "$((current_timestamp-lock_timestamp))"
}


function _current_lock_age_formatted() {
    age_secs="$(_current_lock_age)"
    echo "$((age_secs / 86400)) days(s), $(((age_secs % 86400) / 3600)) hour(s), $(((age_secs % 3600) / 60)) minute(s)"
}

function _get_holder_names() {
    jq -r --arg login "$1" '.[$login][]?' "$REPO_ROOT/.circleci/cluster-lock-users.json"
}

function _assert_lock() {
    if [ -z "${SHARED_CLUSTER:-}" ]; then
        return
    fi

    lockholder=$(_current_lockholder)
    if [ -n "$lockholder" ]; then
        if [ "${1-}" != "--for-ci" ]; then
            if [ "${lockholder}" != "$(whoami)" ]; then
                _error "Cluster already locked by: ${lockholder}"
            fi
            return
        fi

        # Check lock for CI...
        if ! approver=$( "$REPO_ROOT/.circleci/approved-by.sh" ); then
            _error "Could not determine approver for CI workflow"
        fi

        if [[ -n "$approver" ]]; then
            local -a names
            readarray -t names < <( _get_holder_names "$approver" )

            if _contained "$lockholder" "${names[@]}"; then
                _info "CI workflow approved by $approver and locked by ${lockholder}"
            else
                _error "CI workflow approved by $approver alias ${names[*]}, but cluster locked by ${lockholder}"
            fi
        else
            # running for CI, but no approved workflow; we only require the lock
            _info "CI running with cluster lock held by: ${lockholder}"
        fi
    else
        _error "Cluster not locked. (See: https://github.com/DACH-NY/canton-network-node/tree/main/cluster#deploy-a-build-to-a-cluster))"
    fi
}

################################
### Commands
################################

## Subcommand dictionary
##
##    This is a map from subcommand name to help text. The definition of the
##    sumcommand's functionality itself is in a shell function named
##    cluster_${subcommand_name}. The subcommand must be defined in the
##    whitelist dictionary to be invoked.

declare -A subcommand_whitelist

function _prompt_to_confirm() {
    # Assert lock before checking if prompt was confirmed previously.
    # This is to ensure the current invocation obeys the lock guard
    # regardless of prior invocations using --no-lock or not
    if [ "${1-}" != "--no-lock" ]; then
        _assert_lock
    fi

    # Many subcommands invoke other subcommands to do their work. This
    # keeps a record of the first confirmation prompt to avoid
    # prompting the user at every one of these steps.  We also
    # autoconfirm on CI instead of having to be careful to avoid all
    # calls to _prompt_to_confirm.
    if [ -n "${USER_PROMPT_CONFIRMED:-}" ] || [ -n "${CI:-}" ]; then
        return
    fi

    _cluster_show

    if [ -z "${GCP_CLUSTER_PROD_LIKE-}" ] ; then
        if [ -n "${CNCLUSTER_AUTOCONFIRM-}" ] ; then
            _warning "Automatically confirmed (via environment variable): ${subcommand_whitelist[${SUBCOMMAND_NAME}]}"
            return
        fi
    fi

    _confirm "Confirm: ${subcommand_whitelist[${SUBCOMMAND_NAME}]}"
   USER_PROMPT_CONFIRMED=1
}

###

subcommand_whitelist[activate]='Ensure cncluster is correctly authenticated to administer the cluster.'

function subcmd_activate() {
    _cluster_must_exist

    gcloud container clusters get-credentials "${GCP_CLUSTER_NAME}"
}

###

subcommand_whitelist[rlogs]='Stream a running application log stream to standard output'

function _json_log_format() {
    jq -R 'fromjson? | select(type == "object")' \
        | jq -r '"\(.["@timestamp"]) \(.level) [\(.logger_name)] - \(.message)"'
}

function subcmd_rlogs() {
    if [ "${1-}" = "--raw" ]; then
        raw=yes
        shift
    fi

    if [ -z "${1-}" ]; then
        _error "No namespace specified"
    fi

    if [ -z "${2-}" ]; then
        _error "No app specified"
    fi

    _cluster_must_exist

    namespace=$1
    app=$2
    domain=${3:-0}
    app_container="$app"

    k8s_labels_for_app

    if POD_SPEC=$(kubectl get pod \
                          -n "${namespace}" \
                          -l app="${app}" \
                          -o jsonpath='{range .items[0].metadata}{"-n "}{@.namespace}{" "}{@.name}{"\n"}{end}'  \
                          2> /dev/null); then


        if [ -n "${raw-}" ] ; then
            # shellcheck disable=SC2086
            kubectl logs ${POD_SPEC} "${app_container}" -f
        else
            # shellcheck disable=SC2086
            kubectl logs ${POD_SPEC} "${app_container}" -f | _json_log_format
        fi
    else
        _error "No pod for app found: ${app}"
    fi
}

###

subcommand_whitelist[logs]='View an running application log stream in lnav'

function subcmd_logs() {

    if [ "$#" -lt 2 ] || [ "$#" -gt 3 ]; then
       echo "Usage: $0 <namespace> <app> [domain]"
       exit 1
    fi

    _cluster_must_exist

    namespace=$1
    app=$2

    domain=${3:-0}

    app_container="$app"

    k8s_labels_for_app

    if POD_SPEC=$(kubectl get pod \
                          -n "${namespace}" \
                          -l app="${app}" \
                          -o jsonpath='{range .items[0].metadata}{"-n "}{@.namespace}{" "}{@.name}{"\n"}{end}'  \
                          2> /dev/null); then

        kubectl lnav "${POD_SPEC}" "${app_container}"
    else
        _error "No pod for app found: ${app}"
    fi
}


function k8s_labels_for_app() {
    local non_domain_specific_namespaces=("sv" "validator1" "splitwell" "validator")
    local global_domain_specific_apps=("global-domain-cometbft" "global-domain-sequencer" "global-domain-mediator")
    local domain_specific_apps=("participant" "sv-app" "scan-app")

    # shellcheck disable=SC2076
    if [[ " ${global_domain_specific_apps[*]} " =~ " ${app} " && ! " ${non_domain_specific_namespaces[*]} " =~ " ${namespace} " ]]; then
       # If the app is in the list, append the domain to the app
       app_container=${app#"global-domain-"}
       app="global-domain-${domain}-${app#"global-domain-"}"
    elif [[ " ${domain_specific_apps[*]} " =~ " ${app} " && ! " ${non_domain_specific_namespaces[*]} " =~ " ${namespace} " ]]; then
       # If the app is in the list, append the domain to the app
       app="${app}-${domain}"
    fi
}

subcommand_whitelist[gcloud_logs]='View the logs of an application through gcloud. This allows viewing historical logs'

function subcmd_gcloud_logs() {
    if [ "${1-}" = "--download-only" ]; then
        download_only=yes
        shift
    fi

    if [ -z "${1-}" ]; then
        _error "No namespace specified"
    fi

    if [ -z "${2-}" ]; then
        _error "No app specified"
    fi

    if [ -z "${3-}" ]; then
        _error "No filter specified. See https://cloud.google.com/logging/docs/view/logging-query-language for docs on the query language."
    fi

    namespace="$1"
    app="$2"
    filter="$3"

    _cluster_must_exist

    local postgres glr_format
    postgres="$(if [ "$app" = postgres ]; then echo 1; else echo 0; fi)"
    if [ "$postgres" -ne 0 ]; then
        glr_format='text(textPayload)'
    else
        glr_format='json(jsonPayload)'
    fi

    LOGFILE=$(mktemp "$namespace"-"$app"-XXXX.clog)
    _info "Writing log to $LOGFILE"

    function gcloud_read() {
        gcloud logging read --order asc --format "$glr_format" \
          "resource.labels.cluster_name=$GCP_CLUSTER_NAME AND resource.labels.namespace_name=$namespace AND resource.labels.container_name=$app AND $filter"
    }
    function parse_gcloud_format() {
        if [ "$postgres" -eq 0 ]; then
            jq --stream -cn 'fromstream(1 | truncate_stream(inputs) | select(.[0][0] == "jsonPayload")) | .jsonPayload'
        else
            awk '/^---$|^: None$/ {next} {sub("^text_payload: ", ""); print}'
        fi
    }


    if [ -z "${download_only-}" ]
    then
        gcloud_read | parse_gcloud_format > "$LOGFILE" &
        lnav "$LOGFILE"
    else
        gcloud_read | parse_gcloud_format > "$LOGFILE"
    fi
}

###

subcommand_whitelist[set_machine_type]='Rebuilds the default node pool with current cluster machine type and count'

function subcmd_set_machine_type() {
    _prompt_to_confirm
    _cluster_must_exist

    _info "Creating temporary node pool..."
    gcloud container node-pools create temp-pool --cluster "cn-${GCP_CLUSTER_BASENAME}net" \
           --machine-type "${GCP_CLUSTER_NODE_TYPE}" --num-nodes 1 \
           || _error "Could not create node pool with machine type: ${GCP_CLUSTER_NODE_TYPE}"

    _info "Deleting default node pool..."
    gcloud container node-pools delete default-pool --quiet --cluster "cn-${GCP_CLUSTER_BASENAME}net" \
           || _error "Could not delete default node pool. Terminating early."

    _info "Recreating default node pool..."
    gcloud container node-pools create default-pool --cluster "cn-${GCP_CLUSTER_BASENAME}net" \
           --machine-type "${GCP_CLUSTER_NODE_TYPE}" \
           --num-nodes "${GCP_CLUSTER_MIN_NODES}" \
           --enable-autoscaling \
           --min-nodes "${GCP_CLUSTER_MIN_NODES}" \
           --max-nodes "${GCP_CLUSTER_MAX_NODES}" \
           || _error "Could not recreate default node pool. Terminating early."

    _info "Deleting temporary node pool..."
    gcloud container node-pools delete temp-pool --quiet --cluster "cn-${GCP_CLUSTER_BASENAME}net" \
           || _error "Could not delete temporary node pool."
}

###

subcommand_whitelist[upgrade]='Upgrades the cluster to the latest GKE version'

function subcmd_upgrade() {
    _prompt_to_confirm
    _cluster_must_exist

    _info "Upgrading cluster master..."
    gcloud container clusters upgrade "cn-${GCP_CLUSTER_BASENAME}net" --master --quiet

    _info "Upgrading cluster nodes..."
    gcloud container clusters upgrade "cn-${GCP_CLUSTER_BASENAME}net" --quiet
}

###

function _get_gcloud_secret() {
  local -r secret_name="$1"
  gcloud secrets versions access 1 --secret="$secret_name"
}

function _get_service_account_key_id() {
    local -r secret_name="$1"
    _get_gcloud_secret "$secret_name" | jq -r '.private_key_id'
}

subcommand_whitelist[get_dns01_key_id]='Get the gcloud service account key id used for dns challenges.'

function subcmd_get_dns01_key_id() {
    _get_service_account_key_id "${DNS01_SA_KEY_SECRET}"
}

subcommand_whitelist[get_data_export_bucket_key_id]='Get the gcloud service account key id used for data exports.'

function subcmd_get_data_export_bucket_key_id() {
    _get_service_account_key_id "${DATA_EXPORT_BUCKET_SA_KEY_SECRET}"
}

###

function _install_service_account_key() {
    local -r secret_name="$1"
    local -r iam_account="$2"

    SECRET=$(gcloud secrets list --filter "name:$secret_name" --format 'value(name)')

    if [ -z "${SECRET}" ]; then
        _info "Allocating service account key and storing as secret."
        gcloud iam service-accounts keys create /tmp/key.json \
               --iam-account "$iam_account"

        gcloud secrets create "$secret_name" --data-file=/tmp/key.json

        rm /tmp/key.json
    else
        SA_KEY_ID=$(_get_service_account_key_id "$secret_name")

        _info "Service Account key secret already exists: ${SA_KEY_ID}"
    fi
}

subcommand_whitelist[install_dns01_key]='Allocate a DNS SA Key for the project and store it in a secret.'

function subcmd_install_dns01_key() {
    _prompt_to_confirm --no-lock

    _install_service_account_key "${DNS01_SA_KEY_SECRET}" "${DNS01_SA_IAM_ACCOUNT}"
}

subcommand_whitelist[install_data_export_bucket_key]='Allocate a data export SA key for the project and store it in a secret.'

function subcmd_install_data_export_bucket_key() {
    _prompt_to_confirm --no-lock

    _install_service_account_key "${DATA_EXPORT_BUCKET_SA_KEY_SECRET}" "${DATA_EXPORT_BUCKET_SA_IAM_ACCOUNT}"
}
###

function _uninstall_service_account_key() {
    local -r secret_name="$1"
    local -r iam_account="$2"

    SECRET=$(gcloud secrets list --filter "name:$secret_name" --format 'value(name)')

    if [ -z "${SECRET}" ]; then
        _warning "No service account key secret to delete."
    else
        SA_KEY_ID=$(_get_service_account_key_id "$secret_name")

        _info "Deleting SA Key: ${SA_KEY_ID}"

        gcloud iam service-accounts keys delete \
               --iam-account "$iam_account" \
               --quiet \
               "${SA_KEY_ID}" || true

        gcloud secrets delete --quiet "$secret_name"

        _info "Service account key deleted."
    fi
}

subcommand_whitelist[uninstall_dns01_key]='Delete the DNS SA Key for the project and the corresponding secret'

function subcmd_uninstall_dns01_key() {
    _prompt_to_confirm --no-lock

    _uninstall_service_account_key "${DNS01_SA_KEY_SECRET}" "${DNS01_SA_IAM_ACCOUNT}"
}

subcommand_whitelist[uninstall_data_export_bucket_key]='Delete the data export SA key for the project and the corresponding secret'

function subcmd_uninstall_data_export_bucket_key() {
    _prompt_to_confirm --no-lock

    _uninstall_service_account_key "${DATA_EXPORT_BUCKET_SA_KEY_SECRET}" "${DATA_EXPORT_BUCKET_SA_IAM_ACCOUNT}"
}

###

subcommand_whitelist[infra_up]='Apply the infra Pulumi stack.'

function subcmd_infra_up() {
    _info "Activating infrastructure Pulumi stack"

    subcmd_install_dns01_key

    _uses_pulumi_stack infra

    subcmd_pulumi infra up --yes --skip-preview
}

###

subcommand_whitelist[infra_down]='Take the current Pulumi infra stack down.'

function subcmd_infra_down() {
    _prompt_to_confirm
    _cluster_must_exist

    _info "Deactivating infrastructure Pulumi stack"

    subcmd_pulumi infra down --yes --skip-preview
}

###

subcommand_whitelist[create]='Create a cluster from scratch.'

function subcmd_create() {
    _prompt_to_confirm --no-lock

    if _cluster_exists; then
        _error "Cluster already exists."
    else

        #### Cluster can be resized from deployment directories with the following command:
        ####   gcloud container clusters resize "cn-${GCP_CLUSTER_BASENAME}net" --num-nodes 4
        gcloud container clusters create "${GCP_CLUSTER_NAME}" \
               --create-subnetwork name="${GCP_CLUSTER_NAME}-subnet" \
               --enable-master-authorized-networks \
               --enable-ip-alias \
               --enable-private-nodes \
               --machine-type "${GCP_CLUSTER_NODE_TYPE}" \
               --num-nodes "${GCP_CLUSTER_MIN_NODES}" \
               --master-ipv4-cidr "${GCP_MASTER_IPV4_CIDR}" \
               --node-locations "${CLOUDSDK_COMPUTE_REGION}-a" \
               --node-labels digitalasset.com/cluster-name="${GCP_CLUSTER_NAME}" \
               --addons=GcePersistentDiskCsiDriver \
               --enable-autoscaling \
               --min-nodes "${GCP_CLUSTER_MIN_NODES}" \
               --max-nodes "${GCP_CLUSTER_MAX_NODES}"

        #### Enable Firewall Access
        gcloud container clusters update "${GCP_CLUSTER_NAME}" \
               --enable-master-authorized-networks \
               --master-authorized-networks "${GCP_VPN_NETS}"

        #### Delete default firewall rules, if they exist.
        if (gcloud compute firewall-rules delete\
                         default-allow-rdp \
                         default-allow-icmp \
                         default-allow-ssh \
                         --quiet 2> /dev/null); then
            _warning "Deleted default firewall rules."
        else
            _log "Default firewalls already removed and do not need to be deleted."
        fi
    fi

    _log "Authenticating to newly created cluster."
    subcmd_activate

    #### Open port 15017 in GKE firewall, see https://istio.io/latest/docs/setup/platform-setup/gke/
    _log "Opening port 15017 in GKE firewall"
    FW_NAME=$(gcloud compute firewall-rules list --filter="name~gke-cn-${GCP_CLUSTER_BASENAME}net-[0-9a-z]*-master" --format=json | jq -r '.[].name')
    gcloud compute firewall-rules update "${FW_NAME}" --allow tcp:10250,tcp:443,tcp:15017

    subcmd_infra_up

    _log "Determining cluster ingress IP address"
    IPADDR=$(_cluster_ip)

    if [ -z "${IPADDR}" ]; then
        _error "Could not determine cluster IP address."
    fi

    # Create a kms key for pulumi.
    error_message=$(gcloud kms keys create "${GCP_CLUSTER_BASENAME}" --location "$CLOUDSDK_COMPUTE_REGION" --keyring "pulumi" --purpose "encryption" 2>&1)
    exit_code=$?

    if [ $exit_code -ne 0 ]; then
      if [[ $error_message == *"ALREADY_EXISTS"* ]]; then
        # Rotate the key if it exists
        echo "ALREADY_EXISTS error encountered. Rotating the key..."
        gcloud kms keys versions create --key "${GCP_CLUSTER_BASENAME}" --location "$CLOUDSDK_COMPUTE_REGION" --keyring "pulumi" --primary
      else
        echo "Failed to create a KMS key for Pulumi."
        exit $exit_code
      fi
    fi

    _log "Cluster at IP ${IPADDR} ready"

    _warning "Please note that Auth0 applications are not automatically updated at the moment. Make sure to add URLs for your new cluster as allowed callback URLs, allowed logout URLs, etc. in the relevant Auth0 UI applications."
}

###

subcommand_whitelist[reset]='Reset the state of the cluster to a fully blank state. Clears all data.'

function _cluster_reset() {
    _info "Uninstalling Pulumi canton-network-gateway stack"

    _down_stack canton-network
    _down_stack sv-runbook
    _down_stack validator-runbook

    _info "Cluster in reset/idle state."
}

function _down_stack() {
    STACK=$1

    _info "Uninstalling Pulumi ${STACK} stack"

    RETCODE=0
    ERRFILE="./.tmp_ERRFILE"
    ERRMSG=""

    touch "$ERRFILE"

    subcmd_pulumi "$STACK" down --yes --skip-preview 2> >(tee ${ERRFILE} >&2) || { RETCODE="$?"; ERRMSG=$(cat "$ERRFILE")
    }

    rm -rf "$ERRFILE"

    if [ "$RETCODE" -ne 0 ]; then
        case "${ERRMSG}" in
            *"the stack is currently locked"*)
                echo "Retrying because of lock on stack $STACK"
                subcmd_pulumi "$STACK" cancel --yes
                subcmd_pulumi "$STACK" refresh --yes --skip-preview
                _down_stack "$STACK"

                echo "Reset complete. In case a subsequent 'cncluster apply' fails, refer to the documentation on manual cleanup (https://github.com/DACH-NY/canton-network-node/tree/main/cluster#manually-deploying-via-ci)"
                ;;

            *)
                _error "Failed uninstalling stack $STACK, aborting"
                exit 1
                ;;
        esac
    fi
}

function subcmd_reset() {
    _prompt_to_confirm

    _cluster_reset "$@"
}

subcommand_whitelist[ci_apply]='Run only by CircleCI'

function subcmd_ci_apply() {
    _assert_lock --for-ci

    # A CI-specific variant of 'cncluster apply' that removes the need
    # for manual confirmation and ensures that all pods are deleted
    # and recreated during the apply. With current (September 2022)
    # DevNet, the ledger is stored in memory and the pod reset
    # has the effect of clearing out all ledger state.

    if [ "${1-}" == "--skip-reset" ]; then
      skip_reset=yes
      shift
    fi

    if [ -z "${CI-}" ]; then
      _error "This subcommand is available to CI jobs only."
    fi

    # By default, this is unset and we infer the previous values based on the currently running cluster.
    # However, we allow overwriting it to account for cases where the previous cluster is broken in some way.
    if [ -n "${RESTORE_CLUSTER:-}" ] && [ -z "${BOOTSTRAPPING_CONFIG:-}" ]; then
        CLUSTER="$GCP_CLUSTER_BASENAME"
        NOW="$(date +"%Y-%m-%dT%H:%M:%S.000Z")"
        export BOOTSTRAPPING_CONFIG="{\"cluster\": \"$CLUSTER\", \"date\": \"$NOW\"}"
    fi

    _cluster_show

    if [ -n "${BOOTSTRAPPING_CONFIG:-}" ]; then
       _info "Bootstrapping cluster from ${BOOTSTRAPPING_CONFIG}"
    fi

    if [ -z "${skip_reset:-}" ]; then
      _info "Resetting cluster for CI deployment."
      _cluster_reset
    fi

    source_image_tag=$(get-snapshot-version)

    _info "Applying CI deployment: ${source_image_tag}"

    _cluster_apply "${source_image_tag}"
}

###

subcommand_whitelist[ci_assert_fresh_lock]='Run only by CircleCI'

function subcmd_ci_assert_fresh_lock() {
    if [ -z "${SHARED_CLUSTER:-}" ]; then
        _info "Cluster not marked as shared. No lock to check."
        exit 0
    fi

    lockholder=$(_current_lockholder)
    if [ -n "$lockholder" ]; then
        age_secs="$(_current_lock_age)"

        if (( age_secs > 21600 )); then
            _error "Cluster lock held by ${lockholder} is stale. Lock age: $(_current_lock_age_formatted)"
        else
            _info "Cluster lock held by ${lockholder} is fresh. Lock age: $(_current_lock_age_formatted)"
        fi
    else
        _info "Cluster sharable but not locked. No lock to check."
    fi
}

###

subcommand_whitelist[ci_reset_unlock]='Run only by CircleCI'

function subcmd_ci_reset_unlock() {
    # A CI-specific variant of 'cncluster reset' and 'cncluster unlock' that
    # removes the need for manual confirmation and is executed only on shared
    # clusters (like scratchnet).

    if [ -z "${CI-}" ]; then
        _error "This subcommand is available to CI jobs only."
    fi

    if [ -z "${SHARED_CLUSTER:-}" ]; then
        _info "Not resetting and unlocking because not on a shared cluster (like scratchnet)."
        return
    fi

    _cluster_reset
    lockholder=$(_current_lockholder)
    if [ -n "$lockholder" ]; then
        _unlock
        _info "Cluster unlocked. Former lockholder was: ${lockholder}"
    else
        _info "Cluster was not locked."
    fi
}

###

subcommand_whitelist[delete]='Delete all cluster resources.'

function subcmd_delete() {
    _prompt_to_confirm
    _cluster_must_exist

    _info "Taking down pulumi infrastructure stack."
    subcmd_pulumi infra down --yes --skip-preview

    _info "Deleting GKE cluster."
    gcloud container clusters delete --quiet "${GCP_CLUSTER_NAME}"

    _info "Cluster deleted."
}

###

subcommand_whitelist[ipaddr]='Display the cluster\s main IP address.'

function subcmd_ipaddr() {
    _cluster_must_exist
    _cluster_ip
}

###

subcommand_whitelist[eipaddr]='Display the cluster\s Egress IP address. (May not be comprehensive)'

function subcmd_eipaddr() {
    _cluster_must_exist

    kubectl exec -n docs "$(kubectl get pods -n docs -lapp=docs -o name)" -- \
            curl -sSLf http://checkip.amazonaws.com
}

###

subcommand_whitelist[start_frontends]='Run the self-hosted frontends for the preflight test'

function subcmd_start_frontends() {
    _log "Starting frontends needed for preflight check..."

    (cd "${REPO_ROOT}" && \
         NETWORK_APPS_ADDRESS=${GCP_CLUSTER_BASENAME}.network.canton.global ./start-frontends.sh -d -v -p)
}

###

subcommand_whitelist[load_test]='Run the k6 load test against the cluster'

function subcmd_load_test() {
    _log "Starting k6 load test"

    cd "$REPO_ROOT" && sbt load-tester/npmBuild

    hostname="$GCP_CLUSTER_BASENAME.network.canton.global"

    export K6_WALLET_BASE_URL="https://wallet.validator1.$hostname"
    prometheus_rw="https://prometheus.$hostname/api/v1/write"

    K6_PROMETHEUS_RW_SERVER_URL="$prometheus_rw" k6 \
        --verbose \
        --out experimental-prometheus-rw \
        --env EXTERNAL_CONFIG="$(envsubst < "$REPO_ROOT/load-tester/config.sample.json")" \
        run "$REPO_ROOT/load-tester/dist/generate-load.js"
}

###

subcommand_whitelist[preflight]='Run the runbook preflight test against the cluster'

function subcmd_preflight() {
    _log "Starting preflight"

    set +e
    tmux has-session -t cn-frontends
    local tmux_session_check=$?
    set -e

    if [ $tmux_session_check -eq 0 ]; then
        _error "CN Frontends are already running. Please run \`stop-frontends.sh\` from the root and try again."
    fi;

    subcmd_start_frontends

    set +e

    preflight_tests=$(_get_preflight_test_names "core")
    _log "Starting preflight tests: $preflight_tests"
    subcmd_sbt_for_preflight "apps-app/testOnly $preflight_tests"

    local test_result=$?
    set -e

    _log "Stopping frontends..."
    cd "${REPO_ROOT}" && ./stop-frontends.sh

    return $test_result
}

###

subcommand_whitelist[sbt_for_preflight]='Runs Sbt, as if for the runbook preflight test.'

function subcmd_sbt_for_preflight() {
    _needs_auth0_management_api_creds

    (cd "${REPO_ROOT}" && \
         DOMAIN_URL=https://sequencer.sv-1.svc.${GCP_CLUSTER_BASENAME}.network.canton.global \
         NETWORK_APPS_ADDRESS=${GCP_CLUSTER_BASENAME}.network.canton.global \
         NETWORK_APPS_ADDRESS_PROTOCOL=https \
         VALIDATOR_USER_NAME=manual_preflight \
             sbt -DAUTH0_TENANT=dev "$@")
}

###

subcommand_whitelist[preflight_global_domain_upgrade]='Run the global doamin upgrade preflights, preparing the cluster for the upgrade'

function subcmd_preflight_global_domain_upgrade() {
    preflight_tests=$(_get_preflight_test_names "global-domain-upgrade")
    _log "Starting global domain upgrade preflight tests: $preflight_tests"
    cd "${REPO_ROOT}" && \
            NETWORK_APPS_ADDRESS="${GCP_CLUSTER_BASENAME}.network.canton.global" \
            sbt "apps-app/testOnly $preflight_tests"
}

###

subcommand_whitelist[preflight_sv]='Run the SV runbook preflight tests against the cluster'

function subcmd_preflight_sv() {
    preflight_tests=$(_get_preflight_test_names "sv")
    _log "Starting runbook SV preflight tests: $preflight_tests"
    cd "${REPO_ROOT}" && \
            NETWORK_APPS_ADDRESS="${GCP_CLUSTER_BASENAME}.network.canton.global" \
            sbt "apps-app/testOnly $preflight_tests"
}

###

subcommand_whitelist[preflight_validator]='Run the validator runbook preflight tests against the cluster'

function subcmd_preflight_validator() {
    preflight_tests=$(_get_preflight_test_names "validator")
    _log "Starting runbook validator preflight tests: $preflight_tests"
    cd "${REPO_ROOT}" && \
            NETWORK_APPS_ADDRESS="${GCP_CLUSTER_BASENAME}.network.canton.global" \
            sbt "apps-app/testOnly $preflight_tests"
}

###

subcommand_whitelist[info]='Display information on current cluster configuration, including image tags'

function subcmd_info() {
    _cluster_show
    _cluster_must_exist

    kubectl get po -o json \
            --all-namespaces \
            --field-selector metadata.namespace!=kube-system \
        | jq -r '(["NAMESPACE", "POD-NAME", "CONTAINER", "IMAGE", "MEM-LIMIT", "CPU-REQ", "CPU-LIMIT"],(.items[] | .metadata as $pod | .spec.containers[] as $c | $c.resources as $r | [$pod.namespace, $pod.name, $c.name, ($c.image | split(":")[1]), $r.limits.memory, $r.requests.cpu, $r.limits.cpu]))|@tsv' \
        | sort \
        | column -t

}

###

subcommand_whitelist[show]='Display information on current cluster configuration'

function subcmd_show() {
    _cluster_show
    _cluster_must_exist
}

###

subcommand_whitelist[top]='Display current CPU and memory usage by both node and pod'

function subcmd_top() {
    _cluster_show
    _cluster_must_exist

	_log "Node Usage:"
    kubectl top node

    _log ""
	_log "Pod Usage:"
    kubectl top pod --all-namespaces -l clusterName="${GCP_CLUSTER_NAME}"
}

###

subcommand_whitelist[pods]='Display a list of cluster pods'

function subcmd_pods() {
    _cluster_show

    kubectl top node

    _log ""
    kubectl get pods -A | grep -v kube-system
}

###

subcommand_whitelist[wait_version]="Wait for the cluster's version endpoint to return a specific version"

function subcmd_wait_version() {
    _cluster_show

    expected="${1-}"

    if [ -z "$expected" ]; then
        _error "Missing expected version"
        exit 1
    fi

    _retry_until_value "curl -sSLf --connect-timeout 5 http://${GCP_CLUSTER_BASENAME}.network.canton.global/version" "expected version" "$expected"

    _log "Done. Cluster is now reporting version: $expected"
}

###

subcommand_whitelist[wait]='Wait for the cluster to reach a fully ready state'

function subcmd_wait() {
    _cluster_show

    namespace="${1-}"
    app="${2-}"

    if [ -z "$namespace" ]; then
        _log "Waiting for all pods to become ready"
        kubectl wait --for=condition=Ready --all pod --timeout=5m --all-namespaces
    else
        _retry_until_value "kubectl get ns $namespace -o jsonpath='{.status.phase}'" "namespace $namespace to be active" "'Active'"
        if [ -z "$app" ]; then
            _log "Namespace $namespace ready, waiting for all pods"
            _retry_until_success "kubectl wait --for=condition=Ready --all pod --timeout=1s --namespace $namespace"
        else
            _log "Namespace $namespace ready, waiting for $app"
            _retry_until_value "kubectl get pods --selector=app=$app -n $namespace -o name" "pod for app $app" ^"pod" 1
            pod=$ret
            _log "Pod $pod found, waiting for ready state"
            _retry_until_success "kubectl wait --for=condition=Ready --timeout=1s --namespace $namespace $pod"
            _log "Pod $pod ready"
        fi
    fi
}

###

subcommand_whitelist[help]='Display this help message.'

function subcmd_help() {
    _info "Usage: $SCRIPTNAME {subcommand} [options...]"

    _info "Valid subcommands: "
    readarray -t sorted < <(printf '%s\n' "${!subcommand_whitelist[@]}" | sort)

    for ii in "${sorted[@]}";
    do
        if [[ "$ii" != ci_* && "$ii" != _* ]]; then
            printf '%s\t%s\n' "${ii}" "${subcommand_whitelist[${ii}]}"
        fi
    done | column -ts $'\t'
}

###

subcommand_whitelist[_autocomplete]='Utility for autocomplete.'

function subcmd__autocomplete() {
    readarray -t sorted < <(printf '%s\n' "${!subcommand_whitelist[@]}" | sort)

    for ii in "${sorted[@]}";
    do
        if [[ "$ii" != ci_* && "$ii" != _* ]]; then
            echo "${ii}"
        fi
    done

}


###

subcommand_whitelist[pulumi]="Execute a Pulumi command in the context of the current cluster"

function subcmd_pulumi() {

    pulumi_project="${1-}"
    pulumi_cmd="${2-}"
    shift 2

    if [ -z "${pulumi_cmd}" ] || [ -z "${pulumi_project}" ]; then
        _error "Usage: $SCRIPTNAME pulumi <pulumi-project> <pulumi-cmd> [options...]"
    fi

    if [ ! -d "${REPO_ROOT}/cluster/pulumi/${pulumi_project}" ]; then
        _error "Unknown Pulumi project: ${pulumi_project}"
    fi

    # Only mutating operations need a production gate. Developer
    # inspection of clusters should be permissable even in production
    # like clusters.
    case "${pulumi_cmd}" in
        new|up|destroy|down|cancel|refresh|config)
            _production_gate
            ;;
        *)
            ;;
    esac

    local args=(--cwd "${REPO_ROOT}/cluster/pulumi/${pulumi_project}")

    case "${pulumi_cmd}" in
        whoami|org)
            ;;

        *)
            args+=(--stack "organization/${pulumi_project}/${pulumi_project}.${GCP_CLUSTER_BASENAME}")
            ;;
    esac

    case "${pulumi_cmd}" in
        up|down|config)
            _uses_pulumi_stack "${pulumi_project}"
            ;;
        *)
            ;;
    esac

    function run_pulumi() {
        if [[ -n "${GCP_CLUSTER_PROD_LIKE:-}" || "$pulumi_project" == "infra" ]]
        then
            _pulumi "$@"
        else
            PULUMI_EXPERIMENTAL=true PULUMI_SKIP_CHECKPOINTS=true _pulumi "$@"
        fi
    }


    run_pulumi "${args[@]}" "$pulumi_cmd" "$@"
}

###

subcommand_whitelist[apply]="Apply the current Pulumi configuration (--preview to preview only)"

function subcmd_apply() {
    _production_gate
    _cluster_must_exist

    POSITIONAL_ARGS=()
    while [[ $# -gt 0 ]]; do
        case $1 in
            --preview)
                preview="yes"
                shift
                ;;
            --skip-infra)
                skipInfra="yes"
                shift
                ;;
            -*)
                _error "Unknown option $1"
                ;;
            *)
                POSITIONAL_ARGS+=("$1")
                shift
                ;;
        esac
    done
    set -- "${POSITIONAL_ARGS[@]}"

    if [ -n "${1-}" ]; then
        VERSION_NUMBER=$(get-snapshot-version)
        IMAGE_TAG=$1
        _warning "Overriding image tag: ${IMAGE_TAG} (was: ${VERSION_NUMBER})"
    fi

    subcmd_install_data_export_bucket_key

    if [ -n "${preview:-}" ]; then
        make -C "${REPO_ROOT}" cluster/helm/build -j
        _info "Previewing apply for infra:"
        subcmd_pulumi infra preview --show-sames --json "${args[@]}"
        _info "Previewing apply for canton-network:"
        subcmd_pulumi canton-network preview --show-sames --json "${args[@]}"
    else
        _prompt_to_confirm
        make -C "${REPO_ROOT}" cluster/build -j

        if [ -z "${IMAGE_TAG:-}" ]; then
            if [ -z "${CNCLUSTER_SKIP_DOCKER_CHECK-}" ]; then
                _docker_must_be_running
                if ! make -C "${REPO_ROOT}" docker-check -j; then
                    _error "Images missing from artifact registry, cannot apply."
                fi
            else
                _warning "docker-check bypassed with CNCLUSTER_SKIP_DOCKER_CHECK."
            fi
        fi

        if [ -z "${skipInfra:-}" ]; then
            subcmd_infra_up
        else
            _info "Skipping infra deployment"
        fi
        subcmd_pulumi canton-network up --yes --skip-preview "${args[@]}"
    fi
}

###

subcommand_whitelist[pdown]="Take the current Pulumi configuration down"

function subcmd_pdown() {
    _production_gate
    _prompt_to_confirm
    _cluster_must_exist

    subcmd_pulumi canton-network down --yes --skip-preview
}

###

subcommand_whitelist[prefresh]="Refresh the Pulumi resources in the stack"

function subcmd_prefresh() {
    _production_gate
    _prompt_to_confirm
    _cluster_must_exist

    subcmd_pulumi canton-network refresh --yes --skip-preview
}

###

subcommand_whitelist[apply_sv]="Apply the sv-runbook Pulumi stack"

function subcmd_apply_sv(){
    _needs_auth0_sv_management_api_creds

    local -x TARGET_CLUSTER="${1-}"
    if [ -z "$TARGET_CLUSTER" ]; then
        _error "Usage: $SCRIPTNAME apply_sv <target-domain-cluster> [<charts-version>]"
    fi

    _production_gate
    _prompt_to_confirm
    _cluster_must_exist

    local -x CHARTS_VERSION="${2-}"

    _uses_pulumi_stack sv-runbook

    subcmd_install_data_export_bucket_key

    subcmd_pulumi sv-runbook up --yes --skip-preview --show-sames "${args[@]}"
}

###

subcommand_whitelist[ci_apply_sv]='Run only by CircleCI'

function subcmd_ci_apply_sv() {
    _needs_auth0_sv_management_api_creds
    _assert_lock --for-ci

    # A CI-specific variant of 'cncluster apply_sv' that removes the need
    # for manual confirmation, and also always uses the same target cluster
    # as the one the sv is deployed on.

    if [ -z "${CI-}" ]; then
        _error "This subcommand is available to CI jobs only."
    fi

    # By default, this is unset and we infer the previous values based on the currently running cluster.
    # However, we allow overwriting it to account for cases where the previous cluster is broken in some way.
    if [ -n "${RESTORE_CLUSTER:-}" ] && [ -z "${BOOTSTRAPPING_CONFIG:-}" ]; then
        CLUSTER="$GCP_CLUSTER_BASENAME"
        NOW="$(date +"%Y-%m-%dT%H:%M:%S.000Z")"
        export BOOTSTRAPPING_CONFIG="{\"cluster\": \"$CLUSTER\", \"date\": \"$NOW\"}"
    fi

    _cluster_show

    if [ -n "${BOOTSTRAPPING_CONFIG:-}" ]; then
       _info "Bootstrapping SV from ${BOOTSTRAPPING_CONFIG}"
    fi

    local -x TARGET_CLUSTER="${GCP_CLUSTER_BASENAME}"

    local -x CHARTS_VERSION="${1-}"

    _uses_pulumi_stack sv-runbook

    subcmd_install_data_export_bucket_key

    subcmd_pulumi sv-runbook up --yes --skip-preview "${args[@]}"
}

###

subcommand_whitelist[pdown_sv]="Take the current sv-runbook Pulumi configuration down"

function subcmd_pdown_sv(){
    _production_gate
    _prompt_to_confirm
    _cluster_must_exist

    subcmd_pulumi sv-runbook down --yes --skip-preview
}

###

subcommand_whitelist[ci_pdown_sv]="Run only by CircleCI"

function subcmd_ci_pdown_sv(){

    if [ -z "${CI-}" ]; then
        _error "This subcommand is available to CI jobs only."
    fi

    subcmd_pulumi sv-runbook down --yes --skip-preview
}

###

subcommand_whitelist[apply_validator]="Apply the validator-runbook Pulumi stack"

function subcmd_apply_validator(){
    _needs_auth0_sv_management_api_creds

    local -x TARGET_CLUSTER="${1-}"
    if [ -z "$TARGET_CLUSTER" ]; then
        _error "Usage: $SCRIPTNAME apply_validator <target-domain-cluster> [<charts-version>]"
    fi

    _production_gate
    _prompt_to_confirm
    _cluster_must_exist

    local -x CHARTS_VERSION="${2-}"

    _uses_pulumi_stack validator-runbook

    subcmd_install_data_export_bucket_key

    subcmd_pulumi validator-runbook up --yes --skip-preview --show-sames "${args[@]}"
}

###

subcommand_whitelist[ci_apply_validator]='Run only by CircleCI'

function subcmd_ci_apply_validator() {
    _needs_auth0_validator_management_api_creds
    _assert_lock --for-ci

    # A CI-specific variant of 'cncluster apply_validator' that removes the need
    # for manual confirmation, and also always uses the same target cluster
    # as the one the validator is deployed on.

    if [ -z "${CI-}" ]; then
        _error "This subcommand is available to CI jobs only."
    fi

    # By default, this is unset and we infer the previous values based on the currently running cluster.
    # However, we allow overwriting it to account for cases where the previous cluster is broken in some way.
    if [ -n "${RESTORE_CLUSTER:-}" ] && [ -z "${BOOTSTRAPPING_CONFIG:-}" ]; then
        CLUSTER="$GCP_CLUSTER_BASENAME"
        NOW="$(date +"%Y-%m-%dT%H:%M:%S.000Z")"
        export BOOTSTRAPPING_CONFIG="{\"cluster\": \"$CLUSTER\", \"date\": \"$NOW\"}"
    fi

    _cluster_show

    if [ -n "${BOOTSTRAPPING_CONFIG:-}" ]; then
       _info "Bootstrapping Validator from ${BOOTSTRAPPING_CONFIG}"
    fi

    local -x TARGET_CLUSTER="${GCP_CLUSTER_BASENAME}"

    local -x CHARTS_VERSION="${1-}"

    _uses_pulumi_stack validator-runbook

    subcmd_install_data_export_bucket_key

    subcmd_pulumi validator-runbook up --yes --skip-preview "${args[@]}"
}

###

subcommand_whitelist[pdown_validator]="Take the current validator-runbook Pulumi configuration down"

function subcmd_pdown_validator(){
    _production_gate
    _prompt_to_confirm
    _cluster_must_exist

    subcmd_pulumi validator-runbook down --yes --skip-preview
}

###

subcommand_whitelist[ci_pdown_validator]="Run only by CircleCI"

function subcmd_ci_pdown_validator(){

    if [ -z "${CI-}" ]; then
        _error "This subcommand is available to CI jobs only."
    fi

    subcmd_pulumi validator-runbook down --yes --skip-preview
}

###

subcommand_whitelist[lock]="Attempt to claim the lock on a cluster."

function subcmd_lock() {
    lockholder=$(_current_lockholder)
    if [ -n "$lockholder" ]; then
        if [ "${lockholder}" = "$(whoami)" ]; then
            _info "Cluster is already locked to you. Lock age: $(_current_lock_age_formatted)."
        else
            _error "Cluster already locked by: ${lockholder}. Lock age: $(_current_lock_age_formatted)."
        fi
    else
        local lockholder
        lockholder=$(whoami)
        kubectl create secret generic cluster-lock --from-literal=lockholder="$lockholder" > /dev/null
        _info "Cluster lock claimed successfully."
        if ! jq --arg login "$lockholder" -e 'to_entries | map(.value) | flatten | any(. == $login)' "$REPO_ROOT/.circleci/cluster-lock-users.json" >/dev/null; then
            echo
            _warning \
                "There is no corresponding entry for $lockholder in '$REPO_ROOT/.circleci/cluster-lock-users.json'.\n" \
                "You will not be able to run preflight checks on CI, until you add an entry with your CI username to that file."
        fi
    fi
}

###

subcommand_whitelist[lockholder]="Print the current lockholder, if any, for the cluster."

function subcmd_lockholder() {
    _current_lockholder
}

###

subcommand_whitelist[unlock]="Release the lock on a cluster"

function _unlock() {
  kubectl delete secret cluster-lock > /dev/null
}

function _check_stateful_sets() {
    # Checks if any StatefulSets EXCEPT those with a prometheus image (which are part of the infra stack)
    # are currently deployed
    # grep exits with return code 1 if it finds no matches so we account for that
    query_result=$(kubectl get StatefulSets -A -o json 2> /dev/null | jq '.items[].spec.template.spec.containers[].image' |  { grep -v prometheus || test $? = 1; })
    echo "$query_result"
}

function _check_reset_and_unlock() {
    s=$(_check_stateful_sets)

    if [ -n "$s" ]; then
        echo -e "Cluster not reset, it is recommended to reset it before unlocking. Reset now?"
        read -r -p '[y/n]: '
        if [ "${REPLY}" != 'n' ]; then
            _cluster_reset
            echo "Done resetting, unlocking.."
        fi
    else
        echo "Cluster does not need reset, unlocking.."
    fi

    _unlock
}

function subcmd_unlock() {
    _assert_lock

    lockholder=$(_current_lockholder)
    if [ -n "$lockholder" ]; then
        if [ "${lockholder}" = "$(whoami)" ]; then
            _check_reset_and_unlock
            _info "Cluster lock successfully released."
        else
            _error "You cannot unlock cluster locked by: ${lockholder}"
        fi
    else
        _info "Cluster not locked."
    fi
}

###

subcommand_whitelist[unlock_force]="Forcibly release the lock on a cluster."

function subcmd_unlock_force() {
    _prompt_to_confirm --no-lock

    lockholder=$(_current_lockholder)
    if [ -n "$lockholder" ]; then
        _check_reset_and_unlock
        _warning "Cluster forcibly unlocked, please let former lockholder know: ${lockholder}"
    else
        _info "Cluster was not locked."
    fi
}

###

subcommand_whitelist[kill_sv_app]='Spin down sv-app to zero replicas for the specified namespace'

function subcmd_kill_sv_app() {
    _cluster_must_exist

    _assert_lock

    lockholder=$(_current_lockholder)
    if [ -n "$lockholder" ]; then
        if [ "${lockholder}" = "$(whoami)" ]; then
            _info "Killing sv-app for $1"
            kubectl patch deployment sv-app --namespace "$1" -p '{"spec":{"replicas":0}}'
        else
            _error "You cannot edit a cluster locked by: ${lockholder}"
        fi
    else
        _error "Cluster not locked."
    fi
}

###

subcommand_whitelist[revive_sv_app]='Spin up sv-app to one replica for the specified namespace'

function subcmd_revive_sv_app() {
    _cluster_must_exist

    _assert_lock

    lockholder=$(_current_lockholder)
    if [ -n "$lockholder" ]; then
        if [ "${lockholder}" = "$(whoami)" ]; then
            _info "Reviving sv-app for $1"
            kubectl patch deployment sv-app --namespace "$1" -p '{"spec":{"replicas":1}}'
        else
            _error "You cannot edit a cluster locked by: ${lockholder}"
        fi
    else
        _error "Cluster not locked."
    fi
}

###

subcommand_whitelist[debug_shell]='Spin up a debug container on the cluster, and open a shell terminal in it'

function subcmd_debug_shell() {
  _cluster_must_exist

  VERSION_NUMBER=$(get-snapshot-version)

  _info "Deploying debug pod"
  kubectl apply --wait -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: cn-debug
  labels:
    app: cn-debug
spec:
  containers:
  - name: cn-debug
    image: us-central1-docker.pkg.dev/da-cn-shared/cn-images/cn-debug:${VERSION_NUMBER}
    command: ["/bin/sleep", "2h"]
    imagePullPolicy: Always
  restartPolicy: Never
EOF

  ( _info "Waiting for debug pod to become ready" && \
    kubectl wait --for=condition=Ready pod cn-debug --timeout=30s && \
    _info "Opening terminal on debug pod" && \
    kubectl exec -it cn-debug -- /bin/bash ) || true

  _info "Deleting debug pod"
  kubectl delete pod cn-debug
}

###

subcommand_whitelist[participant_console]='Open a Canton console against a single participant running in the target namespace'

function subcmd_participant_console() {
    _cluster_must_exist

    namespace="${1-}"
    domain=${2:-0}

    if [ -z "${namespace}" ]; then
        _error "Usage: $SCRIPTNAME participant_console <namespace-name>"
    fi

    app="participant"
    app_container="$app"
    k8s_labels_for_app

    if ! participant_pod=$(_get_single_pod "$namespace" "$app"); then
      _error "No participant found in namespace '$namespace'."
    fi

    if (netstat -an | grep ".1100[12].*LISTEN"); then
      _error "Ports 11001 and/or 11002 are already in use on localhost. Please close any processes that might be listening on them."
    fi

    app="sv-app"
    k8s_labels_for_app
    sv_app_pod_label=$app
    app="validator-app"
    k8s_labels_for_app
    validator_app_pod_label=$app

    if [ ! "${LEDGER_API_AUTH_TOKEN-}" ] && sv_app_pod=$(_get_single_pod "$namespace" "$sv_app_pod_label"); then
      if LEDGER_API_AUTH_TOKEN=$(_get_env_value "$namespace" "$sv_app_pod" CN_APP_SV_LEDGER_API_AUTH_TOKEN); then
        _info "Using Ledger API token from '$sv_app_pod'..."
      else
        _info "Getting Ledger API Auth0 credentials from '$sv_app_pod'..."
        if \
          client_id=$(_get_env_value "$namespace" "$sv_app_pod" sv-app CN_APP_SV_LEDGER_API_AUTH_CLIENT_ID) && \
          client_secret=$(_get_env_value "$namespace" "$sv_app_pod" sv-app CN_APP_SV_LEDGER_API_AUTH_CLIENT_SECRET) && \
          url=$(_get_env_value "$namespace" "$sv_app_pod" sv-app CN_APP_SV_LEDGER_API_AUTH_URL) && \
          audience=$(_get_env_value "$namespace" "$participant_pod" sv-app AUTH_TARGET_AUDIENCE)
        then
          _info "Getting Ledger API auth token from Auth0 using Ledger API Auth0 credentials from '$sv_app_pod'..."
          LEDGER_API_AUTH_TOKEN=$(_get_ledger_api_auth_token_from_auth0 "$client_id" "$client_secret" "$url" "$audience")
        else
          _info "Failed getting Ledger API Auth0 credentials from '$sv_app_pod'..."
        fi
      fi
    elif validator_app_pod=$(_get_single_pod "$namespace" "$validator_app_pod_label"); then
      if LEDGER_API_AUTH_TOKEN=$(_get_env_value "$namespace" "$validator_app_pod" CN_APP_VALIDATOR_LEDGER_API_AUTH_TOKEN); then
        _info "Using Ledger API token from '$validator_app_pod'..."
      else
        _info "Getting Ledger API Auth0 credentials from '$validator_app_pod'..."
        if \
          client_id=$(_get_env_value "$namespace" "$validator_app_pod" validator-app CN_APP_VALIDATOR_LEDGER_API_AUTH_CLIENT_ID) && \
          client_secret=$(_get_env_value "$namespace" "$validator_app_pod" validator-app CN_APP_VALIDATOR_LEDGER_API_AUTH_CLIENT_SECRET) && \
          url=$(_get_env_value "$namespace" "$validator_app_pod" validator-app CN_APP_VALIDATOR_LEDGER_API_AUTH_URL) && \
          audience=$(_get_env_value "$namespace" "$participant_pod" validator-app AUTH_TARGET_AUDIENCE)
        then
          _info "Getting Ledger API auth token from Auth0 using Ledger API Auth0 credentials from '$validator_app_pod'..."
          LEDGER_API_AUTH_TOKEN=$(_get_ledger_api_auth_token_from_auth0 "$client_id" "$client_secret" "$url" "$audience")
        else
          _info "Failed getting Ledger API Auth0 credentials from '$validator_app_pod'..."
        fi
      fi
    fi
    if [ "${LEDGER_API_AUTH_TOKEN-}" ]; then
      _info "Using Ledger API token \"$LEDGER_API_AUTH_TOKEN\"".
      export LEDGER_API_AUTH_TOKEN
    else
      _warning "No Ledger API token found/set. Only the admin API will work."
    fi

    _info "Starting port forwarding from '$participant_pod'..."
    kubectl port-forward -n "$namespace" "$participant_pod" 11001:5001 11002:5002 &
    port_forwarding_pid=$!

    _info "Starting Canton console..."
    canton -v -c "$REPO_ROOT/build-tools/local-participant.conf"

    _info "Stopping port forwarding."
    kill $port_forwarding_pid
}

function _get_single_pod() {
    namespace="${1-}"
    app_name="${2-}"
    readarray -d ' ' -t matching_pods < <(kubectl get pods -n "$namespace" -l app="$app_name"  -o 'jsonpath={.items[*].metadata.name}')

    if [ ${#matching_pods[@]} -gt 1 ]; then
      _error "More than one pods running the '$app_name' app found in namespace '$namespace'."
    elif [ ${#matching_pods[@]} -eq 1 ]; then
      echo "${matching_pods[0]}"
    else
      return 1
    fi
}

function _get_env_value() {
    namespace=$1
    pod_name=$2
    env_name=$3
    container=$4

    if output=$(kubectl exec -n "$namespace" "$pod_name" -c "$container" -- printenv "$env_name" 2>&1); then
      echo "$output"
    else
      return 1
    fi
}

function _get_ledger_api_auth_token_from_auth0() {
    LEDGER_API_AUTH_CLIENT_ID=$1
    LEDGER_API_AUTH_CLIENT_SECRET=$2
    LEDGER_API_AUTH_URL=$3
    LEDGER_API_AUTH_AUDIENCE=$4

    TOKEN_URL=${LEDGER_API_AUTH_URL//\/.well-known\/openid-configuration/\/oauth\/token/}

    curl -sSLf --request POST \
      --url "$TOKEN_URL" \
      --header "content-type: application/json" \
      --data "{\"client_id\":\"$LEDGER_API_AUTH_CLIENT_ID\",\"client_secret\":\"$LEDGER_API_AUTH_CLIENT_SECRET\",\"audience\":\"$LEDGER_API_AUTH_AUDIENCE\",\"grant_type\":\"client_credentials\"}" \
      | jq '.access_token' \
      | sed s/\"//g
}

function _get_preflight_test_names() {
  hint="${1-}"

  cd "${REPO_ROOT}" && sbt printTests 1>&2

  if [ "${IS_DEVNET-}" != false ]; then
    tests_filename="test-full-class-names-$hint-preflight.log"
  else
    tests_filename="test-full-class-names-$hint-preflight-non-devnet.log"
  fi

  awk '{print $1}' "$REPO_ROOT"/"$tests_filename" | paste -s -d' ' -
}

###

subcommand_whitelist[backup_nodes]='Backup one or more CN nodes in the cluster'

function subcmd_backup_nodes() {
    _cluster_must_exist

    if [ $# -eq 0 ]; then
        nodes="sv-1 sv-2 sv-3 sv-4 validator1 splitwell"
    else
        nodes="$*"
    fi

    for node in $nodes; do
        case "$node" in
            sv-1|sv-2|sv-3|sv-4)
                _info "Backing up sv node $node"
                "$REPO_ROOT"/cluster/scripts/node-backup.sh sv "$node"
                ;;
            validator1|splitwell)
                _info "Backing up validator node $node"
                "$REPO_ROOT"/cluster/scripts/node-backup.sh validator "$node"
                ;;
            *)
                _error "Unknown node $node"
                ;;
        esac
    done
}

###

subcommand_whitelist[restore_node]='Restore a full CN node from backup'

function subcmd_restore_node() {
    _cluster_must_exist

    local force=""
    POSITIONAL_ARGS=()
    while [[ $# -gt 0 ]]; do
        case $1 in
            --force)
                force="--force"
                shift
                ;;
            -*)
                _error "Unknown option $1"
                ;;
            *)
                POSITIONAL_ARGS+=("$1")
                shift
                ;;
        esac
    done
    set -- "${POSITIONAL_ARGS[@]}"

    node="${1-}"
    backup_run_id="${2-}"

    if [ -z "$node" ]; then
        _error "Usage: $SCRIPTNAME restore_node <namespace_name> [<backup_run_id>]"
    fi

    if [ -z "$backup_run_id" ]; then
        _info "No backup run_id given, looking for the latest backup"
        backup_run_id=$("$REPO_ROOT"/cluster/scripts/find-recent-backup.sh "$node")
        if [ -z "$backup_run_id" ]; then
            _error "No recent backup found for $node"
        fi
        _info "Found latest backup run ID: $backup_run_id"
    fi

    case "$node" in
        sv-1|sv-2|sv-3|sv-4)
            _info "Restoring sv node $node"
            "$REPO_ROOT"/cluster/scripts/node-restore.sh $force "$node" "$backup_run_id" cometbft-0 sequencer-0 participant-0 mediator-0 sv-app-0 scan-0 validator
            ;;
        validator1|splitwell)
            _info "Restoring validator node $node"
            "$REPO_ROOT"/cluster/scripts/node-restore.sh $force "$node" "$backup_run_id" participant validator
            ;;
        *)
            _error "Unknown node $node"
            ;;
    esac
}

################################
### Main
################################

if [ -z "${SUBCOMMAND_NAME-}" ]; then
    subcmd_help

    _error  "Missing subcommand"
fi


if [ ! ${subcommand_whitelist[${SUBCOMMAND_NAME}]+_} ]; then
    subcmd_help

    _error  "Unknown subcommand: ${SUBCOMMAND_NAME}"
fi

"subcmd_${SUBCOMMAND_NAME}" "$@"
