#! /usr/bin/env bash
set -eou pipefail

LOCK_FILE="$REPO_ROOT"/daml/dars.lock
DAMLC="$HOME/.cache/daml-build/${SDK_VERSION}/damlc/damlc"

if [ -z "${CI-}" ]; then
    out_file="$LOCK_FILE"
else
    out_file=$(mktemp)
fi

rm -f "$out_file"
cd "$REPO_ROOT"
dars=$(find daml -name "*.dar" | grep "/.daml/dist" | sort)
for dar in $dars
do
    id=$($DAMLC inspect-dar "$dar" --json | jq -r '.main_package_id')
    echo "$dar $id" >> "$out_file"
done

if [ -n "${CI-}" ]; then
    are_diff=0
    diff "$out_file" "$LOCK_FILE" > /dev/null || are_diff=$?
    if [ $are_diff -ne 0 ]; then
        echo "DAR package ids have changed, please run build-tools/dar-lock and commit the updated dars.lock file"
        rm "$out_file"
        exit 1
    fi
    rm "$out_file"
fi
