#! /usr/bin/env bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "${script_dir}/lib/libcli.source"

if [ -z "$1" ] || [ -z "$2" ]; then
    _error "Usage: $0 <from-image-tag> <to-image-tag>"
else
    fromImageTag=$1
    toImageTag=$2
fi

[[ -z "${MAKE}"  ]] && _error 'must be run from within from make'

if ! docker-check "${fromImageTag}" --optional; then
   _error "Cannot promote missing image: ${fromImageTag}"
fi

docker pull "${fromImageTag}"
docker tag "${fromImageTag}" "${toImageTag}"
docker push "${toImageTag}"

echo "${toImageTag}" > target/docker.promote
