#! /usr/bin/env bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "${script_dir}/lib/libcli.source"

if [ -z "$1" ]; then
    _error "Usage: $0 <image-tag>"
else
    image=$1
fi

if [ "$2" = "--force" ]; then
    force=yes
fi

[[ -z "${MAKE}" || ! -f 'target/docker.id' ]] && _error 'must be run from within from make'

id="$(<target/docker.id)"

# matching tag file (without force) skips build

if [ -f "target/docker.push" ]; then

    tagfileimage="$(<target/docker.push)"

    if [ "${image}" = "${tagfileimage}" ]; then
        if [ -z "${force}" ]; then
            _log "Docker image already pushed."
            exit 0
        fi
    else
        _warning "Docker image already pushed. Adding tag."
    fi
fi

if docker-check "${image}" > /dev/null 2>&1; then
  if [ -z "${force}" ]; then
    _warning "Cowardly refusing to push, image already exists in repo:\n${image}\n You can force push with make docker-push-force"
    skippush=yes
  else
    _warning "Forcing push, image already exists in repo:\n${image}"
  fi
fi

if [ -z "${skippush}" ]; then
    if ! _set_x docker tag "${id}" "${image}"; then
        _error "Could not tag image."
        exit 1
    fi

    if ! _set_x docker push "${image}"; then
        _error "Could not push image."
        exit 1
    fi
fi

echo "${image}" > target/docker.push
