#! /usr/bin/env bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "${script_dir}/lib/libcli.source"

if [ -z "$1" ]; then
    _error "Usage: $0 <image-tag>"
else
    image=$1
fi

if [ "$2" = "--force" ]; then
    force=yes
fi

[[ -z "${MAKE}" || ! -f 'target/docker.id' ]] && _error 'must be run from within from make'

id="$(<target/docker.id)"

if ! docker-check "${image}"; then
  if [ -z "${force}" ]; then
    _warning "Cowardly refusing to push, image already exists in repo:\n${image}"
    exit 0
  else
    _warning "Forcing push, image already exists in repo:\n${image}"
  fi
fi

_set_x docker tag "${id}" "${image}"
_set_x docker push "${image}"
