#! /usr/bin/env bash

prefix=$(<"${REPO_ROOT}"/HELM_CHART_VERSION)

sha=$(git rev-parse HEAD)
commit_date=$(git log -n1 --format=%cd --date=format:%Y%m%d "$sha")
number_of_commits=$(git rev-list --count "$sha")
commit_sha_8=$(git log -n1 --format=%h --abbrev=8 "$sha")

echo "$prefix-snapshot.$commit_date.$number_of_commits.0.v$commit_sha_8"
