#! /usr/bin/env bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "${script_dir}/lib/libcli.source"

if [ -z "$1" ]; then
    _error "Usage: $0 <app-name>"
else
    appname=$1
fi

set -euo pipefail

version="$(get-snapshot-version)"

# the version has a v prefix hardcoded in the pulumi-kuburnetes-operator helm chart so we add one as well
if [ "$appname" == "pulumi-kubernetes-operator" ]; then
    version="v${version}"
fi

# if the version is dirty (developer version), we push it to the private dev artifactory registry.
# if the version is built from a non-main, non-release branch snapshot, we push it to the private dev artifactory registry.
# if the version is built from a main, release-line branch, we push it to the public artifactory registry
if [[ $version == *-dirty ]]; then
    echo "digitalasset-canton-network-docker-dev.jfrog.io/digitalasset/${appname}:${version}"
else
  current_branch=$(git rev-parse --abbrev-ref HEAD)
  if [ "$current_branch" == "main" ] || [[ "$current_branch" == release-line-* ]]; then
    echo "digitalasset-canton-network-docker.jfrog.io/digitalasset/${appname}:${version}"
  else
    echo "digitalasset-canton-network-docker-dev.jfrog.io/digitalasset/${appname}:${version}"
  fi
fi

