#!/usr/bin/env bash

current_branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$current_branch" == "main" ]; then
    # If we are on main, we consider the previous commit on main to be the "latest"
    git rev-parse HEAD^
else
    git merge-base main "$current_branch"
fi
