#!/bin/bash

# Converts various types of git references to a valid value for `CHARTS_VERSION`

set -eou pipefail

if [ -z "${1:-}" ]; then
  echo "local"
# take 1.2.3 if argument matches release-line-1.2.3
elif [[ $1 == release-line-*  ]]; then
  echo "${1#release-line-}"
# take latest tag that looks like a release tag (e.g. 1.2.3) if argument matches a commit or tag
elif [ "$(git cat-file -t "$1")" ]; then
  git describe --tags --match "[0-9][0-9\.][0-9\.]*" --abbrev=0 "$1"
# take latest tag that looks like a release tag (e.g. 1.2.3) if argument matches a branch
elif [ "$(git cat-file -t "origin/$1")" ]; then
  git describe --tags --match "[0-9][0-9\.][0-9\.]*" --abbrev=0 "origin/$1"
else
  >&2 echo "Could not parse version $1"
  exit 1
fi
