#! /usr/bin/env bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "${script_dir}/lib/libcli.source"

if [ -z "$1" ]; then
    _error "Usage: $0 <app-name>"
else
    appname=$1
fi

set -euo pipefail

version="$(get-snapshot-version)"

echo "$DEV_DOCKER_REGISTRY/${appname}:${version}"
