#!/bin/bash

set -euo pipefail

# This script is used in CircleCI to determine whether there's been Helm/Pulumi changes since the latest base version.

helm_file_paths=("$REPO_ROOT/cluster")
# Find latest commit where those were modified
changed_files_hash=$(git log -n 1 --format="%H" -- "${helm_file_paths[@]}")

latest_base_version=$(build-tools/find_latest_base_version.sh)

if git merge-base --is-ancestor "$latest_base_version" "$changed_files_hash"; then
    echo "There's been changes to Helm or Pulumi ($changed_files_hash) since the latest base version ($latest_base_version)."
    exit 1
else
    echo "There's been no changes to Helm or Pulumi since the latest base version ($latest_base_version)."
    exit 0
fi
