#!/usr/bin/env bash

set -eou pipefail

# shellcheck disable=SC1091
source "${TOOLS_LIB}/libcli.source"

_info "Re-versioning local Daml models from x.y.z to x.y.z.123"
find "daml" -name "daml.yaml" -exec sed -i 's/^version: \([0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}\)/version: \1.123/g' {} \;
find . -name "*.dar" -not -path "*/test/resources/daml/*" -not -path "*-current.dar" -not -path "./daml/dars/*" -exec rm {} \;

base_version=$(get-snapshot-version latest_release)

ALL_BUNDLES_DIR="${REPO_ROOT}/apps/app/src/test/resources/bundles"
mkdir -p "${ALL_BUNDLES_DIR}"
tarball="${base_version}_cn-node-0.1.0-SNAPSHOT.tar.gz"

if [ -f "${ALL_BUNDLES_DIR}/${tarball}" ]; then
  _info "Release ${base_version} exists locally already"
else
  _info "Fetching and extracting release ${base_version} from GCP"
  export CLOUDSDK_CORE_PROJECT=da-cn-shared
  set +e
  num_retries=0
  # Builds on main aren't serialized, so the previous release might not be available yet.
  # The bundle step takes about 13 minutes currently, so waiting for 20 minutes should be enough.
  max_retries=120
  until gsutil cp "gs://cn-release-bundles/$tarball" "${ALL_BUNDLES_DIR}"; do
  ((++num_retries))
  if ((num_retries>max_retries)); then
    _error "Failed to download release after $max_retries attempts"
  fi
  sleep 10
  done
  set -e
fi

BUNDLE_DIR="${ALL_BUNDLES_DIR}/${base_version}"
mkdir -p "${BUNDLE_DIR}"
tar zxf "${ALL_BUNDLES_DIR}/$tarball" -C "$BUNDLE_DIR"

_info "Copying dar files into the respective daml directories"

# Make sure the base Splitwell uses the base dars, and not "current" from the local repo
mkdir -p "daml/splitwell/src/main/resources/dar/"
cp "${BUNDLE_DIR}/cn-node-0.1.0-SNAPSHOT/dars/splitwell-current.dar" "daml/splitwell/src/main/resources/dar/splitwell-base.dar"
mkdir -p "daml/splitwell/.daml/dist/"
cp "${BUNDLE_DIR}/cn-node-0.1.0-SNAPSHOT/dars/splitwell-current.dar" "daml/splitwell/.daml/dist/splitwell-base.dar"
sed -i 's/splitwell-current.dar/splitwell-base.dar/g' "${BUNDLE_DIR}"/cn-node-0.1.0-SNAPSHOT/examples/splitwell/splitwell-validator.conf
sed -i 's/splitwell-current.dar/splitwell-base.dar/g' "${BUNDLE_DIR}"/cn-node-0.1.0-SNAPSHOT/testResources/include/validators/splitwell-validator.conf
