#! /usr/bin/env bash

IMAGE_TAG=$(get-docker-image-tag)

VERSION_NUMBER=$(get-snapshot-version)

sed --expression="s/IMAGE_TAG/${IMAGE_TAG}/g" | \
    sed --expression="s/VERSION_NUMBER/${VERSION_NUMBER}/g"
