#! /usr/bin/env bash

if [ ! -z "${CNCLUSTER_STATIC_DIRTY_VERSION}" ]; then
    if [ ! -z "${CI}" ]; then
        >&2 echo "CNCLUSTER_STATIC_DIRTY_VERSION and CI must not be set together"
        exit 1
    fi
    echo "${USER}-dirty"
    exit 0
fi

if [ -z "${CI}" ]; then
    revision_prefix="${USER}-"
fi

if [[ $(git diff --stat) != '' || $(git diff --cached) != '' ]]; then
    if [ -z "${CI}" ]; then
        revision_suffix="-dirty"
    else
        >&2 echo "Repo was dirty on CI"
        git status
        git --no-pager diff --cached
        exit 1
    fi
fi


# get the deployment version tag
echo "${tag_prefix}git-${revision_prefix}$(git rev-parse HEAD)${revision_suffix}"
