#! /usr/bin/env bash

if [ -z "${CI}" ]; then
    revision_prefix="${USER}-"
fi

if [[ $(gitdiff --stat) != '' || $(git diff --cached) != '' ]]; then
    if [ -z "${CI}" ]; then
        revision_suffix="-dirty"
    else
        >&2 echo "Repo was dirty on CI"
        git status
        git diff --no-pager --cached
        exit 1
    fi
fi


# get the deployment version tag
echo "${tag_prefix}git-${revision_prefix}$(git rev-parse HEAD)${revision_suffix}"
