#! /usr/bin/env bash

if [ -z "${CI}" ]; then
    revision_prefix="${USER}-"
fi

# TODO(i1017): dirty flag disabled due to annoyingly inconsistent package ids.
#  Once we bump canton version and resolve that, we should uncomment the lines below.
#if [[ $(gitdiff --stat) != '' || $(git diff --cached) != '' ]]; then
#  revision_suffix="-dirty"
#fi


# get the deployment version tag
echo "${tag_prefix}git-${revision_prefix}$(git rev-parse HEAD)${revision_suffix}"
