openapi: 3.0.0
info:
  title: SV API
  version: 0.0.1
tags:
  - name: sv
paths:
  /admin/validator/onboarding/ongoing:
    get:
      tags: [sv]
      x-jvm-package: sv
      operationId: "listOngoingValidatorOnboardings"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ListOngoingValidatorOnboardingsResponse"
  /admin/validator/onboarding/prepare:
    post:
      tags: [sv]
      x-jvm-package: sv
      operationId: "prepareValidatorOnboarding"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/PrepareValidatorOnboardingRequest"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/PrepareValidatorOnboardingResponse"
        "500":
          description: internal server error
          content:
            text/plain:
              schema:
                type: string
  /onboard/validator:
    post:
      tags: [sv]
      x-jvm-package: sv
      operationId: "onboardValidator"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/OnboardValidatorRequest"
      responses:
        "200":
          description: ok
        "400":
          description: bad request
          content:
            text/plain:
              schema:
                type: string
        "401":
          description: unauthorized
          content:
            text/plain:
              schema:
                type: string
  /debug:
    get:
      tags: [sv]
      x-jvm-package: sv
      operationId: "getDebugInfo"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/GetDebugInfoResponse"
  /connected-domains:
    get:
      tags: [sv]
      x-jvm-package: sv
      operationId: "listConnectedDomains"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ListConnectedDomainsResponse"
components:
  schemas:
    ListOngoingValidatorOnboardingsResponse:
      type: object
      required:
        - ongoing_validator_onboardings
      properties:
        ongoing_validator_onboardings:
          type: array
          items:
            $ref: "../../../../common/src/main/openapi/common.yaml#/components/schemas/Contract"

    PrepareValidatorOnboardingRequest:
      type: object
      required:
      - expires_in # duration in seconds
      properties:
        expires_in:
          type: integer
          minimum: 1

    PrepareValidatorOnboardingResponse:
      type: object
      required:
      - secret
      properties:
        secret:
          type: string

    OnboardValidatorRequest:
      type: object
      required:
      - party_id
      - secret
      properties:
        party_id:
          type: string
        secret:
          type: string
      type: object
      required:
      - party_id
      - secret
      properties:
        party_id:
          type: string
        secret:
          type: string

    GetDebugInfoResponse:
      type: object
      required:
        - sv_user
        - sv_party_id
        - svc_party_id
        - coin_rules_contract_id
        - svc_rules_contract_id
      properties:
        # User representing the SV
        sv_user:
          type: string
        # Party representing the SV
        sv_party_id:
          type: string
        # Party representing the whole SVC
        svc_party_id:
          type: string
        # Contract ID of the CoinRules contract associated with the SVC
        coin_rules_contract_id:
          type: string
        # Contract IDs of the SvcRules contract associated with the SVC
        svc_rules_contract_id:
          type: string

    ListConnectedDomainsResponse:
      type: object
      required: ["connected_domains"]
      properties:
        connected_domains:
          "$ref": "../../../../common/src/main/openapi/common.yaml#/components/schemas/ConnectedDomains"
