{{- if and .Values.ingress.sequencer .Values.withSvIngress }}
{{- $cluster := .Values.cluster }}
{{- $releaseNamespace := .Release.Namespace }}
{{- range $migrationId := .Values.ingress.decentralizedSynchronizer.migrationIds }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sequencer-{{ $cluster.svNamespace }}-domain-{{ $migrationId }}
  namespace: {{ $releaseNamespace }}
spec:
  hosts:
    - "sequencer-{{ $migrationId }}.{{ $cluster.svNamespace }}.{{ $cluster.hostname }}"
  gateways:
    - cluster-ingress/cn-http-gateway
  http:
    - match:
        - port: 443
      route:
        - destination:
            port:
              number: 5008
            host: global-domain-{{ $migrationId }}-sequencer.{{ $cluster.svNamespace }}.svc.cluster.local
---
{{- end }}
{{- end }}
