
  deploy__CLUSTERNAME_:
    when:
      equal: [ build, << pipeline.parameters.run-job >> ]
    jobs:
      - hold:
          <<: *main-branch-never
          type: approval
      # Deployment
      - docker_images_push:
          <<: *main-branch-never
          context:
            - artifactory
            - datadog
            - slack-context
          requires:
            - hold
      - deployment_test:
          <<: *main-branch-never
          context:
            - artifactory
            - datadog
            - slack-context
          requires:
            - hold
      - deploy_cluster:
          <<: *main-branch-never
          context:
            - artifactory
            - datadog
            - slack-context
          cluster: "_CLUSTERNAME_"
          # deployment/scratchnet* branches break the workflow links from Github to CircleCI.
          # So we want to avoid creating them.
          update_deployment_branch: false
          requires:
            - deployment_test
            - docker_images_push
      - deploy_sv_runbook:
          <<: *main-branch-never
          context:
            - artifactory
            - datadog
            - slack-context
          cluster: "_CLUSTERNAME_"
          requires:
            - deploy_cluster
      - deploy_validator_runbook:
          <<: *main-branch-never
          context:
            - artifactory
            - datadog
            - slack-context
          cluster: "_CLUSTERNAME_"
          requires:
            - deploy_cluster
      - preflight_check:
          <<: *main-branch-never
          context:
            - artifactory
            - canton-network-vpn
            - datadog
            - slack-context
          cluster: "_CLUSTERNAME_"
          requires:
            - hold
      - preflight_sv_check:
          <<: *main-branch-never
          context:
            - artifactory
            - canton-network-vpn
            - datadog
            - slack-context
          cluster: "_CLUSTERNAME_"
          requires:
            - hold
      - preflight_validator_check:
          <<: *main-branch-never
          context:
            - artifactory
            - canton-network-vpn
            - datadog
            - slack-context
          cluster: "_CLUSTERNAME_"
          requires:
            - hold
      - backup_cluster:
          <<: *main-branch-never
          cluster: "_CLUSTERNAME_"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          requires:
            - deploy_cluster
      - reset_cluster:
          <<: *main-branch-never
          cluster: "_CLUSTERNAME_"
          context:
            - canton-network-vpn
            - datadog
          requires:
            - preflight_check
            - preflight_sv_check
            - preflight_validator_check
            - backup_cluster
