# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2.1
orbs:
  slack: circleci/slack@4.9.3

env: &env
  TERM: dumb
  CI: "true"
  USER: circleci

non_devnet_preflight_params: &non_devnet_preflight_params
  test_names_file: "test-full-class-names-core-preflight-non-devnet.log"

parameters:
  # Bump this when you change the definition of what is being cached to make sure
  # old files don't pollute your build.
  cache-version:
    type: string
    default: "47"
  run-job:
    type: enum
    enum:
      [
        build,
        deploy-upgrade,
        healthcheck-devnet,
        healthcheck-sv-runbook-devnet,
        healthcheck-validator-runbook-devnet,
        backup-devnet,
        publish-public-artifacts,
        deploy-operator,
        backup-status-devnet,
        bump-configs,
      ]
    default: build
  # Whether the cluster should be reset before deploying.
  # It only makes sense to unset this if you are planning to use CI to fix a broken deployment.
  reset-before-deploy:
    type: boolean
    default: true
  # Cluster used for the apply-infra job
  cluster:
    type: string
    default: "none"
  # Controls whether to run partial upgrades in `deploy_ciupgrade`
  run-partial-upgrade:
    type: boolean
    default: true
  # Controls whether to run daml upgrades in `deploy_ciupgrade`
  run-daml-upgrade:
    type: boolean
    default: true
  # The base version to be used as part of a `deploy_ciupgrade` and `deploy_hdm_operator` job
  # Empty/default means "upgrade version if set, else latest on branch"
  base-version:
    type: string
    default: ""
  # The target version for hard migrations in the `deploy_hdm_operator` job
  # Empty/default means "latest on branch"
  upgrade-version:
    type: string
    default: ""
  git-repo:
    type: enum
    enum: [canton-network-internal, canton-network-node]
    default: canton-network-node
  # branch_filter parameter of wait_for_previous_pipeline
  branch-filter:
    type: string
    default: ""
  # for jobs that require a migration-id to be specified
  migration-id:
    type: integer
    default: 0
  # used for copying old backups to a bucket
  before-date:
    type: string
    default: ""

notify-fail: &notify-fail
  context: slack-context
  post-steps:
    - run:
        name: Notify on slack & create GH issue
        when: on_fail
        command: |
          .circleci/notification-scripts/failure_notification.sh \
              --slack_channel C05DT77QF5M \
              --branch_pattern "(deployment\\/.*|main|release-line.*)"
        # (C05DT77QF5M = team-canton-network-internal-ci)

channel-notify-parameter: &channel-notify-parameter
  channel_notify:
    type: string
    # #team-canton-network-internal-ci
    default: C05DT77QF5M

cluster-parameter: &cluster-parameter
  cluster:
    type: enum
    enum: [
        "cilr",
        "ciupgrade",
        "devnet",
        "mainnet",
        "testnet",
        "token-std-dev",
        "none",
      ]
    default: "none"

main-branch-only: &main-branch-only
  filters:
    branches:
      only:
        - main

main-branch-never: &main-branch-never
  filters:
    branches:
      ignore:
        - main

minor-release-branch-never: &minor-release-branch-never
  filters:
    branches:
      ignore:
        - /release-line-\d+\.\d+\.\d+/

executors:
  self_hosted_large:
    resource_class: dach_ny/cn-runner-large
    docker:
      - image: cimg/base:current
      - image: postgres:14
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        command: ["postgres", "-c", "max_connections=16000"]
    environment:
      COURSIER_CACHE: "/cache/coursier"
  self_hosted:
    resource_class: dach_ny/cn-runner-for-testing
    docker:
      - image: cimg/base:current
    environment:
      COURSIER_CACHE: "/cache/coursier"

runner_type: &runner_type
  runner_type:
    type: enum
    enum: ["selfhosted", "circleci"]
