cluster:
  imageTag: IMAGE_TAG
imageRepo: "digitalasset-canton-network-docker.jfrog.io/digitalasset"

enableHealthProbes: true

defaultJvmOptions: -Xms2560M -Xmx2560M -Dscala.concurrent.context.minThreads=4
resources:
  limits:
    memory: 4Gi
  requests:
    cpu: "1"
    memory: 4Gi

sequencer:
  persistence:
    host: postgres.sv-1.svc.cluster.local
    secretName: "postgres-secrets"
    databaseName: cantonnet_sequencer

mediator:
  persistence:
    host: postgres.sv-1.svc.cluster.local
    secretName: "postgres-secrets"
    databaseName: cantonnet_mediator

metrics:
  enable: false
  release: prometheus-grafana-monitoring
  interval: 30s

disableAutoInit: false

# k8s affinity for all deployed pods (optional)
# affinity:

# k8s nodeSelector for all deployed pods (optional)
# nodeSelector:
