{
 "title": "Automations",
 "description": "Track the trigger automations being run by CN Apps",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(cn_trigger_completed_total,namespace)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(cn_trigger_completed_total{namespace=~\"$namespace\"},node_type)"
    }
   },
   {
    "name": "trigger_name",
    "label": "Trigger Name",
    "query": {
     "query": "label_values(cn_trigger_completed_total{namespace=~\"$namespace\", node_type=~\"$app\"},trigger_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Polling Triggers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic",
   "type": "stat",
   "description": "The rate of successful iterations completed",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cn_trigger_completed_total{namespace=~\"$namespace\", node_type=~\"$app\", trigger_name=~\"$trigger_name\", trigger_type=\"polling\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Retries",
   "type": "stat",
   "description": "The rate at which the trigger(s) are failing with retryable errors",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cn_trigger_retried_total{namespace=~\"$namespace\", node_type=~\"$app\", trigger_name=~\"$trigger_name\", trigger_type=\"polling\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "The rate at which trigger(s) are failing with fatal/non-retryable errors",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cn_trigger_iterations_failed_total{namespace=~\"$namespace\", node_type=~\"$app\", trigger_name=~\"$trigger_name\", trigger_type=\"polling\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "histogram",
   "description": "The time it took to perform an iteration",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(cn_trigger_latency_duration_seconds_bucket{namespace=~\"$namespace\", node_type=~\"$app\", trigger_name=~\"$trigger_name\", trigger_type=\"polling\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Top 5 Active Triggers",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(trigger_name) (rate(cn_trigger_completed_total{namespace=~\"$namespace\", node_type=~\"$app\", trigger_type=\"polling\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "timeseries",
   "description": "How busy triggers are within a certain time window",
   "gridPos": { "h": 8, "w": 13, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(trigger_name, instance, node_type, trigger_type) (irate(cn_trigger_latency_duration_seconds_sum{namespace=~\"$namespace\", node_type=~\"$app\", trigger_name=~\"$trigger_name\", trigger_type=\"polling\"}[$__rate_interval]))",
     "legendFormat": "{{node_type}} {{instance}} {{trigger_name}}"
    }
   ]
  },
  { "title": "Task-Based Triggers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Traffic",
   "type": "stat",
   "description": "The rate of successful iterations completed",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cn_trigger_completed_total{namespace=~\"$namespace\", node_type=~\"$app\", trigger_name=~\"$trigger_name\", trigger_type=\"taskbased\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Retries",
   "type": "stat",
   "description": "The rate at which the trigger(s) are failing with retryable errors",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cn_trigger_retried_total{namespace=~\"$namespace\", node_type=~\"$app\", trigger_name=~\"$trigger_name\", trigger_type=\"taskbased\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "The rate at which trigger(s) are failing with fatal/non-retryable errors",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cn_trigger_iterations_failed_total{namespace=~\"$namespace\", node_type=~\"$app\", trigger_name=~\"$trigger_name\", trigger_type=\"taskbased\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "histogram",
   "description": "The time it took to perform an iteration",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(cn_trigger_latency_duration_seconds_bucket{namespace=~\"$namespace\", node_type=~\"$app\", trigger_name=~\"$trigger_name\", trigger_type=\"taskbased\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Top 5 Active Triggers",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(trigger_name) (rate(cn_trigger_completed_total{namespace=~\"$namespace\", node_type=~\"$app\", trigger_type=\"taskbased\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "timeseries",
   "description": "How busy triggers are within a certain time window",
   "gridPos": { "h": 8, "w": 13, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(trigger_name, instance, node_type, trigger_type) (irate(cn_trigger_latency_duration_seconds_sum{namespace=~\"$namespace\", node_type=~\"$app\", trigger_name=~\"$trigger_name\", trigger_type=\"taskbased\"}[$__rate_interval]))",
     "legendFormat": "{{node_type}} {{instance}} {{trigger_name}}"
    }
   ]
  }
 ]
}