commands:

  setup_vpn:
    steps:
      - run:
          name: Install VPN client
          command: |
            # Retry because we've seen Ubuntu be down sometimes.
            n=0
            until [ $n -gt 50 ]; do
              sudo apt-get update && break
              n=$((n+1))
              sleep 10
            done
            n=0
            until [ $n -gt 50 ]; do
              sudo apt-get install -y expect charon-cmd && break
              n=$((n+1))
              sleep 10
            done

            sudo tee /etc/strongswan.d/logging.conf \<<'EOF'
            charon-cmd {
                 filelog {
                     charon {
                           path = /var/log/vpn.log
                           time_format = %b %e %T
                           ike_name = yes
                           flush_line = yes
                           append = yes
                           default = 1
                     }
                    # Uncomment to log also to stderr (but that pollutes also the test step in case we retry there after a VPN failure)
                    #  stderr {
                    #        ike = 2
                    #  }
                 }
            }
      - run:
          name: Copy vpn-related scripts
          command: |
            # We're copying the vpn scripts out of the repo so that we can use them also later,
            # after we checkout an older commit for preflight checks. For vpn scripts, always
            # using the latest version seems the most sensible anyway.
            cp -r .circleci/vpn-scripts /tmp
      - run:
          name: Dump public IP
          command: curl checkip.amazonaws.com
      - run:
          name: Start VPN connection
          # the charon-cmd process must remain running throughout the whole job,
          # so run this step in the background to allow subsequent steps to continue
          background: true
          # we use an "expect" script to spawn charon-cmd, and supply credentials,
          # because the interactive password prompt reads directly from
          # /dev/tty rather than stdin, and simple IO piping doesn't work
          command: |
            /usr/bin/sudo touch /var/log/vpn.log
            /usr/bin/sudo chmod a+w /var/log/vpn.log
            /tmp/vpn-scripts/connect-vpn.expect $VPN_HOST_NAME $VPN_USER $VPN_PASSWORD
      - run:
          name: Define local hostname
          command: |
              # Some CircleCI machine failed to resolve local hostname to 127.0.0.1.
              # Giving "sudo: unable to resolve host ip-172-28-55-xx" for sudo commands
              # This (hacky) step should fix the issue (copied from https://circleci.com/developer/orbs/orb/kindred/kin-l2tp-vpn)
              hostname=$(cat /etc/hostname)
              grep -qxF "127.0.0.1 ${hostname}" /etc/hosts || echo "127.0.0.1 ${hostname}" | sudo tee -a /etc/hosts
      - run:
          name: Verify VPN connection
          command: |
            /tmp/vpn-scripts/wait-for-vpn-and-del-default-route.sh

  setup_vpn_routes:
    parameters:
      <<: *cluster-parameter
    steps:
      - run_bash_command_in_nix:
          cmd_name: Setup VPN Routes - Fetching kube config
          cluster: << parameters.cluster >>
          additional_nix_args: "--keep VPN_HOST_NAME --keep VPN_USER --keep VPN_PASSWORD --keep VPN_HOST_IP"
          gce_authenticate: true
          cmd: |
            export KUBECONFIG=$PWD/.kubecfg
            cncluster activate
            /tmp/vpn-scripts/setup-vpn-routes.sh
          cmd_retry_count: 5
          cmd_before_retry: |-
            echo "VPN connection seems to have died, restarting VPN and retrying..."
            /tmp/vpn-scripts/stop-vpn.sh

            echo "Starting VPN..." | tee -a /var/log/vpn.log
            /tmp/vpn-scripts/connect-vpn.expect "$VPN_HOST_NAME" "$VPN_USER" "$VPN_PASSWORD" &

            echo "Waiting for VPN to reconnect"
            /tmp/vpn-scripts/wait-for-vpn-and-del-default-route.sh

  run_todo_script:
    steps:
      - run_bash_command_in_nix:
          when: always
          cmd: ./scripts/check-todos.sh
          additional_nix_args: "--keep GH_TOKEN --keep CIRCLE_BRANCH --keep CIRCLE_PULL_REQUEST"
      - store_artifacts:
          name: Store To-dos as artifacts
          when: always
          path: todo-out/todos
          destination: todos

  export_migration_id:
    parameters:
      <<: *cluster-parameter
      migration_id:
        type: integer
        default: 0
    steps:
      - run_bash_command_in_nix:
          cmd_name: Export active migration ID
          cluster: << parameters.cluster >>
          when: always
          cmd:  |
            if [ << parameters.migration_id >> -ne 0 ]; then
              echo "migration_id is not set to 0, use the parameter value"

              ACTIVE_MIGRATION_ID=<< parameters.migration_id >>

            else
              echo "migration_id is not set, use the one defined in the config.yaml file"

              CONFIG_FILE="cluster/deployment/<< parameters.cluster >>/config.yaml"

              if [[ -f "$CONFIG_FILE" ]]; then
                ACTIVE_MIGRATION_ID=$(yq '.synchronizerMigration.active.id' "$CONFIG_FILE" 2>/dev/null)
              else
                echo "Error: Configuration file not found: $CONFIG_FILE"
                ACTIVE_MIGRATION_ID=0
              fi

              if [[ "$ACTIVE_MIGRATION_ID" == "null" || -z "$ACTIVE_MIGRATION_ID" ]]; then
                ACTIVE_MIGRATION_ID=0
                echo "Default ACTIVE MIGRATION ID: $ACTIVE_MIGRATION_ID"
              else
                echo "ACTIVE MIGRATION ID: $ACTIVE_MIGRATION_ID"
              fi
            fi

            echo "export ACTIVE_MIGRATION_ID=$ACTIVE_MIGRATION_ID" > tmp-migration-id-env
      - run:
          name: Save migration ID to env
          command: |
            source tmp-migration-id-env
            echo "export ACTIVE_MIGRATION_ID=$ACTIVE_MIGRATION_ID" >> "$BASH_ENV"
            rm tmp-migration-id-env

  run_trailing_whitespace_check:
    steps:
      - run_bash_command_in_nix:
          cmd_name: Check for trailing whitespace
          cmd: ./scripts/check-trailing-whitespace.sh

  run_daml_warts_check:
    steps:
      - run_bash_command_in_nix:
          cmd_name: Check for Daml warts
          cmd: ./scripts/check-daml-warts.sh

  run_daml_return_types_check:
    steps:
      - run_bash_command_in_nix:
          cmd_name: Check Daml choice return types
          cmd: ./scripts/check-daml-return-types.sh

  print_gcloud_logs_commands:
    parameters:
      <<: *cluster-parameter
    steps:
      - run_bash_command_in_nix:
          when: always
          cmd_name: Displaying google cloud logs link
          cluster: << parameters.cluster >>
          additional_nix_args: "--keep CIRCLECI_TOKEN --keep CIRCLE_WORKFLOW_ID --keep CIRCLE_JOB"
          gce_authenticate: true
          cmd_retry_count: 5 # we have seen this fail several times, see #13863
          cmd: |
            $SPLICE_ROOT/.circleci/cn-scripts/display-gcloud-link.sh

  # Cannot be defined as a mix-in (like `<<: notify-fail`) because we need to pass the current cluster as parameter
  notify-cluster-fail:
    parameters:
      <<: *cluster-parameter
      channel_notify:
        # This parameter allows selecting different notification channels, which can be handy when a subteam
        # focuses on bringing a potentially noisy deployment under control; e.g., when we sped up devnet in #3126.
        type: string
        # #team-canton-network-internal-ci
        default: C05DT77QF5M
    steps:
      - run:
          name: Notify on slack
          when: on_fail
          command: |
            .circleci/notification-scripts/failure_notification.sh \
              --cluster << parameters.cluster >> \
              --slack_channel << parameters.channel_notify >> \
              --branch_pattern "(deployment\\/.*|main|release-line.*)"

  # TODO(#14750): consider creating a custom image that already has this configured
  docker_prep_build:
    steps:
      # enable containerd image store, to support multi-platform images (see https://docs.docker.com/desktop/containerd/)
      - run:
          name: Modify Docker Daemon Configuration
          command: |
            echo '{"features": {"containerd-snapshotter": true}}' | sudo tee /etc/docker/daemon.json
            sudo systemctl restart docker

  docker_build:
    parameters:
      is_public:
        type: boolean
        default: false
    steps:
      - run_bash_command_in_nix:
         cmd_name: Build docker images
         additional_nix_args: "--keep DOCKER_CERT_PATH \
                              --keep DOCKER_HOST \
                              --keep DOCKER_MACHINE_NAME \
                              --keep DOCKER_TLS_VERIFY \
                              --keep PULUMI_VERSION \
                              --keep NO_PROXY \
                              --keep CIRCLE_REPOSITORY_URL \
                              --keep CIRCLE_SHA1"
         # Retrying as sometimes the download from docker.io fails
         cmd_retry_count: 5
         cmd: |
           make docker-build -j
  docker_login_artifactory:
    steps:
      - run:
          name: Pre-login checks
          command: |
            if [[ -z "${ARTIFACTORY_USER}" || -z "${ARTIFACTORY_PASSWORD}" ]]; then
                echo "artifactory user:key is empty: ${ARTIFACTORY_USER} / pw. maybe add context:artifactory?"
                exit 1
            fi
      - run_bash_command_in_nix:
         cmd_name: Log in to Artifactory
         additional_nix_args: "--keep DOCKER_CERT_PATH \
                              --keep DOCKER_HOST \
                              --keep DOCKER_MACHINE_NAME \
                              --keep DOCKER_TLS_VERIFY \
                              --keep ARTIFACTORY_USER \
                              --keep ARTIFACTORY_PASSWORD \
                              --keep NO_PROXY"
         # Retrying as sometimes the login fails
         cmd_retry_count: 5
         cmd: |
           echo $ARTIFACTORY_PASSWORD | docker login digitalasset-canton-enterprise-docker.jfrog.io -u "$ARTIFACTORY_USER" --password-stdin
           echo $ARTIFACTORY_PASSWORD | docker login digitalasset-canton-network-docker.jfrog.io -u "$ARTIFACTORY_USER" --password-stdin
           echo $ARTIFACTORY_PASSWORD | docker login digitalasset-canton-network-docker-dev.jfrog.io -u "$ARTIFACTORY_USER" --password-stdin

  cancel_entire_workflow_if_this_job_failed:
    steps:
      - run:
          when: on_fail
          name: Cancel the entire workflow if this job failed
          command: |
            curl -fsSL -X POST -H "Circle-Token: ${CIRCLECI_TOKEN}" "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/cancel"

  get_cluster:
    parameters:
      <<: *cluster-parameter
      when:
        type: enum
        enum: ["on_success", "always", "on_fail"]
        default: "on_success"
    steps:
      - attach_workspace:
          at: /tmp/workspace
          when: << parameters.when >>
      - run:
          name: Setting TARGET_CLUSTER env var
          command: |
            if [ << parameters.cluster >> == user-selected-scratchnet ]; then
              . /tmp/workspace/cn_env_vars
              echo "export TARGET_CLUSTER=$TARGET_CLUSTER" >> "$BASH_ENV"
            else
              echo "export TARGET_CLUSTER=<< parameters.cluster >>" >> "$BASH_ENV"
            fi
          when: << parameters.when >>

  preview_pulumi:
    parameters:
      <<: *cluster-parameter
      project:
        type: string
      when_env:
        type: string
        default: ""
    steps:
      - run_bash_command_in_nix:
          cmd_name: Running << parameters.project >> preview on cluster << parameters.cluster >>
          cluster: << parameters.cluster >>
          additional_nix_args: >
            --keep GH_TOKEN
            --keep SLACK_ACCESS_TOKEN
            --keep AUTH0_MANAGEMENT_API_CLIENT_ID
            --keep AUTH0_CN_MANAGEMENT_API_CLIENT_ID
            --keep AUTH0_MANAGEMENT_API_CLIENT_SECRET
            --keep AUTH0_CN_MANAGEMENT_API_CLIENT_SECRET
            --keep AUTH0_SV_MANAGEMENT_API_CLIENT_ID
            --keep AUTH0_SV_MANAGEMENT_API_CLIENT_SECRET
            --keep AUTH0_VALIDATOR_MANAGEMENT_API_CLIENT_ID
            --keep AUTH0_VALIDATOR_MANAGEMENT_API_CLIENT_SECRET
            --keep AUTH0_MAIN_MANAGEMENT_API_CLIENT_ID
            --keep AUTH0_MAIN_MANAGEMENT_API_CLIENT_SECRET
            --keep ARTIFACTORY_USER
            --keep ARTIFACTORY_PASSWORD
            --keep K6_USERS_PASSWORD
            --keep K6_VALIDATOR_ADMIN_USERNAME
            --keep K6_VALIDATOR_ADMIN_PASSWORD
          gce_authenticate: true
          cmd: |
            if ([ -z "<< parameters.when_env >>" ] || env-bool "<< parameters.when_env >>"); then
              echo "Executing << parameters.project >> preview on << parameters.cluster >>"
              cncluster activate
              export CN_PULUMI_LOAD_ENV_CONFIG_FILE="true"
              # overwrite the use of internal DNS in the config file directly
              sed -i 's/SPLICE_DEPLOYMENT_SV_USE_INTERNAL_VALIDATOR_DNS=true/SPLICE_DEPLOYMENT_SV_USE_INTERNAL_VALIDATOR_DNS=false/g' cluster/deployment/<<parameters.cluster>>/.envrc.vars

              if [ "<< parameters.project >>" == "sv-canton" ]; then
                cncluster pulumi_preview_canton
              else
                cncluster pulumi << parameters.project >> preview --diff
              fi

            else
              echo "Skipping preview of << parameters.project >> on << parameters.cluster >>"
            fi

  set_pr_target_branch:
    steps:
      - run:
          name: Setting TARGET_BRANCH env var
          command: |
            PR_NUMBER=$(echo $CIRCLE_PULL_REQUEST | sed 's|.*/pull/\([0-9]*\)|\1|')
            TARGET_BRANCH=$(curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/DACH-NY/canton-network-node/pulls/$PR_NUMBER | jq -r '.base.ref')
            echo "PR target branch: $TARGET_BRANCH"
            echo export "TARGET_BRANCH=\"$TARGET_BRANCH\"" >> "$BASH_ENV"

  clone_and_update_oss_or_splice:
      parameters:
        repo_name:
          type: string
        repository:
          type: string
        directory:
          type: string
      steps:
      - run:
          name: clone << parameters.repo_name >> repo
          command: |
            set -eou pipefail
            cd ..
            for i in $(seq 1 5)
            do
              git clone "<< parameters.repository >>" << parameters.directory >> && s=0 && break || s=$? && sleep 5
            done
            if [[ $s -ne 0 ]]
            then
              exit $s
            fi
            cd "<< parameters.directory >>"
            if git rev-parse "origin/${CIRCLE_BRANCH}"
            then
              echo "Branch $CIRCLE_BRANCH already exists, creating PR against that branch."
              git checkout "$CIRCLE_BRANCH"
            fi
      - run_bash_command_in_nix:
          cmd_name: dump latest into << parameters.repo_name >>
          cmd: |
            scripts/copy-to-splice.sh ../<< parameters.directory >>


  clone_and_update_open_source:
    steps:
      - clone_and_update_oss_or_splice:
          repo_name: DA oss
          repository: "git@github.com:digital-asset/decentralized-canton-sync.git"
          directory: oss
      - clone_and_update_oss_or_splice:
          repo_name: Splice
          repository: git@github.com:hyperledger-labs/splice.git
          directory: splice

  wait_for_sv_runbook_deployment:
    parameters:
        <<: *cluster-parameter
        check_cluster_version:
          type: boolean
          default: true
        migration_id:
          type: integer
          default: 0
    steps:
      - export_migration_id:
          cluster: << parameters.cluster >>
          migration_id: << parameters.migration_id >>
      - run_bash_command_in_nix:
          cmd_name: wait for sv-runbook deployment to finish
          cluster: << parameters.cluster >>
          additional_nix_args: "--keep VPN_HOST_NAME --keep VPN_USER --keep VPN_PASSWORD --keep VPN_HOST_IP --keep ACTIVE_MIGRATION_ID"
          cmd: |
            if [[ << parameters.check_cluster_version >> == true ]]; then
              VERSION=$(get-snapshot-version)
              cncluster wait_version $VERSION
            fi
            # We use readiness of validator-app in the sv namespace as an approximation to the sv's readiness
            cncluster wait sv validator-app ${ACTIVE_MIGRATION_ID}
            echo "Done waiting. All pods in the cluster are:"
            kubectl get pods -A
          cmd_retry_condition: $(if curl --connect-timeout 5 -s ${GCP_CLUSTER_HOSTNAME}; then echo "false"; else echo "true"; fi)
          cmd_retry_count: 2
          cmd_before_retry: |-
            echo "VPN connection seems to have died, restarting VPN and retrying..."
            /tmp/vpn-scripts/restart-vpn.sh
  deploy_operator:
    parameters:
      <<: *cluster-parameter
      deploy_retry_count:
        type: integer
        default: 2
    steps:
      - run_bash_command_in_nix:
          cmd_name: Install pulumi dependencies
          # When nix packages changed, nix will rebuild stuff here, and sometimes go silent for long periods of time
          no_output_timeout: "20m"
          cluster: << parameters.cluster >>
          cmd: |
            make -j cluster/pulumi/build
          cmd_retry_count: 2
      - run_bash_command_in_nix:
          cmd_name: Apply the deployment stack
          cluster: << parameters.cluster >>
          additional_nix_args: >
            --keep GH_TOKEN
            --keep SLACK_ACCESS_TOKEN
            --keep AUTH0_MANAGEMENT_API_CLIENT_ID
            --keep AUTH0_CN_MANAGEMENT_API_CLIENT_ID
            --keep AUTH0_MANAGEMENT_API_CLIENT_SECRET
            --keep AUTH0_CN_MANAGEMENT_API_CLIENT_SECRET
            --keep AUTH0_SV_MANAGEMENT_API_CLIENT_ID
            --keep AUTH0_SV_MANAGEMENT_API_CLIENT_SECRET
            --keep AUTH0_VALIDATOR_MANAGEMENT_API_CLIENT_ID
            --keep AUTH0_VALIDATOR_MANAGEMENT_API_CLIENT_SECRET
            --keep AUTH0_MAIN_MANAGEMENT_API_CLIENT_ID
            --keep AUTH0_MAIN_MANAGEMENT_API_CLIENT_SECRET
            --keep ARTIFACTORY_USER
            --keep ARTIFACTORY_PASSWORD
            --keep K6_USERS_PASSWORD
            --keep K6_VALIDATOR_ADMIN_USERNAME
            --keep K6_VALIDATOR_ADMIN_PASSWORD
            --keep CIRCLE_BUILD_URL
          gce_authenticate: true
          cmd_retry_count: << parameters.deploy_retry_count >>
          cmd_before_retry: |
            .circleci/post-slack-message.sh "Deployment of deployment stack to cluster << parameters.cluster >> failed. Retrying... ( <${CIRCLE_BUILD_URL}|CI Build> )"
          cmd: |
            export CN_PULUMI_LOAD_ENV_CONFIG_FILE=true
            cncluster activate
            cncluster pulumi operator refresh --yes
            cncluster pulumi operator up --skip-preview --diff

  skip_if_flag_set:
    parameters:
      flag:
        type: string
    steps:
      - run:
          name: Skip if << parameters.flag >> flag is set
          command: |
            last_commit_msg=$(git log -1 --pretty=%B)
            if [[ "$CIRCLE_BRANCH" != "main" && "${last_commit_msg}" == *"[<< parameters.flag >>]"* ]]; then
              echo "<< parameters.flag >> flag is set, skipping this job"
              circleci-agent step halt
            fi
