commands:
  wait_for_pulumi_stacks_updated:
    parameters:
      <<: *cluster-parameter
      pulumi_stack_names:
        type: string
        default: "canton-network"
    steps:
      - run_bash_command_in_nix:
          cmd_name: wait for all pulumi stacks to be updated.
          cluster: << parameters.cluster >>
          no_output_timeout: "30m"
          gce_authenticate: true
          cmd: |
            cncluster activate
            EXPECTED_GIT_COMMIT=$(echo "refs/heads/$(git rev-parse --abbrev-ref HEAD)@sha1:$(git rev-parse HEAD)")
            wait_for_stack_updated() {
              local STACK_NAME=$1
              echo "waiting for stack $STACK_NAME being updated with commit $EXPECTED_GIT_COMMIT"
    
              START_TIME=$(date +%s)
              TIMEOUT=1800
              LAST_UNLOCK_AGO=0
              while true; do
                LAST_SUCCESSFUL_COMMIT=$(kubectl get stack $STACK_NAME -n operator -ojsonpath="{.status.lastUpdate.lastSuccessfulCommit}")
              
                if echo "$LAST_SUCCESSFUL_COMMIT" | grep -q "$EXPECTED_GIT_COMMIT"; then
                  echo "stack $STACK_NAME is successfully updated with commit $EXPECTED_GIT_COMMIT"
                  break
                else
                  echo "stack $STACK_NAME is currently on commit: $LAST_SUCCESSFUL_COMMIT. Waiting for the expecting commit $EXPECTED_GIT_COMMIT."
                fi
                # Check for timeout
                CURRENT_TIME=$(date +%s)
                ELAPSED_TIME=$((CURRENT_TIME - START_TIME))
            
                # TODO(#15978): remove this hack, this is only necessary because the operator restarts and gets stuck with its own lock.
                LAST_UNLOCK_AGO=$((LAST_UNLOCK_AGO + CURRENT_TIME - START_TIME))
                if [ $LAST_UNLOCK_AGO -ge 120 ]; then
                  echo "Force-cancelling pulumi locks under the assumption that the operator got stuck."
                  cncluster pcancel
                  LAST_UNLOCK_AGO=0
                fi
              
                if [ $ELAPSED_TIME -ge $TIMEOUT ]; then
                  echo "Timeout reached without finding stack $STACK_NAME has the updated with expected commit $EXPECTED_GIT_COMMIT."
                  exit 1
                fi
                sleep 5
              done            
            }
            
            echo "<< parameters.pulumi_stack_names >>" | tr ',' '\n' | while read STACK; do
              wait_for_stack_updated "$STACK"
            done
