commands:
  ##### Overall setup
  ###### Pre job
  setup_sbt_test_job:
    parameters:
      <<: *runner_type
    steps:
      - when:
          condition:
            equal: [ "circleci", << parameters.runner_type >> ]
          steps:
            - restore_sbt_cache:
                runner_type: << parameters.runner_type >>
      - when:
          condition:
            equal: [ "selfhosted", << parameters.runner_type >> ]
          steps:
            - restore_sbt_cache_self_hosted:
                runner_type: << parameters.runner_type >>
      - restore_precompiled_classes:
          runner_type: << parameters.runner_type >>
      - restore_frontend_node_modules
      - restore_daml_artifacts

  ###### Post job
  save_sbt_job_result:
    parameters:
      upload_caches:
        type: boolean
        default: false
      <<: *runner_type
    steps:
      - upload_test_reports
      # sbt caches are job-specific, so we're ignoring the upload_caches parameter,
      # and saving those caches in every job
      - save_sbt_cache:
          runner_type: << parameters.runner_type >>
      - when:
          condition: << parameters.upload_caches >>
          steps:
            - save_compiled_classes:
                runner_type: << parameters.runner_type >>
            - save_frontend_node_modules
            - save_daml_artifacts
      # re-enable when it's not broken
      # - when:
      #     condition:
      #       and:
      #         - equal: [ << parameters.upload_caches >>, true ]
      #         - equal: [ << parameters.runner_type >>, "selfhosted" ]
      #     steps:
      #       - save_sbt_cache_self_hosted
      - run:
          name: Convert time stamps in browser logs
          when: on_fail
          command: |
            if [[ -d log && -f scripts/convts.py ]]; then
              find log -type f -name "browser*.log" -print0 | xargs -r0 python3 scripts/convts.py
            fi
      - run:
          name: Remove logfiles if the build was successful
          when: on_success
          command: |
            if [[ -d log ]]; then
              rm -f log/*
            fi
      - run: # Pack logfiles to speedup downloads.
          name: Pack Logfiles
          when: on_fail
          command: |
            if [[ -d log ]]; then
              # pigz fails if there is no file to compress, which can be the case if Canton just rolled its logs
              pigz -r log/* || true
            fi
      - store_artifacts:
          name: Store test logs as artifacts (if any)
          path: log
          destination: log

  ## Caching
  ### Classes
  # Note: compiled_classes and sbt_cache commands are largely copied from the Canton repo
  # save compiled target directories to cache (so we don't recompile everything again and again)
  # uses the target directories in the project (e.g. `canton-network-node/target`) which sbt doesn't cache.
  # This cache is not shared among CI jobs.
  save_compiled_classes:
    parameters:
      # required as they seem to contain some links to the coursier locations
      <<: *runner_type
    steps:
      - run:
          name: Creating archive of compiled classes
          command: |
            mkdir -p /tmp/classes
            # We cache */target/scala/* files and */target/streams/* which
            # includes everything that is required for SBT to do fast rebuilds
            # while avoiding issues arising from caching typescript, daml files or anything else.
            find . -type f -a \( -path '*/target/scala*' -o -path '*/target/streams/*' \) | tar --use-compress-program=pigz -cf /tmp/classes/classes.tar.gz --exclude-vcs -T -
      - save_cache:
          name: Uploading archive with compiled classes to cache
          # Key components:
          # - classes: fixed prefix for uniqueness
          # - branch: to prevent re-usage of classes between branches
          # - dependencies: to prevent re-usage of classes with mismatching libraries (this can lead to subtle errors)
          # - rev: to allow for updating the cache when sources have changed
          # - openapi: guardrail does not track dependencies for schema changes properly so we disable the cache if the imported schema changes, see #2747
          key: &compiled_classes_key << parameters.runner_type >> classes-<< pipeline.parameters.cache-version >> branch:{{ .Branch }} buildprops:{{ checksum "project/build.properties" }} buildcommon:{{ checksum "project/BuildCommon.scala" }} damlplugin:{{ checksum "project/DamlPlugin.scala" }} dependencies:{{ checksum "project/Dependencies.scala" }} canton-dependencies:{{ checksum "project/CantonDependencies.scala" }} houserules:{{ checksum "project/Houserules.scala" }} plugins:{{ checksum "project/plugins.sbt" }} build={{ checksum "build.sbt" }} daml:{{ checksum "daml/dars.lock" }} openapi={{ checksum "openapi-cache-key.txt" }} rev:{{ .Revision }}
          paths:
            - /tmp/classes

  # restore pre-compiled target directories from cache (so we don't recompile everything again and again)
  # uses the target directories in the project (e.g. `canton-network-node/target`) which sbt doesn't cache.
  # This cache is not shared among CI jobs.
  restore_precompiled_classes:
    parameters:
      reset_classes_if_requested:
        type: boolean
        default: false
      # required as they seem to contain some links to the coursier locations
      <<: *runner_type
    steps:
      - run:
          name:
          command: |
            find . -wholename '*/openapi/*.yaml' | LC_ALL=C sort | xargs sha256sum > openapi-cache-key.txt
      - restore_cache:
          name: Downloading archive with compiled classes from cache
          keys:
            # First, try to download class files from the same revision
            - *compiled_classes_key
            # Then, try to download the latest class files produced for the same branch.
            # Make sure that library versions still match.
            - << parameters.runner_type >> classes-<< pipeline.parameters.cache-version >> branch:{{ .Branch }} buildprops:{{ checksum "project/build.properties" }} buildcommon:{{ checksum "project/BuildCommon.scala" }} damlplugin:{{ checksum "project/DamlPlugin.scala" }} dependencies:{{ checksum "project/Dependencies.scala" }} canton-dependencies:{{ checksum "project/CantonDependencies.scala" }} houserules:{{ checksum "project/Houserules.scala" }} plugins:{{ checksum "project/plugins.sbt" }} build={{ checksum "build.sbt" }} daml:{{ checksum "daml/dars.lock" }} openapi={{ checksum "openapi-cache-key.txt" }}
            # Then, try to download the latest class files produced for the main branch.
            # Make sure that library versions still match.
            - << parameters.runner_type >> classes-<< pipeline.parameters.cache-version >> branch:main buildprops:{{ checksum "project/build.properties" }} buildcommon:{{ checksum "project/BuildCommon.scala" }} damlplugin:{{ checksum "project/DamlPlugin.scala" }} dependencies:{{ checksum "project/Dependencies.scala" }} canton-dependencies:{{ checksum "project/CantonDependencies.scala" }} houserules:{{ checksum "project/Houserules.scala" }} plugins:{{ checksum "project/plugins.sbt" }} build={{ checksum "build.sbt" }} daml:{{ checksum "daml/dars.lock" }} openapi={{ checksum "openapi-cache-key.txt" }}
      - run:
          name: Extracting precompiled classes
          command: |
            if [[ << parameters.reset_classes_if_requested >> == true ]] &&
               grep "^$CIRCLE_BRANCH$" .circleci/branches_to_be_fully_recompiled_in_ci.txt > /dev/null
            then
              echo "Do not extract precompiled classes, as a full recompilation has been requested."
              exit 0
            fi

            if [[ -e /tmp/classes/classes.tar.gz ]]; then
              tar --use-compress-program=pigz -xf /tmp/classes/classes.tar.gz

              # For some reason, the reset below may change file modification times stamps, if we don't run `git status`.
              git status

              # Reset changes to files under version control.
              git reset --hard

              # Delete untracked files, except for ignored files.
              git clean -fd
              echo "Finished restoring the pre-compiled cache files"

            else
              echo "No precompiled classes found. Skipping..."
            fi

  ### sbt
  save_sbt_cache:
    parameters:
      <<: *runner_type
    steps:
      - when:
          condition:
            equal: [ "circleci", << parameters.runner_type >> ]
          steps:
            - run:
                name: Make caches readable
                # On machine executors, some files in the caches may be owned by root.
                # Make them readable to the cirecleci user.
                command: |
                  for dir in "$HOME/.ivy2/cache" "$HOME/.cache/coursier/v1" "$HOME/.sbt"; do
                    if [[ -e "$dir" ]]; then
                      # The combination of sudo and `|| true` is a bit of a hack.
                      # The underlying assumption is that chmod is only needed when sudo is available.
                      # Unfortunately, there are jobs where sudo is not available.
                      sudo chmod -R a+r "$dir" || true
                    fi
                  done

      - when:
          condition:
            equal: [ "circleci", << parameters.runner_type >> ]
          steps:
            - save_cache:
                name: Uploading Coursier cache
                # The cache is stored only when the build definition or dependencies change
                key: &coursier-cache-key coursier-canton-job={{ .Environment.CIRCLE_JOB }}-dependencies={{ checksum "project/Dependencies.scala" }}-canton-dependencies={{ checksum "project/CantonDependencies.scala" }}-buildcommon:{{ checksum "project/BuildCommon.scala" }}-buildproperties={{ checksum "project/build.properties" }}-houserules={{ checksum "project/Houserules.scala" }}-plugins={{ checksum "project/plugins.sbt" }}-build={{ checksum "build.sbt" }}
                # Components of the cache key:
                # - Keyword "coursier" to indicate this stores the coursier cache.
                # - Name of the job, to avoid interferences between jobs. (Different jobs populate the cached folders differently.)
                # - Dockerfile to start with a clean state if build tools are updated.
                # - Everything in project that may contain a dependency.
                # - build.sbt as it may contain a hardcoded dependency.
                paths:
                  - "~/.cache/coursier/v1/"

      - save_cache:
          name: Uploading Sbt caches
          # The cache is stored only when the build definition or dependencies change
          key: &sbt-cache-key << parameters.runner_type >> sbt-canton-job={{ .Environment.CIRCLE_JOB }}-dependencies={{ checksum "project/Dependencies.scala" }}-canton-dependencies={{ checksum "project/CantonDependencies.scala" }}-buildcommon:{{ checksum "project/BuildCommon.scala" }}-buildproperties={{ checksum "project/build.properties" }}-houserules={{ checksum "project/Houserules.scala" }}-plugins={{ checksum "project/plugins.sbt" }}-build={{ checksum "build.sbt" }}
          # Components of the cache key:
          # - Keyword "sbt" to indicate this stores Sbt caches.
          # - Otherwise as for the coursier cache key.
          paths:
            - "~/.ivy2/cache" # despite sbt 1.3 using coursier it appears a handful of dependencies are placed in the ivy cache (core sbt plugins and coursier itself)
            - "~/.sbt"

  ##### CCI runners
  restore_sbt_cache:
    parameters:
      <<: *runner_type
    # We are saving to / restoring from several caches to keep individual caches below 500MB.
    # Otherwise, restore_cache may fail for no good reason.
    # See https://circleci.com/docs/2.0/caching/#cache-size
    steps:
      - run:
          name: Deleting cache directories
          # Delete the cache directories so that we don't include arbitrary stuff coming from the docker image.
          command: |
            for dir in "$HOME/.ivy2/cache" "$HOME/.cache/coursier/v1" "$HOME/.sbt"; do
              if [[ -e "$dir" ]]; then
                rm -rfv "$dir"
              fi
            done

      - restore_cache:
          name: Restoring Coursier cache
          keys:
            # Restore the cache for the exact same build configuration.
            - *coursier-cache-key
            # Previously, a cache matching CIRCLE_JOB and project/Dependencies.scala was also attempted but
            # unfortunately sbt and/or coursier fail to detect and use credentials to retrieve missing artifacts
            # from authenticated repos.

      - restore_cache:
          name: Restoring Sbt caches
          keys:
            # First try to restore the cache for the exact same build configuration.
            - *sbt-cache-key
            # If this is not possible and Dependencies.scala hasn't changed, populate the cache with slightly outdated data.
            # This will speed-up compilation, because most libraries are already in the cache.
            - << parameters.runner_type >> sbt-canton-job={{ .Environment.CIRCLE_JOB }}-dependencies={{ checksum "project/Dependencies.scala" }}-canton-dependencies={{ checksum "project/CantonDependencies.scala" }}


  #### Self hosted runners
  # re-enable when it's not broken
  # save_sbt_cache_self_hosted:
  #   steps:
  #     - execute_sbt_command:
  #         pre_sbt_cmd: "export CI_IGNORE_DIRTY_REPO=1"
  #         cmd: pushRemoteCache
  #         cmd_retry_count: 3

  restore_sbt_cache_self_hosted:
    parameters:
      <<: *runner_type
    steps:
      - restore_cache:
          name: Restoring Sbt caches
          keys:
            # First try to restore the cache for the exact same build configuration.
            - *sbt-cache-key
      - restore_daml_artifacts
      - restore_precompiled_classes:
          runner_type: << parameters.runner_type >>
      - restore_frontend_node_modules
      # re-enable when it's not broken
#      - execute_sbt_command:
#          cmd: pullRemoteCache
#          cmd_retry_count: 3
