### Canton Participant

server {
    listen       5002 http2;
    server_name  localhost;

    location / {
       grpc_pass grpc://canton-participant:5002;
    }
}

server {
    listen       5001 http2;
    server_name  localhost;

    location / {
       grpc_pass grpc://canton-participant:5001;
    }
}
