### Canton Participant

server {
    listen       5002 http2;
    server_name  localhost;

    location / {
       grpc_pass grpc://svc-participant.svc:5002;
    }
}

server {
    listen       5001 http2;
    server_name  localhost;

    location / {
       grpc_pass grpc://svc-participant.svc:5001;
    }
}

server {
    listen       10013;
    server_name  localhost;

    location / {
       proxy_pass http://svc-participant.svc:10013;
    }
}
