### Scan App

server {
    listen       5012 http2;
    server_name  localhost;

    location / {
       resolver kube-dns.kube-system.svc.cluster.local;
       grpc_pass grpc://scan-app.svc.svc.cluster.local:5012;
    }
}

server {
    listen       6012 ssl;
    server_name  localhost ssl;

    ssl_certificate     /tmp/tls.crt;
    ssl_certificate_key /tmp/tls.key;

    location / {
       resolver kube-dns.kube-system.svc.cluster.local;
       proxy_pass http://scan-app.svc.svc.cluster.local:6012;
    }
}

server {
    listen       443 ssl;
    listen  [::]:443 ssl;

    server_name  scan.*;

    ssl_certificate     /tmp/tls.crt;
    ssl_certificate_key /tmp/tls.key;

    location / {
        resolver kube-dns.kube-system.svc.cluster.local;
        proxy_pass http://scan-app.svc.svc.cluster.local:6012;
    }
}
