### Scan App

server {
    listen       5012 http2;
    server_name  localhost;

    location / {
       grpc_pass grpc://scan-app:5012;
    }
}

server {
    listen       6012 ssl;
    server_name  localhost ssl;

    ssl_certificate     /tmp/tls.crt;
    ssl_certificate_key /tmp/tls.key;
    
    location / {
       proxy_pass http://scan-app:6012;
       proxy_http_version 1.1;
    }
}
