### Validator App @ Splitwell

server {
    listen       6203;
    server_name  localhost;

    location / {
       proxy_pass http://splitwell-validator-app:6203;
       proxy_http_version 1.1;
    }
}
