### Wallet Web UI @ Splitwell

server {
    listen       80;
    listen  [::]:80;

    server_name  wallet.splitwell.*;
    return 301 https://$host$request_uri;
}

server {
    listen       443 ssl;
    listen  [::]:443 ssl;

    server_name  wallet.splitwell.*;

    ssl_certificate     /tmp/tls.crt;
    ssl_certificate_key /tmp/tls.key;

    location ~ ^/(api/v0/wallet/)(.*) {
       resolver kube-dns.kube-system.svc.cluster.local;
       proxy_pass http://wallet-app.splitwell.svc.cluster.local:5004/$2$is_args$args;
    }

    location ~ ^/(api/v0/validator/)(.*) {
       resolver kube-dns.kube-system.svc.cluster.local;
       proxy_pass http://validator-app.splitwell.svc.cluster.local:5003/$2$is_args$args;
    }

    location / {
        resolver kube-dns.kube-system.svc.cluster.local;
        proxy_pass http://wallet-web-ui.splitwell.svc.cluster.local;
    }
}

server {
    listen       80;
    listen  [::]:80;

    server_name  wallet-new.splitwell.*;
    return 301 https://$host$request_uri;
}

server {
    listen       443 ssl;
    listen  [::]:443 ssl;

    server_name  wallet-new.splitwell.*;

    ssl_certificate     /tmp/tls.crt;
    ssl_certificate_key /tmp/tls.key;

    location / {
        resolver kube-dns.kube-system.svc.cluster.local;
        proxy_pass http://wallet-new-web-ui.splitwell.svc.cluster.local;
    }
}
