### Wallet App @ Splitwise

server {
    listen       5204 http2;
    server_name  localhost;

    location / {
       grpc_pass grpc://splitwise-wallet-app:5004;
    }
}

server {
    listen       6204;
    server_name  localhost;

    location / {
       proxy_pass http://splitwise-wallet-app:6004;
       proxy_http_version 1.1;
    }
}
