### Splitwell App @ Splitwell-validator

server {
    listen       5213 http2;
    server_name  localhost;

    location / {
       grpc_pass grpc://splitwell-app.splitwell:5213;
    }
}

server {
    listen       6213 ssl;
    server_name  localhost ssl;

    ssl_certificate     /tmp/tls.crt;
    ssl_certificate_key /tmp/tls.key;

    location / {
       proxy_pass http://splitwell-app.splitwell:6213;
       proxy_http_version 1.1;
    }
}

server {
    listen       443 ssl;
    listen  [::]:443 ssl;

    server_name  splitwell.*;

    ssl_certificate     /tmp/tls.crt;
    ssl_certificate_key /tmp/tls.key;

    location / {
        proxy_pass http://splitwell-app.splitwell:6213;
        proxy_http_version 1.1;
   }
}
