### Canton Participant @ Splitwell

server {
    listen       5202 http2;
    server_name  localhost;

    location / {
       resolver kube-dns.kube-system.svc.cluster.local;
       grpc_pass grpc://participant.splitwell.svc.cluster.local:5002;
    }
}

server {
    listen       5201 http2;
    server_name  localhost;

    location / {
       resolver kube-dns.kube-system.svc.cluster.local;
       grpc_pass grpc://participant.splitwell.svc.cluster.local:5001;
    }
}

server {
    listen       10213;
    server_name  localhost;

    location / {
       resolver kube-dns.kube-system.svc.cluster.local;
       proxy_pass http://participant.splitwell.svc.cluster.local:10013;
    }
}

server {
    listen       6201;
    server_name  localhost;

    location / {
       resolver kube-dns.kube-system.svc.cluster.local;
       proxy_pass http://participant.splitwell.svc.cluster.local:6001;
       proxy_http_version 1.1;
    }
}
