### Canton Participant @ Splitwell

server {
    listen       5202 http2;
    server_name  localhost;

    location / {
       grpc_pass grpc://splitwell-participant:5002;
    }
}

server {
    listen       5201 http2;
    server_name  localhost;

    location / {
       grpc_pass grpc://splitwell-participant:5001;
    }
}

server {
    listen       10213;
    server_name  localhost;

    location / {
       proxy_pass http://splitwell-participant:10013;
    }
}

server {
    listen       6201;
    server_name  localhost;

    location / {
       proxy_pass http://splitwell-participant:6001;
       proxy_http_version 1.1;
    }
}
