### Canton Participant @ Splitwise

server {
    listen       5202 http2;
    server_name  localhost;

    location / {
       grpc_pass grpc://splitwise-participant:5202;
    }
}

server {
    listen       5201 http2;
    server_name  localhost;

    location / {
       grpc_pass grpc://splitwise-participant:5201;
    }
}


server {
    listen       6201;
    server_name  localhost;

    location / {
       proxy_pass http://splitwise-participant:6201;
       proxy_http_version 1.1;
    }
}
