### SV Apps

#### SV 1

server {
    listen       5014 http2;
    server_name  localhost;

    location / {
       grpc_pass grpc://sv-app-1:5014;
    }
}
server {
    listen       6014 ssl;
    server_name  localhost ssl;

    ssl_certificate     /tmp/tls.crt;
    ssl_certificate_key /tmp/tls.key;

    location / {
       proxy_pass http://sv-app-1:6014;
    }
}

#### SV 2

server {
    listen       5015 http2;
    server_name  localhost;

    location / {
       grpc_pass grpc://sv-app-2:5015;
    }
}
server {
    listen       6015 ssl;
    server_name  localhost ssl;

    ssl_certificate     /tmp/tls.crt;
    ssl_certificate_key /tmp/tls.key;

    location / {
       proxy_pass http://sv-app-2:6015;
    }
}

#### SV 3

server {
    listen       5016 http2;
    server_name  localhost;

    location / {
       grpc_pass grpc://sv-app-3:5016;
    }
}
server {
    listen       6016 ssl;
    server_name  localhost ssl;

    ssl_certificate     /tmp/tls.crt;
    ssl_certificate_key /tmp/tls.key;

    location / {
       proxy_pass http://sv-app-3:6016;
    }
}

#### SV 4

server {
    listen       5017 http2;
    server_name  localhost;

    location / {
       grpc_pass grpc://sv-app-4:5017;
    }
}
server {
    listen       6017 ssl;
    server_name  localhost ssl;

    ssl_certificate     /tmp/tls.crt;
    ssl_certificate_key /tmp/tls.key;

    location / {
       proxy_pass http://sv-app-4:6017;
    }
}
