### Canton Participant @ Validator1

server {
    listen       5102 http2;
    server_name  localhost;

    location / {
       grpc_pass grpc://canton-participant.validator1:5002;
    }
}

server {
    listen       5101 http2;
    server_name  localhost;

    location / {
       grpc_pass grpc://canton-participant.validator1:5001;
    }
}

server {
    listen       10113;
    server_name  localhost;

    location / {
       proxy_pass http://canton-participant.validator1:10013;
    }
}


server {
    listen       6101;
    server_name  localhost;

    location / {
       proxy_pass http://canton-participant.validator1:6001;
       proxy_http_version 1.1;
    }
}
