### Wallet Web UI @ Validator1

server {
    listen       7104;
    listen  [::]:7104;
    server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        proxy_pass http://validator1-wallet-web-ui;
    }
}
