### Validator App @ Validator1

server {
    listen       6103;
    server_name  localhost;

    location / {
       resolver kube-dns.kube-system.svc.cluster.local;
       proxy_pass http://validator-app.validator1.svc.cluster.local:6103;
    }
}
