### Directory Web UI @ Validator1

server {
    listen       80;
    listen  [::]:80;

    server_name  directory.validator1.*;
    return 301 https://$host$request_uri;
}

server {
    listen      443 ssl;
    listen [::]:443 ssl;

    server_name  directory.validator1.*;

    ssl_certificate     /tmp/tls.crt;
    ssl_certificate_key /tmp/tls.key;

    location ~ ^/(api/v0/ledger-api/)(.*) {
       proxy_pass http://validator1-participant:6001/$2;
       proxy_http_version 1.1;
    }

    location ~ ^/(api/v0/wallet/)(.*) {
       proxy_pass http://validator1-wallet-app:6004/$2;
       proxy_http_version 1.1;
    }

    location / {
        proxy_pass http://validator1-directory-web-ui;
    }
}
