### Directory Web UI @ Validator1

server {
    listen       80;
    listen  [::]:80;
    server_name  directory.validator1.*;

    location / {
        proxy_pass http://validator1-directory-web-ui;
    }
}
