### Directory Web UI @ Validator1

server {
    listen       80;
    listen  [::]:80;
    server_name  splitwise.validator1.*;

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        proxy_pass http://validator1-splitwise-web-ui/;
    }
}
