### Canton Participant @ Validator1

server {
    listen       5102 http2;
    server_name  localhost;

    location / {
       grpc_pass grpc://validator1-participant:5102;
    }
}

server {
    listen       5101 http2;
    server_name  localhost;

    location / {
       grpc_pass grpc://validator1-participant:5101;
    }
}
