### Wallet Web UI @ Validator1

server {
    listen       80;
    listen  [::]:80;
    server_name  wallet.validator1.*;

    location ~* .*\..*$ {
        proxy_pass http://validator1-wallet-web-ui;
    }

    location / {
        rewrite / / break; # Hack to allow specifying the URI (i.e. index.html) below.
        proxy_pass http://validator1-wallet-web-ui/index.html;
    }
}
