### Wallet Web UI @ Validator1

server {
    listen       80;
    listen  [::]:80;

    server_name  wallet.validator1.*;
    return 301 https://$host$request_uri;
}

server {
    listen       443 ssl;
    listen  [::]:443 ssl;

    server_name  wallet.validator1.*;

    ssl_certificate     /tmp/tls.crt;
    ssl_certificate_key /tmp/tls.key;

    location ~ ^/(api/v0/wallet/)(.*) {
       proxy_pass http://wallet-app.validator1:6004/$2$is_args$args;
       proxy_http_version 1.1;
    }

    location ~ ^/(api/v0/validator/)(.*) {
       proxy_pass http://validator-app.validator1:6103/$2$is_args$args;
       proxy_http_version 1.1;
    }

    location / {
        proxy_pass http://wallet-web-ui.validator1;
    }
}

server {
    listen       80;
    listen  [::]:80;

    server_name  wallet-new.validator1.*;
    return 301 https://$host$request_uri;
}

server {
    listen       443 ssl;
    listen  [::]:443 ssl;

    server_name  wallet-new.validator1.*;

    ssl_certificate     /tmp/tls.crt;
    ssl_certificate_key /tmp/tls.key;

    location / {
        proxy_pass http://wallet-new-web-ui.validator1;
    }
}
