### Validator App @ Validator1

server {
    listen       6103;
    server_name  localhost;

    location / {
       proxy_pass http://validator-app.validator1:6103;
       proxy_http_version 1.1;
    }
}
