### Validator App @ Validator1

server {
    listen       5103 http2;
    server_name  localhost;

    location / {
       grpc_pass grpc://validator1-validator-app:5103;
    }
}

server {
    listen       6103;
    server_name  localhost;

    location / {
       proxy_pass http://validator1-validator-app:6103;
       proxy_http_version 1.1;
    }
}

server {
    listen       7103;
    server_name  localhost;

    location / {
       proxy_pass http://validator1-validator-app:7103;
    }
}
