### Canton Domain

server {
    listen       5008 http2;
    server_name  localhost;

    location / {
       grpc_pass grpc://canton-domain:5008;
    }
}

server {
    listen       5009 http2;
    server_name  localhost;

    location / {
       grpc_pass grpc://canton-domain:5009;
    }
}
