cluster:
  imageTag: IMAGE_TAG
imageRepo: "digitalasset-canton-network-docker.jfrog.io/digitalasset"

fixedTokens: false

defaultJvmOptions: -Xms2560M -Xmx2560M -Dscala.concurrent.context.minThreads=4
resources:
  limits:
    memory: 4096Mi
  requests:
    cpu: 1
    memory: 4096Mi
