canton {
  parameters {
    non-standard-config = yes
    dev-version-support = yes
    # Bumping because our topology state can get very large due to
    # a large number of participants.
    timeouts.processing.verify-active = 40.seconds
  }

  # Bumping because our topology state can get very large due to
  # a large number of participants.
  monitoring.delay-logging-threshold = 40.seconds

  participants {
    svParticipant {
      storage {
        type = postgres
        # supply your own config here
        # only postgres storage is supported for SV participants at the moment
        # due to the requirements of SVC party migration
      }
      admin-api.port = 5002
      ledger-api.port = 5001
      ledger-api.explicit-disclosure-unsafe = true
      parameters {
        dev-version-support = yes
      }
      init.parameters.unique-contract-keys = false
    }
  }
}
canton.features.enable-preview-commands = yes # required for SVC party migration
canton.features.enable-testing-commands = yes
