canton {
  parameters {
    non-standard-config = yes
    dev-version-support = yes
    # Bumping because our topology state can get very large due to
    # a large number of participants.
    timeouts.processing.verify-active = 40.seconds
  }

  # Bumping because our topology state can get very large due to
  # a large number of participants.
  monitoring.delay-logging-threshold = 40.seconds

  participants-x {
    svParticipant {
      storage {
        type = postgres
        # supply your own config here
        # only postgres storage is supported for SV participants at the moment
        # due to the requirements of SVC party migration
      }
      admin-api.port = 5002
      ledger-api {
        port = 5001
        explicit-disclosure-unsafe = true
        // Note: the sv user name must match the one defined in sv.conf
        user-management-service.additional-admin-user-id = "sv_user"
        user-management-service.additional-admin-user-id = ${?SV_USER_NAME}
      }
      parameters {
        dev-version-support = yes
        initial-protocol-version = dev
      }
      init.parameters.unique-contract-keys = false
    }
  }
}
canton.features.enable-preview-commands = yes # required for SVC party migration
canton.features.enable-testing-commands = yes
