canton {
  validator-apps {
    svValidator {
      onboarding = {
        # our onboarding sponsor is SV1
        sv-client.admin-api.url = ${NETWORK_APPS_ADDRESS_PROTOCOL}"://"${NETWORK_APPS_ADDRESS}":5014"
        # secret must be obtained from SV1 first
        secret = "PLACEHOLDER"
      }
    }
  }
}
