{
 "title": "ACS Commitment Performance",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_participant_sync_commitments_compute_duration_seconds,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(daml_participant_sync_commitments_compute_duration_seconds,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ACS Computation Time (0.99 quantile)",
   "type": "timeseries",
   "description": "Measures the time that the participant node spends computing commitments each reconciliation interval. This measures the full time needed to compute the commitments for all counter parties.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(daml_participant_sync_commitments_compute_duration_seconds{namespace=~\"$namespace\",job=~\"$job\"}[$__rate_interval])) by (namespace, job, le))",
     "legendFormat": "{{namespace}} {{job}}"
    }
   ]
  },
  {
   "title": "ACS Commitment Sequencing Time",
   "type": "timeseries",
   "description": "Measures the time between the end of a commitment period, and the time when the sequencer observes the corresponding commitment.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max by (namespace, job) (daml_participant_sync_commitments_sequencing_time{namespace=~\"$namespace\",job=~\"$job\"})",
     "legendFormat": "{{namespace}} {{job}}"
    }
   ]
  },
  {
   "title": "ACS Commitment Catchup in the last hour",
   "type": "timeseries",
   "description": "Measures how many times the catch-up mode has been triggered over the last hour",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (namespace, job)(increase(daml_participant_sync_commitments_catchup_mode_enabled_total{namespace=~\"$namespace\",job=~\"$job\"}[1h]))",
     "legendFormat": "{{namespace}} {{job}}"
    }
   ]
  },
  {
   "title": "Commitment Checkpoint Lag",
   "type": "timeseries",
   "description": "Lag behind the timestamp the commitment checkpoint was created and the timestamp of the checkpoint; periodic lag spikes around during commitment computation are expected",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min by (namespace, job) ((timestamp(daml_participant_sync_commitments_last_locally_checkpointed{namespace=~\"$namespace\",job=~\"$job\"}) - ((daml_participant_sync_commitments_last_locally_checkpointed{namespace=~\"$namespace\",job=~\"$job\"} > 0) / 1e6)))",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": " Completed ACS Commitment Lag",
   "type": "timeseries",
   "description": "Lag behind the timestamp of when the last completed commitment interval was processed and the timestamp of the interval",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min by (namespace, job) (timestamp(daml_participant_sync_commitments_last_locally_completed{namespace=~\"$namespace\",job=~\"$job\"}) - ((daml_participant_sync_commitments_last_locally_completed{namespace=~\"$namespace\",job=~\"$job\"} > 0) / 1e6))",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": " Incoming Received ACS Commitment Lag",
   "type": "timeseries",
   "description": "Lag behind the timestamp the commitment was received and the timestamp of the commitment",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min by (namespace, job) (timestamp(daml_participant_sync_commitments_last_incoming_received{namespace=~\"$namespace\",job=~\"$job\"}) - ((daml_participant_sync_commitments_last_incoming_received{namespace=~\"$namespace\",job=~\"$job\"} > 0) / 1e6))",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": " Incoming Processed ACS Commitment Lag",
   "type": "timeseries",
   "description": "Lag behind the timestamp the commitment was processed and the timestamp of the commitment",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(timestamp(daml_participant_sync_commitments_last_incoming_processed{namespace=~\"$namespace\",job=~\"$job\"}) - ((daml_participant_sync_commitments_last_incoming_processed{namespace=~\"$namespace\",job=~\"$job\"} > 0) / 1e6))",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": "Last Incoming Received ACS Commitment",
   "type": "timeseries",
   "description": "Timestamp of the latest incoming ACS commitment period end that has been received and enqueued, but not yet processed by the participant.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "max by (namespace, job)(daml_participant_sync_commitments_last_incoming_received{namespace=~\"$namespace\", job=~\"$job\"} != 0)/1e3",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": "Last Incoming Processed ACS Commitment",
   "type": "timeseries",
   "description": "Timestamp of the latest incoming ACS commitment period end that was fully processed by the participant.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "max by (namespace, job)(daml_participant_sync_commitments_last_incoming_processed{namespace=~\"$namespace\", job=~\"$job\"} != 0)/1e3",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": "Last Locally Completed ACS Commitment",
   "type": "timeseries",
   "description": "Timestamp of the latest locally completed ACS commitment interval. Crash recovery will start reingesting from this timestamp on or from the latest checkpointed ACS commitment interval on, whichever is later.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "max by (namespace, job)(daml_participant_sync_commitments_last_locally_completed{namespace=~\"$namespace\", job=~\"$job\"} != 0)/1e3",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": "Last Locally Checkpointed ACS Commitment",
   "type": "timeseries",
   "description": "Timestamp of the latest checkpointed ACS commitment in microseconds. Crash recovery will start reingesting from this timestamp on or from the latest locally completed ACS commitment interval on, whichever is later.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "max by (namespace, job)(daml_participant_sync_commitments_last_locally_checkpointed{namespace=~\"$namespace\", job=~\"$job\"} != 0)/1e3",
     "legendFormat": "{{namespace}}-{{job}}"
    }
   ]
  }
 ]
}