{
 "title": "Sequencer Topology Transactions",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_sequencer_block_events_total,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(daml_sequencer_block_events_total{namespace=\"$namespace\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Topology send rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(type) (rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\", type=\"send-topology\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\", type=\"send-topology\"}[1h]))",
     "legendFormat": "hourly total"
    }
   ]
  },
  {
   "title": "Topology transactions participants last 24h",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(sum by(member) (delta(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\", type=\"send-topology\", member=~\"PAR::.*\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequencer Topology Rate by Participant",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(member) (rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\", member=~\"PAR::.*\", type=\"send-topology\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topology transactions non participants last 24h",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "sort_desc(sum by(member) (delta(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\", type=\"send-topology\", member!~\"PAR::.*\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}