{
 "title": "Sequencer Messages",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_sequencer_block_events_total,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(daml_sequencer_block_events_total{namespace=\"$namespace\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Last 24h messages / s",
   "type": "piechart",
   "description": "The average per second messages for the last 24h",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequencer Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(type) (rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\"}[1h]))",
     "legendFormat": "hourly total"
    }
   ]
  },
  {
   "title": "Confirmation Requests Rate by Member",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(member) (rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\", type=\"send-confirmation-request\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Confirmation Requests by Member in the last Hour",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 11 },
   "targets": [
    {
     "expr": "sort_desc(sum(delta(daml_sequencer_block_events_total{namespace=\"$namespace\",job=\"$job\",type=\"send-confirmation-request\"}[1h])) by (member))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequencer Message Rate by Participant",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\",member=~\"PAR::.*\"}[$__rate_interval])) by (member)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequencer Message Rate by Mediator",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\",member=~\"MED::.*\"}[$__rate_interval])) by (member)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sequencer Message Rate by Member excluding Mediator/Participant",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum by(member) (rate(daml_sequencer_block_events_total{namespace=\"$namespace\", job=\"$job\", member!~\"(MED|PAR)::.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}