{
 "title": "Sequencer Subscriptions 2 (manual)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_sequencer_public_api_subscriptions,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Subscriptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Subscriptions",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "daml_sequencer_public_api_subscriptions",
     "legendFormat": "{{namespace}} M{{migration_id}}"
    }
   ]
  },
  {
   "title": "Number of active subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "daml_sequencer_public_api_subscriptions{namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} M{{migration_id}}"
    }
   ]
  },
  { "title": "Subscription Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Subscriber cache misses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(daml_cache_misses{namespace=~\"$namespace\", cache=\"events-fan-out-buffer\"}[$__rate_interval]) > 0",
     "legendFormat": "outside buffer {{namespace}} {{subscriber}}"
    }
   ]
  },
  {
   "title": "Head vs Last Timestamp Diff",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "daml_sequencer_last_timestamp{namespace=~\"$namespace\"} - daml_sequencer_head_timestamp{namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} diff"
    }
   ]
  }
 ]
}