apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
   name: cn-certificate
   namespace: cluster-ingress
spec:
    dnsNames:
    - '*.validator.svc.pilot.network.canton.global'
    issuerRef:
        name: letsencrypt-production
    secretName: cn-net-tls
