!include($SPLICE_ROOT/cluster/configs/shared/scratchnet.yaml)
multiValidator:
  postgresPvcSize: '500Gi'
  requiresOnboardingSecret: false
loadTester:
  enable: true
  iterationsPerMinute: 1200
svs:
  default:
    sequencer:
      cloudSql:
        tier: 'db-perf-optimized-N-4'
        enterprisePlus: true
        flags:
          max_wal_size: '20480' # 20GB, but GCP doesn't allow to write it that way and must be a number indicating MB
          maintenance_work_mem: '2000000' # 2Gi, but GCP doesn't allow to write it that way and must be a number indicating KB
