package com.daml.network.store

import com.daml.ledger.api.v2.TraceContextOuterClass
import com.daml.ledger.javaapi.data.{
  CreatedEvent,
  DamlRecord,
  ExercisedEvent,
  Int64,
  TransactionTree,
  TreeEvent,
  Value,
}
import com.daml.lf.data.Bytes
import com.daml.network.environment.ledger.api.LedgerClient.GetTreeUpdatesResponse
import com.daml.network.environment.ledger.api.ReassignmentEvent.{Assign, Unassign}
import com.daml.network.environment.ledger.api.{
  LedgerClient,
  Reassignment,
  ReassignmentEvent,
  ReassignmentUpdate,
  TransactionTreeUpdate,
}
import com.daml.network.migration.DomainMigrationInfo
import com.daml.network.store.db.{AcsJdbcTypes, AcsTables, CNPostgresTest}
import com.digitalasset.canton.concurrent.Threading
import com.digitalasset.canton.data.CantonTimestamp
import com.digitalasset.canton.resource.DbStorage
import com.digitalasset.canton.topology.*
import com.digitalasset.canton.util.MonadUtil
import com.digitalasset.canton.{HasActorSystem, HasExecutionContext}
import com.google.protobuf.ByteString
import com.google.rpc.status.Status
import com.google.rpc.status.Status.toJavaProto
import org.apache.pekko.stream.scaladsl.{Keep, Sink}
import org.scalatest.Assertion

import scala.concurrent.Future
import scala.jdk.CollectionConverters.*
import scala.jdk.OptionConverters.*

class UpdateHistoryTest
    extends StoreTest
    with HasExecutionContext
    with StoreErrors
    with HasActorSystem
    with CNPostgresTest
    with AcsJdbcTypes
    with AcsTables {

  import UpdateHistoryTest.*

  "UpdateHistory" should {

    "ingestion" should {

      "handle single create" in {
        val store = mkStore()
        for {
          _ <- initStore(store)
          _ <- create(domain1, cid1, offset1, party1, store)
          updates <- updates(store)
        } yield checkUpdates(
          updates,
          Seq(
            ExpectedCreate(cid1, domain1)
          ),
        )
      }

      "handle transaction with non-standard data" in {
        val store = mkStore()
        for {
          _ <- initStore(store)
          expectedTree <- domain1.ingest(offset => {
            val party1 = mkPartyId("someParty").toProtoPrimitive
            val party2 = mkPartyId("someParty").toProtoPrimitive
            val contractId = nextCid()
            val id1 = new com.daml.ledger.javaapi.data.Identifier(
              "somePackageId1",
              "someModuleName1",
              "someEntityName1",
            )
            val someValue = new DamlRecord(
              new DamlRecord.Field("a", new Int64(42))
            )
            val effectiveAt = CantonTimestamp.Epoch.toInstant
            val recordTime = effectiveAt.plusSeconds(60)
            // Unlike transactions generated by various helper functions, this transaction has
            // a created and exercised event where every field is set to some (arbitrary) non-empty value,
            // including fields that are not normally not used in Splice, such as interfaces or contract keys.
            // This is to make sure serialization doesn't crash on such unexpected optional fields.
            mkTx(
              offset = offset,
              events = Seq(
                new CreatedEvent(
                  /*witnessParties*/ Seq(party1).asJava,
                  /*eventId*/ "someEventId",
                  /*templateId*/ id1,
                  /*packageName*/ "somePackageName",
                  /*contractId*/ contractId,
                  /*arguments*/ someValue,
                  /*createdEventBlob*/ Bytes.assertFromString("00abcd").toByteString,
                  /*interfaceViews*/ new java.util.HashMap(Map(id1 -> someValue).asJava),
                  /*failedInterfaceViews*/ new java.util.HashMap(
                    Map(id1 -> toJavaProto(Status.of(1, "some message", Seq.empty))).asJava
                  ),
                  /*contractKey*/ Some[Value](someValue).toJava,
                  /*signatories*/ Seq(party1, party2).asJava,
                  /*observers*/ Seq(party1, party2).asJava,
                  /*createdAt*/ effectiveAt,
                ),
                new ExercisedEvent(
                  /*witnessParties*/ Seq(party1).asJava,
                  /*eventId*/ "otherEventId",
                  /*templateId*/ id1,
                  /*packageName*/ dummyPackageName,
                  /*interfaceId*/ Some(id1).toJava,
                  /*contractId*/ contractId,
                  /*choice*/ "someChoice",
                  /*choiceArgument*/ someValue,
                  /*actingParties*/ List(party1).asJava,
                  /*consuming*/ false,
                  /*childEventIds*/ List("someEventId").asJava,
                  /*exerciseResult*/ someValue,
                ),
              ),
              domainId = domain1,
              effectiveAt = effectiveAt,
              recordTime = recordTime,
              workflowId = "SomeWorkflowId",
              commandId = "SomeCommandId",
            )
          })(store)
          updates <- updates(store)
        } yield {
          val expectedUpdates = Seq(
            GetTreeUpdatesResponse(
              TransactionTreeUpdate(expectedTree),
              domain1,
            )
          )
          updates.map(withoutLostData) should contain theSameElementsInOrderAs expectedUpdates.map(
            withoutLostData
          )
        }
      }

      "handle reassignments" in {
        implicit val store = mkStore()
        val c = appRewardCoupon(1, party1, contractId = cid1)
        for {
          _ <- initStore(store)
          _ <- domain1.create(c)
          _ <- domain1.unassign(c -> domain2, reassignmentId1, 1)
          _ <- domain2.assign(c -> domain1, reassignmentId1, 1)
          _ <- domain2.exercise(
            c,
            None,
            "Archive",
            com.daml.ledger.javaapi.data.Unit.getInstance(),
            com.daml.ledger.javaapi.data.Unit.getInstance(),
          )
          updates <- updates(store)
        } yield checkUpdates(
          updates,
          Seq(
            ExpectedCreate(cid1, domain1),
            ExpectedUnassign(cid1, domain1, domain2),
            ExpectedAssign(cid1, domain1, domain2),
            ExpectedExercise(cid1, domain2, "Archive"),
          ),
        )
      }

      // Note: we do not really want to support multiple UpdateHistory instances ingesting
      // data for the same party from the same participant. We still want the UpdateHistory
      // to behave correctly if this happens by accident, however.
      "handle many stores concurrently ingesting the same stream" in {
        // 10 stores, all ingesting the same stream
        val stores = (1 to 10).toList.map(_ => mkStore())

        // One update stream with 10 updates
        val updateStreamElements = (1 to 10).toList.map(i =>
          i -> TransactionTreeUpdate(
            mkCreateTx(
              validOffset(i),
              Seq(appRewardCoupon(1, party1, contractId = validContractId(i))),
              defaultEffectiveAt,
              Seq(party1),
              domain1,
              "workflowId",
            )
          )
        )

        // Retry once on failure
        def retryOnceAfterAShortDelay[T](f: => Future[T]): Future[T] = {
          f.recoverWith { case _: Throwable =>
            Future(Threading.sleep(100)).flatMap(_ => f)
          }
        }

        for {
          // Initialize all stores in parallel
          _ <- Future.traverse(stores)(s => initStore(s))
          // Process one update at a time
          _ <- withoutRepeatedIngestionWarning(
            MonadUtil.sequentialTraverse(updateStreamElements) { case (i, update) =>
              logger.info(s"Processing update $i")
              // Ingest the same update on all stores in parallel
              Future.traverse(stores)(s =>
                // The first concurrent update is expected to fail on all but one store
                // with a uniqueness violation error (assuming the updates are really concurrent).
                // At the latest on the next retry, all stores should succeed ingesting the update
                // by figuring out that the given offset was already ingested.
                // In practice, the ingestion service would crash and restart after a "short delay".
                retryOnceAfterAShortDelay(
                  s.ingestionSink
                    .ingestUpdate(
                      domain1,
                      update,
                    )
                )
              )
            },
            maxCount = 199, // 10 stores x 10 updates x up to 2 retries per update
          )
          // Query all stores in parallel
          updatesList <- Future.traverse(stores)(s => updates(s))
        } yield {
          // All stores should return all 10 updates
          updatesList.foreach(updates =>
            checkUpdates(
              updates,
              updateStreamElements.map(u => ExpectedCreate(validContractId(u._1), domain1)),
            )
          )

          succeed
        }
      }

      "two stores: different parties" in {
        val store1 = mkStore(party1, migration1, participant1)
        val store2 = mkStore(party2, migration1, participant1)

        for {
          _ <- initStore(store1)
          _ <- initStore(store2)
          _ <- create(domain1, cid1, offset1, party1, store1)
          _ <- create(domain1, cid2, offset2, party2, store2)
          updates1 <- updates(store1)
          updates2 <- updates(store2)
        } yield {
          checkUpdates(
            updates1,
            Seq(
              ExpectedCreate(cid1, domain1)
            ),
          )
          checkUpdates(
            updates2,
            Seq(
              ExpectedCreate(cid2, domain1)
            ),
          )
        }
      }

      "two stores: different participant" in {
        val store1 = mkStore(party1, migration1, participant1)
        val store2 = mkStore(party1, migration1, participant2)

        for {
          _ <- initStore(store1)
          _ <- initStore(store2)
          // Note: same offset (offsets are participant-specific)
          _ <- create(domain1, cid1, offset1, party1, store1)
          _ <- create(domain1, cid2, offset1, party1, store2)
          updates1 <- updates(store1)
          updates2 <- updates(store2)
        } yield {
          checkUpdates(
            updates1,
            Seq(
              ExpectedCreate(cid1, domain1)
            ),
          )
          checkUpdates(
            updates2,
            Seq(
              ExpectedCreate(cid2, domain1)
            ),
          )
        }
      }

      "two stores: different migration indices" in {
        val store1 = mkStore(party1, migration1, participant1)
        val store2 = mkStore(party1, migration2, participant1)

        for {
          _ <- initStore(store1)
          _ <- initStore(store2)
          // Note: same offset (offsets are not preserved across hard domain migrations)
          _ <- create(domain1, cid1, offset1, party1, store1)
          _ <- create(domain1, cid2, offset1, party1, store2)
          updates1 <- updates(store1)
          updates2 <- updates(store2)
        } yield {
          checkUpdates(
            updates1,
            Seq(
              ExpectedCreate(cid1, domain1)
            ),
          )
          checkUpdates(
            updates2,
            Seq(
              ExpectedCreate(cid2, domain1)
            ),
          )
        }
      }

      "one store: different domains" in {
        val store1 = mkStore(party1, migration1, participant1)

        for {
          _ <- initStore(store1)
          // Note: the two contracts can share a record time (record times are not unique across domains)
          _ <- create(domain1, cid1, offset1, party1, store1)
          _ <- create(domain2, cid2, offset2, party1, store1)
          updates1 <- updates(store1)
        } yield {
          checkUpdates(
            updates1,
            Seq(
              ExpectedCreate(cid1, domain1),
              ExpectedCreate(cid2, domain2),
            ),
          )
        }
      }

    }
  }

  private def create(
      domain: DomainId,
      contractId: String,
      offset: String,
      party: PartyId,
      store: UpdateHistory,
  ) = {
    DomainSyntax(domain).create(
      c = appRewardCoupon(
        round = 0,
        provider = party,
        contractId = contractId,
      ),
      offset = offset,
      txEffectiveAt = defaultEffectiveAt,
      createdEventSignatories = Seq(party),
    )(
      store
    )
  }

  private def validOffset(i: Int) = {
    assert(i > 0)
    "%08d".format(i)
  }

  // Universal begin offset (strictly smaller than any offset used in this suite)
  private val beginOffset = "0".repeat(16)
  // Universal begin offset (strictly larger than any offset used in this suite)
  private val endOffset = "9".repeat(16)

  private def singleRootEvent(tree: TransactionTree): TreeEvent = {
    val rootEventIds = tree.getRootEventIds.asScala
    rootEventIds.length should be(1)
    val rootEventId = rootEventIds.headOption.value
    tree.getEventsById.get(rootEventId)
  }
  private def checkUpdates(
      actual: Seq[LedgerClient.GetTreeUpdatesResponse],
      expected: Seq[ExpectedUpdate],
  ): Assertion = {
    actual.length should be(expected.length)
    actual.zip(expected).foreach {
      case (GetTreeUpdatesResponse(TransactionTreeUpdate(tree), domain), expected) =>
        val rootEvent = singleRootEvent(tree)
        (rootEvent, expected) match {
          case (rootEvent: CreatedEvent, ExpectedCreate(cid, domainId)) =>
            rootEvent.getContractId should be(cid)
            domain should be(domainId)
          case (rootEvent: ExercisedEvent, ExpectedExercise(cid, domainId, choice)) =>
            rootEvent.getContractId should be(cid)
            rootEvent.getChoice should be(choice)
            domain should be(domainId)
          case _ => throw new RuntimeException("Unexpected event type")
        }
      case (GetTreeUpdatesResponse(ReassignmentUpdate(update), domain), expected) =>
        (update.event, expected) match {
          case (unassign: ReassignmentEvent.Unassign, expected: ExpectedUnassign) =>
            unassign.contractId.contractId should be(expected.cid)
            domain should be(expected.domainId)
            unassign.source should be(expected.domainId)
            unassign.target should be(expected.targetDomain)
          case (assign: ReassignmentEvent.Assign, expected: ExpectedAssign) =>
            assign.createdEvent.getContractId should be(expected.cid)
            assign.source should be(expected.sourceDomain)
            assign.target should be(expected.domainId)
          case _ => throw new RuntimeException("Unexpected reassignment type")
        }
      case _ => throw new RuntimeException("Unexpected update type")
    }
    succeed
  }

  private def updates(
      store: UpdateHistory,
      begin: String = beginOffset,
      end: String = endOffset,
  ): Future[Seq[LedgerClient.GetTreeUpdatesResponse]] = store
    .updateStream(begin, end)
    .toMat(Sink.seq)(Keep.right)
    .run()

  private def initStore(implicit store: UpdateHistory): Future[Unit] = {
    store.testIngestionSink.initialize().map(_ => ())
  }

  private def mkStore(
      updateStreamParty: PartyId = party1,
      domainMigrationId: Long = migration1,
      participantId: ParticipantId = participant1,
  ): UpdateHistory = {
    new UpdateHistory(
      storage,
      DomainMigrationInfo(
        domainMigrationId,
        None,
      ),
      participantId,
      updateStreamParty,
      loggerFactory,
    )
  }

  override protected def cleanDb(storage: DbStorage): Future[?] =
    for {
      _ <- resetAllCnAppTables(storage)
    } yield ()

  private val party1 = userParty(1)
  private val party2 = userParty(2)

  private val migration1 = 1L
  private val migration2 = 2L

  private val domain1: DomainId = DomainId.tryFromString("domain1::domain")
  private val domain2: DomainId = DomainId.tryFromString("domain2::domain")

  private val cid1 = validContractId(1)
  private val cid2 = validContractId(2)

  private val offset1 = validOffset(1)
  private val offset2 = validOffset(2)

  private val participant1 = ParticipantId("participant1")
  private val participant2 = ParticipantId("participant2")

  private val reassignmentId1 = "%08d".format(1)
}

object UpdateHistoryTest {
  sealed trait ExpectedUpdate extends Product with Serializable
  final case class ExpectedCreate(cid: String, domainId: DomainId) extends ExpectedUpdate
  final case class ExpectedExercise(cid: String, domainId: DomainId, choice: String)
      extends ExpectedUpdate

  final case class ExpectedAssign(cid: String, sourceDomain: DomainId, domainId: DomainId)
      extends ExpectedUpdate

  final case class ExpectedUnassign(cid: String, domainId: DomainId, targetDomain: DomainId)
      extends ExpectedUpdate

  def withoutLostData(response: GetTreeUpdatesResponse): GetTreeUpdatesResponse = {
    response match {
      case GetTreeUpdatesResponse(TransactionTreeUpdate(tree), domain) =>
        GetTreeUpdatesResponse(TransactionTreeUpdate(withoutLostData(tree)), domain)
      case GetTreeUpdatesResponse(ReassignmentUpdate(transfer), domain) =>
        GetTreeUpdatesResponse(ReassignmentUpdate(withoutLostData(transfer)), domain)
      case _ => throw new RuntimeException("Invalid update type")
    }
  }

  private def withoutLostData(tree: TransactionTree): TransactionTree = {
    new TransactionTree(
      /*updateId = */ tree.getUpdateId,
      /*commandId = */ tree.getCommandId,
      /*workflowId = */ tree.getWorkflowId,
      /*effectiveAt = */ tree.getEffectiveAt,
      /*offset = */ tree.getOffset,
      /*eventsById = */ tree.getEventsById.asScala.view.mapValues(withoutLostData).toMap.asJava,
      /*rootEventIds = */ tree.getRootEventIds,
      /*domainId = */ tree.getDomainId,

      // We don't care about tracing information in the update history.
      /*traceContext = */ TraceContextOuterClass.TraceContext.getDefaultInstance, // Not preserved

      /*recordTime = */ tree.getRecordTime,
    )
  }

  private def withoutLostData(event: TreeEvent): TreeEvent = {
    event match {
      case created: CreatedEvent =>
        withoutLostData(created)
      case exercised: ExercisedEvent =>
        withoutLostData(exercised)
      case _ => throw new RuntimeException("Invalid event type")
    }
  }

  private def withoutLostData(created: CreatedEvent): CreatedEvent = {
    new CreatedEvent(
      // The witnesses returned by the API is the intersection of actual witnesses according
      // to the daml model with the subscribing parties, and we're always subscribing as a single party,
      // so this would always end up being the operator party of our own application which is not very useful.
      /*witnessParties = */ java.util.Collections.emptyList(), // Not preserved

      /*eventId = */ created.getEventId,
      /*templateId = */ created.getTemplateId,
      /*packageName = */ created.getPackageName,
      /*contractId = */ created.getContractId,
      /*arguments = */ created.getArguments,

      // Binary data used for explicit disclosure of active contracts. Not useful for historical data.
      /*createdEventBlob = */ ByteString.EMPTY, // Not preserved

      // None of our daml models use interfaces.
      // Interface views can be computed from the contract payload if you know the daml model.
      // The ledger API only returns interface views that the application has subscribed to, i.e.,
      // our applications will not see interface views of 3rd party daml code.
      /*interfaceViews = */ java.util.Collections.emptyMap(), // Not preserved
      /*failedInterfaceViews = */ java.util.Collections.emptyMap(), // Not preserved

      /*contractKey = */ created.getContractKey,
      /*signatories = */ created.getSignatories,
      /*observers = */ created.getObservers,
      /*createdAt = */ created.getCreatedAt,
    )
  }

  private def withoutLostData(exercised: ExercisedEvent): ExercisedEvent = {
    new ExercisedEvent(
      // The witnesses returned by the API is the intersection of actual witnesses according
      // to the daml model with the subscribing parties, and we're always subscribing as a single party,
      // so this would always end up being the operator party of our own application which is not very useful.
      /*witnessParties = */ java.util.Collections.emptyList(), // Not preserved

      /*eventId = */ exercised.getEventId,
      /*templateId = */ exercised.getTemplateId,
      /*packageName = */ exercised.getPackageName,
      /*interfaceId = */ exercised.getInterfaceId,
      /*contractId = */ exercised.getContractId,
      /*choice = */ exercised.getChoice,
      /*choiceArgument = */ exercised.getChoiceArgument,
      /*actingParties = */ exercised.getActingParties,
      /*consuming = */ exercised.isConsuming,
      /*childEventIds = */ exercised.getChildEventIds,
      /*exerciseResult = */ exercised.getExerciseResult,
    )
  }

  private def withoutLostData(
      transfer: Reassignment[ReassignmentEvent]
  ): Reassignment[ReassignmentEvent] = {
    transfer match {
      case Reassignment(updateId, offset, recordTime, assign: Assign) =>
        Reassignment(
          updateId,
          offset,
          recordTime,
          assign.copy(
            createdEvent = withoutLostData(assign.createdEvent)
          ),
        )
      case Reassignment(updateId, offset, recordTime, unassign: Unassign) =>
        Reassignment(
          updateId,
          offset,
          recordTime,
          unassign,
        )
      case _ => throw new RuntimeException("Invalid transfer type")
    }
  }
}
