infra:
  ipWhitelisting:
    extraWhitelistedIngress:
      - "35.225.102.103/32" # CI GKE cluster for CCI
  prometheus:
    retentionDuration: "30d"
    retentionSize: "200GB"
    storageSize: "600Gi"
pulumiProjectConfig:
  default:
    cloudSql:
      protected: false
    isExternalCluster: true # TODO(#18023): remove it once cluster is reset
validator1:
  participantPruningSchedule:
    cron: "0 /10 * * * ?" # Run every 10min
    maxDuration: "5m"
    retention: "1h" # Keep 1h
  deduplicationDuration: 30m
synchronizerMigration:
  active:
    id: 0
    version: "0.3.18-snapshot.20250321.8640.0.v05582b27"
