canton {
  monitoring.metrics {
    report-jvm-metrics = yes
    report-execution-context-metrics = yes
    reporters = [{
      type = prometheus
      address = "0.0.0.0"
      port = 10013
    }]
  }
}
