apiVersion: v2
name: cn-directory-web-ui
description: Canton Network Directory UI
type: application

version: 0.1.0
appVersion: "1.16.0"

dependencies:
- name: cn-util-lib
  version: 0.1.0
  repository: file://../cn-util-lib