cluster:
  imageTag: IMAGE_TAG
imageRepo: "digitalasset-canton-network-docker.jfrog.io/digitalasset"
defaultJvmOptions: -Xms1152M -Xmx1152M -Dscala.concurrent.context.minThreads=4
resources:
  limits:
    memory: 1536Mi
  requests:
    cpu: "1"
    memory: 1536Mi
