imageRepo: "us-central1-docker.pkg.dev/da-cn-images/cn-images"

defaultJvmOptions: -Xms512M -Xmx512M -Dscala.concurrent.context.minThreads=4
resources:
  limits:
    memory: 1536Mi
  requests:
    cpu: 1
    memory: 1536Mi

bootstrapType: join-via-svc-app