cluster:
  imageTag: IMAGE_TAG

imageRepo: "digitalasset-canton-network-docker.jfrog.io/digitalasset"

fixedTokens: false

defaultJvmOptions: -Xms3072M -Xmx3072M -Dscala.concurrent.context.minThreads=4
resources:
  limits:
    memory: 4096Mi
  requests:
    cpu: 1
    memory: 4096Mi

metrics:
  enable: false
  release: prometheus-grafana-monitoring
  interval: 30s

persistence:
  databaseName: cantonnet_sv
  schema: sv
  host: postgres
  port: 5432
  user: cnadmin
  secretName: "postgres-secrets"

#Domain upgrade specific values
#globalDomainUpgrade:
#  isActiveNode: true # specifies that this node is current active node, the one that manages the PV
#  storageClassName: standard
