openapi: 3.0.0
info:
  title: Common schemas for CN API definitions
  version: 0.0.1
paths: {}
components:
  schemas:
    ContractMetadata:
      type: object
      required: ["createdAt", "driverMetadata", "contractKeyHash"]
      properties:
        createdAt:
          type: string # java.time.Instant in ISO_INSTANT format.
        contractKeyHash:
          type: string
          format: binary # base-16 encoded.
        driverMetadata:
          type: string
          format: binary # base-16 encoded.

    Contract:
      type: object
      properties:
        template_id:
          type: string
        contract_id:
          type: string
        payload:
          type: object
        metadata:
          $ref: '#/components/schemas/ContractMetadata'
        create_arguments_blob:
          type: string
          format: binary # base-16 encoded.
      required: ["template_id", "contract_id", "payload", "metadata", "create_arguments_blob"]
    ContractId:
      type: string
    ConnectedDomains:
      type: object
      additionalProperties:
        type: string
    # Represents a contract that is maybe already cached by the client. If the client sends along a contract-id that
    # matches the contract the server would respond with, the server responds with an empty contract property to indicate
    # that the client's cache is correct.
    MaybeCachedContract:
          type: object
          properties:
            contract:
              $ref: '#/components/schemas/Contract'
    # A map from 'active-contract-id' -> 'MaybeCachedContract'.
    # At the moment this type is used to let clients know which mining rounds they already have cached,
    # which mining rounds they should add to their cache and which they should remove from their cache
    # (those mining rounds who aren't included in the map at all).
    MaybeCachedContractMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/MaybeCachedContract'

