apiVersion: v2
name: cn-participant
type: application
version: VERSION_NUMBER
appVersion: IMAGE_TAG

description: Canton Network Participant

dependencies:
- name: cn-util-lib
  version: 0.2.0
  repository: file://../cn-util-lib
