cluster:
  imageTag: IMAGE_TAG
imageRepo: "digitalasset-canton-network-docker.jfrog.io/digitalasset"

enableHealthProbes: true

defaultJvmOptions: -Xms24576M -Xmx24576M -Dscala.concurrent.context.minThreads=4
resources:
  limits:
    memory: 32Gi
  requests:
    cpu: "4"
    memory: 32Gi

auth:
  jwksUrl: "https://canton-network-dev.us.auth0.com/.well-known/jwks.json"
  targetAudience: "https://canton.network.global"

participantAdminUserNameFrom:
  secretKeyRef:
    key: ledger-api-user
    name: cn-app-sv-ledger-api-auth
    optional: false

metrics:
  enable: false
  release: prometheus-grafana-monitoring
  interval: 30s
