cluster:
  imageTag: VERSION_TAG
imageRepo: "digitalasset-canton-network-docker.jfrog.io/digitalasset"

defaultJvmOptions: -Xms24576M -Xmx24576M -Dscala.concurrent.context.minThreads=4
resources:
  limits:
    memory: 32Gi
  requests:
    cpu: "1"
    memory: 32Gi
