apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: validator-app
  name: validator-app
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: validator-app
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: {{ .Values.defaultJvmOptions }}
        {{- include "cn-util-lib.auth0-env-vars" "validator" | indent 8}}
        - name: CN_APP_SPLITWELL_LEDGER_API_AUTH_USER_NAME
          valueFrom:
            secretKeyRef:
              key: ledger-api-user
              name: cn-app-splitwell-ledger-api-auth
              optional: false
        - name: CN_APP_WALLET_LEDGER_API_AUTH_USER_NAME
          valueFrom:
            secretKeyRef:
              key: ledger-api-user
              name: cn-app-wallet-ledger-api-auth
              optional: false
        - name: CN_APP_VALIDATOR_PARTICIPANT_ADDRESS
          value: participant
        - name: ADDITIONAL_CONFIG
          value: |
            canton.validator-apps.validator_backend.app-instances.splitwise = {
              service-user = ${?CN_APP_SPLITWELL_LEDGER_API_AUTH_USER_NAME}
              wallet-user = ${?CN_APP_SPLITWELL_PROVIDER_WALLET_USER_NAME}
              dars = ["cn-node-0.1.0-SNAPSHOT/dars/splitwell-0.1.0.dar"]
            }
        image: "{{ .Values.imageRepo }}/validator-app:{{ .Values.cluster.imageTag }}"
        imagePullPolicy: Always
        name: validator-app
        ports:
        - containerPort: 6003
          name: sw-val-http
          protocol: TCP
        resources:
          limits:
            memory: 1536Mi
          requests:
            cpu: "1"
            memory: 1536Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
---
apiVersion: v1
kind: Service
metadata:
  name: validator-app
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: validator-app
  ports:
  - name: sw-val-http
    port: 6003
    protocol: TCP
    targetPort: 6003
