package com.daml.network.validator.config

import com.daml.network.auth.AuthConfig
import com.daml.network.config.*
import com.daml.network.scan.config.ScanAppClientConfig
import com.daml.network.sv.config.SvAppClientConfig
import com.daml.network.wallet.config.TreasuryConfig
import com.digitalasset.canton.DomainAlias
import com.digitalasset.canton.config.*
import com.digitalasset.canton.config.RequireTypes.NonNegativeNumeric

import java.nio.file.Path

case class AppInstance(
    serviceUser: String,
    // An optional separate user name for the provider to be used as its user in the wallet.
    // May be useful if the IAM provider does not allow tokens that are used both by
    // machine-to-machine services and login users - in that case, set serviceUser to the m2m
    // one, and walletUser to the login one. If not provided, the serviceUser is onboarded
    // to the wallet automatically.
    walletUser: Option[String],
    dars: Seq[Path],
)

case class ValidatorOnboardingConfig(
    svClient: SvAppClientConfig, // onboarding sponsor
    secret: String, // generated by the sponsor's SV app
)
object ValidatorOnboardingConfig {
  def hideConfidential(config: ValidatorOnboardingConfig): ValidatorOnboardingConfig = {
    val hidden = "****"
    config.copy(secret = hidden)
  }
}

final case class BuyExtraTrafficConfig(
    /** target throughput in bytes per second
      *
      * The top-up trigger uses this to determine how much extra traffic to purchase each time.
      * A value of zero implies that no extra traffic will be purchased automatically and
      * the throughput will be limited to the base rate.
      */
    targetThroughput: NonNegativeNumeric[BigDecimal] =
      NonNegativeNumeric.tryCreate(BigDecimal(0)), // in bytes per second

    /** minimum interval between extra traffic purchases in seconds
      *
      * This allows validator operators to control the frequency at which the top-up trigger
      * will charge them domain fees making spends more predictable. This should be greater than the
      * polling interval of the top-up trigger.
      *
      * Note that the actual interval between top-ups might be larger due to the SVC requiring
      * a minimal top-up amount larger than `targetThroughput * minTopupInterval`.
      */
    minTopupInterval: NonNegativeFiniteDuration = NonNegativeFiniteDuration.ofMinutes(10),
)

case class ValidatorGlobalDomainConfig(
    alias: DomainAlias,
    url: String,
    buyExtraTraffic: BuyExtraTrafficConfig = BuyExtraTrafficConfig(),

    /** amount of extra traffic reserved for transactions required to do traffic topups
      *
      * Note that this will be ignored if the validator is not configured to do topups
      * i.e. the target throughput is set to zero (its default value).
      */
    trafficReservedForTopups: NonNegativeNumeric[Long] = NonNegativeNumeric.tryCreate(100_000L),
)

// Validators are responsible for establishing connections to domains and so need more information than just a `DomainConfig`
case class ValidatorExtraDomainConfig(
    alias: DomainAlias,
    url: String,
)

case class ValidatorDomainConfig(
    global: ValidatorGlobalDomainConfig,
    extra: Seq[ValidatorExtraDomainConfig] = Seq(),
)

case class ValidatorAppBackendConfig(
    override val adminApi: CommunityAdminServerConfig = CommunityAdminServerConfig(),
    override val storage: CommunityStorageConfig = CommunityStorageConfig.Memory(),
    ledgerApiUser: String,
    // If not set the ledgerApiUser name is used.
    // This can be used to give a nicer name to the validator party.
    validatorPartyHint: Option[String] = None,
    // An optional separate user name for the validator operator to be used as its user in the
    // wallet. May be useful if the IAM provider does not allow tokens that are used both by
    // machine-to-machine services and login users - in that case, set ledgerApiUser to the m2m
    // one, and validatorWalletUser to the login one. If not provided, the ledgerApiUser is onboarded
    // to the wallet automatically.
    validatorWalletUser: Option[String],
    auth: AuthConfig,
    appInstances: Map[String, AppInstance],
    participantClient: CNParticipantClientConfig,
    scanClient: ScanAppClientConfig,
    override val automation: AutomationConfig = AutomationConfig(),
    domains: ValidatorDomainConfig,
    onboarding: Option[ValidatorOnboardingConfig],
    enableCoinRulesUpgrade: Boolean = false,
    treasury: TreasuryConfig = TreasuryConfig(),
    participantBootstrappingDump: Option[ParticipantBootstrapDumpConfig] = None,
    // TODO(#5855) so we can lock; remove this again
    foundingSvClient: SvAppClientConfig,
    // TODO(#6247) Remove the option to disable this
    enableAdminAuth: Boolean = true,
    participantIdentitiesBackup: Option[BackupDumpConfig] = None,
) extends CNNodeBackendConfig // TODO(#736): fork or generalize this trait.
    {
  override val nodeTypeName: String = "validator"

  override def clientAdminApi: ClientConfig = adminApi.clientConfig

}

case class ValidatorAppClientConfig(
    adminApi: NetworkAppClientConfig
) extends HttpCNNodeClientConfig {
  override def clientAdminApi: NetworkAppClientConfig = adminApi
}
