package com.daml.network.validator.config

import com.daml.network.auth.AuthConfig
import com.daml.network.config.{
  AutomationConfig,
  CNHttpClientConfig,
  CNRemoteParticipantConfig,
  LocalCNNodeConfig,
  RemoteCNNodeConfig,
}
import com.daml.network.scan.config.ScanAppClientConfig
import com.daml.network.sv.config.RemoteSvAppConfig
import com.daml.network.wallet.config.TreasuryConfig
import com.digitalasset.canton.config.*

import java.nio.file.Path

case class AppInstance(
    serviceUser: String,
    // An optional separate user name for the provider to be used as its user in the wallet.
    // May be useful if the IAM provider does not allow tokens that are used both by
    // machine-to-machine services and login users - in that case, set serviceUser to the m2m
    // one, and walletUser to the login one. If not provided, the serviceUser is onboarded
    // to the wallet automatically.
    walletUser: Option[String],
    dars: Seq[Path],
)

case class ValidatorOnboardingConfig(
    remoteSv: RemoteSvAppConfig, // onboarding sponsor
    secret: String, // generated by the sponsor's SV app
)
object ValidatorOnboardingConfig {
  def hideConfidential(config: ValidatorOnboardingConfig): ValidatorOnboardingConfig = {
    val hidden = "****"
    config.copy(secret = hidden)
  }
}

case class ValidatorAppBackendConfig(
    override val adminApi: CommunityAdminServerConfig = CommunityAdminServerConfig(),
    override val storage: CommunityStorageConfig = CommunityStorageConfig.Memory(),
    ledgerApiUser: String,
    // An optional separate user name for the validator operator to be used as its user in the
    // wallet. May be useful if the IAM provider does not allow tokens that are used both by
    // machine-to-machine services and login users - in that case, set ledgerApiUser to the m2m
    // one, and validatorWalletUser to the login one. If not provided, the ledgerApiUser is onboarded
    // to the wallet automatically.
    validatorWalletUser: Option[String],
    auth: AuthConfig,
    appInstances: Map[String, AppInstance],
    remoteParticipant: CNRemoteParticipantConfig,
    remoteScan: ScanAppClientConfig,
    override val automation: AutomationConfig = AutomationConfig(),
    domains: ValidatorDomainConfig,
    onboarding: Option[ValidatorOnboardingConfig],
    enableCoinRulesUpgrade: Boolean = false,
    treasury: TreasuryConfig = TreasuryConfig(),
) extends LocalCNNodeConfig // TODO(#736): fork or generalize this trait.
    {
  override val nodeTypeName: String = "validator"

  override def clientAdminApi: ClientConfig = adminApi.clientConfig

}

case class ValidatorAppClientConfig(
    adminApi: CNHttpClientConfig
) extends RemoteCNNodeConfig {
  override def clientAdminApi: ClientConfig = adminApi.clientConfig
}
