imageRepo: "digitalasset-canton-network-docker.jfrog.io/digitalasset"
cluster:
  imageTag: IMAGE_TAG
  ingress: istio-ingress.cluster-ingress
defaultJvmOptions: -Xms384M -Xmx384M -Dscala.concurrent.context.minThreads=4
cometbftPorts:
  - 26656
  - 26666
  - 26676
  - 26686
  - 26696
