openapi: 3.0.0
info:
  title: Scan API
  version: 0.0.1
tags:
  - name: external
    description: |
      These endpoints are intended for public usage and will remain backward-compatible.
  - name: internal
    description: |
      For internal usage only, not guaranteed to be stable or backward-compatible.
  - name: deprecated
    description: |
      These endpoints are deprecated and will be removed in a future release.
  - name: scan
    description: |
      The internal and external endpoints.
servers:
  - url: https://example.com/api/scan
paths:
  /v0/history/bulk/download/{object_key}:
    get:
      tags: [external, scan]
      x-jvm-package: scanStream
      operationId: "bulkStorageDownload"
      description: TBD
      parameters:
        - name: "object_key"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: TBD
          content:
              application/octet-stream:
                schema:
                  type: string
                  format: binary
                  x-scala-type: org.apache.pekko.http.scaladsl.model.ResponseEntity
        "404":
          $ref: "../../../../common/src/main/openapi/common-external.yaml#/components/responses/404"

