openapi: 3.0.0
info:
  title: Scan API
  version: 0.0.1
tags:
  - name: scan
paths:
  /api/v0/svc-party-id:
    get:
      tags: [scan]
      x-jvm-package: scan
      operationId: "getSvcPartyId"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/GetSvcPartyIdResponse"
  /api/v0/closed-rounds:
    get:
      tags: [scan]
      x-jvm-package: scan
      operationId: "getClosedRounds"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/GetClosedRoundsResponse"
  /api/v0/transfer-context:
    get:
      tags: [scan]
      x-jvm-package: scan
      operationId: "getTransferContext"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/GetTransferContextResponse"
  /api/v0/open-and-issuing-mining-rounds:
    post:
      tags: [scan]
      x-jvm-package: scan
      operationId: "getOpenAndIssuingMiningRounds"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/GetOpenAndIssuingMiningRoundsRequest"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/GetOpenAndIssuingMiningRoundsResponse"
  /api/v0/coin-rules:
    post:
      tags: [scan]
      x-jvm-package: scan
      operationId: "getCoinRules"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/GetCoinRulesRequest"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/GetCoinRulesResponse"
  /api/v0/featured-apps:
    get:
      tags: [scan]
      x-jvm-package: scan
      operationId: "listFeaturedAppRights"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ListFeaturedAppRightsResponse"
  /api/v0/featured-apps/{provider_party_id}:
    get:
      tags: [scan]
      x-jvm-package: scan
      operationId: "lookupFeaturedAppRight"
      parameters:
        - name: "provider_party_id"
          in: "path"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/LookupFeaturedAppRightResponse"
  /api/v0/connected-domains:
    get:
      tags: [scan]
      x-jvm-package: scan
      operationId: "listConnectedDomains"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ListConnectedDomainsResponse"
  /total-coin-balance:
    get:
      tags: [scan]
      x-jvm-package: scan
      operationId: "getTotalCoinBalance"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/GetTotalCoinBalanceResponse"
components:
  schemas:
    GetSvcPartyIdResponse:
      type: object
      required: ["svc_party_id"]
      properties:
        svc_party_id:
          type: string
    GetClosedRoundsResponse:
      type: object
      required: ["rounds"]
      properties:
        rounds:
          type: array
          items:
            "$ref": "../../../../common/src/main/openapi/common.yaml#/components/schemas/Contract"
    GetTransferContextResponse:
      type: object
      properties:
        coin_rules:
          $ref: "../../../../common/src/main/openapi/common.yaml#/components/schemas/Contract"
        latest_open_mining_round:
          $ref: "../../../../common/src/main/openapi/common.yaml#/components/schemas/Contract"
        open_mining_rounds:
          type: array
          items:
            $ref: "../../../../common/src/main/openapi/common.yaml#/components/schemas/Contract"
      required: ["latest_open_mining_round", "open_mining_rounds"]
    GetOpenAndIssuingMiningRoundsRequest:
      type: object
      required: ["cached_open_mining_round_contract_ids", "cached_issuing_round_contract_ids"]
      properties:
        cached_open_mining_round_contract_ids:
          type: array
          items:
            $ref: "../../../../common/src/main/openapi/common.yaml#/components/schemas/ContractId"
        cached_issuing_round_contract_ids:
          type: array
          items:
            $ref: "../../../../common/src/main/openapi/common.yaml#/components/schemas/ContractId"
    GetOpenAndIssuingMiningRoundsResponse:
      type: object
      required: ["open_mining_rounds", "issuing_mining_rounds"]
      properties:
        open_mining_rounds:
          $ref: "../../../../common/src/main/openapi/common.yaml#/components/schemas/MaybeCachedContractMap"
        issuing_mining_rounds:
          $ref: "../../../../common/src/main/openapi/common.yaml#/components/schemas/MaybeCachedContractMap"
    GetCoinRulesRequest:
      type: object
      properties:
        cached_coin_rules_contract_id:
          $ref: "../../../../common/src/main/openapi/common.yaml#/components/schemas/ContractId"
    GetCoinRulesResponse:
      type: object
      properties:
        coin_rules_update:
          $ref: "../../../../common/src/main/openapi/common.yaml#/components/schemas/MaybeCachedContract"
      required:
        - coin_rules_update
    ListFeaturedAppRightsResponse:
      type: object
      required: ["featured_apps"]
      properties:
        featured_apps:
          type: array
          items:
            $ref: "../../../../common/src/main/openapi/common.yaml#/components/schemas/Contract"
    LookupFeaturedAppRightResponse:
      type: object
      properties:
        featured_app_right:
          $ref: "../../../../common/src/main/openapi/common.yaml#/components/schemas/Contract"
    ListConnectedDomainsResponse:
      type: object
      required: ["connected_domains"]
      properties:
        connected_domains:
          "$ref": "../../../../common/src/main/openapi/common.yaml#/components/schemas/ConnectedDomains"
    GetTotalCoinBalanceResponse:
      type: object
      required: ["total_unlocked_balance", "total_locked_balance"]
      properties:
        total_unlocked_balance:
          type: string
        total_locked_balance:
          type: string
