canton {
  validator-apps {
    splitwell_validator_backend {
      storage.type = memory
      admin-api = {
        address = "0.0.0.0"
        port = 5203
      }
      remote-participant = {
        admin-api = {
          address = "splitwell-participant"
          port = 5002
        }
        ledger-api = {
          client-config = {
            address = "splitwell-participant"
            port = 5001
          }
          auth-config = {
            type = "client-credentials"
            well-known-config-url = ${?CN_APP_SPLITWELL_VALIDATOR_LEDGER_API_AUTH_URL}
            client-id = ${?CN_APP_SPLITWELL_VALIDATOR_LEDGER_API_AUTH_CLIENT_ID}
            client-secret = ${?CN_APP_SPLITWELL_VALIDATOR_LEDGER_API_AUTH_CLIENT_SECRET}
            # TODO(#1837) use actual audience of the target participant
            audience = "https://canton.network.global"
          }
        }
      }
      remote-scan = {
        admin-api.port = 5012
        admin-api.address = "scan-app"
        admin-api.url = "http://scan-app:7012"
      }
      ledger-api-user = ${?CN_APP_SPLITWELL_VALIDATOR_LEDGER_API_AUTH_USER_NAME}
      # We currently don't need a login user for splitwell validator, so reusing the same username as the ledger-api-user
      # Note that this is a m2m user, which one cannot use for logging in to the wallet
      validator-wallet-user = ${?CN_APP_SPLITWELL_VALIDATOR_LEDGER_API_AUTH_USER_NAME}
      wallet-service-user = ${?CN_APP_SPLITWELL_WALLET_LEDGER_API_AUTH_USER_NAME}
      auth {
        algorithm = "rs-256"
        audience = "https://canton.network.global"
        jwks-url = "https://canton-network-dev.us.auth0.com/.well-known/jwks.json"
      }
      app-instances {
        splitwell {
          service-user = ${?CN_APP_SPLITWELL_LEDGER_API_AUTH_USER_NAME}
          wallet-user = ${?CN_APP_SPLITWELL_PROVIDER_WALLET_USER_NAME}
          dars = ["splitwell-0.1.0.dar"]
        }
      }
      domains {
        global = "global"
      }
    }
  }
  features.enable-testing-commands = yes
}
