#!/usr/bin/env bash
set -euo pipefail

LIB=$REPO_ROOT/cluster/lib

source $LIB/context-switch

set +u
APP_LABEL=$1
if [ "$APP_LABEL" == "" ]; then
    echo "Usage:\t ./app-expose <APP_LABEL> [PORT:80]"
    exit 1
fi
set -u

PORT="${2:-80}"

# Max timeout in seconds
TIMEOUT=10
POLL_DURATION=0.75
READY=false

start=$(date +%s)
while [ $(expr $(date +%s) - $start) -lt $TIMEOUT ]
do
    running=$(kubectl get pods -l app=$APP_LABEL --field-selector=status.phase=Running | grep Running)

    if [ "$running" == "" ]; then
        echo "Waiting for pod to enter Running phase..."
    else
        READY=true
        break
    fi
    sleep $POLL_DURATION
done

if [ "$READY" == "true" ]; then
    echo "Pod is running! Forwarding port..."
    kubectl port-forward service/$APP_LABEL 0:$PORT
else
    echo "Operation timed out! Pod did not become ready within $TIMEOUT seconds."
    exit 1
fi
