apiVersion: apps/v1
kind: Deployment
metadata:
  name: cn-docs-deployment
  labels:
    app: cn-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cn-docs
  template:
    metadata:
      labels:
        app: cn-docs
    spec:
      containers:
      - name: cn-docs
        image:  us-central1-docker.pkg.dev/cn-devnet-353712/cn-devnet-images/docs:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cn-docs-service
spec:
  type: LoadBalancer
  selector:
    app: cn-docs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  loadBalancerIP: 35.202.15.15
  loadBalancerSourceRanges:
  - 35.194.81.56/32
  - 35.198.147.95/32
  - 35.189.40.124/32
