#!/usr/bin/env bash
set -euo pipefail

LIB=$REPO_ROOT/cluster/lib

source $LIB/context-switch

if [ "$K8S_CONTEXT" == "gcloud" ]; then
    source $LIB/gcloud-setup
    source $LIB/gcloud-connect
fi

source $LIB/k8s-apply
