#!/usr/bin/env bash
set -euo pipefail

source lib/context-switch

if [ "$K8S_CONTEXT" == "gcloud" ]; then
    echo "Deleting gcloud cluster..."
    source lib/gcloud-setup
    source lib/gcloud-delete
elif [ "$K8S_CONTEXT" == "minikube" ]; then
    echo "Deleting minikube cluster..."
    source lib/minikube-delete
fi

echo "Cluster deleted."
