#!/usr/bin/env bash
set -euo pipefail

LIB=$REPO_ROOT/cluster/lib

source $LIB/context-switch

if [ "$K8S_CONTEXT" == "gcloud" ]; then
    source $LIB/gcloud-setup
    source $LIB/gcloud-connect
elif [ "$K8S_CONTEXT" == "minikube" ]
    echo "Warning: running in minikube mode: 'cluster-connect' is a no-op."
fi
