#!/usr/bin/env bash
set -euo pipefail

source lib/context-switch

if [ "$K8S_CONTEXT" == "gcloud" ]; then
    echo "Creating gcloud cluster..."
    source lib/gcloud-setup
    source lib/gcloud-create
    source lib/gcloud-connect
elif [ "$K8S_CONTEXT" == "minikube" ]; then
    echo "Creating minikube cluster..."
    source lib/minikube-create
else
    echo "Unknown cluster type: ${K8S_CONTEXT}"
    exit 1
fi

source lib/k8s-apply
