#!/usr/bin/env bash
set -euo pipefail

LIB=$REPO_ROOT/cluster/lib

source $LIB/context-switch

if [ "$K8S_CONTEXT" == "gcloud" ]; then
    echo "Deleting gcloud cluster..."
    source $LIB/gcloud-setup
    source $LIB/gcloud-delete
elif [ "$K8S_CONTEXT" == "minikube" ]; then
    echo "Deleting minikube cluster..."
    source $LIB/minikube-delete
fi

echo "Cluster deleted."
