#!/usr/bin/env bash
set -euo pipefail

LIB=$REPO_ROOT/cluster/lib

if [ "$K8S_CONTEXT" == "gcloud" ]; then
    echo "Creating gcloud cluster..."
    source $LIB/gcloud-setup
    source $LIB/gcloud-create
    source $LIB/gcloud-connect
elif [ "$K8S_CONTEXT" == "minikube" ]; then
    echo "Creating minikube cluster..."
    source $LIB/minikube-create
else
    echo "Unknown cluster type: ${K8S_CONTEXT}"
    exit 1
fi

source $LIB/k8s-apply
