# Reference configuration options
#svs:
#  sv-1:
#    cometbft:
#      snapshotName: "nicu-test-cometbft-cloning"
infra:
  ipWhitelisting:
    extraWhitelistedIngress: [ ]
  prometheus:
    retentionDuration: "1y"
    retentionSize: "1500GB"
    storageSize: "2Ti"
# configs specific for the pulumi project
# will be applied to all the stacks in the project
pulumiProjectConfig:
  default:
    # skip helm installs and create only non helm resources.
    # this for example lets you create the cloud sql instances without having deployments using them, and restoring them from other sources
    installDataOnly: false
    isExternalCluster: false
    cloudSql:
      enabled: false
      protected: true
      # default tier is equivalent to "Standard" machine with 2 vCpus and 7.5GB RAM
      tier: 'db-custom-2-7680'
  sv-runbook:
    cloudSql:
      enabled: false
## in the form <pulumi-project>:
##                <settings>
## ex:
#  canton-network:
#    installDataOnly: true
monitoring:
  alerting:
    enableNoDataAlerts: false
    alerts:
      trafficWaste:
        kilobytes: 1
        overMinutes: 5
      cometbft:
        expectedMaxBlocksPerSecond: 3.5
      loadTester:
        minRate: 0.95
