secretsprovider: gcpkms://projects/da-cn-shared/locations/us-central1/keyRings/pulumi/cryptoKeys/shared
encryptedkey: CiQAras7yTWoz5za9jXU4FWzBw+2jNLQOgPm+3bxNLG9sjUCP7QSSQBZPvExaBbc/lZLWkdpElLGtho+fjdTRgldrplM9WHt1qXH3nOOgxxYldJ9IRrxJy7ycNWzqUX2t5LgSGN4x8QVbKXyewZg3F4=
