#!/usr/bin/env bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "${script_dir}/libcli.source"

if [ -z "$1" ]; then
    _error "Usage: $0 <image-tag>"
else
    image=$1
fi

# start the check
_log "Considering image: ${image}"

# check if docker is running
out="$(docker info 2>&1)" || _error "docker seems to be down:\n${out}"

# check the image exists
gcloud container images describe "${image}" > /dev/null 2>&1
IMAGE_CHECK=$?

if [ "${IMAGE_CHECK}" -eq 0 ] ; then
  _log "Image exists in repo"
  rc=1
else
  _log "Image does not exist in repo"
  rc=0
fi

exit ${rc}
