#! /usr/bin/env bash
set -euo pipefail

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "${script_dir}/libcli.source"

[[ -z "${MAKE}" || ! -f 'target/docker.id' && ! -f 'target/docker.images' ]] && _error 'must be ran from make'

id="$(<target/docker.id)"

while read -r image; do
  if docker-check "${image}"; then
    _set_x docker tag "${id}" "${image}"
    _set_x docker push "${image}"
  else
    _warning "Cowardly refusing to push, image already exists in repo:\n${image}"
  fi
done < target/docker.images
