validator1:
  kms:
    type: gcp
    locationId: us-central1
    projectId: da-cn-devnet
    keyRingId: validator1_dev
synchronizerMigration:
  active:
    id: 1
    version: 0.3.21
    releaseReference:
      gitReference: "refs/heads/release-line-0.3.21"
      repoUrl: https://github.com/DACH-NY/canton-network-node
      pulumiStacksDir: "cluster/stacks/prod"
      pulumiBaseDir: "cluster/pulumi"
      deploymentDir: "cluster/deployment"
      spliceRoot: "."
pulumiProjectConfig:
  default:
    interAppsDependencies: false
    isExternalCluster: true
    cloudSql:
      enabled: true
  sv-runbook:
    cloudSql:
      enabled: true
monitoring:
  alerting:
    enableNoDataAlerts: true
    alerts:
      trafficWaste:
        # we expect more frequent timeouts on devnet and therefore sequencer request amplification so we allow a higher threshold"
        kilobytes: 10
        overMinutes: 30
      cloudSql:
        maintenance: true
      cometbft:
        expectedMaxBlocksPerSecond: 5
      loadTester:
        # DevNet fluctuates a bit more than our internal clusters so we alert only when it drops below 0.9
        minRate: 0.9
operatorDeployment:
  reference:
    gitReference: refs/heads/main
    repoUrl: https://github.com/DACH-NY/canton-network-node
    pulumiStacksDir: "cluster/stacks/prod"
    pulumiBaseDir: "cluster/pulumi"
    deploymentDir: "cluster/deployment"
    spliceRoot: "."
