infra:
  ipWhitelisting:
    extraWhitelistedIngress:
      - "35.225.102.103/32" # CI GKE cluster for CCI (for preflights)
validator1:
  kms:
    type: gcp
    locationId: us-central1
    projectId: da-cn-devnet
    keyRingId: validator1_dev
synchronizerMigration:
  active:
    id: 0
    provider: external
    version: 0.3.16
    releaseReference: "refs/heads/release-line-0.3.16"
pulumiProjectConfig:
  default:
    isExternalCluster: true
monitoring:
  alerting:
    enableNoDataAlerts: true
    alerts:
      trafficWaste:
        # we expect more frequent timeouts on devnet and therefore sequencer request amplification so we allow a higher threshold"
        kilobytes: 10
        overMinutes: 30
      cometbft:
        expectedMaxBlocksPerSecond: 5
      loadTester:
        # DevNet fluctuates a bit more than our internal clusters so we alert only when it drops below 0.9
        minRate: 0.9
operatorDeployment:
  reference: refs/heads/main
