apiVersion: apps/v1
kind: Deployment
metadata:
  name: scan-app
  namespace: {{ .Release.Namespace }}
  labels:
    app: scan-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scan-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: scan-app
    spec:
      containers:
      - name: scan-app
        image: "{{ .Values.imageRepo }}/scan-app:{{ (.Values.cluster).imageTag }}"
        env:
        - name: JAVA_TOOL_OPTIONS
          value: {{ .Values.defaultJvmOptions }} {{ .Values.additionalJvmOptions }}
        {{- with .Values.persistence }}
        - name: ADDITIONAL_CONFIG_PERSISTENCE
          value: |
            canton.scan-apps.scan-app.storage {
              type = postgres
              config {
                dataSourceClass = "org.postgresql.ds.PGSimpleDataSource"
                properties = {
                  databaseName = "{{ .databaseName }}"
                  currentSchema = "{{ .schema }}"
                  serverName = "{{ .host }}"
                  portNumber = {{ .port }}
                  user = "{{ .user }}"
                  password = ${CN_APP_POSTGRES_PASSWORD}
                }
              }
            }
        - name: CN_APP_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.persistence.secretName }}
              key: postgresPassword
        {{- end }}
        {{- include "cn-util-lib.auth0-env-vars" (dict "appName" "scan" "keyName" "sv" "fixedTokens" (.Values.cluster).fixedTokens) | indent 8}}
        - name: CN_APP_SCAN_PARTICIPANT_ADDRESS
          value: {{ .Values.participantAddress | default "participant" | quote }}
        - name: CN_APP_SCAN_SEQUENCER_ADDRESS
          value: {{ .Values.sequencerAddress | default "global-domain-sequencer" | quote }}
        imagePullPolicy: Always
        ports:
        - containerPort: 5012
          name: scan-api
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /api/scan/livez
            port: 5012
          initialDelaySeconds: 60
          periodSeconds: 60
          failureThreshold: 5
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/scan/readyz
            port: 5012
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 5
          timeoutSeconds: 3
        {{- with .Values.resources }}
        resources: {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- if .Values.init }}
      initContainers:
        - name: {{ .Release.Name }}-init
          image: postgres:14
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgresPassword
                  name: {{ .Values.persistence.secretName }}
          command:
            - 'bash'
            - '-c'
            - |
              until errmsg=$(psql -h {{ .Values.persistence.host }} --username=cnadmin --dbname={{ .Values.init.initDb }} -c 'create database {{ .Values.persistence.databaseName }}' 2>&1); do
                if [[ $errmsg == *"already exists"* ]]; then
                  echo "Database {{ .Values.persistence.databaseName }} already exists. Done."
                  break
                fi

                echo "trying to create postgres database {{ .Values.persistence.databaseName }}, last error: $errmsg";
                sleep 2;
              done
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: scan-app
  namespace: {{ .Release.Namespace }}
  labels:
    app: scan-app
spec:
  selector:
    app: scan-app
  ports:
  - name: scan-api
    port: 5012
    protocol: TCP
  - name: metrics
    port: 10013
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scan-web-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: scan-web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scan-web-ui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: scan-web-ui
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: {{ .Values.defaultJvmOptions }} {{ .Values.additionalJvmOptions }}
        - name: CN_APP_CNS_UI_CLUSTER
          value: {{ .Values.clusterUrl | quote }}
        image: "{{ .Values.imageRepo }}/scan-web-ui:{{ (.Values.cluster).imageTag }}"
        imagePullPolicy: Always
        name: scan-web-ui
        ports:
        - containerPort: 80
          name: scan-ui
          protocol: TCP
        resources:
          limits:
            cpu: 1
            memory: 1536Mi
---
apiVersion: v1
kind: Service
metadata:
  name: scan-web-ui
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: scan-web-ui
  ports:
  - name: scan-ui
    port: 80
    protocol: TCP
