{{- $scanAppLabel := include "appLabel" (list .Values "scan-app") }}
{{- if .Values.metrics.enable }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: {{ .Values.metrics.release }}
  name: {{ include "appLabel" (list .Values "scan-sm") }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:

  - port: metrics
    interval: {{ .Values.metrics.interval }}

  selector:
    matchLabels:
      app: {{ $scanAppLabel }}

  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}

{{- end }}
