_client_credentials_auth_config {
  type = "client-credentials"
  well-known-config-url = ${?CN_APP_SV_LEDGER_API_AUTH_URL}
  client-id = ${?CN_APP_SV_LEDGER_API_AUTH_CLIENT_ID}
  client-secret = ${?CN_APP_SV_LEDGER_API_AUTH_CLIENT_SECRET}
  # TODO(#2052) use actual audience of the target participant
  audience = "https://canton.network.global"
}

_sv_participant_client {
  admin-api = {
    address = ${CN_APP_SV_PARTICIPANT_ADDRESS}
    port = 5002
  }
  ledger-api.client-config = {
    address = ${CN_APP_SV_PARTICIPANT_ADDRESS}
    port = 5001
  }
  ledger-api.auth-config = ${_client_credentials_auth_config}
}

_svc_client {
  admin-api.port = 5005
  admin-api.address = "svc-app.sv-1"
}

_onboarding {
  type = ${?CN_APP_SV_ONBOARDING_TYPE}
  name = ${?CN_APP_SV_ONBOARDING_NAME}
  initial-tick-duration = ${?CN_APP_SV_INITIAL_TICK_DURATION}
  public-key = ${?CN_APP_SV_PUBLIC_KEY}
  private-key = ${?CN_APP_SV_PRIVATE_KEY}
}

canton {
  sv-apps {
    sv {
      storage.type = memory
      admin-api = {
        address = "0.0.0.0"
        port = 5014
      }
      participant-client = ${_sv_participant_client}
      ledger-api-user = ${CN_APP_SV_LEDGER_API_AUTH_USER_NAME}
      validator-ledger-api-user = ${CN_APP_VALIDATOR_LEDGER_API_AUTH_USER_NAME}
      auth {
        algorithm = "rs-256"
        audience = "https://canton.network.global"
        audience = ${?CN_APP_SV_AUTH_AUDIENCE}
        jwks-url = "https://canton-network-dev.us.auth0.com/.well-known/jwks.json"
        jwks-url = ${?CN_APP_SV_AUTH_JWKS_URL}
      }
      svc-client = ${_svc_client}
      domains {
        global {
          alias = "global"
        }
      }
      is-dev-net = ${?CN_APP_SV_IS_DEV_NET}
      onboarding = ${_onboarding}
      initial-coin-price-vote = 1.0
      approved-sv-identities = [
        { name = "Canton-Foundation-2", public-key = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEsRRntNkOLF2Wh7JxV0rBQPgT+SendIjFLXKUXCrLbVHqomkypHQiZP8OgFMSlByOnr81fqiUt3G36LUpg/fmgA==" },
        { name = "Canton-Foundation-3", public-key = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE0fnbBQiM7UiSNaV6tjPq5lK2buIx5L5nzUuhYWxBk341nFChcbK9pDEO4O6gdxexb/OQP6RhQkDOTDdTCr77CA==" },
        { name = "Canton-Foundation-4", public-key = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEa76d2OWmkpCQ2dTWsWyhofV3tOGdlkhoCnPpY7BbQhCb0s3laR1vp57JYu/d5Cf+332PF2XrgjC0yBWUqM4syQ==" },
        { name = "DA-Test-Node", public-key = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE7uz+zW1YcPJIl+TKqXv6/dfxcx+3ISVFgP6m2saeQ0l6r2lNW+WLfq+HUMcycxX9t6bUJ5kyEebYyfk9JW18KA==" },
        { name = "DA-Helm-Test-Node", public-key = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1eb+JkH2QFRCZedO/P5cq5d2+yfdwP+jE+9w3cT6BqfHxCd/PyA0mmWMePovShmf97HlUajFuN05kZgxvjcPQw==" },
        { name = "scratchNetSv", public-key = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEBU0KX9Sqw0kRgW06xsmcScXnjAeKsa2EK+DYDhzC+qf5y3D2SJxl4/R8HFfxE2WehPY02r47Wu686niFHOvwNA==" },
        { name = "damlHub", public-key = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE5ZIIu7ciMWwgNmciMq8SfgY6eVi1o8feUEztydSg4cn8bF2mcd59XF7zbXRoxNKpLW2gNz6gnv8Ldfn5MkHPbA==" },
        { name = "intellecteu-canton-da-test", public-key = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEr/iPpyuFu2U914tHyNUDuECT4/AYz9J+nLQRTC8m+95yQ6Y4Oah+Y3u3o5MK4a9D+qkoNGoG6ng0HcjA6TGKmw==" },
        # Jean Safar (CX)
        { name = "svJean", public-key = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAESxcNzqTXgL+ocVESayKc4nddN6taa/uFI9ca7GGIJs1Ns3yKFDDu6UCDKH+qlXA0+CcmyW6ytvZ9WPVeD7JsMw==" },
        { name = "sbi", public-key = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAETM+CeyHvphl9RiPDKL3vVX7F+Qo4fIhJopmgU5B7IzkwSdFic20hFB6tnAuCTU+UBjqZgh8N/h9r+CTrXMPsRg==" },
      ]
    }
  }
  features.enable-testing-commands = yes
}
