_client_credentials_auth_config {
  type = "client-credentials"
  well-known-config-url = ${?CN_APP_SV_LEDGER_API_AUTH_URL}
  client-id = ${?CN_APP_SV_LEDGER_API_AUTH_CLIENT_ID}
  client-secret = ${?CN_APP_SV_LEDGER_API_AUTH_CLIENT_SECRET}
  # TODO(#1837) use actual audience of the target participant
  audience = "https://canton.network.global"
}

_sv_participant_remote {
  admin-api = {
    address = "canton-participant"
    port = 5002
  }
  ledger-api.client-config = {
    address = "canton-participant"
    port = 5001
  }
  ledger-api.auth-config = ${_client_credentials_auth_config}
}

_svc_remote {
  admin-api.port = 5005
  admin-api.address = "svc-app"
}

canton {
  sv-apps {
    sv {
      storage.type = memory
      admin-api = {
        address = "0.0.0.0"
        port = ${?CN_APP_SV_ADMIN_API_PORT}
      }
      remote-participant = ${_sv_participant_remote}
      daml-user = ${?CN_APP_SV_LEDGER_API_AUTH_USER_NAME}
      remote-svc = ${_svc_remote}
    }
  }
  features.enable-testing-commands = yes
}
