{
 "title": "Global Domain Catchup",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(daml_sequencer_client_handler_delay,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sequencer Client Delay",
   "type": "timeseries",
   "description": "Delay on event processing of a sequencer, compared to the collective",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "daml_sequencer_client_handler_delay{namespace=~\"$namespace\", component=\"sequencer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mediator Client Delay",
   "type": "timeseries",
   "description": "Delay on event processing of a mediator, compared to its corresponding sequencer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "daml_sequencer_client_handler_delay{namespace=~\"$namespace\", component=\"mediator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Participant Client Delay",
   "type": "timeseries",
   "description": "Delay on event processing of the participant, compared to the sequencers it is connected to.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "daml_sequencer_client_handler_delay{namespace=~\"$namespace\",component=\"participant\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CometBFT Block Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "cometbft_consensus_latest_block_height{namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CometBFT Block Syncing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "cometbft_consensus_block_syncing{namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}