{
 "title": "Http Client",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_http_client_requests_duration_seconds,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(daml_http_client_requests_duration_seconds{namespace=~\"$namespace\"},job)"
    }
   },
   {
    "name": "operation",
    "query": {
     "query": "label_values(daml_http_client_requests_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", http_client=~\"$http_client\"},operation)"
    }
   },
   {
    "name": "http_client",
    "query": {
     "query": "label_values(daml_http_client_requests_duration_seconds{namespace=~\"$namespace\", job=~\"$job\"},http_client)"
    }
   },
   { "name": "percentile", "query": "0.9,0.95,0.99" }
  ]
 },
 "panels": [
  {
   "title": "Client requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "histogram_count(rate(daml_http_client_requests_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", operation=~\"$operation\", status_code=~\"2.*\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{job}} {{http_client}} {{operation}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "histogram_count(rate(daml_http_client_requests_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", operation=~\"$operation\", status_code!~\"2.*\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{job}} {{http_client}} {{operation}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Client Requests Timing quantile 0.95 ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, rate(daml_http_client_requests_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", http_client=~\"$http_client\", operation=~\"$operation\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{job}} {{http_client}} {{operation}} {{status_code}}"
    }
   ]
  },
  {
   "title": "In Flight Client Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "daml_http_client_requests_inflight{namespace=~\"$namespace\", job=~\"$job\", http_client=~\"$http_client\", operation=~\"$operation\"}\n",
     "legendFormat": "{{namespace}} {{job}} {{http_client}} {{operation}} {{status_code}}"
    }
   ]
  }
 ]
}