cluster:
  imageTag: IMAGE_TAG
imageRepo: "digitalasset-canton-network-docker.jfrog.io/digitalasset"
schedule: "0 0 0 0 0"
config: "{}"
prometheusRw: ""

# k8s affinity for all deployed pods (optional)
# affinity:

# k8s nodeSelector for all deployed pods (optional)
# nodeSelector:
