canton {
  validator-apps {
    splitwise_validator_backend {
      storage.type = memory
      admin-api = {
        address = "0.0.0.0"
        port = 5203
      }
      remote-participant = {
        admin-api = {
          address = "splitwise-participant"
          port = 5002
        }
        ledger-api = {
          client-config = {
            address = "splitwise-participant"
            port = 5001
          }
          auth-config = {
            type = "client-credentials"
            well-known-config-url = ${?CN_APP_SPLITWISE_VALIDATOR_LEDGER_API_AUTH_URL}
            client-id = ${?CN_APP_SPLITWISE_VALIDATOR_LEDGER_API_AUTH_CLIENT_ID}
            client-secret = ${?CN_APP_SPLITWISE_VALIDATOR_LEDGER_API_AUTH_CLIENT_SECRET}
            # TODO(#1837) use actual audience of the target participant
            audience = "https://canton.network.global"
          }
        }
      }
      remote-scan = {
        admin-api.port = 5012
        admin-api.address = "scan-app"
      }
      ledger-api-user = ${?CN_APP_SPLITWISE_VALIDATOR_LEDGER_API_AUTH_USER_NAME}
      wallet-service-user = ${?CN_APP_SPLITWISE_WALLET_LEDGER_API_AUTH_USER_NAME}
      auth {
        algorithm = "rs-256"
        audience = "https://canton.network.global"
        jwks-url = "https://canton-network-dev.us.auth0.com/.well-known/jwks.json"
      }
      app-instances {
        splitwise {
          service-user = ${?CN_APP_SPLITWISE_LEDGER_API_AUTH_USER_NAME}
          # TODO(#2388): use a different wallet-user, corresponding to a username/password one in auth0
          wallet-user = ${?CN_APP_SPLITWISE_LEDGER_API_AUTH_USER_NAME}
          dars = ["splitwise-0.1.0.dar"]
        }
      }
      domains {
        global = "global"
      }
    }
  }
  features.enable-testing-commands = yes
}
