_participant_remote {
  admin-api = {
    address = "splitwise-participant"
    port = 5202
  }

  ledger-api = {
    address = "splitwise-participant"
    port = 5201
  }
}

_scan_remote {
  admin-api.port = 5012
  admin-api.address = "scan-app"
}

canton {
  validator-apps {
    splitwise_validator_backend {
      storage.type = memory
      admin-api = {
        address = "0.0.0.0"
        port = 5203
      }
      remote-participant = ${_participant_remote}
      remote-scan = ${_scan_remote}
      daml-user = "splitwise_validator_service_user"
      wallet-service-user = "splitwise_wallet_service_user"
      app-instances {
        splitwise {
          service-user = "splitwise_service_user"
          dars = ["splitwise-0.1.0.dar"]
        }
      }
    }
  }
  features.enable-testing-commands = yes
}
