# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

ARG canton_version
ARG image_sha256

FROM europe-docker.pkg.dev/da-images/public-all/docker/canton-sequencer:${canton_version}@${image_sha256}

