# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# ARG base_version
# FROM canton:${base_version}

# ARG base_version
# LABEL org.opencontainers.image.base.name="canton:${base_version}"

# EXPOSE 5008
# EXPOSE 5009
# EXPOSE 5010
# EXPOSE 10013

# COPY app.conf /app/

FROM: europe-docker.pkg.dev/da-images/public-unstable/docker/canton-sequencer:3.4.9-snapshot.20251124.17412.0.v0564fd04
