canton.participants.app-provider = ${_participant} {
  storage.config.properties.databaseName = participant-app-provider
  monitoring {
    http-health-server.port = 3${CANTON_HTTP_HEALTHCHECK_PORT_SUFFIX}
    grpc-health-server.port= 3${CANTON_GRPC_HEALTHCHECK_PORT_SUFFIX}
  }
  http-ledger-api.port = 3${PARTICIPANT_JSON_API_PORT_SUFFIX}
  admin-api.port = 3${PARTICIPANT_ADMIN_API_PORT_SUFFIX}
  ledger-api.port = 3${PARTICIPANT_LEDGER_API_PORT_SUFFIX}
}

canton.sequencers.app-sequencer {

  storage = ${_storage} {
    config.properties {
      databaseName = "app-sequencer"
      currentSchema = "app-sequencer"
    }
  }

  public-api {
    address = "0.0.0.0"
    port = 5018
  }

  admin-api {
    address = "0.0.0.0"
    port = 5019
  }

  monitoring.grpc-health-server {
    address = "0.0.0.0"
    port = 5072
  }

  sequencer {
    config {
      storage = ${_storage} {
        config.properties {
          databaseName = "app-sequencer"
          currentSchema = "app-sequencer-driver"
        }
      }
    }
    type = reference
  }
}

canton.mediators.app-mediator {

  storage = ${_storage} {
    config.properties {
      databaseName = "app-mediator"
      currentSchema = "app-mediator"
    }
  }

  admin-api {
    address = "0.0.0.0"
    port = 5017
  }

  monitoring.grpc-health-server {
    address = "0.0.0.0"
    port = 5071
  }
}
