networks:
  compose-sv_splice-sv-public:
    external: true

services:
  validator:
    networks:
      - compose-sv_splice-sv-public

  participant:
    networks:
      - compose-sv_splice-sv-public
