events {
    worker_connections  64;
}

http {

  # TODO(#14303): At some point I thought Firefox did not work well with wallet.localhost
  # but I can't reproduce that any more, consider removing the 3000/3001 ports option.
  server {
    listen 3000;
    location /api/validator {
      rewrite ^\/(.*) /$1 break;
      proxy_pass http://validator:5003/api/validator;
    }
    location / {
      proxy_pass http://wallet-web-ui:80/;
    }
  }

  server {
    listen 3001;
    location /api/validator {
      rewrite ^\/(.*) /$1 break;
      proxy_pass http://validator:5003/api/validator;
    }
    location / {
      proxy_pass http://ans-web-ui:80/;
    }
  }

  server {
    listen 80;
    server_name wallet.localhost;
    location /api/validator {
      rewrite ^\/(.*) /$1 break;
      proxy_pass http://validator:5003/api/validator;
    }
    location / {
      proxy_pass http://wallet-web-ui:80/;
    }
  }

  server {
    listen 80;
    server_name ans.localhost;
    location /api/validator {
      rewrite ^\/(.*) /$1 break;
      proxy_pass http://validator:5003/api/validator;
    }
    location / {
      proxy_pass http://ans-web-ui:80/;
    }
  }
}
