apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-app
  namespace: {{ .Release.Namespace }}
  labels:
    app: validator-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: validator-app
    spec:
      containers:
      - name: validator-app
        image: "{{ .Values.imageRepo }}/validator-app:{{ (.Values.cluster).imageTag }}"
        imagePullPolicy: Always
        env:
        - name: JAVA_TOOL_OPTIONS
          value: {{ .Values.defaultJvmOptions }}
        - name: CN_APP_VALIDATOR_PARTICIPANT_ADDRESS
          value: {{ .Values.participantAddress | default "participant" | quote }}
        {{ if .Values.appDars -}}
        - name: CN_APP_DARS
          value: {{ .Values.appDars | toJson | quote }}
        {{ end }}
        {{- include "cn-util-lib.auth0-env-vars" (dict "appName" "validator" "keyName" "validator" "fixedTokens" (.Values.cluster).fixedTokens) | indent 8}}
        {{- range $ii, $user := .Values.additionalUsers }}
        - name: {{ $user.name }}
          {{ if $user.value }}
          value: {{ $user.value }}
          {{ end }}
          {{ if $user.valueFrom }}
          valueFrom: {{ $user.valueFrom | toYaml | nindent 12 }}
          {{ end }}
        {{- end }}
        {{ if .Values.additionalConfig -}}
        - name: ADDITIONAL_CONFIG_OTHER
          value: {{- .Values.additionalConfig | toYaml | indent 12 }}
        {{ end }}
        {{ if .Values.svSponsorAddress -}}
        - name: CN_APP_VALIDATOR_SV_SPONSOR_ADDRESS
          value: {{ .Values.svSponsorAddress | quote }}
        {{ if .Values.onboardingSecretFrom -}}
        - name: CN_APP_VALIDATOR_ONBOARDING_SECRET
          valueFrom: {{ .Values.onboardingSecretFrom | toYaml | nindent 12 }}
        {{ else -}}
        # Onboarding without specifying a secret only works in devnet
        - name: CN_APP_DEVNET
          value: "1"
        {{ end -}}
        {{ else -}}
        # Validator has either already been onboarded or
        # is a supervalidator’s validator that does not need this.
        - name: ADDITIONAL_CONFIG_NO_ONBOARDING
          value: |
            canton.validator-apps.validator_backend.onboarding = null
        {{ end -}}
        {{ if .Values.scanAddress -}}
        - name: CN_APP_VALIDATOR_SCAN_ADDRESS
          value: {{ .Values.scanAddress | quote }}
        {{ end }}
        {{ if .Values.validatorWalletUser }}
        - name: CN_APP_VALIDATOR_WALLET_USER_NAME
          value: {{ .Values.validatorWalletUser }}
        {{ end }}
        {{ if .Values.validatorPartyHint }}
        - name: CN_APP_VALIDATOR_PARTY_HINT
          value: {{ .Values.validatorPartyHint }}
        {{ end }}
        {{ if (.Values.auth).audience }}
        - name: CN_APP_VALIDATOR_AUTH_AUDIENCE
          value: {{ .Values.auth.audience | quote }}
        {{ end }}
        {{ if (.Values.auth).jwksUrl }}
        - name: CN_APP_VALIDATOR_AUTH_JWKS_URL
          value: {{ .Values.auth.jwksUrl | quote }}
        {{ end }}
        {{ if .Values.svValidator }}
        - name: CN_APP_VALIDATOR_SV_VALIDATOR
          value: "true"
        {{ end }}
        - name: CN_APP_VALIDATOR_GLOBAL_DOMAIN_URL
          value: {{ .Values.globalDomainUrl | quote }}
        {{- range $ii, $domain := .Values.extraDomains }}
        - name: ADDITIONAL_CONFIG_EXTRA_DOMAIN_{{ $ii }}
          value: |
            canton.validator-apps.validator_backend.domains.extra.{{ $ii }} = {
              alias = {{ $domain.alias | quote }}
              url = {{ $domain.url | quote }}
            }
        {{- end }}
        {{- if (.Values.topup).enabled }}
        - name: ADDITIONAL_CONFIG_TOPUPS
          value: |
            canton.validator-apps.validator_backend.domains.global.buy-extra-traffic.target-throughput = {{ (.Values.topup).targetThroughput }}
            canton.validator-apps.validator_backend.domains.global.buy-extra-traffic.min-topup-interval = {{ (.Values.topup).minTopupInterval }}
        {{- end }}
        {{- with .Values.participantIdentitiesDumpPeriodicBackup }}
        - name: ADDITIONAL_CONFIG_CN_APP_VALIDATOR_PARTICIPANT_IDENTITIES_DUMP_PERIODIC_BACKUP
          value: |
            canton.validator-apps.validator_backend.participant-identities-backup = {
              type = gcp
              bucket {
                project-id = {{ .bucket.projectId }}
                bucket-name = {{ .bucket.bucketName }}
                credentials {
                  type = service-account
                  json-credentials = ${CN_APP_VALIDATOR_BACKUP_BUCKET_SERVICE_ACCOUNT_CREDENTIALS}
                }
              }
              prefix = {{ .prefix | quote }}
              backup-interval = {{ .backupInterval }}
            }
        - name: CN_APP_VALIDATOR_BACKUP_BUCKET_SERVICE_ACCOUNT_CREDENTIALS
          valueFrom:
            secretKeyRef:
              key: "json-credentials"
              name: {{ .bucket.secretName }}
        {{- end }}
        {{- with .Values.participantIdentitiesDumpImport }}
        - name: ADDITIONAL_CONFIG_CN_APP_SV_PARTICIPANT_IDENTITIES_DUMP_IMPORT
          value: |
            canton.validator-apps.validator_backend.participant-bootstrapping-dump {
              type = file
              file = /participant-bootstrapping-dump/content
            }
        {{- end }}
        ports:
        - containerPort: 5003
          name: val-http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /livez
            port: 5003
          initialDelaySeconds: 60
          periodSeconds: 60
          failureThreshold: 5
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 5003
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 5
          timeoutSeconds: 3
        {{- with .Values.participantIdentitiesDumpImport }}
        volumeMounts:
          - name: participant-bootstrapping-dump-volume
            mountPath: /participant-bootstrapping-dump
            readOnly: true
        {{- end }}
        {{- with .Values.resources }}
        resources: {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.participantIdentitiesDumpImport }}
      volumes:
        - name: participant-bootstrapping-dump-volume
          secret:
            secretName: {{ .secretName }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: validator-app
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: validator-app
  ports:
  - name: val-http
    port: 5003
    protocol: TCP
