apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-app
  namespace: {{ .Release.Namespace }}
  labels:
    app: validator-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: validator-app
    spec:
      containers:
      - name: validator-app
        image: "{{ .Values.imageRepo }}/validator-app:{{ .Values.cluster.imageTag }}"
        imagePullPolicy: Always
        env:
        - name: JAVA_TOOL_OPTIONS
          value: {{ .Values.defaultJvmOptions }}
        {{- include "cn-util-lib.auth0-env-vars" "validator" | indent 8}}
        - name: CN_APP_WALLET_LEDGER_API_AUTH_USER_NAME
          valueFrom:
            secretKeyRef:
              key: ledger-api-user
              name: cn-app-wallet-ledger-api-auth
              optional: false
        - name: CN_APP_VALIDATOR_WALLET_USER_NAME
          value: auth0|63e3d75ff4114d87a2c1e4f5
        - name: CN_APP_DARS
          value: '["cn-node-0.1.0-SNAPSHOT/dars/directory-service-0.1.0.dar", "cn-node-0.1.0-SNAPSHOT/dars/splitwell-0.1.0.dar"]'
        - name: CN_APP_VALIDATOR_PARTICIPANT_ADDRESS
          value: participant
        ports:
        - containerPort: 6003
          name: val1-val-http
          protocol: TCP
        {{- with .Values.resources }}
        resources: {{- toYaml . | nindent 10 }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: validator-app
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: validator-app
  ports:
  - name: val1-val-http
    port: 6003
    protocol: TCP
    targetPort: 6003
