imageRepo: "digitalasset-canton-network-docker.jfrog.io/digitalasset"
cluster:
  imageTag: IMAGE_TAG
  hostPrefix: "svc."
withSvIngress: true
defaultJvmOptions: -Xms384M -Xmx384M -Dscala.concurrent.context.minThreads=4
ingress:
  wallet: true
  sv: true
  cns: true
  scan: true
  sequencer: true
  globalDomain:
    globalDomainId: ""
    activeGlobalDomainId: ""
