_client_credentials_auth_config {
  type = "client-credentials"
  well-known-config-url = ${?CN_APP_SPLITWELL_LEDGER_API_AUTH_URL}
  client-id = ${?CN_APP_SPLITWELL_LEDGER_API_AUTH_CLIENT_ID}
  client-secret = ${?CN_APP_SPLITWELL_LEDGER_API_AUTH_CLIENT_SECRET}
  # TODO(#2052) use actual audience of the target participant
  audience = "https://canton.network.global"
}

_participant_client {
  admin-api = {
    address = "participant"
    port = 5002
  }

  ledger-api = {
    client-config = {
      address = "participant"
      port = 5001
    }
    auth-config = ${_client_credentials_auth_config}
  }
}

_validator_client {
  admin-api.url = "validator-app:5003"
}

_scan_client {
  admin-api.url = "http://scan-app.sv-1:5012"
}

canton {
  splitwell-apps {
    splitwell_backend {
      storage.type = memory
      admin-api = {
        address = "0.0.0.0"
        port = 5213
      }
      participant-client = ${_participant_client}
      scan-client = ${_scan_client}
      provider-user = ${?CN_APP_SPLITWELL_LEDGER_API_AUTH_USER_NAME}
      domains {
        splitwell {
          preferred {
            alias = "splitwell"
          }
          others = []
        }
      }
    }
  }
  features.enable-testing-commands = yes

  monitoring.metrics.reporters = [{
    type = prometheus
    address = "0.0.0.0"
    port = 10013
  }]
}
