apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.imageRepo }}/canton-participant:{{ .Values.cluster.imageTag }}"
        imagePullPolicy: Always
        env:
        - name: JAVA_TOOL_OPTIONS
          value: {{ .Values.defaultJvmOptions }}
        - name: CANTON_PARTICIPANT_POSTGRES_SERVER
          value: {{ .Values.postgres }}
        - name: CANTON_PARTICIPANT_POSTGRES_SCHEMA
          value: {{ .Values.postgresSchema }}
        - name: CANTON_PARTICIPANT_USERS
          value: {{ .Values.participantUsers | toJson }}
        - name: CANTON_PARTICIPANT_EXTRA_DOMAINS
          value: {{ .Values.extraDomains | toJson }}
        {{ .Values.extraEnvVars | toYaml | nindent 8 }}
        {{- with .Values.globalDomain }}
        {{- if .alias }}
        - name: GLOBAL_DOMAIN_ALIAS
          value: "{{ .alias }}"
        {{- end }}
        {{- if .url }}
        - name: GLOBAL_DOMAIN_URL
          value: "{{ .url }}"
        {{- end }}
        {{- end }}
        ports:
        - containerPort: 5002
          name: lg-adm-api
          protocol: TCP
        - containerPort: 5001
          name: lg-api
          protocol: TCP
        - containerPort: 10013
          name: metrics-api
          protocol: TCP
        {{- with .Values.resources }}
        resources: {{- toYaml . | nindent 10 }}
        {{- end }}
      - name: envoy-proxy-lg-api
        image: "{{ .Values.imageRepo }}/envoy-proxy:{{ .Values.cluster.imageTag }}"
        imagePullPolicy: Always
        env:
        - name: GRPC_ADDRESS
          value: 127.0.0.1
        - name: GRPC_PORT
          value: "5001"
        - name: GRPC_WEB_PORT
          value: "6001"
        ports:
        - containerPort: 6001
          name: lg-api-gw
          protocol: TCP
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 256Mi
      - name: json-api
        image: "{{ .Values.imageRepo }}/json-api:{{ .Values.cluster.imageTag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 7575
          name: json-api
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: lg-adm-api
    port: 5002
    protocol: TCP
  - name: lg-api
    port: 5001
    protocol: TCP
  - name: metrics
    port: 10013
    protocol: TCP
  - name: lg-api-gw
    port: 6001
    protocol: TCP
  - name: json-api
    port: 7575
    protocol: TCP
