{
 "title": "History backfiling",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(splice_history_txlog_backfilling_latest_record_time,namespace)"
    }
   },
   {
    "name": "migration",
    "query": {
     "query": "label_values(splice_history_txlog_backfilling_completed,migration)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(splice_history_txlog_backfilling_completed,service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "There are three backfilling background tasks:\n\n1. `ScanHistoryBackfillingTrigger` backfills regular updates\n    - Data is loaded from peer scan apps using BFT network calls\n1. `ScanHistoryBackfillingTrigger` backfills import updates\n    - Data is loaded from peer scan apps using BFT network calls\n1. `TxLogBackfillingTrigger` backfills txlog entries\n    - Data is loaded from the local UpdateHistory\n\nThe tasks are completed sequentially in the above order.\nE.g., txlog backfilling won't start until update history backfilling is complete."
   }
  },
  { "title": "Updates (scan)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Backfilled transactions count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by(namespace)(splice_history_backfilling_transaction_count{namespace=~\"$namespace\", migration=~\"$migration\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate backfilled transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max by (namespace)(rate(splice_history_backfilling_transaction_count{namespace=~\"$namespace\", migration=~\"$migration\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backfilled events count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by(namespace)(splice_history_backfilling_event_count{namespace=~\"$namespace\", migration=~\"$migration\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate backfilled events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "max by(namespace)(rate(splice_history_backfilling_event_count{namespace=~\"$namespace\", migration=~\"$migration\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backfilling completed",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "max by(namespace)(splice_history_backfilling_completed{namespace=~\"$namespace\", migration=~\"$migration\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last record time backfilled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "min by(namespace)((splice_history_backfilling_latest_record_time{namespace=~\"$namespace\", migration=~\"$migration\"}>-62135596800000)/1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Import Updates (scan)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Backfilled import contracts count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "max by(namespace)(splice_history_import_updates_backfilling_contract_count{namespace=~\"$namespace\", migration=~\"$migration\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate backfilled contracts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "max by (namespace)(rate(splice_history_import_updates_backfilling_contract_count{namespace=~\"$namespace\", migration=~\"$migration\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Import update backfilling completed",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "max by(namespace)(splice_history_import_updates_backfilling_completed{namespace=~\"$namespace\", migration=~\"$migration\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last migration id backfilled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "min by(namespace)((splice_history_import_updates_backfilling_latest_migration_id{namespace=~\"$namespace\", migration=~\"$migration\"}>-1))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TxLog entries (all apps)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Processed transactions count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "max by(namespace)(splice_history_txlog_backfilling_transaction_count{namespace=~\"$namespace\", migration=~\"$migration\", service=~\"$service\"})",
     "legendFormat": "{{namespace}} {{service}}"
    }
   ]
  },
  {
   "title": "Rate processed transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "max by (namespace)(rate(splice_history_txlog_backfilling_transaction_count{namespace=~\"$namespace\", migration=~\"$migration\", service=~\"$service\"}[5m]))",
     "legendFormat": "{{namespace}} {{service}}"
    }
   ]
  },
  {
   "title": "Processed events count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "max by(namespace)(splice_history_txlog_backfilling_event_count{namespace=~\"$namespace\", migration=~\"$migration\", service=~\"$service\"})",
     "legendFormat": "{{namespace}} {{service}}"
    }
   ]
  },
  {
   "title": "Rate processed events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "max by(namespace)(rate(splice_history_txlog_backfilling_event_count{namespace=~\"$namespace\", migration=~\"$migration\", service=~\"$service\"}[5m]))",
     "legendFormat": "{{namespace}}{{service}}"
    }
   ]
  },
  {
   "title": "TxLog backfilling completed",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "max by(namespace, service) (splice_history_txlog_backfilling_completed{namespace=~\"$namespace\", migration=~\"$migration\", service=~\"$service\"})",
     "legendFormat": "{{namespace}} {{service}}"
    }
   ]
  },
  {
   "title": "Last record time backfilled",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "min by(namespace)((splice_history_txlog_backfilling_latest_record_time{namespace=~\"$namespace\", migration=~\"$migration\", service=~\"$service\"}>-62135596800000)/1000)",
     "legendFormat": "{{namespace}} {{service}}"
    }
   ]
  }
 ]
}