!include($SPLICE_ROOT/cluster/configs/shared/scratchnet.yaml)
synchronizerMigration:
  active:
    id: 0
    version: 0.6.0-snapshot.20260415.2477.0.v0b27ede1
    releaseReference:
      repoUrl: https://github.com/hyperledger-labs/splice
      gitReference: refs/heads/mblaze-da/participant-migration-deployment/4173
      pulumiBaseDir: "cluster/pulumi"
      pulumiStacksDir: "cluster/stacks/scratchnets"
      deploymentDir: "cluster/deployment"
      spliceRoot: "."
      privateConfigsDir: "cluster/configs/configs-private"
      publicConfigsDir: "cluster/configs/configs"
    migrateParticipantsFromSvCantonToSv: true
operatorDeployment:
  reference:
    repoUrl: https://github.com/hyperledger-labs/splice
    gitReference: refs/heads/mblaze-da/participant-migration-deployment/4173
    pulumiBaseDir: "cluster/pulumi"
    pulumiStacksDir: "cluster/stacks/scratchnets"
    deploymentDir: "cluster/deployment"
    spliceRoot: "."
    privateConfigsDir: "cluster/configs/configs-private"
    publicConfigsDir: "cluster/configs/configs"
