validator1:
  kms:
    type: gcp
    locationId: us-central1
    projectId: da-cn-devnet
    keyRingId: validator1_test
synchronizerMigration:
  active:
    id: 1
    provider: external
    version: 0.3.13
    releaseReference: "refs/heads/release-line-0.3.13"
pulumiProjectConfig:
  default:
    isExternalCluster: true
monitoring:
  alerting:
    enableNoDataAlerts: true
operatorDeployment:
  reference: refs/heads/main
