canton {
  features {
    enable-testing-commands = yes
  }
  parameters {
    manual-start = no
  }

  monitoring {
    metrics.reporters = [{
      type = jmx
    }]
  }

  participants {
    splitwise_participant {
      storage.type = memory

      admin-api {
        address = "0.0.0.0"
        port = 5202
      }

      ledger-api {
        address = "0.0.0.0"
        port = 5201
        max-deduplication-duration = 30s
      }
    }
  }
}

canton.participants.splitwise_participant.parameters {
  unsafe-enable-daml-lf-dev-version = yes
  will-corrupt-your-system-dev-version-support = yes
}

canton.participants.splitwise_participant.init.parameters.unique-contract-keys = false
