# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

ARG canton_version

FROM europe-docker.pkg.dev/da-images/public-all/docker/canton-mediator:${canton_version}
