{
 "title": "JVM Metrics",
 "tags": [ "jvm" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(jvm_gc_duration_seconds_count,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(jvm_gc_duration_seconds_count{namespace=~\"$namespace\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(jvm_gc_duration_seconds_count{namespace=~\"$namespace\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_cpu_count{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_cpu_recent_utilization_ratio{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(container, pod) (rate(jvm_cpu_time_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} {{container}}"
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "jvm_thread_count{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "{{job}} - daemon {{jvm_thread_daemon}} - {{jvm_thread_state}}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "GC Runs",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by(gc, container, pod, jvm_gc_name, jvm_gc_action, namespace) (rate(jvm_gc_duration_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{jvm_gc_name}} {{jvm_gc_action}} {{pod}} {{container}}"
    }
   ]
  },
  {
   "title": "GC Timing",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(jvm_gc_action, jvm_gc_name, container, pod, namespace) (rate(jvm_gc_duration_seconds_sum{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "rate {{namespace}} {{jvm_gc_name}} {{jvm_gc_action}} {{pod}} {{container}}"
    },
    {
     "expr": "sum by(jvm_gc_action, jvm_gc_name, container, pod, namespace) (rate(jvm_gc_duration_seconds_sum{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval])) / sum by(jvm_gc_action, jvm_gc_name, container, pod, namespace) (rate(jvm_gc_duration_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "avg {{namespace}} {{jvm_gc_name}} {{jvm_gc_action}} {{pod}} {{container}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "{{pod}} {{container}} - {{jvm_memory_pool_name}} - {{jvm_memory_type}}"
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_limit_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "{{pod}} {{container}} - {{jvm_memory_pool_name}} - {{jvm_memory_type}}"
    }
   ]
  },
  {
   "title": "Memory Used After Last GC ",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_after_last_gc_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "{{pod}} {{container}} - {{jvm_memory_pool_name}} - {{jvm_memory_type}}"
    }
   ]
  },
  {
   "title": "Memory Committed ",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "{{pod}} {{container}} - {{jvm_memory_pool_name}} - {{jvm_memory_type}}"
    }
   ]
  }
 ]
}