{
 "title": "Executor",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_db_wait_duration_seconds_count,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Waittime",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, namespace, node_name, node_type, component, name, node) (rate(cn_db_storage_general_executor_waittime_duration_seconds_bucket{namespace=~\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "0.99 {{namespace}} {{node_name}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, namespace, node_name, node_type, component, name, node) (rate(cn_db_storage_general_executor_waittime_duration_seconds_bucket{namespace=~\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "0.95 {{namespace}} {{node_name}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, namespace, node_name, node_type, component, name, node) (rate(daml_db_storage_general_executor_waittime_duration_seconds_bucket{namespace=~\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "0.99 {{namespace}} {{component}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, namespace, node_name, node_type, component, name, node) (rate(daml_db_storage_general_executor_waittime_duration_seconds_bucket{namespace=~\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "0.95 {{namespace}} {{component}}"
    }
   ]
  },
  {
   "title": "Running executor",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "cn_db_storage_general_executor_running{namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} {{node_name}}"
    },
    {
     "expr": "daml_db_storage_general_executor_running{namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} {{component}}"
    }
   ]
  },
  {
   "title": "Queued executor",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "cn_db_storage_general_executor_queued{namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} {{node_name}}"
    },
    {
     "expr": "daml_db_storage_general_executor_queued{namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} {{component}}"
    }
   ]
  }
 ]
}