{
 "title": "Pool",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(db_client_connections_max,namespace)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(db_client_connections_max{namespace=~\"$namespace\"},service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "db_client_connections_max{namespace=~\"$namespace\", service=~\"$app\"}",
     "legendFormat": "max {{namespace}} {{pool_name}} {{app}}"
    },
    {
     "expr": "db_client_connections_idle_min{namespace=~\"$namespace\", service=~\"$app\"}",
     "legendFormat": "min idle {{namespace}} {{pool_name}} {{app}}"
    },
    {
     "expr": "db_client_connections_usage{namespace=~\"$namespace\", service=~\"$app\"}",
     "legendFormat": "{{state}} {{namespace}} {{pool_name}} {{app}}"
    }
   ]
  },
  {
   "title": "Pending requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "db_client_connections_pending_requests{namespace=~\"$namespace\", service=~\"$app\"}",
     "legendFormat": "{{namespace}} {{pool_name}} {{app}}"
    }
   ]
  },
  {
   "title": "Avg Connection use time ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(namespace, service, pool_name) (rate(db_client_connections_use_time_milliseconds_sum{namespace=~\"$namespace\", service=~\"$app\"}[$__rate_interval])) / sum by(namespace, service, pool_name) (rate(db_client_connections_use_time_milliseconds_count{namespace=~\"$namespace\", service=~\"$app\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{pool_name}} {{app}}"
    }
   ]
  },
  {
   "title": "Connection Use",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(namespace, service, pool_name) (rate(db_client_connections_use_time_milliseconds_count{namespace=~\"$namespace\", service=~\"$app\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{pool_name}} {{app}}"
    }
   ]
  },
  {
   "title": "Avg Connection wait time ",
   "type": "timeseries",
   "description": "Time waiting to get a connection from the pool ",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(namespace, service, pool_name) (rate(db_client_connections_wait_time_milliseconds_count{namespace=~\"$namespace\", service=~\"$app\"}[$__rate_interval])) / sum by(namespace, service, pool_name) (rate(db_client_connections_wait_time_milliseconds_count{namespace=~\"$namespace\", service=~\"$app\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{pool_name}} {{app}}"
    }
   ]
  },
  {
   "title": "Connection Borrow",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(namespace, service, pool_name) (rate(db_client_connections_wait_time_milliseconds_count{namespace=~\"$namespace\", service=~\"$app\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{pool_name}} {{app}}"
    }
   ]
  },
  {
   "title": "Avg Connection create time ",
   "type": "timeseries",
   "description": "Time it takes to create a connection",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(namespace, service, pool_name) (rate(db_client_connections_create_time_milliseconds_count{namespace=~\"$namespace\", service=~\"$app\"}[$__rate_interval])) / sum by(namespace, service, pool_name) (rate(db_client_connections_create_time_milliseconds_count{namespace=~\"$namespace\", service=~\"$app\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{pool_name}} {{app}}"
    }
   ]
  },
  {
   "title": "Connection Create",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(namespace, service, pool_name) (rate(db_client_connections_create_time_milliseconds_count{namespace=~\"$namespace\", service=~\"$app\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{pool_name}} {{app}}"
    }
   ]
  }
 ]
}