apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: svc-app
  name: svc-app
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: svc-app
    spec:
      containers:
      - name: svc-app
        image: "{{ .Values.imageRepo }}/svc-app:{{ .Values.cluster.imageTag }}"
        imagePullPolicy: Always
        env:
        - name: JAVA_TOOL_OPTIONS
          value: -Xms1152M -Xmx1152M -Dscala.concurrent.context.minThreads=4
        {{- include "cn-util-lib.auth0-env-vars" "svc" | indent 8}}
        ports:
        - containerPort: 5005
          name: svc-app-adm-api
          protocol: TCP
        resources:
          limits:
            memory: 1536Mi
          requests:
            cpu: "1"
            memory: 1536Mi
---
apiVersion: v1
kind: Service
metadata:
  name: svc-app
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: svc-app
  ports:
  - name: svc-app-adm-api
    port: 5005
    protocol: TCP
    targetPort: 5005