{
 "title": "gRPC Endpoints",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_grpc_server_started_total, namespace)"
    }
   },
   {
    "name": "component",
    "query": {
     "query": "label_values(daml_grpc_server_started_total{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(daml_grpc_server_started_total{namespace=\"$namespace\", service=\"$component\"}, grpc_service_name)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "label_values(daml_grpc_server_started_total{namespace=\"$namespace\", service=\"$component\",grpc_service_name=~\"$service\"}, grpc_method_name)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   { "name": "quantile", "query": "0.5,0.9,0.95,0.99" }
  ]
 },
 "panels": [
  {
   "title": "Latency Quantile",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum by(grpc_service_name, grpc_client_type, grpc_method_name, grpc_server_type, grpc_code, le) (rate(daml_grpc_server_duration_seconds_bucket{namespace=\"$namespace\", service=\"$component\", grpc_service_name=~\"$service\", grpc_method_name=~\"$method\"}[$__rate_interval])))",
     "legendFormat": "{{grpc_method_name}} - {{grpc_code}} ({{grpc_client_type}} - {{grpc_server_type}})"
    }
   ]
  },
  {
   "title": "Requests Started",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(grpc_server_type, grpc_service_name, grpc_client_type, grpc_method_name) (rate(daml_grpc_server_started_total{namespace=\"$namespace\", service=\"$component\", grpc_service_name=~\"$service\", grpc_method_name=~\"$method\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_method_name}}  ({{grpc_client_type}} - {{grpc_server_type}}) "
    }
   ]
  },
  {
   "title": "Requests Finished",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(grpc_server_type, grpc_service_name, grpc_client_type, grpc_method_name, grpc_code) (rate(daml_grpc_server_handled_total{namespace=\"$namespace\", service=\"$component\", grpc_service_name=~\"$service\", grpc_method_name=~\"$method\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_method_name}} - {{grpc_code}} -  ({{grpc_client_type}} - {{grpc_server_type}}) "
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(grpc_server_type, grpc_service_name, grpc_client_type, grpc_method_name, grpc_code) (rate(daml_grpc_server_handled_total{namespace=\"$namespace\", service=\"$component\", grpc_service_name=~\"$service\", grpc_method_name=~\"$method\", grpc_code!=\"OK\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_method_name}} - {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Error Distribution",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(service, grpc_server_type, grpc_service_name, grpc_client_type, grpc_method_name, grpc_code) (rate(daml_grpc_server_handled_total{namespace=\"$namespace\", service=\"$component\", grpc_service_name=~\"$service\", grpc_method_name=~\"$method\", grpc_code!=\"OK\"}[1m])) / on(service, grpc_server_type, grpc_service_name, grpc_client_type, grpc_method_name) group_left() sum by(service, grpc_server_type, grpc_service_name, grpc_client_type, grpc_method_name) (rate(daml_grpc_server_handled_total{namespace=\"$namespace\", service=\"$component\", grpc_service_name=~\"$service\", grpc_method_name=~\"$method\"}[1m]))",
     "legendFormat": "{{grpc_method_name}} -- {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Average Request Payload Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(grpc_server_type, grpc_service_name, grpc_client_type, grpc_method_name) (rate(daml_grpc_server_messages_received_bytes_sum{namespace=\"$namespace\", service=\"$component\", grpc_service_name=~\"$service\", grpc_method_name=~\"$method\"}[$__rate_interval])) / sum by(grpc_server_type, grpc_service_name, grpc_client_type, grpc_method_name) (rate(daml_grpc_server_messages_received_bytes_count{namespace=\"$namespace\", service=\"$component\", grpc_service_name=~\"$service\", grpc_method_name=~\"$method\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_method_name}} - ({{grpc_client_type}} - {{grpc_server_type}})"
    }
   ]
  },
  {
   "title": "Request Payload Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(grpc_server_type, grpc_service_name, grpc_client_type, grpc_method_name) (rate(daml_grpc_server_messages_received_bytes_sum{namespace=\"$namespace\", service=\"$component\", grpc_service_name=~\"$service\", grpc_method_name=~\"$method\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_method_name}} - ({{grpc_client_type}} - {{grpc_server_type}})"
    }
   ]
  }
 ]
}