{
 "title": "Http Server",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(daml_http_requests_duration_seconds,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(daml_http_requests_duration_seconds{namespace=~\"$namespace\"},job)"
    }
   },
   { "name": "percentile", "query": "0.9,0.95,0.99" }
  ]
 },
 "panels": [
  {
   "title": "Handled Requests",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "histogram_count(rate(daml_http_requests_duration_seconds{namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{job}} {{http_service}} {{operation}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Request Timing quantile $percentile",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, rate(daml_http_requests_duration_seconds{namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} {{job}} {{http_service}} {{operation}} {{status_code}}"
    }
   ]
  },
  {
   "title": "In Flight Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "daml_http_requests_inflight{namespace=~\"$namespace\", job=~\"$job\"}",
     "legendFormat": "{{namespace}} {{job}} {{http_service}} {{operation}} {{status_code}}"
    }
   ]
  }
 ]
}