name: "Post SBT job"
description: "Post SBT job"
inputs:
  cache_version:
    description: "Version of the cache"
    required: true
  setup_sbt_cache_hits:
    description: "Cache hits from the setup SBT job (should be the cache_hits output from the setup SBT job)"
    required: true
runs:
  using: 'composite'
  steps:
    - name: Store precompiled classes
      uses: ./.github/actions/cache/precompiled_classes/save
      with:
        cache_version: ${{ inputs.cache_version }}
        load_cache_hit: ${{ fromJson(inputs.setup_sbt_cache_hits).classes }}

    - name: Store SBT Cache
      uses: ./.github/actions/cache/sbt/save
      with:
        cache_version: ${{ inputs.cache_version }}
        load_cache_hit: ${{ fromJson(inputs.setup_sbt_cache_hits).sbt }}

    - name: Store frontend node_modules
      uses: ./.github/actions/cache/frontend_node_modules/save
      with:
        cache_version: ${{ inputs.cache_version }}
        load_cache_hit: ${{ fromJson(inputs.setup_sbt_cache_hits).node_modules }}

    - name: Store Daml artifacts
      uses: ./.github/actions/cache/daml_artifacts/save
      with:
        cache_version: ${{ inputs.cache_version }}
        load_cache_hit: ${{ fromJson(inputs.setup_sbt_cache_hits).daml }}
