-- Copyright (c) 2023 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
-- SPDX-License-Identifier: Apache-2.0


-- We allow many stores to ingest into the same tables to enable:
--   - fast rollbacks on app upgrades (the new app can start re-ingesting w/o deleting the data ingested by its previous version)
--   - one app maintaining multiple stores (e.g., one per end-user wallet)
--   - multiple app instances running in the same process and sharing the DB
create table store_descriptors (
    -- The DB internal identifier of the store
    id int generated by default as identity primary key,

    -- A JSON object serving as the specification of the concrete ingestion pipeline used by the store.
    -- Used to by the apps to lookup the DB internal 'id' for their specific ingestion pipeline.
    descriptor jsonb not null unique,

    -- the last ingested offset, if any
    last_ingested_offset text
);

-- Templates for create event tables
------------------------------------

-- A template for a table containing a store's create events extended with custom indices.
create table acs_store_template(
    -- The id of the store that this create event belongs to
    store_id int not null,

    -- A monotonically increasing number for events in a store, which is used to serve paginated queries that in
    -- turn drive streaming reads of create events in applications.
    event_number bigint generated by default as identity primary key,

    -- contract data
    contract_id text not null,
    template_id text not null,
    create_arguments jsonb not null,

    -- contract metadata for explicit disclosure
    contract_metadata_created_at bigint,
    contract_metadata_contract_key_hash text,
    contract_metadata_driver_internal bytea,

    -- expiry time of expiring contracts in micros since unix epoch
    -- part of the template as we expect all stores to support expiry
    -- TODO(#3822): wire this up with the generic expiry interface on contracts
    contract_expires_at bigint
);

create unique index acs_store_template_sid_cid
    on acs_store_template (store_id, contract_id);

create index acs_store_template_sid_tid_en
    on acs_store_template (store_id, template_id, event_number);

create index acs_store_template_sid_tid_ce
    on acs_store_template (store_id, template_id, contract_expires_at)
    where contract_expires_at is not null;


-- A template for a table containing a store's TxLog entries extended with custom indices.
--
-- Note: this table only stores TxLog index records, which contain minimum amount of information
-- required to efficiently find relevant TxLog entries.
-- The full TxLog entry can be recreated by loading the daml transaction associated with a given index record,
-- and then passing the daml transaction to TxLogStore.Parser.parse().
create table txlog_store_template(
    -- The id of the store that this TxLog entry belongs to
    store_id int not null,

    -- A monotonically increasing number for entries in a store, which is used to serve paginated queries that in
    -- turn drive streaming reads of TxLog entries in applications.
    entry_number bigint generated by default as identity primary key,

    -- The daml transaction event that is associated with this TxLog entry
    event_id text not null unique,

    "offset" text,

    domain_id text not null,

    acs_contract_id text
);

-- User Wallet Store
--------------------

create table user_wallet_acs_store(
    like acs_store_template including all,

    -- reestablish foreign key constraint as that one is not copied by the LIKE statement above
    foreign key (store_id) references store_descriptors(id)

    -- index columns
    ----------------
);

create table user_wallet_txlog_store(
    like txlog_store_template including all,

    -- reestablish foreign key constraint as that one is not copied by the LIKE statement above
    foreign key (store_id) references store_descriptors (id)

    -- index columns
    ----------------
);

-- Directory store
------------------

create table directory_acs_store(
    like acs_store_template including all,

    -- reestablish foreign key constraint as that one is not copied by the LIKE statement above
    foreign key (store_id) references store_descriptors(id),

    -- index columns
    ----------------

    -- the party id of the directory user of a DirectoryInstall contract
    directory_install_user text,

    -- the name of the directory entry
    directory_entry_name text,

    -- party-id of the directory user that owns a directory entry contracts
    directory_entry_owner text,

    -- the contract-id of a subscription's context contract
    -- used for a DB-level join of subscriptions and their context contracts
    subscription_context_contract_id text,

    -- subscriptions: when the next payment is due
    subscription_next_payment_due_at bigint
);

-- pointwise lookup of payment context contracts
create index directory_acs_store_sid_sccid
    on directory_acs_store (store_id, subscription_context_contract_id)
    where subscription_context_contract_id is not null;

-- retrieve directory installs by user
create index directory_acs_store_sid_diu
    on directory_acs_store (store_id, directory_install_user)
    where directory_install_user is not null;

-- retrieve directory entries by name
create index directory_acs_store_sid_den_tpo
    on directory_acs_store (store_id, directory_entry_name text_pattern_ops)
    where directory_entry_name is not null;

-- retrieve the entries owned by a particular party paged by name
create index directory_acs_store_sid_deo_den
    on directory_acs_store (store_id, directory_entry_owner, directory_entry_name)
    where directory_entry_owner is not null and directory_entry_name is not null;

-- retrieve payments that are due
create index directory_acs_store_sid_snpd
    on directory_acs_store (store_id, subscription_next_payment_due_at)
    where subscription_next_payment_due_at is not null;

-- Scan store
------------------

create table scan_acs_store
(
    like acs_store_template including all,

    -- reestablish foreign key constraint as that one is not copied by the LIKE statement above
    foreign key (store_id) references store_descriptors (id),

    -- index columns
    ----------------

    -- the round of the OpenMiningRound/ClosedMiningRound/IssuingMiningRound/SummarizingMiningRound contract
    round                       bigint,

    -- the party id of the validator
    validator                   text,

    -- amount of coins
    amount                      numeric,

    -- the receiver of an ImportCrate contract
    import_crate_receiver text,

    -- the provider partyid of a FeaturedAppRight contract
    featured_app_right_provider text
);

-- lookup validator traffic
create index scan_acs_store_sid_tid_val
    on scan_acs_store (store_id, template_id, validator, event_number)
    where validator is not null;

-- list ImportCrates
create index scan_acs_store_sid_tid_icrn
    on scan_acs_store (store_id, template_id, import_crate_receiver)
    where import_crate_receiver is not null;

-- lookup FeaturedAppRight
create index scan_acs_store_sid_tid_farp
    on scan_acs_store (store_id, template_id, featured_app_right_provider)
    where featured_app_right_provider is not null;

create table scan_txlog_store
(
    like txlog_store_template including all,

    -- reestablish foreign key constraint as that one is not copied by the LIKE statement above
    foreign key (store_id) references store_descriptors (id),

    -- index columns
    ----------------

    -- defines what type of index record this row represents.
    -- parent traits (e.g. RewardIndexRecord) are *not* present in the DB, only their subclasses
    index_record_type                                        text not null,

    -- the round of a OpenMiningRound/ClosedMiningRound/Reward/ExtraTrafficPurchase IndexRecord
    round                                                    bigint,

    -- The value of the reward coupon (in CC) in AppRewardIndexRecord/ValidatorRewardIndexRecord
    reward_amount                                            numeric,

    -- the party of a AppRewardIndexRecord/ValidatorRewardIndexRecord
    rewarded_party                                           text,

    -- change_to_initial_amount_as_of_round_zero in BalanceChangeIndexRecord
    balance_change_change_to_initial_amount_as_of_round_zero numeric,

    -- change_to_holding_fees_rate in BalanceChangeIndexRecord
    balance_change_change_to_holding_fees_rate               numeric,

    -- the validator of a ExtraTrafficPurchaseIndexRecord
    extra_traffic_validator                                  text,

    -- traffic_purchased in ExtraTrafficPurchaseIndexRecord
    extra_traffic_purchase_traffic_purchased                 bigint,

    -- cc_spent in ExtraTrafficPurchaseIndexRecord
    extra_traffic_purchase_cc_spent                          numeric
);

create index scan_txlog_store_sid_irt_r_en
    on scan_txlog_store (store_id, index_record_type, round, entry_number desc);

-- SV store
------------------

create table sv_acs_store
(
    like acs_store_template including all,

    -- reestablish foreign key constraint as that one is not copied by the LIKE statement above
    foreign key (store_id) references store_descriptors (id),

    -- index columns
    ----------------

    -- candidate_secret in ValidatorOnboarding or secret in UsedSecret
    onboarding_secret text,

    -- candidate_name in ApprovedSvIdentity
    sv_candidate_name text
);

-- lookup validator onboarding or used secret by secret
create index sv_acs_store_sid_tid_vocs
    on sv_acs_store (store_id, template_id, onboarding_secret)
    where onboarding_secret is not null;

-- lookup approved sv identity by candidate name
create index sv_acs_store_sid_tid_asicn
    on sv_acs_store (store_id, template_id, sv_candidate_name)
    where sv_candidate_name is not null;


-- SVC store
------------------

create table svc_acs_store
(
    like acs_store_template including all,

    -- reestablish foreign key constraint as that one is not copied by the LIKE statement above
    foreign key (store_id) references store_descriptors (id),

    -- index columns
    ----------------

    -- In Coin/LockedCoin contracts, round_of_expiry = (created_at_round + (initial_amount / rate_per_round))
    -- as defined in CNNodeUtil.coinExpiresAt
    coin_round_of_expiry          bigint,

    -- the round in which an AppReward or ValidatorReward was rewarded
    reward_round                  bigint,

    -- the app provider in an AppRewardCoupon OR the user in a ValidatorRewardCoupon
    reward_party                  text,

    -- the round in an Open/Close MiningRound contract
    mining_round                  bigint,

    -- The ActionRequiringConfirmation in contracts Confirmation and VoteRequest
    -- we store as json because we don't expect to have that many contracts.
    -- Ideally we would store a hash, but that fails with a HashingError.ForbiddenContractId
    action_requiring_confirmation jsonb,

    -- the confirmer party in a Confirmation contract
    confirmer                     text,

    -- the token in an SvOnboardingRequest
    sv_onboarding_token           text,

    -- The party and name of the candidate respectively, in an SvOnboardingRequest or SvOnboardingConfirmed
    sv_candidate_party            text,
    sv_candidate_name             text,

    -- the validator party in a ValidatorLicense or ValidatorTraffic
    validator                     text,

    -- the traffic purchased in a ValidatorTraffic
    total_traffic_purchased       bigint,

    -- the SV in a CoinPriceVote contract, or the voter in a Vote contract
    voter                         text,

    -- the contract id of a VoteRequest in a Vote contract
    vote_request_cid              text,

    -- the requester in a VoteRequest or ElectionRequest contract
    requester                     text,

    -- the epoch in an ElectionRequest
    election_request_epoch        bigint,

    -- the receiver in an ImportCrate
    import_crate_receiver         text
);

-- ordered mining rounds
create index svc_acs_store_sid_tid_mr
    on svc_acs_store (store_id, template_id, mining_round)
    where mining_round is not null;

-- list expired coins
create index svc_acs_store_sid_tid_croe
    on svc_acs_store (store_id, template_id, coin_round_of_expiry)
    where coin_round_of_expiry is not null;

-- list confirmations
create index svc_acs_store_sid_tid_ah_c
    on svc_acs_store (store_id, template_id, action_requiring_confirmation, confirmer)
    where action_requiring_confirmation is not null;

-- list rewards
create index svc_acs_store_sid_tid_rr_rp
    on svc_acs_store (store_id, template_id, reward_round, reward_party)
    where reward_round is not null and reward_party is not null;

-- lookup sv onboarding by token
create index svc_acs_store_sid_tid_sot
    on svc_acs_store (store_id, template_id, sv_onboarding_token)
    where sv_onboarding_token is not null;

-- lookup sv onboarding by party and/or name
create index svc_acs_store_sid_tid_scp_scn
    on svc_acs_store (store_id, template_id, sv_candidate_party, sv_candidate_name)
    where sv_candidate_party is not null;

-- lookup sv onboarding by name
create index svc_acs_store_sid_tid_scn
    on svc_acs_store (store_id, template_id, sv_candidate_name)
    where sv_candidate_name is not null;

-- list votes by voter & vote request contract id
create index svc_acs_store_sid_tid_v_vrc
    on svc_acs_store (store_id, template_id, voter, vote_request_cid)
    where voter is not null;

-- list votes by vote request contract id
create index svc_acs_store_sid_tid_vrc
    on svc_acs_store (store_id, template_id, vote_request_cid)
    where vote_request_cid is not null;

-- list by validator
create index svc_acs_store_sid_tid_v_tp
    on svc_acs_store (store_id, template_id, validator, total_traffic_purchased)
    where validator is not null;

-- list vote requests
create index svc_acs_store_sid_tid_ah_r
    on svc_acs_store (store_id, template_id, action_requiring_confirmation, requester)
    where action_requiring_confirmation is not null;

-- list election requests
create index svc_acs_store_sid_tid_ere_r
    on svc_acs_store (store_id, template_id, election_request_epoch, requester)
    where election_request_epoch is not null and requester is not null;

-- list import crates
create index svc_acs_store_sid_tid_icr
    on svc_acs_store (store_id, template_id, import_crate_receiver)
    where import_crate_receiver is not null;
