-- Copyright (c) 2023 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
-- SPDX-License-Identifier: Apache-2.0


-- We allow many stores to ingest into the same tables to enable:
--   - fast rollbacks on app upgrades (the new app can start re-ingesting w/o deleting the data ingested by its previous version)
--   - one app maintaining multiple stores (e.g., one per end-user wallet)
--   - multiple app instances running in the same process and sharing the DB
create table store_descriptors (
    -- The DB internal identifier of the store
    id int generated by default as identity primary key,

    -- A JSON object serving as the specification of the concrete ingestion pipeline used by the store.
    -- Used to by the apps to lookup the DB internal 'id' for their specific ingestion pipeline.
    descriptor jsonb not null unique,

    -- the last ingested offset, if any
    last_ingested_offset text
);

-- Templates for create event tables
------------------------------------

-- A template for a table containing a store's create events extended with custom indices.
create table acs_store_template(
    -- The id of the store that this create event belongs to
    store_id int not null,

    -- A monotonically increasing number for events in a store, which is used to serve paginated queries that in
    -- turn drive streaming reads of create events in applications.
    event_number bigint generated by default as identity primary key,

    -- contract data
    contract_id text not null unique,
    template_id text not null,
    create_arguments jsonb not null,

    -- contract metadata for explicit disclosure
    contract_metadata_created_at bigint,
    contract_metadata_contract_key_hash text,
    contract_metadata_driver_internal bytea,

    -- expiry time of expiring contracts in micros since unix epoch
    -- part of the template as we expect all stores to support expiry
    -- TODO(#3822): wire this up with the generic expiry interface on contracts
    contract_expires_at bigint
);

create index acs_store_template_sid_cid
    on acs_store_template (store_id, contract_id);

create index acs_store_template_sid_tid_en
    on acs_store_template (store_id, template_id, event_number);

create index acs_store_template_sid_tid_ce
    on acs_store_template (store_id, template_id, contract_expires_at)
    where contract_expires_at is not null;


-- A template for a table containing a store's TxLog entries extended with custom indices.
--
-- Note: this table only stores TxLog index records, which contain minimum amount of information
-- required to efficiently find relevant TxLog entries.
-- The full TxLog entry can be recreated by loading the daml transaction associated with a given index record,
-- and then passing the daml transaction to TxLogStore.Parser.parse().
create table txlog_store_template(
    -- The id of the store that this TxLog entry belongs to
    store_id int not null,

    -- A monotonically increasing number for entries in a store, which is used to serve paginated queries that in
    -- turn drive streaming reads of TxLog entries in applications.
    entry_number bigint generated by default as identity primary key,

    -- The daml transaction event that is associated with this TxLog entry
    event_id text not null unique
);

-- User Wallet Store
--------------------

create table user_wallet_acs_store(
    like acs_store_template including all,

    -- reestablish foreign key constraint as that one is not copied by the LIKE statement above
    foreign key (store_id) references store_descriptors(id),

    -- index columns
    ----------------

    -- The round for which a reward coupons was registered
    reward_coupon_round_number bigint,

    -- The time as of which a subscription can be renewed
    subscription_ready_for_renewal_at bigint
);

create index user_wallet_acs_store_sid_rcrn
    on user_wallet_acs_store (store_id, reward_coupon_round_number)
    where reward_coupon_round_number is not null;

create index user_wallet_acs_store_sid_srfr
    on user_wallet_acs_store (store_id, subscription_ready_for_renewal_at)
    where subscription_ready_for_renewal_at is not null;


create table user_wallet_txlog_store(
    like txlog_store_template including all,

    -- reestablish foreign key constraint as that one is not copied by the LIKE statement above
    foreign key (store_id) references store_descriptors (id)

    -- index columns
    ----------------
);

-- Directory store
------------------

create table directory_acs_store(
    like acs_store_template including all,

    -- reestablish foreign key constraint as that one is not copied by the LIKE statement above
    foreign key (store_id) references store_descriptors(id),

    -- index columns
    ----------------

    -- the party id of the directory user of a DirectoryInstall contract
    directory_install_user text,

    -- the name of the directory entry
    directory_entry_name text,

    -- party-id of the directory user that owns a directory entry contracts
    directory_entry_owner text,

    -- the contract-id of a subscription's context contract
    -- used for a DB-level join of subscriptions and their context contracts
    subscription_context_contract_id text,

    -- subscriptions: when the next payment is due
    subscription_next_payment_due_at bigint
);

-- pointwise lookup of payment context contracts
create index directory_acs_store_sid_sccid
    on directory_acs_store (store_id, subscription_context_contract_id)
    where subscription_context_contract_id is not null;

-- retrieve directory installs by user
create index directory_acs_store_sid_diu
    on directory_acs_store (store_id, directory_install_user)
    where directory_install_user is not null;

-- retrieve directory entries by name
create index directory_acs_store_sid_den_tpo
    on directory_acs_store (store_id, directory_entry_name text_pattern_ops)
    where directory_entry_name is not null;

-- retrieve the entries owned by a particular party paged by name
create index directory_acs_store_sid_deo_den
    on directory_acs_store (store_id, directory_entry_owner, directory_entry_name)
    where directory_entry_owner is not null and directory_entry_name is not null;

-- retrieve payments that are due
create index directory_acs_store_sid_snpd
    on directory_acs_store (store_id, subscription_next_payment_due_at)
    where subscription_next_payment_due_at is not null;
