create table acs_snapshot_data
(
    row_id      bigint generated by default as identity primary key,
    create_id   bigint not null references update_history_creates (row_id),
    -- These fields are duplicates from update_history_creates, to improve query/index performance
    -- The `stakeholder` column is the unnesting of array_cat(signatories, observers).
    -- If we didn't unnest, we'd have to build a GIN index over that array, which doesn't have as good performance.
    template_id text   not null,
    stakeholder text   not null
);

create table acs_snapshot
(
    snapshot_record_time bigint not null primary key,
    migration_id         bigint not null,
    -- Keeping the first and last row ids allows querying acs_snapshot_data via the primary key index.
    -- NOTE: that only works if one snapshot is generated at a time.
    first_row_id         bigint not null references acs_snapshot_data (row_id),
    last_row_id          bigint not null references acs_snapshot_data (row_id),
    check (first_row_id <= last_row_id)
);

-- include (create_id) allows for index-only scans.
create index acs_snapshot_data_all_filters on acs_snapshot_data (template_id, stakeholder, row_id) include (create_id);
create index acs_snapshot_data_template_only_filter on acs_snapshot_data (template_id, row_id) include (create_id);
create index acs_snapshot_data_stakeholder_only_filter on acs_snapshot_data (stakeholder, row_id) include (create_id);