create table update_history_reassignments
(
    -- The id of the history that this create event belongs to
    history_id                  int not null references update_history_descriptors (id),

    -- A generated identifier for the update.
    -- Not useful for anything other than an opaque primary key for this table.
    row_id                      bigint generated by default as identity primary key,

    -- The time when this row was inserted, used for debugging and monitoring
    ingested_at                 timestamptz not null default now(),

    -- Primary identifier of the update.
    -- The tuple (history_id, migration_id, update_id) should be unique, but we do not actually create a unique
    -- constraint for this, as the update_id is a large random string, which would lead to expensive index updates.
    update_id                   text not null,

    -- Information useful for ordering or partitioning updates
    record_time                 bigint not null, -- When was this update sequenced
    participant_offset          text not null,   -- TODO(#10605): local to the participant, drop this once we have the record time
    domain_id                   text not null,   -- The domain of the reassignment batch
    migration_id                int not null,    -- The thing that increments with each hard domain migration
    workflow_id                 text null
);
