-- Incremental ACS snapshot for ingestion
create table acs_incremental_snapshot_data_next
(
    create_id    bigint      not null,
    contract_id  text        not null,

    -- Contract data included to avoid joining with UpdateHistory tables
    -- during the expensive operation of saving incremental ACS snapshots.
    created_at   bigint      not null,
    unlocked_amulet_balance  numeric not null,
    locked_amulet_balance    numeric not null,
    template_id  text        not null,
    stakeholders text[]      not null
);

-- Needed for fast insert/remove by contract id
alter table acs_incremental_snapshot_data_next
    add constraint acs_incremental_snapshot_data_next_pk
       primary key (contract_id);

-- Needed because ACS snapshots are ordered by creation time
create index acs_incremental_snapshot_data_next_ca_ci
    on acs_incremental_snapshot_data_next (created_at, contract_id);

-- Incremental ACS snapshot for backfilling
create table acs_incremental_snapshot_data_backfill
(
    create_id    bigint      not null,
    contract_id  text        not null,

    created_at   bigint      not null,
    unlocked_amulet_balance  numeric not null,
    locked_amulet_balance    numeric not null,
    template_id  text        not null,
    stakeholders text[]      not null
);

alter table acs_incremental_snapshot_data_backfill
    add constraint acs_incremental_snapshot_data_backfill_pk
        primary key (contract_id);

create index acs_incremental_snapshot_data_backfill_ca_ci
    on acs_incremental_snapshot_data_backfill (created_at, contract_id);

-- State of the incremental ACS snapshots
create table acs_incremental_snapshot
(
    snapshot_id                     bigint generated by default as identity primary key,
    history_id                      bigint not null references update_history_descriptors (id),

    -- We maintain two incremental ACS snapshots in parallel, one for the ingestion
    -- and one for backfilling. Each incremental ACS snapshot gets its own table.
    -- This column indicates which table this snapshot is for.
    table_name                      text   not null,

    -- The time as of which this snapshot represents the ACS.
    record_time                     bigint not null,
    migration_id                    bigint not null,

    -- The time at which the snapshot should be copied to acs_snapshot_data.
    target_record_time              bigint not null

);

create unique index acs_incremental_snapshot_hid_tn
    on acs_incremental_snapshot (history_id, table_name);
