create table sequencer_traffic_summary_store
(
    -- Primary key for the table
    row_id                      bigint generated by default as identity,
    -- The time when this row was inserted, used for debugging and monitoring
    ingested_at                 timestamptz not null default now(),
    -- History identifier for update history partitioning
    history_id                  bigint not null,
    -- Migration identifier for domain migrations
    migration_id                bigint not null,
    -- Domain identifier
    domain_id                   text not null,
    -- Time as of which the message was sequenced
    sequencing_time             bigint not null,
    -- The sender of the message (typically the participant id of the validator node)
    sender                      text not null,
    -- Total traffic cost of the message paid by the sender
    total_traffic_cost          bigint not null,
    -- Traffic cost per envelope (parallel array with envelope_view_hashes)
    envelope_traffic_costs      bigint[] not null,
    -- View hashes per envelope, stored as JSONB array of arrays (parallel array with envelope_traffic_costs)
    -- Each element contains view hashes for one envelope, e.g., [["hash1","hash2"],["hash3"]]
    envelope_view_hashes        jsonb not null,
    constraint sequencer_traffic_summary_store_pkey primary key (row_id)
);

-- Index for efficient querying by history, migration and sequencing time
create index sequencer_traffic_hi_mi_st on sequencer_traffic_summary_store (history_id, migration_id, sequencing_time);

-- Unique index for deduplication (safety net) and efficient existence checks
create unique index sequencer_traffic_hi_st on sequencer_traffic_summary_store (history_id, sequencing_time);
