create table sequencer_traffic_summary_store
(
    -- Primary key for the table
    row_id                      bigint generated by default as identity primary key,
    -- The time when this row was inserted, used for debugging and monitoring
    ingested_at                 timestamptz not null default now(),
    -- History identifier for update history partitioning
    -- The synchronizer-id is included in the history_id via a unique store_name in update_history_descriptors
    history_id                  bigint not null,
    -- Migration identifier for domain migrations
    migration_id                bigint not null,
    -- Time as of which the message was sequenced
    sequencing_time             bigint not null,
    -- The sender of the message (typically the participant id of the validator node)
    sender                      text not null,
    -- Total traffic cost of the message paid by the sender
    total_traffic_cost          bigint not null
);

-- Unique index for deduplication (safety net) and efficient existence checks
create unique index sequencer_traffic_hi_st on sequencer_traffic_summary_store (history_id, sequencing_time);

-- Child table for envelope data (one-to-many relationship with traffic summaries)
create table sequencer_traffic_envelope_store
(
    -- Foreign key to parent traffic summary
    traffic_summary_row_id      bigint not null references sequencer_traffic_summary_store (row_id),
    -- Envelope index within the traffic summary (0-based)
    envelope_index              int not null,
    -- Traffic cost for this envelope
    traffic_cost                bigint not null,
    -- View hashes for this envelope
    view_hashes                 text[] not null,
    primary key (traffic_summary_row_id, envelope_index)
);
