create table sequencer_traffic_summary_store
(
    -- Primary key for the table
    row_id                      bigint generated by default as identity primary key,
    -- The time when this row was inserted, used for debugging and monitoring
    ingested_at                 timestamptz not null default now(),
    -- History identifier for update history partitioning
    -- The synchronizer-id is included in the history_id via a unique store_name in update_history_descriptors
    history_id                  bigint not null,
    -- Migration identifier for domain migrations
    migration_id                bigint not null,
    -- Time as of which the message was sequenced
    sequencing_time             bigint not null,
    -- Total traffic cost of the message paid by the sender
    total_traffic_cost          bigint not null,
    -- Envelope data as JSONB array: [{"traffic_cost": 123, "view_hashes": ["h1", "h2"]}, ...]
    envelopes                   jsonb not null default '[]'::jsonb
);

-- Unique index for deduplication (safety net) and efficient existence checks
create unique index sequencer_traffic_hi_st on sequencer_traffic_summary_store (history_id, sequencing_time);
