apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prefix" (list .Values "initial-data") }}
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "setup/shared/initial-data/*").AsConfig | indent 2 }}
