---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prefix" (list .Values "cometbft-data") }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.node.identifier }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.db.volumeSize }}
  storageClassName: {{ $.Values.db.volumeStorageClass }}
  volumeMode: Filesystem
  {{- with .Values.db.volumeNodeAffinity }}
  nodeAffinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
