---
{{- $fullName := "cometbft" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "cometbft-data"
  labels:
    app: {{ $fullName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.db.volumeSize }}
  storageClassName: {{ $.Values.db.volumeStorageClass }}
  volumeMode: Filesystem
