---
{{- $fullName := include "prefix" (list .Values "keys") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
data:
  node_key.json: {{ include "nodeKeyJson" .Values.node.privateKey | trim |  b64enc }}
  priv_validator_key.json: {{ include "privValidatorKeyJson" . | trim | b64enc }}
