{{- if .Values.metrics.enable }}
{{- $fullRpcHostName := include "prefix" (list .Values "cometbft-rpc") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: {{ .Values.metrics.release }}
  name: {{ include "prefix" (list .Values "cometbft-sm") }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:

  - port: cometbft-metrics
    interval: {{ .Values.metrics.interval }}

  selector:
    matchLabels:
      name: {{ $fullRpcHostName }}

  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}

{{- end }}
