apiVersion: 1
groups:
  - orgId: 1
    name: automation
    folder: canton-network
    interval: 5m
    rules:
      - uid: fe73c0e7-dcb3-4975-a7d1-04ed8da087be
        title: Automation Failures
        condition: threshold
        data:
          - refId: total
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              editorMode: code
              expr: sum by(namespace, node_type, trigger_name, migration) (delta(cn_trigger_completed_total{trigger_name=~".+", outcome=~".+"}[10m]))
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: total
          - refId: failures
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              editorMode: code
              expr: sum by(namespace, node_type, trigger_name, migration) (delta(cn_trigger_completed_total{trigger_name=~".+", outcome=~"failure"}[10m])) or on() vector(0)
              hide: false
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: failures
          - refId: failure_pct
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params: []
                  reducer:
                    params: []
                    type: avg
                  type: query
              datasource:
                name: Expression
                type: __expr__
                uid: __expr__
              expression: ${failures} / ${total} * 100
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: failure_pct
              type: math
          - refId: threshold
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params: []
                  reducer:
                    params: []
                    type: avg
                  type: query
              datasource:
                name: Expression
                type: __expr__
                uid: __expr__
              expression: failure_pct
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: threshold
              type: threshold
        dashboardUid: a3e1385f-6f03-46d9-908c-34aca0f507a6
        panelId: 14
        noDataState: $NODATA
        execErrState: Error
        for: 5m
        annotations:
          __dashboardUid__: a3e1385f-6f03-46d9-908c-34aca0f507a6
          __panelId__: "14"
          description: The {{ index $labels "trigger_name" }} for the {{ index $labels "node_type" }} app in the {{ index $labels "namespace" }} namespace on migration id {{ index $labels "migration" }} experienced {{ index $values "failure_pct" }}% failures in the last 10 minutes.
          severity: |-
            {{- if (gt $values.failure_pct.Value 50.0) -}}
            critical
            {{- else -}}
            warning
            {{- end -}}
          summary: '{{ index $values "failure_pct" }}% fatal errors occurred in {{ index $labels "namespace" }} - {{ index $labels "trigger_name" }} automation trigger'
        labels:
          gcloud_filter: 'resource.labels.namespace_name=%22{{ index $labels "namespace" }}%22%0A%22{{ index $labels "trigger_name" }}%22'
        isPaused: false
