apiVersion: 1
groups:
  - orgId: 1
    name: deployments
    folder: canton-network
    interval: 1m
    rules:
      - uid: adkhl6u18pqtce
        title: Failing Stacks
        condition: D
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              editorMode: code
              exemplar: true
              expr: stacks_failing
              format: time_series
              instant: true
              interval: ""
              intervalMs: 30000
              legendFormat: stacks_active
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: D
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - D
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: D
              type: threshold
        dashboardUid: QP_wDqDnz
        panelId: 6
        noDataState: NoData
        execErrState: Error
        for: 1m
        annotations:
          __dashboardUid__: QP_wDqDnz
          __panelId__: "6"
          description: The pulumi operator failed to update the {{ $labels.name }} stack. Check the logs for the deployment.
          runbook_url: ""
          summary: '{{ $labels.name }} stack failed to update'
        labels:
          "": ""
        isPaused: false
