apiVersion: 1
groups:
  - orgId: 1
    name: traffic
    folder: canton-network
    interval: 1m
    rules:
      - uid: adw5rd048zf9ca
        title: Wasted Traffic
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              editorMode: code
              expr: sum by (namespace, job, member) (delta(daml_sequencer_traffic_control_wasted_traffic_total{member=~"PAR::.*"}[$WASTED_TRAFFIC_ALERT_TIME_RANGE_MINSm])) / 1000
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: B
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: []
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - B
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: last
              refId: B
              type: reduce
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - $WASTED_TRAFFIC_ALERT_THRESHOLD_KB
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        dashboardUid: fdnphvrryfq4gf
        panelId: 6
        noDataState: OK
        execErrState: Error
        for: 1m
        annotations:
          __dashboardUid__: fdnphvrryfq4gf
          __panelId__: "6"
          description: The rate of traffic wasted by sequencer {{ index $labels "job" }} in namespace {{ index $labels "namespace" }} for member {{ index $labels "member" }} exceeded $WASTED_TRAFFIC_ALERT_THRESHOLD_KB kB over $WASTED_TRAFFIC_ALERT_TIME_RANGE_MINS mins
          severity: critical
          summary: Traffic wasted by {{ index $labels "namespace" }} sequencer for {{ index $labels "member" }} exceeded threshold
        labels: {}
        isPaused: false
