_storage {
  type = postgres
  config {
    dataSourceClass = "org.postgresql.ds.PGSimpleDataSource"
    properties = {
      serverName = ${CANTON_DOMAIN_POSTGRES_SERVER}
      portNumber = "5432"
      databaseName = "cantonnet"
      currentSchema = "sequencer"
      user = "cnadmin"
      password = "cnadmin"
      user = ${?CANTON_DOMAIN_POSTGRES_USER}
      password = ${?CANTON_DOMAIN_POSTGRES_PASSWORD}
    }
  }
}

canton {
  parameters {
    manual-start = no
    non-standard-config = yes
    dev-version-support = yes
  }

  sequencers-x {
    sequencer {
      topology-x {
        enable-topology-transaction-validation = false
      }
      storage = ${_storage}
      storage.config.properties.currentSchema = "sequencer"

      public-api {
        address = "0.0.0.0"
        port = 5008
      }

      admin-api {
        address = "0.0.0.0"
        port = 5009
      }

      parameters.initial-protocol-version = dev

      sequencer {
        config {
          cometbft-node-host = ${SEQUENCER_DRIVER_COMETBFT_HOST}
          cometbft-node-port = ${SEQUENCER_DRIVER_COMETBFT_PORT}
        }
        type = "CometBFT"
      }
    }
  }

  monitoring.metrics.reporters = [{
    type = prometheus
    address = "0.0.0.0"
    port = 10013
  }]
}
