pulumiProjectConfig:
  default:
    interAppsDependencies: false
    cloudSql:
      enabled: true
      protected: true
      tier: "db-custom-4-7680"
  sv-runbook:
    cloudSql:
      enabled: true
svs:
  sv-13:
    participant:
      kms:
        keyRingId: sv-13_participant_cilr
        locationId: us-central1
validator1:
  kms:
    type: gcp
    locationId: us-central1
    projectId: da-cn-ci-2
    keyRingId: validator1_validator
  participantPruningSchedule:
    cron: "0 /10 * * * ?" # Run every 10min
    maxDuration: "5m"
    retention: "25h" # Keep 25h of data, this must be bigger than the max dedup duration used which is 24h in our apps
sv:
  cometbft:
    # CometBFT pruning is a lie, see https://github.com/DACH-NY/canton-network-node/issues/17692
    volumeSize: "4000Gi"
synchronizerMigration:
  archived:
  - id: 4
    version: "0.3.21"
    releaseReference:
      gitReference: "refs/tags/cilr-3.2"
      repoUrl: https://github.com/DACH-NY/canton-network-node
      pulumiStacksDir: "cluster/stacks/ci"
      pulumiBaseDir: "cluster/pulumi"
      deploymentDir: "cluster/deployment"
      spliceRoot: "."
  active:
    id: 5
    version: "0.4.0-snapshot.20250424.9146.0.v5142d2e3"
    releaseReference:
      gitReference: "refs/tags/cilr"
      repoUrl: https://github.com/DACH-NY/canton-network-node
      pulumiStacksDir: "cluster/stacks/ci"
      pulumiBaseDir: "cluster/pulumi"
      deploymentDir: "cluster/deployment"
      spliceRoot: "."
persistentSequencerHeapDumps: true
monitoring:
  alerting:
    enableNoDataAlerts: true
    alerts:
      trafficWaste:
        kilobytes: 50
        overMinutes: 30
      cometbft:
        expectedMaxBlocksPerSecond: 7
operatorDeployment:
  reference:
    gitReference: refs/heads/main
    repoUrl: https://github.com/DACH-NY/canton-network-node
    pulumiStacksDir: "cluster/stacks/ci"
    pulumiBaseDir: "cluster/pulumi"
    deploymentDir: "cluster/deployment"
    spliceRoot: "."
