infra:
  ipWhitelisting:
    extraWhitelistedIngress:
      - "35.225.102.103/32" # CI GKE cluster for CCI
synchronizerMigration:
  active:
    id: 4
    provider: external
    version: 0.3.1-snapshot.20241127.7721.0.v26811473
    releaseReference: "refs/tags/cilr"
persistentSequencerHeapDumps: true
