workflow:
  deploy_cidaily:
    when:
      equal: [ deploy-cidaily, << pipeline.parameters.run-job >> ]
    jobs:
      - artifacts_push:
          <<: *notify-fail
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
      - wait_for_previous_pipeline:
          <<: *notify-fail
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          workflow_names: "deploy_cidaily cidaily_health_check redeploy_validator_runbook_cidaily redeploy_sv_runbook_cidaily backup_cidaily restore_sv_cidaily restore_validator_cidaily"
      - reset_cluster:
          cluster: "cidaily"
          silence_deployment_alerts: true
          context:
            - artifactory
            - slack-context
          requires:
            - wait_for_previous_pipeline
      - deploy_cluster:
          name: deploy_cluster_cidaily
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          cluster: "cidaily"
          requires:
            - artifacts_push
            - reset_cluster
      - preflight_check:
          cluster: "cidaily"
          <<: *main-branch-only
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          wait_for_sv: false
          # Order: deploy_cluster->preflight_check->publish_public_release->deploy_sv_runbook->preflight_sv_check
          requires:
            - artifacts_push
            - deploy_cluster_cidaily
      - publish_public_release:
          <<: *main-branch-only
          <<: *notify-fail
          context:
            - artifactory
            - slack-context
          requires:
            - preflight_check
      - create_oss_pr:
          <<: *main-branch-only
          <<: *notify-fail
          context:
            - artifactory
            - slack-context
          requires:
            - preflight_check
      - deploy_sv_runbook:
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "cidaily"
          use_published_artifacts: true
          requires:
            - deploy_cluster_cidaily
            - publish_public_release
            - artifacts_push
      - deploy_validator_runbook:
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          cluster: "cidaily"
          use_published_artifacts: true
          requires:
            - deploy_cluster_cidaily
            - publish_public_release
            - artifacts_push
      - preflight_sv_check:
          <<: *main-branch-only
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "cidaily"
          requires:
            - deploy_sv_runbook
      - preflight_validator_check:
          <<: *main-branch-only
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "cidaily"
          requires:
            - deploy_validator_runbook
      - backup_cluster:
          name: backup_cidaily
          <<: *main-branch-only
          cluster: "cidaily"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          requires:
            - deploy_cluster_cidaily

  cidaily_health_check:
    when:
      equal: [ healthcheck-cidaily, << pipeline.parameters.run-job >> ]
    jobs:
      - wait_for_previous_pipeline:
          <<: *notify-fail
          filters:
            branches:
              only:
                - deployment/cidaily
          context:
            - artifactory
            - slack-context
          # Only wait for sv runbook deployments and for backup-recovery, concurrent preflight checks are fine.
          workflow_names: "redeploy_sv_runbook_cidaily redeploy_validator_runbook_cidaily deploy-cidaily"
      - cancel_if_previous_pipeline:
          <<: *notify-fail
          filters:
            branches:
              only:
                - deployment/cidaily
          context:
            - artifactory
            - slack-context
          # Cancel health check if any deploy is running as it's redundant to run it (they are run as part of the deployment)
          # It doesn't make sense to run it as there are high chances that the old version pre-flights will fail on the new deployment
          workflow_names: "deploy_cidaily"
      - cancel_if_previous_pipeline:
          name: skip_during_catchup
          <<: *notify-fail
          filters:
            branches:
              only:
                - deployment/cidaily
          context:
            - artifactory
            - slack-context
          # Skip healthchecks for 60 minutes after starting an sv/validator node restore from backup.
          # ATM, some tests are expected to fail while an SV is catching up, others are prone to failure.
          max_pipeline_age_secs: 3600
          workflow_names: "restore_sv_cidaily restore_validator_cidaily"
          only_if_running: false
      - preflight_check:
          filters:
            branches:
              only:
                - deployment/cidaily
          cluster: "cidaily"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          requires:
            - wait_for_previous_pipeline
            - cancel_if_previous_pipeline
            - skip_during_catchup

  redeploy_sv_runbook_cidaily:
    when:
      equal: [ redeploy-sv-runbook-cidaily, << pipeline.parameters.run-job >> ]
    jobs:
      - wait_for_previous_pipeline:
          <<: *notify-fail
          filters:
            branches:
              only:
                - deployment/cidaily
          context:
            - artifactory
            - slack-context
          workflow_names: "deploy_cidaily redeploy_validator_runbook_cidaily redeploy_sv_runbook_cidaily cidaily_health_check restore_sv_cidaily restore_validator_cidaily"
      - cancel_if_previous_pipeline:
          <<: *notify-fail
          filters:
            branches:
              only:
                - deployment/cidaily
          context:
            - artifactory
            - slack-context
          # Cancel runbook deployment if any deploy is running as it will try to deploy an old version
          # because the branch is not yet updated.
          workflow_names: "deploy_cidaily"
      - deploy_sv_runbook:
          filters:
            branches:
              only:
                - deployment/cidaily
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "cidaily"
          use_published_artifacts: true
          silence_deployment_alerts: true
          requires:
            - wait_for_previous_pipeline
            - artifacts_push
      - preflight_sv_check:
          filters:
            branches:
              only:
                - deployment/cidaily
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "cidaily"
          requires:
            - deploy_sv_runbook

  redeploy_validator_runbook_cidaily:
    when:
      equal: [ redeploy-validator-runbook-cidaily, << pipeline.parameters.run-job >> ]
    jobs:
      - wait_for_previous_pipeline:
          <<: *notify-fail
          filters:
            branches:
              only:
                - deployment/cidaily
          context:
            - artifactory
            - slack-context
          workflow_names: "redeploy_validator_runbook_cidaily cidaily_health_check restore_sv_cidaily restore_validator_cidaily"
      - cancel_if_previous_pipeline:
          <<: *notify-fail
          filters:
            branches:
              only:
                - deployment/cidaily
          context:
            - artifactory
            - slack-context
          # Cancel runbook deployment if any deploy is running as it will try to deploy an old version
          # because the branch is not yet updated.
          workflow_names: "deploy_cidaily"
      - deploy_validator_runbook:
          filters:
            branches:
              only:
                - deployment/cidaily
          context:
            - artifactory
            - slack-context
          cluster: "cidaily"
          use_published_artifacts: true
          silence_deployment_alerts: true
          requires:
            - wait_for_previous_pipeline
            - artifacts_push
      - preflight_validator_check:
          filters:
            branches:
              only:
                - deployment/cidaily
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "cidaily"
          requires:
            - deploy_validator_runbook

  backup_cidaily:
    when:
      equal: [ backup-cidaily, << pipeline.parameters.run-job >> ]
    jobs:
      - wait_for_previous_pipeline:
          <<: *notify-fail
          filters:
            branches:
              only:
                - deployment/cidaily
          context:
            - artifactory
            - slack-context
          workflow_names: "deploy_cidaily backup_cidaily restore_sv_cidaily restore_validator_cidaily"
      - backup_cluster:
          filters:
            branches:
              only:
                - deployment/cidaily
          cluster: "cidaily"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          requires:
            - wait_for_previous_pipeline

  restore_sv_cidaily:
    when:
      equal: [ restore-sv-cidaily, << pipeline.parameters.run-job >> ]
    jobs:
      - wait_for_previous_pipeline:
          <<: *notify-fail
          filters:
            branches:
              only:
                - deployment/cidaily
          context:
            - artifactory
            - slack-context
          workflow_names: "deploy_cidaily cidaily_health_check backup_cidaily restore_sv_cidaily"
      - restore_node:
          filters:
            branches:
              only:
                - deployment/cidaily
          cluster: "cidaily"
          # sv-3 chosen quite arbitrarily as one SV to restore from backup
          namespace_name: "sv-3"
          silence_deployment_alerts: true
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          requires:
            - wait_for_previous_pipeline

  restore_validator_cidaily:
    when:
      equal: [ restore-validator-cidaily, << pipeline.parameters.run-job >> ]
    jobs:
      - wait_for_previous_pipeline:
          <<: *notify-fail
          filters:
            branches:
              only:
                - deployment/cidaily
          context:
            - artifactory
            - slack-context
          workflow_names: "deploy_cidaily cidaily_health_check backup_cidaily restore_validator_cidaily"
      - restore_node:
          filters:
            branches:
              only:
                - deployment/cidaily
          cluster: "cidaily"
          namespace_name: "validator1"
          silence_deployment_alerts: true
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          requires:
            - wait_for_previous_pipeline
