workflow:
  deploy_cimain:
    when:
      equal: [ build, << pipeline.parameters.run-job >> ]
    jobs:
      - artifacts_push:
          <<: *notify-fail
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
        # We build the tests early in the workflow to populate the caches already, otherwise
        # the tests take longer since they may build the whole repo again.
        # We do it separately on circleci and self-hosted because their caches are separate,
        # and we use both for preflights.
      - build_tests_self_hosted:
          <<: *notify-fail
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
      - build_tests_circleci:
          <<: *notify-fail
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
      - wait_for_previous_pipeline:
          <<: *notify-fail
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          workflow_names: "deploy_cimain"
          wait_type: "cancel_waiting_and_wait_workflow"
      - autoscaler_prevent_scaledown:
          cluster: "cimain"
          requires:
            - wait_for_previous_pipeline
      - reset_cluster:
          cluster: "cimain"
          silence_deployment_alerts: true
          context:
            - artifactory
            - slack-context
          requires:
            - wait_for_previous_pipeline
      - deploy_cluster:
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          cluster: "cimain"
          update_deployment_branch: false  # No need to create a deployment branch for cimain
          cancel_workflow_on_failure: true
          requires:
            - autoscaler_prevent_scaledown
            - reset_cluster
            - artifacts_push
      - preflight_check:
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          cluster: "cimain"
          wait_for_sv: false
          requires:
            - deploy_cluster
            - build_tests_self_hosted
      - preflight_check_docker:
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "cimain"
          wait_for_sv: false
          requires:
            - deploy_cluster
            - build_tests_circleci
      - deploy_sv_runbook:
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          cluster: "cimain"
          silence_deployment_alerts: true
          requires:
            - deploy_cluster
      - preflight_sv_check:
          <<: *main-branch-only
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "cimain"
          requires:
            - deploy_cluster
            - build_tests_self_hosted
      - deploy_validator_runbook:
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          cluster: "cimain"
          silence_deployment_alerts: true
          requires:
            - deploy_cluster
      - preflight_validator_check:
          <<: *main-branch-only
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "cimain"
          requires:
            - deploy_cluster
            - build_tests_self_hosted
      - backup_cluster:
          <<: *main-branch-only
          cluster: "cimain"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          requires:
            - deploy_cluster
            - deploy_sv_runbook
            - deploy_validator_runbook
      - restore_node:
          <<: *main-branch-only
          cluster: "cimain"
          namespace_name: "sv-3"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          requires:
            - backup_cluster
            - preflight_sv_check
            - preflight_validator_check
            - preflight_check
            - preflight_check_docker
      - reset_cluster:
          name: "reset_end"
          <<: *main-branch-only
          cluster: "cimain"
          context:
            - slack-context
          requires:
            - restore_node
      - autoscaler_allow_scaledown:
          cluster: "cimain"
          requires:
            - restore_node
