workflow:
  deploy_cimain:
    when:
      equal: [ build, << pipeline.parameters.run-job >> ]
    jobs:
      - docker_images_push:
          <<: *notify-fail
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
      - wait_for_previous_pipeline:
          <<: *notify-fail
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          workflow_names: "deploy_cimain"
      - deploy_cluster:
          name: "deploy_cluster_for_migration"
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          cluster: "cimain"
          send_deployment_notification: false
          update_deployment_branch: false  # No need to create a deployment branch for cimain
          cancel_workflow_on_failure: true
          requires:
            - wait_for_previous_pipeline
            - docker_images_push
      - preflight_check:
          <<: *main-branch-only
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "cimain"
          wait_for_sv: false
          parallelism: 1
          requires:
            - wait_for_previous_pipeline
            - docker_images_push
      - deploy_sv_runbook:
          name: "deploy_sv_runbook_for_migration"
          <<: *main-branch-never
          context:
            - artifactory
            - slack-context
          cluster: "cimain"
          requires:
            - deploy_cluster_for_migration
      - preflight_sv_check:
           name: "preflight_sv_check_before_migration"
           <<: *main-branch-never
           context:
             - artifactory
             - canton-network-vpn
             - slack-context
           cluster: "cimain"
           requires:
             - deploy_cluster_for_migration
      - backup_cluster:
          name: "backup_cluster_before_migration"
          <<: *main-branch-only
          cluster: "cimain"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          requires:
            - deploy_cluster_for_migration
            - deploy_sv_runbook_for_migration
      - preflight_check:
          name: "trigger_global_domain_migration"
          <<: *main-branch-only
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "cimain"
          test_names_file: "test-full-class-names-global-domain-upgrade-preflight.log"
          parallelism: 1
          wait_for_sv: false
          requires:
            - preflight_check
            - preflight_sv_check_before_migration
            - backup_cluster_before_migration
      - deploy_cluster:
          name: "migrate_cluster"
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          cluster: "cimain"
          send_deployment_notification: false
          update_deployment_branch: false
          global_domain_active_migration_id: 1
          global_domain_migrate_from_id: 0
          global_domain_legacy_migration_id: 0
          requires:
            - trigger_global_domain_migration
      - preflight_check:
          name: "preflight_check_migrated"
          <<: *main-branch-only
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "cimain"
          migration_id: 1
          requires:
            - trigger_global_domain_migration
      - deploy_sv_runbook:
          name: "migrate_sv_runbook"
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          cluster: "cimain"
          send_deployment_notification: false
          requires:
            - trigger_global_domain_migration
          global_domain_active_migration_id: 1
          global_domain_migrate_from_id: 0
          global_domain_legacy_migration_id: 0
      - preflight_sv_check:
          name: "preflight_sv_check_migrated"
          migration_id: 1
          <<: *main-branch-only
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "cimain"
          requires:
            - trigger_global_domain_migration
      - deploy_validator_runbook:
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          cluster: "cimain"
          global_domain_active_migration_id: 1
          # TODO(#10441) uncomment once doing migration
          # global_domain_migrate_from_id: 0
          # global_domain_legacy_migration_id: 0
          requires:
            - migrate_cluster
      - preflight_validator_check:
          <<: *main-branch-only
          name: "preflight_validator_check_migrated"
          migration_id: 1
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "cimain"
          requires:
            - trigger_global_domain_migration
      - restore_node:
          <<: *main-branch-only
          cluster: "cimain"
          namespace_name: "sv-3"
          expected_migration_id: 1
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          requires:
            - preflight_sv_check_migrated
            - preflight_validator_check_migrated
            - preflight_check_migrated
