workflow:
  deploy_ciperiodic_non_devnet:
    when:
      equal: [ deploy-ciperiodic-non-devnet, << pipeline.parameters.run-job >> ]
    jobs:
      - artifacts_push:
          <<: *notify-fail
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
      - wait_for_previous_pipeline:
          <<: *notify-fail
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          workflow_names: "deploy_ciperiodic_migration deploy_ciperiodic_sv_reonboard deploy_ciperiodic_non_devnet"
          wait_type: "wait_workflow"
      - enable_autoscaler:
          name: "ensure_autoscaler_enabled"
          <<: *main-branch-only
          cluster: "ciperiodic"
          requires:
            - wait_for_previous_pipeline
      - autoscaler_set_min_nodes:
          name: "Prevent scaledowns (by setting a high min_nodes)"
          <<: *main-branch-only
          cluster: "ciperiodic"
          # Set min nodes to MAX_NODES to prevent scale downs
          num_nodes_from_env_var: "GCP_CLUSTER_MAX_NODES"
          requires:
            - ensure_autoscaler_enabled
      - deploy_cluster:
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          cluster: "ciperiodic"
          update_deployment_branch: false
          silence_deployment_alerts: true
          cancel_workflow_on_failure: true
          force_non_devnet: true
          requires:
            - wait_for_previous_pipeline
            - artifacts_push
      - preflight_check:
          <<: *main-branch-only
          <<: *non_devnet_preflight_params
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciperiodic"
          force_non_devnet: true
          requires:
            - wait_for_previous_pipeline
            - artifacts_push
      - deploy_sv_runbook:
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "ciperiodic"
          force_non_devnet: true
          requires:
            - deploy_cluster
      - preflight_sv_check:
          <<: *main-branch-only
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciperiodic"
          force_non_devnet: true
          requires:
             - deploy_cluster
      - deploy_validator_runbook:
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          cluster: "ciperiodic"
          force_non_devnet: true
          requires:
            - deploy_cluster
      - preflight_validator_check:
          <<: *main-branch-only
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciperiodic"
          force_non_devnet: true
          requires:
            - deploy_cluster
      - reset_cluster:
          <<: *main-branch-only
          cluster: "ciperiodic"
          is_shared_cluster: false
          context:
            - canton-network-vpn
          requires:
            - preflight_sv_check
            - preflight_validator_check
            - preflight_check
      - autoscaler_set_min_nodes:
          name: "set_min_nodes"
          <<: *main-branch-only
          cluster: "ciperiodic"
          num_nodes_from_env_var: "GCP_CLUSTER_MIN_NODES"
          requires:
            - preflight_sv_check
            - preflight_validator_check
            - preflight_check
