workflow:
  deploy_ciperiodic_migration:
    when:
      equal: [ deploy-ciperiodic-migration, << pipeline.parameters.run-job >> ]
    jobs:
      - artifacts_push:
          <<: *notify-fail
          context:
            - artifactory
            - slack-context
      - wait_for_previous_pipeline:
          <<: *notify-fail
          context:
            - artifactory
            - slack-context
          workflow_names: "deploy_ciperiodic_migration deploy_ciperiodic_sv_reonboard deploy_ciperiodic_non_devnet"
          wait_type: "wait_workflow"
      - autoscaler_prevent_scaledown:
          cluster: "ciperiodic"
          requires:
            - wait_for_previous_pipeline
      - reset_cluster:
          name: "reset_initially"
          cluster: "ciperiodic"
          extra_migrations_reset: "0,1"
          context:
            - canton-network-vpn
            - slack-context
          requires:
            - wait_for_previous_pipeline
      - deploy_cluster:
          name: "deploy_cluster_for_migration"
          context:
            - artifactory
            - slack-context
          cluster: "ciperiodic"
          update_deployment_branch: false  # No need to create a deployment branch for ciperiodic
          cancel_workflow_on_failure: true
          deploy_version: << pipeline.parameters.base-version >>
          requires:
            - artifacts_push
            - reset_initially
      - deploy_sv_runbook:
          name: "deploy_sv_runbook_for_migration"
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "ciperiodic"
          deploy_version: << pipeline.parameters.base-version >>
          requires:
            - deploy_cluster_for_migration
      - deploy_validator_runbook:
          name: "deploy_validator_runbook_for_migration"
          context:
            - artifactory
            - slack-context
          cluster: "ciperiodic"
          deploy_version: << pipeline.parameters.base-version >>
          requires:
            - deploy_cluster_for_migration
      - pre_migration_dump_identities:
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "ciperiodic"
          requires:
            - deploy_cluster_for_migration
            - deploy_validator_runbook_for_migration
      - pre_migration_compose_validator:
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "ciperiodic"
          base_version: << pipeline.parameters.base-version >>
          requires:
            - deploy_cluster_for_migration
      - hard_migration:
          name: "prepare_cluster_for_migration"
          context:
            - artifactory
            - slack-context
          cluster: "ciperiodic"
          action: "prepare"
          scope: "core"
          base_version: << pipeline.parameters.base-version >>
          upgrade_version: << pipeline.parameters.upgrade-version >>
          requires:
            - deploy_cluster_for_migration
      - hard_migration:
          name: "prepare_sv_runbook_for_migration"
          context:
            - artifactory
            - slack-context
          cluster: "ciperiodic"
          action: "prepare"
          scope: "sv"
          base_version: << pipeline.parameters.base-version >>
          upgrade_version: << pipeline.parameters.upgrade-version >>
          requires:
            - deploy_sv_runbook_for_migration
      - trigger_global_domain_migration:
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciperiodic"
          requires:
            - deploy_cluster_for_migration
            - deploy_sv_runbook_for_migration
      - hard_migration:
          name: "migrate_cluster"
          context:
            - artifactory
            - slack-context
          cluster: "ciperiodic"
          action: "migrate"
          scope: "core"
          base_version: << pipeline.parameters.base-version >>
          upgrade_version: << pipeline.parameters.upgrade-version >>
          requires:
            - prepare_cluster_for_migration
            - trigger_global_domain_migration
            - pre_migration_compose_validator
            - pre_migration_dump_identities
      - preflight_check:
          name: "preflight_check_migrated"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciperiodic"
          cluster_version: << pipeline.parameters.upgrade-version >>
          migration_id: 1
          requires:
            - trigger_global_domain_migration
      - hard_migration:
          name: "migrate_sv_runbook"
          context:
            - artifactory
            - slack-context
          cluster: "ciperiodic"
          action: "migrate"
          scope: "sv"
          base_version: << pipeline.parameters.base-version >>
          upgrade_version: << pipeline.parameters.upgrade-version >>
          requires:
            - prepare_sv_runbook_for_migration
            - migrate_cluster
      # Re-enable once latest release is > 0.2.3
#      - preflight_sv_check:
#          name: "preflight_sv_check_migrated"
#          <<: *main-branch-only
#          context:
#            - artifactory
#            - canton-network-vpn
#            - slack-context
#          cluster: "ciperiodic"
#          cluster_version: << pipeline.parameters.upgrade-version >>
#          migration_id: 1
#          requires:
#            - migrate_cluster
      - hard_migration:
          name: "migrate_validator_runbook"
          context:
            - artifactory
            - slack-context
          cluster: "ciperiodic"
          action: "migrate"
          scope: "validator"
          base_version: << pipeline.parameters.base-version >>
          upgrade_version: << pipeline.parameters.upgrade-version >>
          requires:
            - migrate_cluster
      - post_migration_verify_identities:
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "ciperiodic"
          requires:
            - pre_migration_dump_identities
            - migrate_cluster
            - migrate_validator_runbook
      - preflight_validator_check:
          name: "preflight_validator_check_migrated"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciperiodic"
          cluster_version: << pipeline.parameters.upgrade-version >>
          migration_id: 1
          requires:
            - migrate_cluster
      - post_migration_compose_validator:
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "ciperiodic"
          upgrade_version: << pipeline.parameters.upgrade-version >>
          requires:
            - migrate_cluster
      - backup_cluster:
          name: "backup_cluster_after_migration"
          cluster: "ciperiodic"
          migration_id: 1
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          requires:
            # Re-enable once latest release is > 0.2.3
#            - preflight_sv_check_migrated
            - preflight_validator_check_migrated
            - preflight_check_migrated
      - restore_node:
          cluster: "ciperiodic"
          namespace_name: "sv-3"
          migration_id: 1
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          requires:
            - backup_cluster_after_migration
      - reset_sv_runbook:
          name: "reset_sv_runbook_after_migration"
          extra_migrations_reset: "0,1"
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "ciperiodic"
          requires:
            - migrate_sv_runbook
      - deploy_sv_runbook:
          name: "deploy_fresh_sv_runbook_after_migration"
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "ciperiodic"
          deploy_version: << pipeline.parameters.upgrade-version >>
          global_domain_active_migration_id: 1
          requires:
            - reset_sv_runbook_after_migration
      #          # Re-enable once latest release is > 0.2.3
      #            - preflight_sv_check_migrated
      - preflight_sv_check:
          name: "preflight_sv_check_redeployed"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciperiodic"
          cluster_version: << pipeline.parameters.upgrade-version >>
          migration_id: 1
          requires:
            # We wait for the runbook to redeploy to make sure we're not testing the original deployment
            - deploy_fresh_sv_runbook_after_migration
      - reset_cluster:
          cluster: "ciperiodic"
          extra_migrations_reset: "0,1"
          context:
            - canton-network-vpn
            - slack-context
          requires:
            - restore_node
            - preflight_sv_check_redeployed
            - post_migration_compose_validator
      - autoscaler_allow_scaledown:
          cluster: "ciperiodic"
          requires:
            - restore_node
            - preflight_sv_check_redeployed
            - post_migration_compose_validator
