workflow:
  deploy_ciperiodic_sv_reonboard:
    when:
      equal: [ deploy-ciperiodic-sv-reonboard, << pipeline.parameters.run-job >> ]
    jobs:
      - wait_for_previous_pipeline:
          <<: *notify-fail
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          workflow_names: "deploy_ciperiodic_migration deploy_ciperiodic_sv_reonboard deploy_ciperiodic_non_devnet"
          wait_type: "wait_workflow"
      - artifacts_push:
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          requires:
            - wait_for_previous_pipeline
      - enable_autoscaler:
          name: "ensure_autoscaler_enabled"
          <<: *main-branch-only
          cluster: "ciperiodic"
          requires:
            - wait_for_previous_pipeline
      - autoscaler_set_min_nodes:
          name: "Prevent scaledowns (by setting a high min_nodes)"
          <<: *main-branch-only
          cluster: "ciperiodic"
          # Set min nodes to MAX_NODES to prevent scale downs
          num_nodes_from_env_var: "GCP_CLUSTER_MAX_NODES"
          requires:
            - ensure_autoscaler_enabled
      - deploy_cluster:
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          cluster: "ciperiodic"
          update_deployment_branch: false
          cancel_workflow_on_failure: true
          requires:
            - artifacts_push
      - deploy_sv_runbook:
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "ciperiodic"
          requires:
            - deploy_cluster
      - preflight_check:
          name: "offboard_sv_runbook"
          <<: *main-branch-only
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciperiodic"
          test_names_file: "test-full-class-names-offboard-sv-runbook-preflight.log"
          parallelism: 1
          wait_for_sv: false
          requires:
            - deploy_sv_runbook
            - preflight_sv_check
      - deploy_validator_to_recover_sv_amulets:
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          validator_party_hint: "DA-Helm-Test-Node"
          validator_new_participant_id: "new-participant"
          restore_identity_from_sv_runbook: true
          cluster: "ciperiodic"
          requires:
            - offboard_sv_runbook
      - deploy_sv_runbook:
          name: "redeploy_sv_runbook"
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "ciperiodic"
          requires:
            - deploy_validator_to_recover_sv_amulets
      - preflight_check:
          name: "preflight_sv_reonboard_check"
          <<: *main-branch-only
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciperiodic"
          test_names_file: "test-full-class-names-re-onboard-sv-runbook-preflight.log"
          parallelism: 1
          wait_for_sv: false
          requires:
            - redeploy_sv_runbook
      - preflight_sv_check:
          <<: *main-branch-only
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciperiodic"
          requires:
            - deploy_cluster
      - reset_cluster:
          <<: *main-branch-only
          cluster: "ciperiodic"
          is_shared_cluster: false
          context:
            - canton-network-vpn
          requires:
            - preflight_sv_reonboard_check
      - autoscaler_set_min_nodes:
          name: "set_min_nodes"
          <<: *main-branch-only
          cluster: "ciperiodic"
          num_nodes_from_env_var: "GCP_CLUSTER_MIN_NODES"
          requires:
            - preflight_sv_check
            - preflight_validator_check
            - preflight_check
