workflow:
  deploy_ciupgrade:
    # the parameters run-job, run-partial-upgrade and base-version are set in launch_ciupgrade_workflow
    when:
      equal: [ deploy-ciupgrade, << pipeline.parameters.run-job >> ]
    jobs:
      - wait_for_previous_pipeline:
          <<: *notify-fail
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          workflow_names: "deploy_ciupgrade"
          wait_type: "wait_workflow"
      - reset_cluster:
          # note that this reset is executed on the latest version to properly cleanup previous deploy_ciupgrade runs
          name: reset_cluster
          <<: *main-branch-only
          cluster: "ciupgrade"
          is_shared_cluster: false
          context:
            - canton-network-vpn
          requires:
            - wait_for_previous_pipeline
      - deploy_cluster:
          name: "deploy_cluster_for_upgrade"
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          cluster: "ciupgrade"
          reset_cluster: false # done in reset_cluster job
          send_deployment_notification: false
          update_deployment_branch: false  # No need to create a deployment branch for ciupgrade
          cancel_workflow_on_failure: true
          deploy_version: << pipeline.parameters.base-version >>
          requires:
            - reset_cluster
      - preflight_check:
          name: "preflight_check_initial"
          <<: *main-branch-only
          cluster_version: << pipeline.parameters.base-version >>
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciupgrade"
          wait_for_sv: false
          parallelism: 1
          requires:
            - reset_cluster
      - deploy_sv_runbook:
          name: "deploy_sv_runbook_for_upgrade"
          deploy_version: << pipeline.parameters.base-version >>
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "ciupgrade"
          send_deployment_notification: false
          requires:
            - deploy_cluster_for_upgrade
      - preflight_sv_check:
           name: "preflight_sv_check_initial"
           <<: *main-branch-only
           cluster_version: << pipeline.parameters.base-version >>
           context:
             - artifactory
             - canton-network-vpn
             - slack-context
           cluster: "ciupgrade"
           requires:
             - deploy_cluster_for_upgrade
      - deploy_validator_runbook:
          name: "deploy_validator_runbook_for_upgrade"
          deploy_version: << pipeline.parameters.base-version >>
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          cluster: "ciupgrade"
          requires:
            - deploy_cluster_for_upgrade
      - preflight_validator_check:
          name: "preflight_validator_initial"
          <<: *main-branch-only
          cluster_version: << pipeline.parameters.base-version >>
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciupgrade"
          requires:
            - deploy_cluster_for_upgrade
      - docker_images_push:
          <<: *notify-fail
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          requires:
            - wait_for_previous_pipeline
      - deploy_partial_upgrade:
          name: "deploy_partial_upgrade"
          cluster: "ciupgrade"
          context:
            - artifactory
            - slack-context
          <<: *main-branch-only
          run: << pipeline.parameters.run-partial-upgrade >>
          requires:
            - docker_images_push
            - preflight_check_initial
            - preflight_sv_check_initial
            - preflight_validator_initial
      - preflight_check:
          name: "preflight_check_partial_upgrade"
          <<: *main-branch-only
          cluster_version: << pipeline.parameters.base-version >> # the /version endpoint is not served by sv1 nor validator1
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciupgrade"
          run: << pipeline.parameters.run-partial-upgrade >>
          wait_for_sv: false
          parallelism: 1
          requires:
            - deploy_partial_upgrade
      - preflight_sv_check:
          name: "preflight_sv_check_partial_upgrade"
          <<: *main-branch-only
          cluster_version: << pipeline.parameters.base-version >>
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciupgrade"
          run: << pipeline.parameters.run-partial-upgrade >>
          requires:
            - deploy_partial_upgrade
      - preflight_validator_check:
          name: "preflight_validator_partial_upgrade"
          <<: *main-branch-only
          cluster_version: << pipeline.parameters.base-version >>
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciupgrade"
          run: << pipeline.parameters.run-partial-upgrade >>
          requires:
            - deploy_partial_upgrade
      - deploy_cluster:
          name: "deploy_final_upgrade"
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          cluster: "ciupgrade"
          reset_cluster: false
          send_deployment_notification: false
          update_deployment_branch: false
          cancel_workflow_on_failure: true
          requires:
            - preflight_check_partial_upgrade
            - preflight_sv_check_partial_upgrade
            - preflight_validator_partial_upgrade
      - preflight_check:
          name: "preflight_check_final_upgrade"
          <<: *main-branch-only
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciupgrade"
          wait_for_sv: false
          parallelism: 1
          requires:
            - deploy_final_upgrade
      - preflight_check:
          name: "preflight_daml_upgrade"
          <<: *main-branch-only
          run: << pipeline.parameters.run-daml-upgrade >>
          test_names_file: "test-daml-ciupgrade-vote.log"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciupgrade"
          wait_for_sv: false
          parallelism: 1
          requires:
            - preflight_check_final_upgrade
      # the deployment of both SV runbook and validator runbook should be finished
      # before the daml upgrade vote is effective
      - deploy_sv_runbook:
          name: "upgrade_sv_runbook_after_daml_upgrade"
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "ciupgrade"
          send_deployment_notification: false
          requires:
            - preflight_daml_upgrade
      - deploy_validator_runbook:
          name: "upgrade_validator_runbook_after_daml_upgrade"
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          cluster: "ciupgrade"
          requires:
            - preflight_daml_upgrade
      - wait_for_daml_upgrade:
          name: "wait_for_daml_upgrade"
          <<: *main-branch-only
          context:
            - canton-network-vpn
          run: << pipeline.parameters.run-daml-upgrade >>
          cluster: "ciupgrade"
          requires:
            - preflight_daml_upgrade
      - preflight_check:
          name: "preflight_after_daml_upgrade"
          <<: *main-branch-only
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciupgrade"
          wait_for_sv: false
          parallelism: 1
          requires:
            - wait_for_daml_upgrade
      - preflight_sv_check:
          name: "preflight_sv_check_after_sv_upgrade"
          <<: *main-branch-only
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciupgrade"
          requires:
            - wait_for_daml_upgrade
      - preflight_validator_check:
          name: "preflight_validator_runbook_after_upgrade"
          <<: *main-branch-only
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciupgrade"
          requires:
            - wait_for_daml_upgrade
      - deploy_sv_runbook:
          name: "redeploy_sv_runbook_after_daml_upgrade"
          # by resetting the SV runbook, it's as if a new SV was onboarded,
          # thus testing that SVs joining after an upgrade also work
          reset_cluster: true
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "ciupgrade"
          send_deployment_notification: false
          requires:
            - wait_for_daml_upgrade
            - preflight_sv_check_after_sv_upgrade
            - preflight_validator_runbook_after_upgrade
      - deploy_validator_runbook:
          name: "redeploy_validator_runbook_after_daml_upgrade"
          # by resetting the Validator runbook, it's as if a new Validator was onboarded,
          # thus testing that Validators joining after an upgrade also work
          reset_cluster: true
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          cluster: "ciupgrade"
          requires:
            - wait_for_daml_upgrade
            - preflight_sv_check_after_sv_upgrade
            - preflight_validator_runbook_after_upgrade
      - preflight_sv_check:
          name: "preflight_sv_check_after_sv_redeploy"
          <<: *main-branch-only
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciupgrade"
          requires:
            - redeploy_sv_runbook_after_daml_upgrade
      - preflight_validator_check:
          name: "preflight_validator_runbook_after_redeploy"
          <<: *main-branch-only
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciupgrade"
          requires:
            - redeploy_validator_runbook_after_daml_upgrade
