workflow:
  deploy_ciupgrade:
    when:
      equal: [ build, << pipeline.parameters.run-job >> ]
    jobs:
      - cancel_if_current_commit_is_base_version:
          <<: *main-branch-only
      - wait_for_previous_pipeline:
          <<: *notify-fail
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          workflow_names: "deploy_ciupgrade"
          requires:
            - cancel_if_current_commit_is_base_version
      - deploy_cluster:
          name: "deploy_cluster_for_migration"
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          cluster: "ciupgrade"
          send_deployment_notification: false
          update_deployment_branch: false  # No need to create a deployment branch for ciupgrade
          cancel_workflow_on_failure: true
          deploy_version: "$LATEST_BASE_VERSION"
          requires:
            - wait_for_previous_pipeline
      - preflight_check:
          name: "preflight_check_initial"
          <<: *main-branch-only
          get_snapshot_version_override: "latest_base"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciupgrade"
          wait_for_sv: false
          parallelism: 1
          requires:
            - wait_for_previous_pipeline
      - deploy_sv_runbook:
          name: "deploy_sv_runbook_for_migration"
          deploy_version: "$LATEST_BASE_VERSION"
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "ciupgrade"
          send_deployment_notification: false
          requires:
            - deploy_cluster_for_migration
      - preflight_sv_check:
           name: "preflight_sv_check_initial"
           <<: *main-branch-only
           get_snapshot_version_override: "latest_base"
           context:
             - artifactory
             - canton-network-vpn
             - slack-context
           cluster: "ciupgrade"
           requires:
             - deploy_cluster_for_migration
      - deploy_validator_runbook:
          name: "deploy_validator_runbook_for_migration"
          deploy_version: "$LATEST_BASE_VERSION"
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          cluster: "ciupgrade"
          requires:
            - deploy_cluster_for_migration
      - preflight_validator_check:
          name: "preflight_validator_initial"
          <<: *main-branch-only
          get_snapshot_version_override: "latest_base"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciupgrade"
          requires:
            - deploy_cluster_for_migration
      - docker_images_push:
          <<: *notify-fail
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          requires:
            - wait_for_previous_pipeline
      - deploy_partial_upgrade:
          name: "deploy_partial_upgrade"
          cluster: "ciupgrade"
          context:
            - artifactory
            - slack-context
          <<: *main-branch-only
          requires:
            - docker_images_push
            - preflight_check_initial
            - preflight_sv_check_initial
            - preflight_validator_initial
      - preflight_check:
          name: "preflight_check_partial_upgrade"
          <<: *main-branch-only
          get_snapshot_version_override: "latest_base" # the /version endpoint is not served by sv1 nor validator1
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciupgrade"
          wait_for_sv: false
          parallelism: 1
          requires:
            - deploy_partial_upgrade
      - preflight_sv_check:
          name: "preflight_sv_check_partial_upgrade"
          <<: *main-branch-only
          get_snapshot_version_override: "latest_base"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciupgrade"
          requires:
            - deploy_partial_upgrade
      - preflight_validator_check:
          name: "preflight_validator_partial_upgrade"
          <<: *main-branch-only
          get_snapshot_version_override: "latest_base"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciupgrade"
          requires:
            - deploy_partial_upgrade
      - deploy_cluster:
          name: "deploy_final_upgrade"
          <<: *main-branch-only
          context:
            - artifactory
            - slack-context
          cluster: "ciupgrade"
          reset_cluster: false
          send_deployment_notification: false
          update_deployment_branch: false
          cancel_workflow_on_failure: true
          requires:
            - preflight_check_partial_upgrade
            - preflight_sv_check_partial_upgrade
            - preflight_validator_partial_upgrade
      - preflight_check:
          name: "preflight_check_final_upgrade"
          <<: *main-branch-only
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciupgrade"
          wait_for_sv: false
          parallelism: 1
          requires:
            - deploy_final_upgrade
      - preflight_sv_check:
          name: "preflight_sv_check_final_upgrade"
          <<: *main-branch-only
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciupgrade"
          requires:
            - deploy_final_upgrade
      - preflight_validator_check:
          name: "preflight_validator_final_upgrade"
          <<: *main-branch-only
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "ciupgrade"
          requires:
            - deploy_final_upgrade
# TODO (#9917): these steps (roughly) are needed for a domain migration test.
#      - backup_cluster:
#          name: "backup_cluster_before_migration"
#          <<: *main-branch-only
#          cluster: "ciupgrade"
#          context:
#            - artifactory
#            - canton-network-vpn
#            - slack-context
#          requires:
#            - deploy_cluster_for_migration
#            - deploy_sv_runbook_for_migration
#            - deploy_validator_runbook_for_migration
#      - preflight_check:
#          name: "trigger_global_domain_migration"
#          <<: *main-branch-only
#          context:
#            - artifactory
#            - canton-network-vpn
#            - slack-context
#          cluster: "ciupgrade"
#          test_names_file: "test-full-class-names-global-domain-upgrade-preflight.log"
#          parallelism: 1
#          wait_for_sv: false
#          requires:
#            - preflight_check
#            - preflight_sv_check_initial
#            - preflight_validator_initial
#            - backup_cluster_before_migration
#      - deploy_cluster:
#          name: "prepare_cluster_for_migration"
#          <<: *main-branch-only
#          context:
#            - artifactory
#            - slack-context
#          cluster: "ciupgrade"
#          send_deployment_notification: false
#          update_deployment_branch: false  # No need to create a deployment branch for ciupgrade
#          cancel_workflow_on_failure: true
#          reset_cluster: false
#          global_domain_active_migration_id: 0
#          global_domain_upgrade_migration_id: 1
#          requires:
#            - deploy_cluster_for_migration
#      - deploy_sv_runbook:
#          name: "prepare_sv_runbook_for_migration"
#          <<: *main-branch-only
#          context:
#            - artifactory
#            - slack-context
#            - canton-network-vpn
#          cluster: "ciupgrade"
#          send_deployment_notification: false
#          requires:
#            - deploy_sv_runbook_for_migration
#          global_domain_active_migration_id: 0
#          global_domain_upgrade_migration_id: 1
#          reset_cluster: false
#      - deploy_cluster:
#          name: "migrate_cluster"
#          <<: *main-branch-only
#          context:
#            - artifactory
#            - slack-context
#          cluster: "ciupgrade"
#          send_deployment_notification: false
#          update_deployment_branch: false
#          global_domain_active_migration_id: 1
#          global_domain_migrate_from_id: 0
#          global_domain_legacy_migration_id: 0
#          requires:
#            - trigger_global_domain_migration
#            - prepare_cluster_for_migration
#      - preflight_check:
#          name: "preflight_check_migrated"
#          <<: *main-branch-only
#          context:
#            - artifactory
#            - canton-network-vpn
#            - slack-context
#          cluster: "ciupgrade"
#          migration_id: 1
#          requires:
#            - trigger_global_domain_migration
#      - deploy_sv_runbook:
#          name: "migrate_sv_runbook"
#          <<: *main-branch-only
#          context:
#            - artifactory
#            - slack-context
#            - canton-network-vpn
#          cluster: "ciupgrade"
#          send_deployment_notification: false
#          requires:
#            - trigger_global_domain_migration
#            - prepare_sv_runbook_for_migration
#          global_domain_active_migration_id: 1
#          global_domain_migrate_from_id: 0
#          global_domain_legacy_migration_id: 0
#          reset_cluster: false
#      - preflight_sv_check:
#          name: "preflight_sv_check_migrated"
#          migration_id: 1
#          <<: *main-branch-only
#          context:
#            - artifactory
#            - canton-network-vpn
#            - slack-context
#          cluster: "ciupgrade"
#          requires:
#            - trigger_global_domain_migration
#      - deploy_validator_runbook:
#          name: "migrate_validator_runbook"
#          <<: *main-branch-only
#          context:
#            - artifactory
#            - slack-context
#          cluster: "ciupgrade"
#          global_domain_active_migration_id: 1
#          global_domain_migrate_from_id: 0
#          reset_cluster: false
#          requires:
#            - trigger_global_domain_migration
#      - preflight_validator_check:
#          <<: *main-branch-only
#          name: "preflight_validator_check_migrated"
#          migration_id: 1
#          context:
#            - artifactory
#            - canton-network-vpn
#            - slack-context
#          cluster: "ciupgrade"
#          requires:
#            - trigger_global_domain_migration
#      - restore_node:
#          <<: *main-branch-only
#          cluster: "ciupgrade"
#          namespace_name: "sv-3"
#          expected_migration_id: 1
#          context:
#            - artifactory
#            - canton-network-vpn
#            - slack-context
#          requires:
#            - preflight_sv_check_migrated
#            - preflight_validator_check_migrated
#            - preflight_check_migrated
