
  deploy_scratchnet:
    when:
      equal: [ build, << pipeline.parameters.run-job >> ]
    jobs:
      - hold_scratchnet:
          <<: *main-branch-never
          name: use_scratchneta
          type: approval
      - release_hold_set_scratchnet:
          requires:
            - use_scratchneta
      - hold_scratchnet:
          <<: *main-branch-never
          name: use_scratchnetb
          type: approval
      - release_hold_set_scratchnet:
          requires:
            - use_scratchnetb
      - hold_scratchnet:
          <<: *main-branch-never
          name: use_scratchnetc
          type: approval
      - release_hold_set_scratchnet:
          requires:
            - use_scratchnetc
      - hold_scratchnet:
          <<: *main-branch-never
          name: use_scratchnetd
          type: approval
      - release_hold_set_scratchnet:
          requires:
            - use_scratchnetd
      - hold_scratchnet:
          <<: *main-branch-never
          name: use_scratchnete
          type: approval
      - release_hold_set_scratchnet:
          requires:
            - use_scratchnete
      - hold_set_scratchnet:
          <<: *main-branch-never
          type: approval
      - set_scratchnet:
          <<: *main-branch-never
          requires:
            - hold_set_scratchnet
      - artifacts_push:
          <<: *main-branch-never
          context:
            - artifactory
            - slack-context
          requires:
            - set_scratchnet
      - deploy_cluster:
          name: "deploy_cluster_for_migration"
          <<: *main-branch-never
          context:
            - artifactory
            - slack-context
          cluster: "user-selected-scratchnet"
          # deployment/scratchnet* branches break the workflow links from Github to CircleCI.
          # So we want to avoid creating them.
          update_deployment_branch: false
          cancel_workflow_on_failure: true
          requires:
            - set_scratchnet
            - artifacts_push
      - preflight_check:
          name: "preflight_check_core"
          <<: *main-branch-never
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "user-selected-scratchnet"
          wait_for_sv: false
          parallelism: 1
          requires:
            - artifacts_push
            - set_scratchnet
      - deploy_sv_runbook:
          name: "deploy_sv_runbook_for_migration"
          <<: *main-branch-never
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "user-selected-scratchnet"
          requires:
            - deploy_cluster_for_migration
      - preflight_sv_check:
           name: "preflight_sv_check_before_migration"
           <<: *main-branch-never
           context:
             - artifactory
             - canton-network-vpn
             - slack-context
           cluster: "user-selected-scratchnet"
           requires:
             - deploy_cluster_for_migration
      - deploy_validator_runbook:
          name: "deploy_validator_runbook_for_migration"
          <<: *main-branch-never
          context:
            - artifactory
            - slack-context
          cluster: "user-selected-scratchnet"
          requires:
            - deploy_cluster_for_migration
      - preflight_validator_check:
          name: "preflight_validator_check_before_migration"
          <<: *main-branch-never
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "user-selected-scratchnet"
          requires:
            - deploy_cluster_for_migration
      - backup_cluster:
          name: "backup_cluster_before_migration"
          <<: *main-branch-never
          cluster: "user-selected-scratchnet"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          requires:
            - deploy_cluster_for_migration
            - deploy_sv_runbook_for_migration
            - deploy_validator_runbook_for_migration
      - deploy_cluster:
          name: "prepare_cluster_for_migration"
          <<: *main-branch-never
          context:
            - artifactory
            - slack-context
          cluster: "user-selected-scratchnet"
          # deployment/scratchnet* branches break the workflow links from Github to CircleCI.
          # So we want to avoid creating them.
          update_deployment_branch: false
          global_domain_active_migration_id: 0
          global_domain_upgrade_migration_id: 1
          reset_cluster: false
          requires:
            - deploy_cluster_for_migration
      - deploy_sv_runbook:
          name: "prepare_sv_runbook_for_migration"
          <<: *main-branch-never
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "user-selected-scratchnet"
          requires:
            - deploy_sv_runbook_for_migration
          global_domain_active_migration_id: 0
          global_domain_upgrade_migration_id: 1
          reset_cluster: false
      - preflight_check:
          name: "trigger_global_domain_migration"
          <<: *main-branch-never
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "user-selected-scratchnet"
          test_names_file: "test-full-class-names-global-domain-upgrade-preflight.log"
          parallelism: 1
          wait_for_sv: false
          requires:
            - preflight_check_core
            - preflight_sv_check_before_migration
            - preflight_validator_check_before_migration
            - backup_cluster_before_migration
      - deploy_cluster:
          name: "migrate_cluster"
          <<: *main-branch-never
          context:
            - artifactory
            - slack-context
          cluster: "user-selected-scratchnet"
          # deployment/scratchnet* branches break the workflow links from Github to CircleCI.
          # So we want to avoid creating them.
          update_deployment_branch: false
          global_domain_active_migration_id: 1
          global_domain_migrate_from_id: 0
          global_domain_legacy_migration_id: 0
          requires:
            - trigger_global_domain_migration
            - prepare_cluster_for_migration
      - preflight_check:
          name: "preflight_check_migrated"
          <<: *main-branch-never
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "user-selected-scratchnet"
          migration_id: 1
          parallelism: 1
          requires:
            - trigger_global_domain_migration
      - deploy_sv_runbook:
          name: "migrate_sv_runbook"
          <<: *main-branch-never
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "user-selected-scratchnet"
          requires:
            - trigger_global_domain_migration
            - prepare_sv_runbook_for_migration
          global_domain_active_migration_id: 1
          global_domain_migrate_from_id: 0
          global_domain_legacy_migration_id: 0
          reset_cluster: false
      - preflight_sv_check:
          name: "preflight_sv_check_migrated"
          migration_id: 1
          <<: *main-branch-never
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "user-selected-scratchnet"
          requires:
            - trigger_global_domain_migration
      - deploy_validator_runbook:
          name: "migrate_validator_runbook"
          <<: *main-branch-never
          context:
            - artifactory
            - slack-context
          cluster: "user-selected-scratchnet"
          global_domain_active_migration_id: 1
          global_domain_migrate_from_id: 0
          reset_cluster: false
          requires:
            - trigger_global_domain_migration
      - preflight_validator_check:
          name: "preflight_validator_check_migrated"
          migration_id: 1
          <<: *main-branch-never
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "user-selected-scratchnet"
          requires:
            - trigger_global_domain_migration
      - restore_node:
          name: "restore_node_after_migration"
          <<: *main-branch-never
          cluster: "user-selected-scratchnet"
          namespace_name: "sv-3"
          expected_migration_id: 1
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          requires:
            - preflight_sv_check_migrated
            - preflight_validator_check_migrated
            - preflight_check_migrated
      - reset_cluster:
          <<: *main-branch-never
          cluster: "user-selected-scratchnet"
          context:
            - canton-network-vpn
          requires:
            - restore_node_after_migration
            - preflight_sv_check_migrated
            - preflight_validator_check_migrated
            - preflight_check_migrated
            - migrate_sv_runbook
            - migrate_validator_runbook

  # Simple deployment with no migration
  deploy_scratchnet_basic:
    when:
      equal: [ build, << pipeline.parameters.run-job >> ]
    jobs:
      - hold_scratchnet:
          <<: *main-branch-never
          name: use_scratchneta
          type: approval
      - release_hold_set_scratchnet:
          requires:
            - use_scratchneta
      - hold_scratchnet:
          <<: *main-branch-never
          name: use_scratchnetb
          type: approval
      - release_hold_set_scratchnet:
          requires:
            - use_scratchnetb
      - hold_scratchnet:
          <<: *main-branch-never
          name: use_scratchnetc
          type: approval
      - release_hold_set_scratchnet:
          requires:
            - use_scratchnetc
      - hold_scratchnet:
          <<: *main-branch-never
          name: use_scratchnetd
          type: approval
      - release_hold_set_scratchnet:
          requires:
            - use_scratchnetd
      - hold_scratchnet:
          <<: *main-branch-never
          name: use_scratchnete
          type: approval
      - release_hold_set_scratchnet:
          requires:
            - use_scratchnete
      - hold_set_scratchnet:
          <<: *main-branch-never
          type: approval
      - set_scratchnet:
          <<: *main-branch-never
          requires:
            - hold_set_scratchnet
      - artifacts_push:
          <<: *main-branch-never
          context:
            - artifactory
            - slack-context
          requires:
            - set_scratchnet
      - deploy_cluster:
          <<: *main-branch-never
          context:
            - artifactory
            - slack-context
          cluster: "user-selected-scratchnet"
          # deployment/scratchnet* branches break the workflow links from Github to CircleCI.
          # So we want to avoid creating them.
          update_deployment_branch: false
          cancel_workflow_on_failure: true
          requires:
            - artifacts_push
            - set_scratchnet
      - preflight_check:
          <<: *main-branch-never
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "user-selected-scratchnet"
          parallelism: 1
          requires:
            - artifacts_push
            - set_scratchnet
      - backup_cluster:
          <<: *main-branch-never
          cluster: "user-selected-scratchnet"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          requires:
            - deploy_cluster
            - deploy_sv_runbook
      - restore_node:
          <<: *main-branch-never
          cluster: "user-selected-scratchnet"
          namespace_name: "sv-3"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          requires:
            - preflight_check
            - preflight_sv_check
            - preflight_validator_check
            - backup_cluster
      - restore_node:
          name: "restore_validator_node"
          <<: *main-branch-never
          cluster: "user-selected-scratchnet"
          namespace_name: "validator1"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          requires:
            - preflight_check
            - preflight_sv_check
            - preflight_validator_check
            - backup_cluster
      - deploy_sv_runbook:
          <<: *main-branch-never
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "user-selected-scratchnet"
          requires:
            - deploy_cluster
      - preflight_sv_check:
           <<: *main-branch-never
           context:
             - artifactory
             - canton-network-vpn
             - slack-context
           cluster: "user-selected-scratchnet"
           requires:
             - deploy_cluster
      - deploy_validator_runbook:
          <<: *main-branch-never
          context:
            - artifactory
            - slack-context
          cluster: "user-selected-scratchnet"
          requires:
            - deploy_cluster
      - preflight_validator_check:
          <<: *main-branch-never
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "user-selected-scratchnet"
          requires:
            - deploy_cluster
      - reset_cluster:
          <<: *main-branch-never
          cluster: "user-selected-scratchnet"
          context:
            - canton-network-vpn
          requires:
            - preflight_validator_check
            - preflight_sv_check
            - restore_node


  deploy_scratchnet_DR:
    when:
      equal: [ build, << pipeline.parameters.run-job >> ]
    jobs:
      - hold_scratchnet:
          <<: *main-branch-never
          name: use_scratchneta
          type: approval
      - release_hold_set_scratchnet:
          requires:
            - use_scratchneta
      - hold_scratchnet:
          <<: *main-branch-never
          name: use_scratchnetb
          type: approval
      - release_hold_set_scratchnet:
          requires:
            - use_scratchnetb
      - hold_scratchnet:
          <<: *main-branch-never
          name: use_scratchnetc
          type: approval
      - release_hold_set_scratchnet:
          requires:
            - use_scratchnetc
      - hold_scratchnet:
          <<: *main-branch-never
          name: use_scratchnetd
          type: approval
      - release_hold_set_scratchnet:
          requires:
            - use_scratchnetd
      - hold_scratchnet:
          <<: *main-branch-never
          name: use_scratchnete
          type: approval
      - release_hold_set_scratchnet:
          requires:
            - use_scratchnete
      - hold_set_scratchnet:
          <<: *main-branch-never
          type: approval
      - set_scratchnet:
          <<: *main-branch-never
          requires:
            - hold_set_scratchnet
      - artifacts_push:
          <<: *main-branch-never
          context:
            - artifactory
            - slack-context
          requires:
            - set_scratchnet
      - test_DR:
          <<: *main-branch-never
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "user-selected-scratchnet"
          requires:
            - artifacts_push
            - set_scratchnet
      - preflight_check:
          name: preflight_check_DR
          <<: *main-branch-never
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "user-selected-scratchnet"
          migration_id: 1
          parallelism: 1
          requires:
            - test_DR
      - deploy_sv_runbook:
          name: deploy_sv_runbook_DR
          global_domain_active_migration_id: 1
          <<: *main-branch-never
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "user-selected-scratchnet"
          requires:
            - test_DR
      - preflight_sv_check:
          name: preflight_sv_check_DR
          <<: *main-branch-never
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "user-selected-scratchnet"
          migration_id: 1
          requires:
            - test_DR
      - deploy_validator_runbook:
          name: deploy_validator_runbook_DR
          global_domain_active_migration_id: 1
          <<: *main-branch-never
          context:
            - artifactory
            - slack-context
          cluster: "user-selected-scratchnet"
          requires:
            - test_DR
      - preflight_validator_check:
          name: preflight_validator_check_DR
          <<: *main-branch-never
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: "user-selected-scratchnet"
          migration_id: 1
          requires:
            - test_DR
      - reset_cluster:
          name: reset_cluster_DR
          <<: *main-branch-never
          cluster: "user-selected-scratchnet"
          context:
            - canton-network-vpn
          requires:
            - preflight_check_DR
            - preflight_sv_check_DR
            - preflight_validator_check_DR
            - deploy_validator_runbook_DR
            - deploy_sv_runbook_DR
