workflow:
  determine_ciupgrade_work:
    when:
      equal: [ build, << pipeline.parameters.run-job >> ]
    jobs:
      - cancel_if_current_commit_is_base_version:
          <<: *main-branch-only
          context: slack-context
      - launch_ciupgrade_workflow:
          <<: *main-branch-only
          context: slack-context
          requires:
            - cancel_if_current_commit_is_base_version
