workflow:
  devnet_health_check:
    when:
      equal: [ healthcheck-devnet, << pipeline.parameters.run-job >> ]
    jobs:
      - preflight_check:
          filters:
            branches:
              only:
                - /release-line-.*/
          channel_notify: C06SMCCBYQH # #team-canton-network-dev-testnet-deployment
          cluster: "devnet"
          migration_id: 3
          context:
            - artifactory
            - canton-network-vpn
            - slack-context

  reset_sv_runbook_devnet:
    when:
      equal: [ reset-sv-runbook-devnet, << pipeline.parameters.run-job >> ]
    jobs:
      - wait_for_previous_pipeline:
          <<: *notify-fail
          filters:
            branches:
              only:
                - /release-line-.*/
          context:
            - artifactory
            - slack-context
          workflow_names: "reset_sv_runbook_devnet"
      - reset_sv_runbook:
          filters:
            branches:
              only:
                - /release-line-.*/
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "devnet"
          channel_notify: C06SMCCBYQH # #team-canton-network-dev-testnet-deployment
          requires:
            - wait_for_previous_pipeline

  reset_validator_runbook_devnet:
    when:
      equal: [ reset-validator-runbook-devnet, << pipeline.parameters.run-job >> ]
    jobs:
      - wait_for_previous_pipeline:
          <<: *notify-fail
          filters:
            branches:
              only:
                - /release-line-.*/
          context:
            - artifactory
            - slack-context
          workflow_names: "reset_validator_runbook_devnet"
      - reset_validator_runbook:
          filters:
            branches:
              only:
                - /release-line-.*/
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: "devnet"
          channel_notify: C06SMCCBYQH # #team-canton-network-dev-testnet-deployment
          requires:
            - wait_for_previous_pipeline

  healthcheck_sv_runbook_devnet:
    when:
      equal: [ healthcheck-sv-runbook-devnet, << pipeline.parameters.run-job >> ]
    jobs:
      - wait_for_previous_pipeline:
          <<: *notify-fail
          filters:
            branches:
              only:
                - /release-line-.*/
          context:
            - artifactory
            - slack-context
          workflow_names: "healthcheck_sv_runbook_devnet reset_sv_runbook_devnet"
      - preflight_sv_check:
          filters:
            branches:
              only:
                - /release-line-.*/
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          channel_notify: C06SMCCBYQH # #team-canton-network-dev-testnet-deployment
          cluster: "devnet"
          migration_id: 3
          requires:
            - wait_for_previous_pipeline

  healthcheck_validator_runbook_devnet:
    when:
      equal: [ healthcheck-validator-runbook-devnet, << pipeline.parameters.run-job >> ]
    jobs:
      - wait_for_previous_pipeline:
          <<: *notify-fail
          filters:
            branches:
              only:
                - /release-line-.*/
          context:
            - artifactory
            - slack-context
          workflow_names: "healthcheck_validator_runbook_devnet reset_validator_runbook_devnet"
      - preflight_validator_check:
          filters:
            branches:
              only:
                - /release-line-.*/
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          channel_notify: C06SMCCBYQH # #team-canton-network-dev-testnet-deployment
          cluster: "devnet"
          migration_id: 3
          requires:
            - wait_for_previous_pipeline

  backup_devnet:
    when:
      equal: [ backup-devnet, << pipeline.parameters.run-job >> ]
    jobs:
      - backup_cluster:
          filters:
            branches:
              only:
                - /release-line-.*/
          channel_notify: C06SMCCBYQH # #team-canton-network-dev-testnet-deployment
          cluster: "devnet"
          migration_id: 3
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
