workflow:
  devnet_health_check:
    when:
      equal: [ healthcheck-devnet, << pipeline.parameters.run-job >> ]
    jobs:
      - cancel_if_previous_pipeline:
          <<: *notify-fail
          filters:
            branches:
              only:
                - deployment/devnet
          context:
            - artifactory
            - slack-context
          # Cancel health check if any deploy is running as it's redundant to run it (they are run as part of the deployment)
          # It doesn't make sense to run it as there are high chances that the old version pre-flights will fail on the new deployment
          workflow_names: "deploy_devnet"
      - preflight_check:
          filters:
            branches:
              only:
                - deployment/devnet
          channel_notify: C06SMCCBYQH # #team-canton-network-dev-testnet-deployment
          cluster: "devnet"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          requires:
            - cancel_if_previous_pipeline

  redeploy_sv_runbook_devnet:
    when:
      equal: [ redeploy-sv-runbook-devnet, << pipeline.parameters.run-job >> ]
    jobs:
      - wait_for_previous_pipeline:
          <<: *notify-fail
          filters:
            branches:
              only:
                - deployment/devnet
          context:
            - artifactory
            - slack-context
          workflow_names: "deploy_devnet redeploy_sv_runbook_devnet devnet_health_check"
      - cancel_if_previous_pipeline:
          <<: *notify-fail
          filters:
            branches:
              only:
                - deployment/devnet
          context:
            - artifactory
            - slack-context
          # Cancel runbook deployment if any deploy is running as it will try to deploy an old version
          # because the branch is not yet updated.
          workflow_names: "deploy_devnet"
      - artifacts_push:
          <<: *notify-fail
          context:
            - artifactory
            - slack-context
          skip_if_exists: true
      - deploy_sv_runbook:
          filters:
            branches:
              only:
                - deployment/devnet
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          channel_notify: C06SMCCBYQH # #team-canton-network-dev-testnet-deployment
          cluster: "devnet"
          use_published_artifacts: false
          requires:
            - wait_for_previous_pipeline
            - artifacts_push
      - preflight_sv_check:
          filters:
            branches:
              only:
                - deployment/devnet
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          channel_notify: C06SMCCBYQH # #team-canton-network-dev-testnet-deployment
          cluster: "devnet"
          requires:
            - deploy_sv_runbook

  redeploy_validator_runbook_devnet:
    when:
      equal: [ redeploy-validator-runbook-devnet, << pipeline.parameters.run-job >> ]
    jobs:
      - wait_for_previous_pipeline:
          <<: *notify-fail
          filters:
            branches:
              only:
                - deployment/devnet
          context:
            - artifactory
            - slack-context
          workflow_names: "deploy_devnet redeploy_validator_runbook_devnet"
      - cancel_if_previous_pipeline:
          <<: *notify-fail
          filters:
            branches:
              only:
                - deployment/devnet
          context:
            - artifactory
            - slack-context
          # Cancel runbook deployment if any deploy is running as it will try to deploy an old version
          # because the branch is not yet updated.
          workflow_names: "deploy_devnet"
      - artifacts_push:
          <<: *notify-fail
          context:
            - artifactory
            - slack-context
          skip_if_exists: true
      - deploy_validator_runbook:
          filters:
            branches:
              only:
                - deployment/devnet
          context:
            - artifactory
            - slack-context
          channel_notify: C06SMCCBYQH # #team-canton-network-dev-testnet-deployment
          cluster: "devnet"
          use_published_artifacts: false
          requires:
            - wait_for_previous_pipeline
            - artifacts_push
      - preflight_validator_check:
          filters:
            branches:
              only:
                - deployment/devnet
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          channel_notify: C06SMCCBYQH # #team-canton-network-dev-testnet-deployment
          cluster: "devnet"
          delay_mins: 30
          requires:
            - deploy_validator_runbook

  backup_devnet:
    when:
      equal: [ backup-devnet, << pipeline.parameters.run-job >> ]
    jobs:
      - wait_for_previous_pipeline:
          <<: *notify-fail
          filters:
            branches:
              only:
                - deployment/devnet
          context:
            - artifactory
            - slack-context
          workflow_names: "deploy_devnet"
      - backup_cluster:
          filters:
            branches:
              only:
                - deployment/devnet
          channel_notify: C06SMCCBYQH # #team-canton-network-dev-testnet-deployment
          cluster: "devnet"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          requires:
            - wait_for_previous_pipeline
