workflow:
  apply_infra:
    when:
      equal: [ apply-infra, << pipeline.parameters.run-job >> ]
    jobs:
      - deploy_infra:
          context:
            - artifactory
            - slack-context
          cluster: << pipeline.parameters.cluster >>
