workflow:
  backup_mainnet:
    when:
      equal: [ backup-mainnet, << pipeline.parameters.run-job >> ]
    jobs:
      - backup_cluster:
          filters:
            branches:
              only:
                - /release-line-.*/
          include_splitwell: false
          include_validator1: false
          channel_notify: C0731SHS3HB # #team-canton-network-mainnet-deployment
          cluster: "mainnet"
          internal_stack: false
          parallelism: 1
          context:
            - artifactory
            - canton-network-vpn
            - slack-context

  backup_status_mainnet:
    when:
      equal: [ backup-status-mainnet, << pipeline.parameters.run-job >> ]
    jobs:
      - backup_status_cluster:
          cluster: "mainnet"
          channel_notify: C0731SHS3HB # #team-canton-network-mainnet-deployment
          alert_threshold: "4 hours ago"
          context:
            - slack-context
            - canton-network-vpn

  copy_mainnet_backup_to_bucket:
    when:
      equal: [ copy-mainnet-backup-to-bucket, << pipeline.parameters.run-job >> ]
    jobs:
      - copy_backup_to_bucket:
          cluster: "mainnet-old"
          before-date: << pipeline.parameters.before-date >>
          channel_notify: C0731SHS3HB # #team-canton-network-mainnet-deployment
          context:
            - slack-context
