workflow:
  backup_mainnet:
    when:
      equal: [ backup-mainnet, << pipeline.parameters.run-job >> ]
    jobs:
      - backup_cluster:
          filters:
            branches:
              only:
                - deployment/mainnet
          include_splitwell: false
          include_validator1: false
          channel_notify: C0731SHS3HB # #team-canton-network-mainnet-deployment
          cluster: "mainnet"
          parallelism: 1
          migration_id: << pipeline.parameters.migration-id >>
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
