workflow:
  redeploy_operator:
    when:
      equal: [ deploy-operator, << pipeline.parameters.run-job >> ]
    jobs:
      - deploy_operator:
          context:
            - artifactory
            - slack-context
          cluster: << pipeline.parameters.cluster >>

