workflow:
  backup_testnet:
    when:
      equal: [ backup-testnet, << pipeline.parameters.run-job >> ]
    jobs:
      - backup_cluster:
          filters:
            branches:
              only:
                - /release-line-.*/
          channel_notify: C06SMCCBYQH # #team-canton-network-dev-testnet-deployment
          cluster: "testnet"
          migration_id: 0
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
