workflow:
  deploy_upgrade:
    # the parameters run-job, run-partial-upgrade and base-version are set in launch_ciupgrade_workflow
    when:
      equal: [ deploy-upgrade, << pipeline.parameters.run-job >> ]
    jobs:
      - wait_for_previous_pipeline:
          <<: *notify-fail
          context:
            - artifactory
            - slack-context
          workflow_names: "deploy_upgrade"
          wait_type: "cancel_waiting_and_wait_workflow"
          branch_filter: << pipeline.parameters.branch-filter >>
      - autoscaler_prevent_scaledown:
          cluster: << pipeline.parameters.cluster >>
          requires:
            - wait_for_previous_pipeline
      - reset_cluster:
          # note that this reset is executed on the latest version to properly cleanup previous deploy_ciupgrade runs
          name: reset_cluster
          cluster: << pipeline.parameters.cluster >>
          unlock_shared_cluster: false
          silence_deployment_alerts: true
          context:
            - canton-network-vpn
            - slack-context
          requires:
            - wait_for_previous_pipeline
      - deploy_cluster:
          name: "deploy_cluster_for_upgrade"
          context:
            - artifactory
            - slack-context
          cluster: << pipeline.parameters.cluster >>
          reset_cluster: false # done in reset_cluster job
          skip_infra: true # we need to skip infra because it can lead to issues if it was updated... see #12005
          update_deployment_branch: false  # No need to create a deployment branch for ciupgrade
          cancel_workflow_on_failure: true
          deploy_version: << pipeline.parameters.base-version >>
          run_upgrade_workarounds: true
          requires:
            - reset_cluster
      - preflight_check:
          name: "preflight_check_initial"
          cluster_version: << pipeline.parameters.base-version >>
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: << pipeline.parameters.cluster >>
          wait_for_sv: false
          requires:
            - reset_cluster
      - deploy_sv_runbook:
          name: "deploy_sv_runbook_for_upgrade"
          reset_cluster: false
          deploy_version: << pipeline.parameters.base-version >>
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: << pipeline.parameters.cluster >>
          run_upgrade_workarounds: true
          requires:
            - deploy_cluster_for_upgrade
      - preflight_sv_check:
           name: "preflight_sv_check_initial"
           cluster_version: << pipeline.parameters.base-version >>
           context:
             - artifactory
             - canton-network-vpn
             - slack-context
           cluster: << pipeline.parameters.cluster >>
           requires:
             - deploy_cluster_for_upgrade
      - deploy_validator_runbook:
          name: "deploy_validator_runbook_for_upgrade"
          reset_cluster: false
          deploy_version: << pipeline.parameters.base-version >>
          context:
            - artifactory
            - slack-context
          cluster: << pipeline.parameters.cluster >>
          run_upgrade_workarounds: true
          requires:
            - deploy_cluster_for_upgrade
      - preflight_validator_check:
          name: "preflight_validator_initial"
          cluster_version: << pipeline.parameters.base-version >>
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: << pipeline.parameters.cluster >>
          requires:
            - deploy_cluster_for_upgrade
      - artifacts_push:
          <<: *notify-fail
          context:
            - artifactory
            - slack-context
          requires:
            - wait_for_previous_pipeline
      - deploy_partial_upgrade:
          name: "deploy_partial_upgrade"
          cluster: << pipeline.parameters.cluster >>
          context:
            - artifactory
            - slack-context
          run: << pipeline.parameters.run-partial-upgrade >>
          silence_deployment_alerts: true
          requires:
            - artifacts_push
            - preflight_check_initial
            - preflight_sv_check_initial
            - preflight_validator_initial
      - preflight_check:
          name: "preflight_check_partial_upgrade"
          cluster_version: << pipeline.parameters.base-version >>
          check_cluster_version: false # we want to run the preflight in base version, but the version is reported as upgraded
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: << pipeline.parameters.cluster >>
          run: << pipeline.parameters.run-partial-upgrade >>
          wait_for_sv: false
          requires:
            - deploy_partial_upgrade
      - preflight_sv_check:
          name: "preflight_sv_check_partial_upgrade"
          cluster_version: << pipeline.parameters.base-version >>
          check_cluster_version: false # we want to run the preflight in base version, but the version is reported as upgraded
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: << pipeline.parameters.cluster >>
          run: << pipeline.parameters.run-partial-upgrade >>
          requires:
            - deploy_partial_upgrade
      - preflight_validator_check:
          name: "preflight_validator_partial_upgrade"
          cluster_version: << pipeline.parameters.base-version >>
          check_cluster_version: false # we want to run the preflight in base version, but the version is reported as upgraded
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: << pipeline.parameters.cluster >>
          run: << pipeline.parameters.run-partial-upgrade >>
          requires:
            - deploy_partial_upgrade
      - deploy_cluster:
          name: "deploy_final_upgrade"
          context:
            - artifactory
            - slack-context
          cluster: << pipeline.parameters.cluster >>
          reset_cluster: false
          update_deployment_branch: false
          cancel_workflow_on_failure: true
          requires:
            - preflight_check_partial_upgrade
            - preflight_sv_check_partial_upgrade
            - preflight_validator_partial_upgrade
      - preflight_check:
          name: "preflight_check_final_upgrade"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: << pipeline.parameters.cluster >>
          test_names_file: "test-full-class-names-core-preflight.log,test-full-class-names-validator1-preflight.log,test-full-class-names-docker-compose-validator-preflight.log"
          with_docker: true
          wait_for_sv: false
          requires:
            - deploy_final_upgrade
      - preflight_check:
          name: "preflight_daml_upgrade"
          run: << pipeline.parameters.run-daml-upgrade >>
          test_names_file: "test-daml-ciupgrade-vote.log"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: << pipeline.parameters.cluster >>
          wait_for_sv: false
          requires:
            - preflight_check_final_upgrade
      # the deployment of both SV runbook and validator runbook should be finished
      # before the daml upgrade vote is effective
      - deploy_sv_runbook:
          name: "upgrade_sv_runbook_after_daml_upgrade"
          reset_cluster: false
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: << pipeline.parameters.cluster >>
          requires:
            - preflight_daml_upgrade
      - deploy_validator_runbook:
          name: "upgrade_validator_runbook_after_daml_upgrade"
          reset_cluster: false
          context:
            - artifactory
            - slack-context
          cluster: << pipeline.parameters.cluster >>
          requires:
            - preflight_daml_upgrade
      - wait_for_daml_upgrade:
          name: "wait_for_daml_upgrade"
          context:
            - canton-network-vpn
          run: << pipeline.parameters.run-daml-upgrade >>
          cluster: << pipeline.parameters.cluster >>
          requires:
            - preflight_daml_upgrade
      - preflight_check:
          name: "preflight_after_daml_upgrade"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: << pipeline.parameters.cluster >>
          wait_for_sv: false
          requires:
            - wait_for_daml_upgrade
            - upgrade_sv_runbook_after_daml_upgrade
            - upgrade_validator_runbook_after_daml_upgrade
      - preflight_sv_check:
          name: "preflight_sv_check_after_sv_upgrade"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: << pipeline.parameters.cluster >>
          requires:
            - wait_for_daml_upgrade
            - upgrade_sv_runbook_after_daml_upgrade
            - upgrade_validator_runbook_after_daml_upgrade
      - preflight_validator_check:
          name: "preflight_validator_runbook_after_upgrade"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: << pipeline.parameters.cluster >>
          requires:
            - wait_for_daml_upgrade
            - upgrade_sv_runbook_after_daml_upgrade
            - upgrade_validator_runbook_after_daml_upgrade
      - deploy_sv_runbook:
          name: "redeploy_sv_runbook_after_daml_upgrade"
          # by resetting the SV runbook, it's as if a new SV was onboarded,
          # thus testing that SVs joining after an upgrade also work
          reset_cluster: true
          silence_deployment_alerts: true
          context:
            - artifactory
            - slack-context
            - canton-network-vpn
          cluster: << pipeline.parameters.cluster >>
          requires:
            - wait_for_daml_upgrade
            - preflight_sv_check_after_sv_upgrade
            - preflight_validator_runbook_after_upgrade
      - deploy_validator_runbook:
          name: "redeploy_validator_runbook_after_daml_upgrade"
          # by resetting the Validator runbook, it's as if a new Validator was onboarded,
          # thus testing that Validators joining after an upgrade also work
          reset_cluster: true
          silence_deployment_alerts: true
          context:
            - artifactory
            - slack-context
          cluster: << pipeline.parameters.cluster >>
          requires:
            - wait_for_daml_upgrade
            - preflight_sv_check_after_sv_upgrade
            - preflight_validator_runbook_after_upgrade
      - preflight_sv_check:
          name: "preflight_sv_check_after_sv_redeploy"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: << pipeline.parameters.cluster >>
          requires:
            - redeploy_sv_runbook_after_daml_upgrade
      - preflight_validator_check:
          name: "preflight_validator_runbook_after_redeploy"
          context:
            - artifactory
            - canton-network-vpn
            - slack-context
          cluster: << pipeline.parameters.cluster >>
          requires:
            - redeploy_validator_runbook_after_daml_upgrade
      - reset_cluster:
          name: reset_cluster_after_upgrade
          unlock_shared_cluster: true
          cluster: << pipeline.parameters.cluster >>
          context:
            - canton-network-vpn
            - slack-context
          requires:
            - preflight_sv_check_after_sv_redeploy
            - preflight_validator_runbook_after_redeploy
      - autoscaler_allow_scaledown:
          cluster: << pipeline.parameters.cluster >>
          requires:
            - reset_cluster_after_upgrade
