nodeName: "YOUR_SV_NAME"

founder:
  externalAddress: TARGET_CLUSTER.network.canton.global:26656

node:
  id: YOUR_COMETBFT_NODE_ID
  identifier: "cometbft"
  externalAddress: "cometbft.sv.svc.YOUR_HOSTNAME:26656"
  keysSecret: "cometbft-keys"

genesis:
  chainId: "TARGET_CLUSTER"

stateSync:
  # Uncomment the line below to disable state sync
  # enable: false

  # Note that the port number is significant in the list of rpcServers
  rpcServers: "https://sv.sv-1.svc.TARGET_CLUSTER.network.canton.global:443/api/sv/v0/admin/domain/cometbft/json-rpc,https://sv.sv-1.svc.TARGET_CLUSTER.network.canton.global:443/api/sv/v0/admin/domain/cometbft/json-rpc"
