nodeName: "YOUR_SV_NAME"

founder:
  # Replace MIGRATION_ID (part of port number!) with the current migration ID of the global synchronizer.
  externalAddress: TARGET_CLUSTER.network.canton.global:26MIGRATION_ID16

node:
  id: YOUR_COMETBFT_NODE_ID
  # Replace MIGRATION_ID with the current migration ID of the global synchronizer.
  identifier: "global-domain-MIGRATION_ID-cometbft"
  # Replace both instances of MIGRATION_ID (also part of port number!) with the current migration ID of the global synchronizer.
  externalAddress: "global-domain-MIGRATION_ID-cometbft.sv.YOUR_HOSTNAME:26MIGRATION_ID56"
  keysSecret: "cometbft-keys"

genesis:
  # Replace MIGRATION_ID with the current migration ID of the global synchronizer.
  chainId: "TARGET_CLUSTER-MIGRATION_ID"
  # Reserved for future use; keep at 0 until further notice
  chainIdSuffix: "0"

stateSync:
  # Uncomment the line below to disable state sync
  # enable: false

  # Note that the port number is significant in the list of rpcServers
  rpcServers: "https://sv.sv-2.TARGET_CLUSTER.network.canton.global:443/api/sv/v0/admin/domain/cometbft/json-rpc,https://sv.sv-2.TARGET_CLUSTER.network.canton.global:443/api/sv/v0/admin/domain/cometbft/json-rpc"

# k8s affinity for all deployed pods (optional)
# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: topology.kubernetes.io/zone
#           operator: In
#           values:
#             - antarctica-east1
#             - antarctica-west1

# k8s nodeSelector for all deployed pods (optional)
# nodeSelector:
#   disktype: ssd
