postgres: postgres
postgresSchema: sv_participant
globalDomain:
  alias: global
  # replace TARGET_CLUSTER with your actual target cluster
  url: http://TARGET_CLUSTER.network.canton.global:5008
auth:
  # replace OIDC_AUTHORITY_URL with your provider's OIDC URL
  jwksUrl: "https://OIDC_AUTHORITY_URL/.well-known/jwks.json"
  # If you want to configure audience, replace OIDC_AUTHORITY_PARTICIPANT_TARGET_AUDIENCE with audience for Ledger API
  # Otherwise, remove this line
  targetAudience: "OIDC_AUTHORITY_PARTICIPANT_TARGET_AUDIENCE"
enableHealthProbes: true
