# Replace MIGRATION_ID with the current migration ID of the global synchronizer.
migration:
  id: "MIGRATION_ID"

# Replace SERIAL_ID with the current serial ID of the global synchronizer.
participantAddress: "participant-SERIAL_ID"
synchronizers:
  current:
    sequencer: "global-domain-SERIAL_ID-sequencer"
    mediator: "global-domain-SERIAL_ID-mediator"

persistence:
  host: apps-pg
  secretName: apps-pg-secret

spliceInstanceNames:
  networkName: # Please provide a value as provided in the docs
  networkFaviconUrl: # Please provide a value as provided in the docs
  amuletName: # Please provide a value as provided in the docs
  amuletNameAcronym: # Please provide a value as provided in the docs
  nameServiceName: # Please provide a value as provided in the docs
  nameServiceNameAcronym: # Please provide a value as provided in the docs
