joinWithKeyOnboarding:
  sponsorApiUrl: "https://sv.sv-1.svc.TARGET_CLUSTER.network.canton.global/api/v0/sv"
  svcApiAddress: "TARGET_CLUSTER.network.canton.global"
# Replace YOUR_SV_NAME with the name you provided for your SV identity
onboardingName: YOUR_SV_NAME
auth:
  audience: https://canton.network.global
  jwksUrl: https://YOUR_INSTANCE_NAME.us.auth0.com/.well-known/jwks.json
