joinWithKeyOnboarding:
  sponsorApiUrl: "https://sv.sv-1.svc.TARGET_CLUSTER.network.canton.global/api/v0/sv"
# Replace YOUR_SV_NAME with the name you provided for your SV identity
onboardingName: YOUR_SV_NAME
globalDomainUrl: "http://TARGET_CLUSTER.network.canton.global:5008"
foundingSvApiUrl: "https://sv.sv-1.svc.TARGET_CLUSTER.network.canton.global/api/v0/sv"
auth:
  # The default value of audience is ``https://canton.network.global``.
  # If you want to configure a custom audience for SV app backend, uncomment this line and replace OIDC_AUTHORITY_SV_AUDIENCE with the audience of your choice.
  # audience: "OIDC_AUTHORITY_SV_AUDIENCE"
  # replace OIDC_AUTHORITY_URL with your provider's OIDC URL
  jwksUrl: "https://OIDC_AUTHORITY_URL/.well-known/jwks.json"
cometBFT:
  enabled: true
  automationEnabled: false
  connectionUri: "http://cometbft-cometbft-rpc:26657"
approvedSvIdentities:
  - name: sbi
    publicKey: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAETM+CeyHvphl9RiPDKL3vVX7F+Qo4fIhJopmgU5B7IzkwSdFic20hFB6tnAuCTU+UBjqZgh8N/h9r+CTrXMPsRg==
  - name: Liberty-City-Ventures
    publicKey: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEr/iPpyuFu2U914tHyNUDuECT4/AYz9J+nLQRTC8m+95yQ6Y4Oah+Y3u3o5MK4a9D+qkoNGoG6ng0HcjA6TGKmw==
  - name: Digital-Asset
    publicKey: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEsRRntNkOLF2Wh7JxV0rBQPgT+SendIjFLXKUXCrLbVHqomkypHQiZP8OgFMSlByOnr81fqiUt3G36LUpg/fmgA==
# PARTICIPANT_BOOTSTRAP_START
# Uncomment the two lines below if you are bootstrapping from an existing participant
# identities dump.
# participantBootstrappingDump:
#  secretName: participant-identities-dump
# PARTICIPANT_BOOTSTRAP_END
