joinWithKeyOnboarding:
  sponsorApiUrl: "https://sv.sv-1.svc.TARGET_CLUSTER.network.canton.global/api/v0/sv"
  svcApiAddress: "TARGET_CLUSTER.network.canton.global"
# Replace YOUR_SV_NAME with the name you provided for your SV identity
onboardingName: YOUR_SV_NAME
auth:
  audience: https://canton.network.global
  # replace OIDC_AUTHORITY_URL with your provider's OIDC URL
  jwksUrl: "https://OIDC_AUTHORITY_URL/.well-known/jwks.json"
