participantAddress: "participant"
scanAddress: "https://scan.sv-1.svc.TARGET_CLUSTER.network.canton.global/api/v0/scan"
# Replace SV_WALLET_USER_ID with the user id in your IAM that you want to use to log into
# the wallet as the SV party. Note that this should be the full user id, e.g., ``auth0|43b68e1e4978b000cefba352``
# not only the suffix ``43b68e1e4978b000cefba352``:
validatorWalletUser: "SV_WALLET_USER_ID"
clusterUrl: "TARGET_CLUSTER.network.canton.global"
globalDomainUrl: "http://TARGET_CLUSTER.network.canton.global:5008"
foundingSvApiUrl: "https://sv.sv-1.svc.TARGET_CLUSTER.network.canton.global/api/v0/sv"
auth:
  # If you want to configure a custom audience for Validator app backend, uncomment this line and replace OIDC_AUTHORITY_VALIDATOR_AUDIENCE with the audience of your choice
  # The default value of audience is ``https://canton.network.global``.
  # audience: "OIDC_AUTHORITY_VALIDATOR_AUDIENCE"

  # If you want to configure a custom audience for ledger API, replace OIDC_AUTHORITY_LEDGER_API_AUDIENCE with the audience of your choice
  # The default value of audience is ``https://canton.network.global``.
  # ledgerApiAudience: "OIDC_AUTHORITY_LEDGER_API_AUDIENCE"

  # replace OIDC_AUTHORITY_URL with your provider's OIDC URL
  jwksUrl: "https://OIDC_AUTHORITY_URL/.well-known/jwks.json"

topup:
  enabled: true
  targetThroughput: 10000
  minTopupInterval: "1m"
