package com.daml.network.util

import com.daml.network.codegen.java.cc.round.{IssuingMiningRound, OpenMiningRound}
import com.daml.network.console.WalletAppClientReference
import com.daml.network.integration.tests.CoinTests.{CoinTestCommon, CoinTestConsoleEnvironment}
import com.daml.network.util.CommonCoinAppInstanceReferences
import com.digitalasset.canton.concurrent.Threading
import com.digitalasset.canton.console.CommandFailure
import com.digitalasset.canton.topology.PartyId

import java.time.Duration
import scala.annotation.nowarn
import scala.concurrent.duration.*

trait TimeTestUtil extends CoinTestCommon {
  this: CommonCoinAppInstanceReferences & WalletTestUtil =>

  // Advance time by `duration`; works only if the used Canton instance uses simulated time.
  protected def advanceTime(
      duration: Duration
  )(implicit env: CoinTestConsoleEnvironment): Unit = {
    clue(s"attempting to advance time by $duration") {
      if (duration.isNegative()) {
        fail("Cannot advance time by negative duration.");
      } else if (!duration.isZero()) {
        // We sleep for 1s before changing the time here. This avoids inflight commands
        // getting dropped by the sequencer due to exceeding max-sequencing-time.
        // While we do recover from such an issue, we recover from it once the participant
        // times out with LOCAL_VERDICT_TIMEOUT. That timeout is measured in wall clock
        // so we will wait the full participantResponseTimeout (30s by default) which
        // then results in `eventually`’s in tests never completing.
        // Waiting 1s should ensure that existing background automation (e.g. coin merging)
        // can complete in-flight commands before we change the time. The assumption here
        // is that our period automation also takes sim time into account so if
        // the time does not change, it won’t continue sending commands.
        Threading.sleep(1000)

        // it doesn't seem to matter which participant we run these from - all get synced
        val now = svc.remoteParticipant.ledger_api.time.get()
        try {
          // actually advance the time
          logger.info(s"advancing time by $duration ...")
          svc.remoteParticipant.ledger_api.time.set(now, now.plus(duration))
        } catch {
          case _: CommandFailure =>
            fail(
              "Could not advance time. " +
                "Is Canton configured with `parameters.clock.type = sim-clock`?"
            )
        }
        // We don't get feedback about the success of setting the time here, so we check ourselves.
        if (svc.remoteParticipant.ledger_api.time.get() == now) {
          fail(
            "Could not advance time. " +
              "Are participants configured with `testing-time.type = monotonic-time`?"
          )
        }
      }
    }
  }

  /** This function advances time by ~one tick and waits for the SVC round management automation for open, summarizing
    * and issuing rounds to finish processing the events generated by the new time.
    * This function does not wait for the closed round automation.
    */
  @nowarn("msg=match may not be exhaustive")
  def advanceRoundsByOneTick(implicit env: CoinTestConsoleEnvironment) = {

    val Seq(lowestOpen, middleOpen, highestOpen) =
      aliceWalletBackend.remoteParticipant.ledger_api.acs
        .filterJava(OpenMiningRound.COMPANION)(
          aliceValidator.getValidatorPartyId()
        )
        .map(_.data.round.number)

    val previousIssuingRounds = aliceWalletBackend.remoteParticipant.ledger_api.acs
      .filterJava(IssuingMiningRound.COMPANION)(
        aliceValidator.getValidatorPartyId()
      )
      .map(_.data.round.number)

    // not exactly 150s because of the skew parameter.
    actAndCheck("advancing time", advanceTime(Duration.ofSeconds(160)))(
      s"waiting for open and issuing round automation (should create OR ${highestOpen + 1}, should advance IR ${previousIssuingRounds}",
      _ =>
        eventually(5.seconds) {
          val Seq(newLowestOpen, newMiddleOpen, newHighestOpen) =
            aliceWalletBackend.remoteParticipant.ledger_api.acs
              .filterJava(OpenMiningRound.COMPANION)(
                aliceValidator.getValidatorPartyId()
              )
              .map(_.data.round.number)
              .sorted

          newLowestOpen shouldBe lowestOpen + 1
          newLowestOpen shouldBe middleOpen
          newMiddleOpen shouldBe highestOpen
          newHighestOpen shouldBe highestOpen + 1

          val newIssuingRounds = aliceWalletBackend.remoteParticipant.ledger_api.acs
            .filterJava(IssuingMiningRound.COMPANION)(
              aliceValidator.getValidatorPartyId()
            )
            .map(_.data.round.number)
          if (previousIssuingRounds.size < 3)
            newIssuingRounds.size shouldBe previousIssuingRounds.size + 1
          else {
            val Seq(lowestIssuing, middleIssuing, highestIssuing) = previousIssuingRounds
            newIssuingRounds should have size 3
            val Seq(newLowestIssuing, newMiddleIssuing, newHighestIssuing) = newIssuingRounds

            newLowestIssuing shouldBe lowestIssuing + 1
            newLowestIssuing shouldBe middleIssuing
            newMiddleIssuing shouldBe highestIssuing
            newHighestIssuing shouldBe highestIssuing + 1
          }
        },
    )
  }

  def p2pTransferAndTriggerAutomation(
      senderWallet: WalletAppClientReference,
      receiverWallet: WalletAppClientReference,
      receiver: PartyId,
      amount: BigDecimal,
      senderTransferFeeRatio: BigDecimal = 1.0,
      advanceTimeBy: Duration = Duration.ofSeconds(1),
  )(implicit env: CoinTestConsoleEnvironment) = {
    p2pTransfer(senderWallet, receiverWallet, receiver, amount, senderTransferFeeRatio)
    eventually() {
      // wait until we observe the accepted transfer offer
      receiverWallet.listAcceptedTransferOffers() should have size 1
    }
    // ... before we advance time to trigger the automation.
    advanceTime(advanceTimeBy)
  }
}
