#!/usr/bin/env python

# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

import json
import os
import sys

APPS_DIR = "apps"
REQUIRED_NAMESPACE = "@lfdecentralizedtrust/"


def main():
    errors = []

    for root, dirs, files in os.walk(APPS_DIR):
        # Skip node_modules
        if "node_modules" in root:
            continue

        # Skip autogenerated @daml.js packages
        if "/daml.js/" in root or root.endswith("/daml.js"):
            continue

        if "package.json" not in files:
            continue

        package_json_path = os.path.join(root, "package.json")

        # Skip the root apps/package.json (workspace root, not a publishable package)
        if package_json_path == os.path.join(APPS_DIR, "package.json"):
            continue

        try:
            with open(package_json_path, "r") as f:
                package = json.load(f)
        except (json.JSONDecodeError, IOError):
            continue

        name = package.get("name")
        if not name:
            continue

        if not name.startswith(REQUIRED_NAMESPACE):
            errors.append(
                f"ERROR: Package '{name}' in {package_json_path} is not properly namespaced.\n"
                f"       Internal packages must start with '{REQUIRED_NAMESPACE}'"
            )

    if errors:
        for error in errors:
            print(error)
        print()
        print("Some internal npm packages are not properly namespaced.")
        print(f"Please rename them to use the '{REQUIRED_NAMESPACE}' prefix.")
        sys.exit(1)
    else:
        print("All internal npm packages are properly namespaced.")


if __name__ == "__main__":
    main()
