#!/usr/bin/env bash

# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This script checks that all internal npm packages in the apps directory
# are properly namespaced with @lfdecentralizedtrust/splice-

set -euo pipefail

APPS_DIR="apps"
REQUIRED_NAMESPACE="@lfdecentralizedtrust/splice-"

fail=0

# Find all package.json files in the apps directory
while IFS= read -r package_json; do
  # Skip node_modules
  if [[ "$package_json" == *"/node_modules/"* ]]; then
    continue
  fi

  # Skip autogenerated @daml.js packages from apps/common/frontend/daml.js
  if [[ "$package_json" == *"/daml.js/"* ]]; then
    continue
  fi

  # Skip the root apps/package.json, since it's the workspace root, not a package
  if [[ "$package_json" == "apps/package.json" ]]; then
    continue
  fi

  package_name=$(jq -r '.name // empty' "$package_json" 2>/dev/null)

  if [[ -z "$package_name" ]]; then
    continue
  fi

  if [[ "$package_name" != "$REQUIRED_NAMESPACE"* ]]; then
    echo "ERROR: Package '$package_name' in $package_json is not properly namespaced."
    echo "       Internal packages must start with '$REQUIRED_NAMESPACE'"
    fail=1
  fi
  
done < <(find "$APPS_DIR" -name "package.json" -type f)

if [[ $fail -ne 0 ]]; then
  echo ""
  echo "Some internal npm packages are not properly namespaced."
  echo "Please rename them to use the '$REQUIRED_NAMESPACE' prefix."
  exit 1
else
  echo "All internal npm packages are properly namespaced."
fi
