canton {
  features {
    enable-testing-commands = yes
  }
  parameters {
    manual-start = no
  }

  monitoring {
    metrics.reporters = [{
      type = jmx
    }]
  }

  participants {
    svc_participant {
      storage.type = memory

      // When spinning up a local SVC and validator, port 5002/5001 is already taken by the validator participant
      // and hence we use ports 5102/5101 here
      // (technically, the SVC is first but we don't want a comment like this in the runbook)
      admin-api {
        address = "0.0.0.0"
        port = 5102
      }

      ledger-api {
        address = "0.0.0.0"
        port = 5101
        max-deduplication-duration = 30s
      }
    }
  }
}

canton.participants.svc_participant.parameters.unsafe-enable-daml-lf-dev-version = true
