{{- $appIdentifier := include "domainMigrationIdOrDefaultValue" (list .Values "sv-web-ui") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $appIdentifier }}
  name: {{ $appIdentifier }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $appIdentifier }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ $appIdentifier }}
    spec:
      containers:
        - env:
            - name: CN_APP_SV_UI_AUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: client-id
                  name: cn-app-sv-ui-auth
                  optional: false
            - name: CN_APP_SV_UI_AUTH_URL
              valueFrom:
                secretKeyRef:
                  key: url
                  name: cn-app-sv-ui-auth
                  optional: false
            - name: CN_APP_SV_UI_AUTH_AUDIENCE
              value: {{ (.Values.auth).audience | default "https://canton.network.global" | quote }}
            - name: CN_APP_SV_UI_CLUSTER
              value: {{ .Values.clusterUrl | quote }}
          image: "{{ .Values.imageRepo }}/sv-web-ui:{{ (.Values.cluster).imageTag }}"
          imagePullPolicy: Always
          name: sv-web-ui
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 1
              memory: 1536Mi
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $appIdentifier }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ $appIdentifier }}
  ports:
    - name: http
      port: 80
      protocol: TCP
