---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sv-app
  namespace: {{ .Release.Namespace }}
  labels:
    app: sv-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sv-app
  strategy:
    type: "Recreate"
  template:
    metadata:
      labels:
        app: sv-app
    spec:
      containers:
        - name: sv-app
          image: "{{ .Values.imageRepo }}/sv-app:{{ .Values.cluster.imageTag }}"
          imagePullPolicy: "Always"
          env:
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.defaultJvmOptions }}
            {{- include "cn-util-lib.auth0-env-vars" (dict "appName" "sv" "keyName" "sv" "fixedTokens" .Values.cluster.fixedTokens) | indent 12}}
            {{- include "cn-util-lib.auth0-user-env-var" (dict "appName" "validator" "keyName" "validator") | indent 12}}
            {{- if eq .Values.onboardingType "found-collective" }}
            - name: CN_APP_SV_IS_DEV_NET
              value: {{ .Values.isDevNet | quote }}
            {{- with .Values.acsDumpImport }}
            - name: ADDITIONAL_CONFIG_ACS_DUMP_IMPORT
              value: |
                canton.sv-apps.sv.onboarding.bootstrapping-dump {
                  type = gcp
                  bucket {
                    project-id = {{ .bucket.config.projectId }}
                    bucket-name = {{ .bucket.config.bucketName }}
                    credentials {
                      type = service-account
                      json-credentials = ${CN_APP_SV_BOOTSTRAPPING_DUMP_SERVICE_ACCOUNT_CREDENTIALS}
                    }
                  }
                  path = {{ .path | quote }}
                }
            - name: CN_APP_SV_BOOTSTRAPPING_DUMP_SERVICE_ACCOUNT_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  key: "json-credentials"
                  name: {{ .bucket.secretName }}
            {{- end }}
            {{- end }}
            - name: CN_APP_SV_PARTICIPANT_ADDRESS
              value: {{ .Values.participantAddress | default "participant" | quote }}
            {{- if .Values.onboardingType }}
            - name: CN_APP_SV_ONBOARDING_TYPE
              value: {{ .Values.onboardingType }}
            {{- end }}
            {{- if .Values.onboardingName }}
            - name: CN_APP_SV_ONBOARDING_NAME
              value: {{ .Values.onboardingName }}
            {{- end }}
            {{ if ((.Values.auth).audience) }}
            - name: CN_APP_SV_AUTH_AUDIENCE
              value: {{ .Values.auth.audience | quote }}
            {{ end }}
            {{ if ((.Values.auth).jwksUrl) }}
            - name: CN_APP_SV_AUTH_JWKS_URL
              value: {{ .Values.auth.jwksUrl | quote }}
            {{ end }}
            {{- with .Values.joinWithKeyOnboarding }}
            - name: ADDITIONAL_CONFIG_SV_ONBOARDING
              value: |
                _onboarding {
                  type = "join-with-key"
                  sv-client.admin-api.url = "{{ .sponsorApiUrl }}"
                }
            - name: CN_APP_SV_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  key: public
                  name: "cn-app-sv-key"
                  optional: false
            - name: CN_APP_SV_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: private
                  name: "cn-app-sv-key"
                  optional: false
            {{- end }}
            # Checking .Values.domain does not differentiate between
            # it being unset and set to an empty object
            {{- if (.Values.domain).enable }}
            {{- with .Values.domain }}
            - name: ADDITIONAL_CONFIG_SV_DOMAIN
              value: |
                canton.sv-apps.sv.local-domain-node {
                  sequencer {
                    admin-api {
                      address = {{ .sequencerAddress | default "global-domain-sequencer" | quote }}
                      port = 5009
                    }
                    public-api {
                      address = {{ .sequencerAddress | default "global-domain-sequencer" | quote }}
                      port = 5008
                    }
                  }
                  mediator {
                    admin-api {
                      address = {{ .mediatorAddress | default "global-domain-mediator" | quote }}
                      port = 5007
                    }
                  }
                }
            {{- end }}
            {{- end }}
            - name: CN_APP_SV_GLOBAL_DOMAIN_URL
              value: {{ .Values.globalDomainUrl | quote }}
            {{- if (.Values.cometBFT).enabled }}
            - name: CN_APP_SV_COMETBFT_ENABLED
              value: {{ (.Values.cometBFT).enabled | quote }}
            {{- end }}
            {{- if (.Values.cometBFT).connectionUri }}
            - name: CN_APP_SV_COMETBFT_CONNECTION_URI
              value: {{ (.Values.cometBFT).connectionUri }}
            {{- end }}
            {{- range $ii, $onboarding := .Values.expectedValidatorOnboardings }}
            - name: ADDITIONAL_CONFIG_VALIDATOR_ONBOARDING_{{ $ii }}
              value: |
                canton.sv-apps.sv.expected-validator-onboardings.{{ $ii }} = {
                  secret = ${CN_APP_VALIDATOR_ONBOARDING_SECRET_{{ $ii }}}
                  expires-in = {{ $onboarding.expiresIn }}
                }
            - name: CN_APP_VALIDATOR_ONBOARDING_SECRET_{{ $ii }}
              valueFrom: {{ $onboarding.secretFrom | toYaml | nindent 16 }}
            {{- end }}
            {{- range $ii, $sv := .Values.approvedSvIdentities }}
            - name: ADDITIONAL_CONFIG_APPROVED_SV_IDENTITY_{{ $ii }}
              value: |
                canton.sv-apps.sv.approved-sv-identities.{{ $ii }} = {
                  name = {{ $sv.name | quote }}
                  public-key = {{ $sv.publicKey | quote }}
                }
            {{- end }}
            {{- with .Values.acsDumpPeriodicExport }}
            - name: ADDITIONAL_CONFIG_CN_APP_SV_ACS_DUMP_PERIODIC_EXPORT
              value: |
                canton.sv-apps.sv.acs-store-dump = {
                  type = gcp
                  bucket {
                    project-id = {{ .bucket.config.projectId }}
                    bucket-name = {{ .bucket.config.bucketName }}
                    credentials {
                      type = service-account
                      json-credentials = ${CN_APP_SV_BACKUP_BUCKET_SERVICE_ACCOUNT_CREDENTIALS}
                    }
                  }
                  prefix = {{ .prefix | quote }}
                  backup-interval = {{ .backupInterval }}
                }
            - name: CN_APP_SV_BACKUP_BUCKET_SERVICE_ACCOUNT_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  key: "json-credentials"
                  name: {{ .bucket.secretName }}
            {{- end }}
            {{- with .Values.participantIdentitiesDumpImport }}
            - name: ADDITIONAL_CONFIG_CN_APP_SV_PARTICIPANT_IDENTITIES_DUMP_IMPORT
              value: |
                canton.sv-apps.sv.participant-bootstrapping-dump {
                  type = file
                  file = /participant-bootstrapping-dump/content
                }
            {{- end }}
          ports:
            - name: sv-api
              containerPort: 5014
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /livez
              port: 5014
            initialDelaySeconds: 60
            periodSeconds: 60
            failureThreshold: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 5014
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
            timeoutSeconds: 10
          {{- with .Values.participantIdentitiesDumpImport }}
          volumeMounts:
            - name: participant-bootstrapping-dump-volume
              mountPath: /participant-bootstrapping-dump
              readOnly: true
          {{- end }}
          {{- with .Values.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.participantIdentitiesDumpImport }}
      volumes:
        - name: participant-bootstrapping-dump-volume
          secret:
            secretName: {{ .secretName }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: sv-app
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: sv-app
  ports:
  - name: sv-api
    port: 5014
    protocol: TCP
