---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sv-app
  namespace: {{ .Release.Namespace }}
  labels:
    app: sv-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sv-app
  strategy:
    type: "Recreate"
  template:
    metadata:
      labels:
        app: sv-app
    spec:
      containers:
        - name: sv-app
          image: "{{ .Values.imageRepo }}/sv-app:{{ .Values.cluster.imageTag }}"
          imagePullPolicy: "Always"
          env:
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.defaultJvmOptions }}
            {{- include "cn-util-lib.auth0-env-vars" (dict "appName" "sv" "fixedTokens" .Values.cluster.fixedTokens) | indent 12}}
            - name: CN_APP_SV_ADMIN_API_PORT
              value: "5014"
            - name: CN_APP_SV_IS_DEV_NET
              value: "true"
            - name: CN_APP_SV_BOOTSTRAP_TYPE
              value: {{ .Values.bootstrapType }}
          ports:
            - name: sv-api
              containerPort: 5014
              protocol: TCP
          {{- with .Values.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: sv-app
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: sv-app
  ports:
  - name: sv-api
    port: 5014
    protocol: TCP