---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sv-app
  namespace: {{ .Release.Namespace }}
  labels:
    app: sv-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sv-app
  strategy:
    type: "Recreate"
  template:
    metadata:
      labels:
        app: sv-app
    spec:
      containers:
        - name: sv-app
          image: "{{ .Values.imageRepo }}/sv-app:{{ .Values.cluster.imageTag }}"
          imagePullPolicy: "Always"
          env:
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.defaultJvmOptions }}
            {{- include "cn-util-lib.auth0-env-vars" (dict "appName" "sv" "keyName" "sv" "fixedTokens" .Values.cluster.fixedTokens) | indent 12}}
            {{- include "cn-util-lib.auth0-user-env-var" (dict "appName" "validator" "keyName" "validator") | indent 12}}
            - name: CN_APP_SV_IS_DEV_NET
              value: "true"
            - name: CN_APP_SV_PARTICIPANT_ADDRESS
              value: {{ .Values.participantAddress | default "participant" | quote }}
            {{- if .Values.onboardingType }}
            - name: CN_APP_SV_ONBOARDING_TYPE
              value: {{ .Values.onboardingType }}
            {{- end }}
            {{- if .Values.onboardingName }}
            - name: CN_APP_SV_ONBOARDING_NAME
              value: {{ .Values.onboardingName }}
            {{- end }}
            {{ if ((.Values.auth).audience) }}
            - name: CN_APP_SV_AUTH_AUDIENCE
              value: {{ .Values.auth.audience | quote }}
            {{ end }}
            {{ if ((.Values.auth).jwksUrl) }}
            - name: CN_APP_SV_AUTH_JWKS_URL
              value: {{ .Values.auth.jwksUrl | quote }}
            {{ end }}
            {{- with .Values.joinWithKeyOnboarding }}
            - name: ADDITIONAL_CONFIG_SV_ONBOARDING
              value: |
                _onboarding {
                  type = "join-with-key"
                  sv-client.admin-api.url = "{{ .sponsorApiUrl }}"
                }
            - name: CN_APP_SV_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  key: public
                  name: "cn-app-sv-key"
                  optional: false
            - name: CN_APP_SV_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: private
                  name: "cn-app-sv-key"
                  optional: false
            {{- end }}
            - name: CN_APP_SV_GLOBAL_DOMAIN_URL
              value: {{ .Values.globalDomainUrl | quote }}
            {{- if (.Values.cometBFT).enabled }}
            - name: CN_APP_SV_COMETBFT_ENABLED
              value: {{ (.Values.cometBFT).enabled | quote }}
            {{- end }}
            {{- if (.Values.cometBFT).automationEnabled }}
            - name: CN_APP_SV_COMETBFT_AUTOMATION_ENABLED
              value: {{ (.Values.cometBFT).automationEnabled | quote }}
            {{- end }}
            {{- if (.Values.cometBFT).connectionUri }}
            - name: CN_APP_SV_COMETBFT_CONNECTION_URI
              value: {{ (.Values.cometBFT).connectionUri }}
            {{- end }}
          ports:
            - name: sv-api
              containerPort: 5014
              protocol: TCP
          {{- with .Values.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: sv-app
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: sv-app
  ports:
  - name: sv-api
    port: 5014
    protocol: TCP
