{{- if eq .Values.onboardingType "found-collective" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: svc-app
  name: svc-app
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: svc-app
    spec:
      containers:
      - name: svc-app
        image: "{{ .Values.imageRepo }}/svc-app:{{ (.Values.cluster).imageTag }}"
        imagePullPolicy: Always
        env:
        - name: JAVA_TOOL_OPTIONS
          value: {{ .Values.defaultJvmOptions }}
        - name: CN_APP_SVC_PARTICIPANT_ADDRESS
          value: {{ .Values.participantAddress }}
        {{- include "cn-util-lib.auth0-env-vars" (dict "appName" "svc" "keyName" "sv" "fixedTokens" (.Values.cluster).fixedTokens) | indent 8}}
        ports:
        - containerPort: 5005
          name: svc-app-adm-api
          protocol: TCP
        {{- with .Values.resources }}
        resources: {{- toYaml . | nindent 10 }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: svc-app
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: svc-app
  ports:
  - name: svc-app-adm-api
    port: 5005
    protocol: TCP
{{- end}}
