#### SV 2

server {
    listen       5114 ssl;
    server_name  localhost ssl;

    ssl_certificate     /tmp/tls.crt;
    ssl_certificate_key /tmp/tls.key;

    location / {
       resolver kube-dns.kube-system.svc.cluster.local;
       proxy_pass http://sv-app.sv-2.svc.cluster.local:5114;
    }
}
