### SV Apps

#### SV 1

server {
    listen       5014 ssl;
    server_name  localhost ssl;

    ssl_certificate     /tmp/tls.crt;
    ssl_certificate_key /tmp/tls.key;

    location / {
       resolver kube-dns.kube-system.svc.cluster.local;
       proxy_pass http://sv-app.sv-1.svc.cluster.local:5014;
    }
}

#### SV 2

server {
    listen       5114 ssl;
    server_name  localhost ssl;

    ssl_certificate     /tmp/tls.crt;
    ssl_certificate_key /tmp/tls.key;

    location / {
       resolver kube-dns.kube-system.svc.cluster.local;
       proxy_pass http://sv-app.sv-2.svc.cluster.local:5114;
    }
}

#### SV 3

server {
    listen       5214 ssl;
    server_name  localhost ssl;

    ssl_certificate     /tmp/tls.crt;
    ssl_certificate_key /tmp/tls.key;

    location / {
       resolver kube-dns.kube-system.svc.cluster.local;
       proxy_pass http://sv-app.sv-3.svc.cluster.local:5214;
    }
}

#### SV 4

server {
    listen       5314 ssl;
    server_name  localhost ssl;

    ssl_certificate     /tmp/tls.crt;
    ssl_certificate_key /tmp/tls.key;

    location / {
       resolver kube-dns.kube-system.svc.cluster.local;
       proxy_pass http://sv-app.sv-4.svc.cluster.local:5314;
    }
}
