### Wallet Web UI @ SV2

server {
    listen       80;
    listen  [::]:80;

    server_name  wallet.sv-2.svc.*;
    return 301 https://$host$request_uri;
}

server {
    listen       443 ssl;
    listen  [::]:443 ssl;

    server_name  wallet.sv-2.svc.*;

    ssl_certificate     /tmp/tls.crt;
    ssl_certificate_key /tmp/tls.key;

    location ~ ^/(api/v0/validator/)(.*) {
       resolver kube-dns.kube-system.svc.cluster.local;
       proxy_pass http://validator-app.sv-2.svc.cluster.local:5003/$2$is_args$args;
    }

    location / {
        resolver kube-dns.kube-system.svc.cluster.local;
        proxy_pass http://wallet-web-ui.sv-2.svc.cluster.local;
    }
}
