---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  namespace: {{ .Release.Namespace }}
  labels:
    app: docs
    clusterName: {{ .Values.cluster.name }}
    moduleName: docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  strategy:
    type: "Recreate"
  template:
    metadata:
      labels:
        app: docs
        clusterName: {{ .Values.cluster.name }}
        moduleName: docs
    spec:
      containers:
        - name: docs
          image: "{{ .Values.imageRepo }}/docs:{{ .Values.cluster.imageTag }}"
          imagePullPolicy: "Always"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          resources:
            limits:
              memory: "1536Mi"
            requests:
              cpu: 1
              memory: "1536Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: docs
  namespace: {{ .Release.Namespace }}
  labels:
    clusterName: {{ .Values.cluster.name }}
spec:
  selector:
    app: docs
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcs-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app: gcs-proxy
    clusterName: {{ .Values.cluster.name }}
    moduleName: gcs-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcs-proxy
  strategy:
    type: "Recreate"
  template:
    metadata:
      labels:
        app: gcs-proxy
        clusterName: {{ .Values.cluster.name }}
        moduleName: gcs-proxy
    spec:
      containers:
        - name: gcs-proxy
          image: "{{ .Values.imageRepo }}/gcs-proxy:{{ .Values.cluster.imageTag }}"
          imagePullPolicy: "Always"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
            requests:
              cpu: 1
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: gcs-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    clusterName: {{ .Values.cluster.name }}
spec:
  selector:
    app: gcs-proxy
  ports:
  - name: http
    port: 8080
    protocol: TCP
