_client_credentials_auth_config {
  type = "client-credentials"
  well-known-config-url = ${?CN_APP_SCAN_LEDGER_API_AUTH_URL}
  client-id = ${?CN_APP_SCAN_LEDGER_API_AUTH_CLIENT_ID}
  client-secret = ${?CN_APP_SCAN_LEDGER_API_AUTH_CLIENT_SECRET}
  # TODO(#1837) use actual audience of the target participant
  audience = "https://canton.network.global"
}

_scan_participant_remote {
  admin-api = {
    address = "participant"
    port = 5002
  }

  ledger-api.client-config = {
    address = "participant"
    port = 5001
  }
  ledger-api.auth-config = ${_client_credentials_auth_config}
}

canton {
  scan-app {
    storage.type = memory
    admin-api = {
      address = "0.0.0.0"
      port = 5012
    }
    remote-participant = ${_scan_participant_remote}
    svc-user = ${?CN_APP_SCAN_LEDGER_API_AUTH_USER_NAME}
    domains {
      global = "global"
    }
  }
}
canton.features.enable-testing-commands = yes
