_validator_participant_remote {
  admin-api.port = 5102
  ledger-api.port = 5101
}

_scan_remote {
  admin-api.port = 5012
  admin-api.address = dev.network.canton.global
  admin-api.address = ${?NETWORK_APPS_ADDRESS}
}

canton {
  validator-apps {
    validatorApp {
      storage.type = memory
      admin-api.port = 5103
      remote-participant = ${_validator_participant_remote}
      daml-user = "validator_user"
      remote-scan = ${_scan_remote}
      wallet-service-user = ${canton.wallet-apps.walletApp.service-user}
# BEGIN_SPLITWISE_CONFIG
      app-instances {
        splitwise {
          service-user = "splitwise-service-user"
          dars = ["dars/splitwise-0.1.0.dar"]
        }
      }
# END_SPLITWISE_CONFIG
    }
  }

  wallet-apps {
    walletApp {
      storage.type = memory
      admin-api.port = 5104
      service-user = "wallet_service_user"
      remote-participant = ${_validator_participant_remote}
      remote-scan = ${_scan_remote}
      validator.admin-api = ${canton.validator-apps.validatorApp.admin-api}
      auth {
        algorithm = "hs-256-unsafe"
        secret = "test"
        enable-auth = false
      }
    }
  }
}
