canton {
  participants {
    splitwiseParticipant {
      storage.type = memory
      admin-api.port = 5102
      ledger-api.port = 5101
      ledger-api.explicit-disclosure-unsafe = true
      parameters {
        unsafe-enable-daml-lf-dev-version = yes
        will-corrupt-your-system-dev-version-support = yes
      }
      init.parameters.unique-contract-keys = false
    }
  }
}
canton.features.enable-testing-commands = yes
