_validator_participant_remote {
  admin-api.port = 5002
  ledger-api.port = 5001
}

_scan_remote {
  admin-api.port = 5012
  admin-api.address = ${?NETWORK_APPS_ADDRESS}
}

canton {
  splitwise-app-clients {
    aliceSplitwise {
      admin-api.address = 127.0.0.1
      admin-api.port = 5113
      ledger-api = ${_validator_participant_remote.ledger-api}
      remote-scan = ${_scan_remote}
      ledger-api-user = "alice"
    }
    bobSplitwise {
      admin-api.address = 127.0.0.1
      admin-api.port = 5113
      ledger-api = ${_validator_participant_remote.ledger-api}
      remote-scan = ${_scan_remote}
      ledger-api-user = "bob"
    }
  }
  features.enable-testing-commands = yes
}
