# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

ARG base_version

FROM splice-app:${base_version}

COPY app.conf bootstrap.sc pre-bootstrap.sh health-check.sh /app/
