_participant_remote {
  admin-api = {
    address = "validator1-participant"
    port = 5102
  }

  ledger-api = {
    client-config = {
      address = "validator1-participant"
      port = 5101
    }
    auth-config.type = "none"
  }
}

_scan_remote {
  admin-api.port = 5012
  admin-api.address = "scan-app"
}

canton {
  validator-apps {
    validator1_validator_backend {
      storage.type = memory
      admin-api = {
        address = "0.0.0.0"
        port = 5103
      }
      remote-participant = ${_participant_remote}
      remote-scan = ${_scan_remote}
      daml-user = "validator1_validator_service_user"
      wallet-service-user = "validator1_wallet_service_user"
      app-instances {
      }
    }
  }
  features.enable-testing-commands = yes
}
