openapi: 3.0.0
info:
  title: Directory API
  version: 0.0.1
tags:
  - name: directory
servers:
  - url: https://example.com/api/validator
paths:
  /v0/entry/create:
    post:
      tags: [directory]
      x-jvm-package: external.directory
      operationId: "createDirectoryEntry"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateDirectoryEntryRequest"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/CreateDirectoryEntryResponse"
        "400":
          description: |
            Invalid request, check the error response for details.
          content:
            application/json:
              schema:
                $ref: "../../../../common/src/main/openapi/common-external.yaml#/components/schemas/ErrorResponse"
        "500":
          $ref: "../../../../common/src/main/openapi/common-external.yaml#/components/responses/500"
  /v0/entry/all:
    get:
      tags: [ directory ]
      x-jvm-package: external.directory
      operationId: "listDirectoryEntries"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListDirectoryEntriesResponse"
        "404":
          $ref: "../../../../common/src/main/openapi/common-external.yaml#/components/responses/404"
        "500":
          $ref: "../../../../common/src/main/openapi/common-external.yaml#/components/responses/500"
  /v0/directory/install:
    post:
      tags: [ directory ]
      x-jvm-package: external.directory
      operationId: "createDirectoryInstall"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateDirectoryInstallResponse"
        "500":
          $ref: "../../../../common/src/main/openapi/common-external.yaml#/components/responses/500"
    get:
      tags: [ directory ]
      x-jvm-package: external.directory
      operationId: "fetchDirectoryInstall"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FetchDirectoryInstallResponse"
        "404":
          $ref: "../../../../common/src/main/openapi/common-external.yaml#/components/responses/404"
        "500":
          $ref: "../../../../common/src/main/openapi/common-external.yaml#/components/responses/500"


components:
  schemas:
    CreateDirectoryEntryRequest:
      type: object
      required:
        - name
        - url
        - description
      properties:
        name:
          type: string
        url:
          type: string
        description:
          type: string
    CreateDirectoryEntryResponse:
      type: object
      required:
        - name
        - url
        - description
        - entryContextCid
        - subscriptionRequestCid
      properties:
        entryContextCid:
          $ref: "../../../../common/src/main/openapi/common-external.yaml#/components/schemas/ContractId"
        subscriptionRequestCid:
          $ref: "../../../../common/src/main/openapi/common-external.yaml#/components/schemas/ContractId"
        name:
          type: string
        url:
          type: string
        description:
          type: string
    ListDirectoryEntriesResponse:
      type: object
      required:
        - entries
      properties:
        entries:
          type: array
          items:
            $ref: "#/components/schemas/DirectoryEntryResponse"
    DirectoryEntryResponse:
      type: object
      required:
        - contractId
        - name
        - amount
        - currency
        - expiresAt
        - paymentInterval
        - paymentDuration
      properties:
        contractId:
          $ref: "../../../../common/src/main/openapi/common-external.yaml#/components/schemas/ContractId"
        name:
          type: string
        amount:
          type: string
        currency:
          type: string
        expiresAt:
          type: string
        paymentInterval:
          type: string
        paymentDuration:
          type: string
    CreateDirectoryInstallResponse:
      type: object
      required:
        - contractId
      properties:
        contractId:
          $ref: "../../../../common/src/main/openapi/common-external.yaml#/components/schemas/ContractId"
    FetchDirectoryInstallResponse:
      type: object
      required:
        - contractId
        - entryFee
        - entryLifetime
      properties:
        contractId:
          $ref: "../../../../common/src/main/openapi/common-external.yaml#/components/schemas/ContractId"
        entryFee:
          type: string
        entryLifetime:
          type: string

