openapi: 3.0.0
info:
  title: Validator API
  version: 0.0.1
tags:
  - name: validator
paths:
  /readyz:
    $ref: "../../../../common/src/main/openapi/common.yaml#/paths/~1readyz"
  /livez:
    $ref: "../../../../common/src/main/openapi/common.yaml#/paths/~1livez"
  /validator-user:
    get:
      tags: [validatorPublic]
      x-jvm-package: validatorPublic
      operationId: "getValidatorUserInfo"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/GetValidatorUserInfoResponse"
  /register:
    post:
      tags: [validator]
      x-jvm-package: validator
      operationId: "register"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/RegistrationRequest"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/RegistrationResponse"

  /admin/users:
    post:
      tags: [validator]
      x-jvm-package: validatorAdmin
      operationId: "onboardUser"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/OnboardUserRequest"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/OnboardUserResponse"

    get:
      tags: [validator]
      x-jvm-package: validatorAdmin
      operationId: "listUsers"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ListUsersResponse"

  /admin/users/offboard:
    post:
      tags: [validator]
      x-jvm-package: validatorAdmin
      operationId: "offboardUser"
      parameters:
        - in: query
          name: username
          required: true
          schema:
            type: string
      responses:
        "200":
          description: ok
        "404":
          $ref: "../../../../common/src/main/openapi/common.yaml#/components/responses/404"

  /admin/participant/identities:
    get:
      tags: [validator]
      x-jvm-package: validatorAdmin
      operationId: "dumpParticipantIdentities"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "../../../../common/src/main/openapi/common.yaml#/components/schemas/ParticipantIdentitiesDump"

  /app-manager/authorize:
    post:
      tags: [appManager]
      x-jvm-package: appManager
      operationId: "authorize"
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                redirect_uri:
                  type: string
                state:
                  type: string
                user_id:
                  type: string
              required:
                - redirect_uri
                - state
                - user_id
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/AuthorizeResponse"
  /app-manager/oauth2/.well-known/openid-configuration:
    get:
      tags: [appManager]
      x-jvm-package: appManager
      operationId: "oauth2OpenIDConfiguration"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/OpenIDConfigurationResponse"
  /app-manager/oauth2/.well-known/jwks.json:
    get:
      tags: [appManager]
      x-jvm-package: appManager
      operationId: "oauth2Jwks"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/JwksResponse"
  /app-manager/oauth2/token:
    post:
      tags: [appManager]
      x-jvm-package: appManager
      operationId: "oauth2Token"
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                code:
                  type: string
                redirect_uri:
                  type: string
                client_id:
                  type: string
              required:
                - grant_type
                - code
                - redirect_uri
                - client_id
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TokenResponse"
        "400":
          $ref: "../../../../common/src/main/openapi/common.yaml#/components/responses/400"

  /app-manager/apps/installed:
    get:
      tags: [appManager]
      x-jvm-package: appManager
      operationId: "listInstalledApps"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ListInstalledAppsResponse"
  /app-manager/apps/install:
    post:
      tags: [appManager]
      x-jvm-package: appManager
      operationId: "installApp"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/InstallAppRequest"
      responses:
        "201":
          description: ok
        "409":
          $ref: "../../../../common/src/main/openapi/common.yaml#/components/responses/409"

  /app-manager/apps/registered:
    get:
      tags: [appManager]
      x-jvm-package: appManager
      operationId: "listRegisteredApps"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ListRegisteredAppsResponse"
  /app-manager/apps/registered/{app}/manifest.json:
    get:
      tags: [appManager]
      x-jvm-package: appManager
      operationId: "getAppManifest"
      parameters:
        - name: app
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Manifest"
        "404":
          $ref: "../../../../common/src/main/openapi/common.yaml#/components/responses/404"
  /app-manager/apps/registered/{app}/bundle.tar.gz:
    get:
      tags: [appManager]
      x-jvm-package: appManager
      operationId: "getAppBundle"
      parameters:
        - name: app
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/GetAppBundleResponse"
        "404":
          $ref: "../../../../common/src/main/openapi/common.yaml#/components/responses/404"
  /app-manager/apps/register:
    post:
      tags: [appManager]
      x-jvm-package: appManager
      operationId: "registerApp"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                app_bundle:
                  type: string
                  format: binary
              required:
                - app_bundle
      responses:
        "201":
          description: ok
        "409":
          $ref: "../../../../common/src/main/openapi/common.yaml#/components/responses/409"
        "400":
          $ref: "../../../../common/src/main/openapi/common.yaml#/components/responses/400"

components:
  schemas:
    OnboardUserRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string

    OnboardUserResponse:
      type: object
      required:
        - party_id
      properties:
        party_id:
          type: string

    RegistrationRequest:
      type: object
      nullable: true

    RegistrationResponse:
      type: object
      required:
        - party_id
      properties:
        party_id:
          type: string

    GetValidatorUserInfoResponse:
      type: object
      required:
        - party_id
        - user_name
        - featured
      properties:
        party_id:
          type: string
        user_name:
          type: string
        featured:
          type: boolean

    ListUsersResponse:
      type: object
      required:
        - usernames
      properties:
        usernames:
          type: array
          items:
            type: string

    AuthorizeResponse:
      type: object
      required:
        - redirect_uri
      properties:
        redirect_uri:
          type: string

    OpenIDConfigurationResponse:
      type: object
      required:
        - issuer
        - authorization_endpoint
        - token_endpoint
        - jwks_uri
      properties:
        issuer:
          type: string
        authorization_endpoint:
          type: string
        token_endpoint:
          type: string
        jwks_uri:
          type: string

    JwksResponse:
      type: object
      properties:
        keys:
          type: array
          items:
            "$ref": "#/components/schemas/Jwk"
      required:
        - keys

    Jwk:
      type: object
      properties:
        kid:
          type: string
        kty:
          type: string
        alg:
          type: string
        use:
          type: string
        n:
          type: string
        e:
          type: string
      required:
        - kid
        - kty
        - alg
        - use
        - n
        - e

    TokenResponse:
      type: object
      properties:
        access_token:
          type: string
        token_type:
          type: string
        # TODO(#6839): consider adding expires_in, refresh_token, scope
      required:
        - access_token
        - token_type

    ListInstalledAppsResponse:
      type: object
      required:
        - apps
      properties:
        apps:
          type: array
          items:
            "$ref": "#/components/schemas/InstalledApp"

    ListRegisteredAppsResponse:
      type: object
      required:
        - apps
      properties:
        apps:
          type: array
          items:
            "$ref": "#/components/schemas/RegisteredApp"

    InstalledApp:
      type: object
      required:
        - name
        - url
      properties:
        name:
          type: string
        url:
          type: string

    RegisteredApp:
      type: object
      required:
        - name
        - manifest_url
      properties:
        name:
          type: string
        manifest_url:
          type: string

    Manifest:
      type: object
      required:
        - name
        - version
        - bundle
        - ui_url
        - domains
      properties:
        name:
          type: string
        version:
          type: string
        bundle:
          type: string
        ui_url:
          type: string
        domains:
          type: array
          items:
            "$ref": "#/components/schemas/Domain"

    Domain:
      type: object
      required:
        - alias
        - url
      properties:
        alias:
          type: string
        url:
          type: string

    GetAppBundleResponse:
      type: object
      required:
        - base64_bundle
      properties:
        # base64 because guardrail doesn't support generating binary files on the client side
        base64_bundle:
          type: string

    InstallAppRequest:
      type: object
      required:
        - manifest_url
      properties:
        manifest_url:
          type: string
