openapi: 3.0.0
info:
  title: Validator API
  version: 0.0.1
tags:
  - name: validator
paths:
  /validator-user:
    get:
      tags: [validator]
      x-jvm-package: validator
      operationId: "getValidatorUserInfo"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/GetValidatorUserInfoResponse"
  /register:
    post:
      tags: [validator]
      x-jvm-package: validator
      operationId: "register"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/RegistrationRequest"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/RegistrationResponse"
  /users:
    post:
      tags: [validator]
      x-jvm-package: validator
      operationId: "onboardUser"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/OnboardUserRequest"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/OnboardUserResponse"
    get:
      tags: [validator]
      x-jvm-package: validator
      operationId: "listUsers"
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ListUsersResponse"

  /users/offboard:
    post:
      tags: [validator]
      x-jvm-package: validator
      operationId: "offboardUser"
      parameters:
        - in: query
          name: username
          required: true
          schema:
            type: string
      responses:
        "200":
          description: ok
        "404":
          description: not_found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    OnboardUserRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string

    OnboardUserResponse:
      type: object
      required:
        - party_id
      properties:
        party_id:
          type: string

    RegistrationRequest:
      type: object
      nullable: true

    RegistrationResponse:
      type: object
      required:
        - party_id
      properties:
        party_id:
          type: string

    GetValidatorUserInfoResponse:
      type: object
      required:
        - party_id
        - user_name
      properties:
        party_id:
          type: string
        user_name:
          type: string

    ListUsersResponse:
      type: object
      required:
        - usernames
      properties:
        usernames:
          type: array
          items:
            type: string

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
