apiVersion: apps/v1

kind: Deployment
metadata:
  name: docs-deployment
  labels:
    app: docs

spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
      - name: docs
        image: docs:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1

kind: Service
metadata:
  name: docs-service

spec:
  type: NodePort
  selector:
      app: docs
  ports:
    - port: 80
