!include(base-sv.yaml)
pruning:
  cometbft:
    retainBlocks: 2000 # corresponds to a retention period of ~2 hours
svApp:
  resources:
    limits:
      cpu: "3"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 2Gi
scanApp:
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: "2"
      memory: 2Gi
participant:
  resources:
    requests:
      cpu: "1"
sequencer:
  # formerly the effect of `SEQUENCER_LOW_RESOURCES=true`
  resources:
    limits:
      cpu: "3"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 2Gi
mediator:
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 2Gi
cometbft:
  resources:
    limits:
      memory: 4Gi
    requests:
      memory: 2Gi
