package com.daml.network.integration.tests

import com.daml.network.codegen.java.cc.api.v1
import com.daml.network.codegen.java.cc.round.{IssuingMiningRound, OpenMiningRound}
import com.daml.network.console.{
  WalletAppBackendReference,
  WalletAppClientReference,
  WalletAppReference,
}
import com.daml.network.environment.CoinEnvironmentImpl
import com.daml.network.integration.CoinEnvironmentDefinition
import com.daml.network.util.{CoinUtil, CommonCoinAppInstanceReferences, Proto}
import com.daml.network.wallet.admin.api.client.commands.GrpcWalletAppClient
import com.digitalasset.canton.console.CommandFailure
import com.digitalasset.canton.integration.*
import com.digitalasset.canton.topology.PartyId

import java.time.Duration
import scala.annotation.nowarn
import scala.concurrent.duration.*
import scala.jdk.CollectionConverters.*
import scala.jdk.OptionConverters.*

/** Analogue to Canton's CommunityTests */
object CoinTests {
  type CoinTestConsoleEnvironment = TestConsoleEnvironment[CoinEnvironmentImpl]
  type SharedCoinEnvironment =
    SharedEnvironment[CoinEnvironmentImpl, CoinTestConsoleEnvironment]
  type IsolatedCoinEnvironments =
    IsolatedEnvironments[CoinEnvironmentImpl, CoinTestConsoleEnvironment]

  trait CoinIntegrationTest
      extends BaseIntegrationTest[CoinEnvironmentImpl, CoinTestConsoleEnvironment]
      with IsolatedCoinEnvironments
      with CommonCoinAppInstanceReferences {

    override def environmentDefinition
        : BaseEnvironmentDefinition[CoinEnvironmentImpl, CoinTestConsoleEnvironment] =
      CoinEnvironmentDefinition
        .simpleTopology(this.getClass.getSimpleName)

    // Advance time by `duration`; works only if the used Canton instance uses simulated time.
    protected def advanceTime(
        duration: Duration
    )(implicit env: CoinTestConsoleEnvironment): Unit =
      clue(s"attempting to advance time by $duration") {
        if (duration.isNegative()) {
          fail("Cannot advance time by negative duration.");
        } else if (!duration.isZero()) {
          // it doesn't seem to matter which participant we run these from - all get synced
          val now = svc.remoteParticipant.ledger_api.time.get()
          try {
            // actually advance the time
            logger.info(s"advancing time by $duration ...")
            svc.remoteParticipant.ledger_api.time.set(now, now.plus(duration))
          } catch {
            case _: CommandFailure =>
              fail(
                "Could not advance time. " +
                  "Is Canton configured with `parameters.clock.type = sim-clock`?"
              )
          }
          // We don't get feedback about the success of setting the time here, so we check ourselves.
          if (svc.remoteParticipant.ledger_api.time.get() == now) {
            fail(
              "Could not advance time. " +
                "Are participants configured with `testing-time.type = monotonic-time`?"
            )
          }
        }
      }

    /** This function advances time by ~one tick and waits for the SVC round management automation for open, summarizing
      * and issuing rounds to finish processing the events generated by the new time.
      * This function does not wait for the closed round automation.
      */
    @nowarn("msg=match may not be exhaustive")
    def advanceRoundsByOneTick(implicit env: CoinTestConsoleEnvironment) = {

      val Seq(lowestOpen, middleOpen, highestOpen) =
        aliceWalletBackend.remoteParticipant.ledger_api.acs
          .filterJava(OpenMiningRound.COMPANION)(
            aliceValidator.getValidatorPartyId()
          )
          .map(_.data.round.number)

      val previousIssuingRounds = aliceWalletBackend.remoteParticipant.ledger_api.acs
        .filterJava(IssuingMiningRound.COMPANION)(
          aliceValidator.getValidatorPartyId()
        )
        .map(_.data.round.number)

      // not exactly 150s because of the skew parameter.
      actAndCheck("advancing time", advanceTime(Duration.ofSeconds(160)))(
        s"waiting for open and issuing round automation (should create OR ${highestOpen + 1}, should advance IR ${previousIssuingRounds}",
        _ =>
          eventually(5.seconds) {
            val Seq(newLowestOpen, newMiddleOpen, newHighestOpen) =
              aliceWalletBackend.remoteParticipant.ledger_api.acs
                .filterJava(OpenMiningRound.COMPANION)(
                  aliceValidator.getValidatorPartyId()
                )
                .map(_.data.round.number)
                .sorted

            newLowestOpen shouldBe lowestOpen + 1
            newLowestOpen shouldBe middleOpen
            newMiddleOpen shouldBe highestOpen
            newHighestOpen shouldBe highestOpen + 1

            val newIssuingRounds = aliceWalletBackend.remoteParticipant.ledger_api.acs
              .filterJava(IssuingMiningRound.COMPANION)(
                aliceValidator.getValidatorPartyId()
              )
              .map(_.data.round.number)
            if (previousIssuingRounds.size < 3)
              newIssuingRounds.size shouldBe previousIssuingRounds.size + 1
            else {
              val Seq(lowestIssuing, middleIssuing, highestIssuing) = previousIssuingRounds
              newIssuingRounds should have size 3
              val Seq(newLowestIssuing, newMiddleIssuing, newHighestIssuing) = newIssuingRounds

              newLowestIssuing shouldBe lowestIssuing + 1
              newLowestIssuing shouldBe middleIssuing
              newMiddleIssuing shouldBe highestIssuing
              newHighestIssuing shouldBe highestIssuing + 1
            }
          },
      )
    }

    /** @param expectedQuantityRanges : lower and upper bounds for coins sorted by their initial quantity in ascending order. */
    def checkWallet(
        walletParty: PartyId,
        wallet: WalletAppReference,
        expectedQuantityRanges: Seq[(BigDecimal, BigDecimal)],
    ): Unit = clue(s"checking wallet with $expectedQuantityRanges") {
      eventually(10.seconds, 500.millis) {
        val coins =
          wallet.list().coins.sortBy(coin => coin.contract.payload.quantity.initialQuantity)
        coins should have size (expectedQuantityRanges.size.toLong)
        coins
          .zip(expectedQuantityRanges)
          .foreach { case (coin, quantityBounds) =>
            coin.contract.payload.owner shouldBe walletParty.toPrim
            val coinQuantity =
              coin.contract.payload.quantity
            assertInRange(coinQuantity.initialQuantity, quantityBounds)
            coinQuantity.ratePerRound shouldBe
              CoinUtil.defaultHoldingFee
          }
      }
    }

    def checkBalance(
        wallet: WalletAppClientReference,
        expectedRound: Long,
        expectedUQRange: (BigDecimal, BigDecimal),
        expectedLQRange: (BigDecimal, BigDecimal),
        expectedHRange: (BigDecimal, BigDecimal),
    ): Unit = clue(s"Checking balance in round $expectedRound") {
      eventually() {
        val balance = wallet.balance()
        balance.round shouldBe expectedRound
        assertInRange(balance.unlockedQty, expectedUQRange)
        assertInRange(balance.lockedQty, expectedLQRange)
        assertInRange(balance.holdingFees, expectedHRange)
      }
    }

    def assertInRange(value: BigDecimal, range: (BigDecimal, BigDecimal)): Unit = {
      value should (be >= range._1 and be <= range._2)
    }

    def lockCoins(
        userWallet: WalletAppBackendReference,
        userParty: PartyId,
        validatorParty: PartyId,
        coins: Seq[GrpcWalletAppClient.CoinPosition],
        quantity: Int,
        transferContext: v1.coin.AppTransferContext,
    ): Unit = clue(s"Locking $quantity coins for $userParty") {
      val coinOpt = coins.find(_.effectiveQuantity >= quantity)
      val expirationOpt = Proto.decode(Proto.Timestamp)(
        20000000000000000L // Wed May 18 2033
      )

      (coinOpt, expirationOpt) match {
        case (Some(coin), Right(expiration)) => {
          userWallet.remoteParticipant.ledger_api.commands.submitJava(
            Seq(userParty, validatorParty),
            optTimeout = None,
            commands = transferContext.coinRules
              .exerciseCoinRules_Transfer(
                new v1.coin.Transfer(
                  userParty.toProtoPrimitive,
                  userParty.toProtoPrimitive,
                  Seq[v1.coin.TransferInput](
                    new v1.coin.transferinput.InputCoin(
                      coin.contract.contractId.toInterface(v1.coin.Coin.INTERFACE)
                    )
                  ).asJava,
                  Seq[v1.coin.TransferOutput](
                    new v1.coin.transferoutput.OutputSenderCoin(
                      Some(BigDecimal(quantity).bigDecimal).toJava,
                      Some(
                        new v1.coin.TimeLock(
                          Seq(userParty.toProtoPrimitive).asJava,
                          expiration,
                        )
                      ).toJava,
                    ),
                    new v1.coin.transferoutput.OutputSenderCoin(
                      None.toJava,
                      None.toJava,
                    ),
                  ).asJava,
                  "lock coins",
                ),
                new v1.coin.TransferContext(
                  transferContext.openMiningRound,
                  Map.empty[v1.round.Round, v1.round.IssuingMiningRound.ContractId].asJava,
                  Map.empty[String, v1.coin.ValidatorRight.ContractId].asJava,
                ),
              )
              .commands
              .asScala
              .toSeq,
          )
        }
        case _ => {
          coinOpt shouldBe a[Some[_]]
          expirationOpt shouldBe a[Right[_, _]]
        }
      }
    }

    /** A function abstracting the common pattern of acting and then waiting for the action to
      * eventually have its expected results.
      */
    def actAndCheck[T, U](
        action: String,
        actionExpr: => T,
    )(check: String, checkFun: T => U): (T, U) = {
      {
        val x = clue(s"(act) $action")(actionExpr)
        clue(s"(check) $check") {
          eventually() {
            val y = checkFun(x)
            (x, y)
          }
        }
      }
    }
  }
}
