_client_credentials_auth_config {
  type = "client-credentials"
  well-known-config-url = ${?CN_APP_VALIDATOR_LEDGER_API_AUTH_URL}
  client-id = ${?CN_APP_VALIDATOR_LEDGER_API_AUTH_CLIENT_ID}
  client-secret = ${?CN_APP_VALIDATOR_LEDGER_API_AUTH_CLIENT_SECRET}
  # TODO(#1837) use actual audience of the target participant
  audience = "https://canton.network.global"
}

canton {
  validator-apps {
    validator_backend {
      storage.type = memory
      admin-api = {
        address = "0.0.0.0"
        port = 5003
      }
      remote-participant = {
        admin-api = {
          address = ${CN_APP_VALIDATOR_PARTICIPANT_ADDRESS}
          port = 5002
        }
        ledger-api = {
          client-config = {
            address = ${CN_APP_VALIDATOR_PARTICIPANT_ADDRESS}
            port = 5001
          }
          auth-config = ${_client_credentials_auth_config}
        }
      }
      remote-scan = {
        admin-api.port = 5012
        admin-api.address = "scan-app.svc"
        admin-api.url = "http://scan-app.svc:6012"
      }
      ledger-api-user = ${CN_APP_VALIDATOR_LEDGER_API_AUTH_USER_NAME}
      validator-wallet-user = ${?CN_APP_VALIDATOR_WALLET_USER_NAME}
      wallet-service-user = ${CN_APP_WALLET_LEDGER_API_AUTH_USER_NAME}
      auth {
        algorithm = "rs-256"
        audience = "https://canton.network.global"
        jwks-url = "https://canton-network-dev.us.auth0.com/.well-known/jwks.json"
      }
      app-instances {
      }
      onboarding = {
        # our onboarding sponsor is SV1
        remote-sv.admin-api.port = 5014
        remote-sv.admin-api.url = "http://sv-app.sv-1:6014"
        # secret must be obtained from SV1 first; we do this in `pre-bootstrap.sh`
        secret = "PLACEHOLDER"
      }
      domains {
        global = "global"
      }
    }
  }
  features.enable-testing-commands = yes
}
