canton {
  parameters {
    manual-start = no
  }

  domains {
    svc_domain {
      storage.type = memory

      public-api {
        address = "0.0.0.0"
        port = 6018
      }

      admin-api {
        address = "0.0.0.0"
        port = 6019
      }
    }
  }

  monitoring {
    metrics.reporters = [{
      type = jmx
    }]
  }
}