// Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

package com.daml.network.wallet.store

import com.daml.network.codegen.java.splice.wallet.{
  buytrafficrequest as trafficRequestCodegen,
  install as installCodegen,
  payment as paymentCodegen,
  subscriptions as subsCodegen,
  transferoffer as transferCodegen,
}
import com.daml.network.util.ExerciseNodeCompanion

// TODO(#3984): This entire file could have been generated by some codegen

object WalletAppInstall_ExecuteBatch
    extends ExerciseNodeCompanion.Mk(
      template = installCodegen.WalletAppInstall.COMPANION,
      choice = installCodegen.WalletAppInstall.CHOICE_WalletAppInstall_ExecuteBatch,
    )

object WalletAppInstall_CreateTransferOffer
    extends ExerciseNodeCompanion.Mk(
      template = installCodegen.WalletAppInstall.COMPANION,
      choice = installCodegen.WalletAppInstall.CHOICE_WalletAppInstall_CreateTransferOffer,
    )

case object TransferOffer_Accept
    extends ExerciseNodeCompanion.Mk(
      template = transferCodegen.TransferOffer.COMPANION,
      choice = transferCodegen.TransferOffer.CHOICE_TransferOffer_Accept,
    )

case object TransferOffer_Reject
    extends ExerciseNodeCompanion.Mk(
      template = transferCodegen.TransferOffer.COMPANION,
      choice = transferCodegen.TransferOffer.CHOICE_TransferOffer_Reject,
    )

case object TransferOffer_Withdraw
    extends ExerciseNodeCompanion.Mk(
      template = transferCodegen.TransferOffer.COMPANION,
      choice = transferCodegen.TransferOffer.CHOICE_TransferOffer_Withdraw,
    )

case object TransferOffer_Expire
    extends ExerciseNodeCompanion.Mk(
      template = transferCodegen.TransferOffer.COMPANION,
      choice = transferCodegen.TransferOffer.CHOICE_TransferOffer_Expire,
    )

object AcceptedTransferOffer_Complete
    extends ExerciseNodeCompanion.Mk(
      template = transferCodegen.AcceptedTransferOffer.COMPANION,
      choice = transferCodegen.AcceptedTransferOffer.CHOICE_AcceptedTransferOffer_Complete,
    )

case object AcceptedTransferOffer_Expire
    extends ExerciseNodeCompanion.Mk(
      template = transferCodegen.AcceptedTransferOffer.COMPANION,
      choice = transferCodegen.AcceptedTransferOffer.CHOICE_AcceptedTransferOffer_Expire,
    )

case object AcceptedTransferOffer_Abort
    extends ExerciseNodeCompanion.Mk(
      template = transferCodegen.AcceptedTransferOffer.COMPANION,
      choice = transferCodegen.AcceptedTransferOffer.CHOICE_AcceptedTransferOffer_Abort,
    )

case object AcceptedTransferOffer_Withdraw
    extends ExerciseNodeCompanion.Mk(
      template = transferCodegen.AcceptedTransferOffer.COMPANION,
      choice = transferCodegen.AcceptedTransferOffer.CHOICE_AcceptedTransferOffer_Withdraw,
    )

object AppPaymentRequest_Accept
    extends ExerciseNodeCompanion.Mk(
      template = paymentCodegen.AppPaymentRequest.COMPANION,
      choice = paymentCodegen.AppPaymentRequest.CHOICE_AppPaymentRequest_Accept,
    )

object AcceptedAppPayment_Collect
    extends ExerciseNodeCompanion.Mk(
      template = paymentCodegen.AcceptedAppPayment.COMPANION,
      choice = paymentCodegen.AcceptedAppPayment.CHOICE_AcceptedAppPayment_Collect,
    )

object AcceptedAppPayment_Reject
    extends ExerciseNodeCompanion.Mk(
      template = paymentCodegen.AcceptedAppPayment.COMPANION,
      choice = paymentCodegen.AcceptedAppPayment.CHOICE_AcceptedAppPayment_Reject,
    )

object AcceptedAppPayment_Expire
    extends ExerciseNodeCompanion.Mk(
      template = paymentCodegen.AcceptedAppPayment.COMPANION,
      choice = paymentCodegen.AcceptedAppPayment.CHOICE_AcceptedAppPayment_Expire,
    )

object WalletAppInstall_CreateBuyTrafficRequest
    extends ExerciseNodeCompanion.Mk(
      template = installCodegen.WalletAppInstall.COMPANION,
      choice = installCodegen.WalletAppInstall.CHOICE_WalletAppInstall_CreateBuyTrafficRequest,
    )

object BuyTrafficRequest_Complete
    extends ExerciseNodeCompanion.Mk(
      template = trafficRequestCodegen.BuyTrafficRequest.COMPANION,
      choice = trafficRequestCodegen.BuyTrafficRequest.CHOICE_BuyTrafficRequest_Complete,
    )

case object BuyTrafficRequest_Cancel
    extends ExerciseNodeCompanion.Mk(
      template = trafficRequestCodegen.BuyTrafficRequest.COMPANION,
      choice = trafficRequestCodegen.BuyTrafficRequest.CHOICE_BuyTrafficRequest_Cancel,
    )

case object BuyTrafficRequest_Expire
    extends ExerciseNodeCompanion.Mk(
      template = trafficRequestCodegen.BuyTrafficRequest.COMPANION,
      choice = trafficRequestCodegen.BuyTrafficRequest.CHOICE_BuyTrafficRequest_Expire,
    )

object SubscriptionRequest_AcceptAndMakePayment
    extends ExerciseNodeCompanion.Mk(
      template = subsCodegen.SubscriptionRequest.COMPANION,
      choice = subsCodegen.SubscriptionRequest.CHOICE_SubscriptionRequest_AcceptAndMakePayment,
    )

object SubscriptionInitialPayment_Collect
    extends ExerciseNodeCompanion.Mk(
      template = subsCodegen.SubscriptionInitialPayment.COMPANION,
      choice = subsCodegen.SubscriptionInitialPayment.CHOICE_SubscriptionInitialPayment_Collect,
    )

object SubscriptionInitialPayment_Reject
    extends ExerciseNodeCompanion.Mk(
      template = subsCodegen.SubscriptionInitialPayment.COMPANION,
      choice = subsCodegen.SubscriptionInitialPayment.CHOICE_SubscriptionInitialPayment_Reject,
    )

object SubscriptionInitialPayment_Expire
    extends ExerciseNodeCompanion.Mk(
      template = subsCodegen.SubscriptionInitialPayment.COMPANION,
      choice = subsCodegen.SubscriptionInitialPayment.CHOICE_SubscriptionInitialPayment_Expire,
    )

object SubscriptionIdleState_MakePayment
    extends ExerciseNodeCompanion.Mk(
      template = subsCodegen.SubscriptionIdleState.COMPANION,
      choice = subsCodegen.SubscriptionIdleState.CHOICE_SubscriptionIdleState_MakePayment,
    )

object SubscriptionIdleState_ExpireSubscription
    extends ExerciseNodeCompanion.Mk(
      template = subsCodegen.SubscriptionIdleState.COMPANION,
      choice = subsCodegen.SubscriptionIdleState.CHOICE_SubscriptionIdleState_ExpireSubscription,
    )

object SubscriptionPayment_Collect
    extends ExerciseNodeCompanion.Mk(
      template = subsCodegen.SubscriptionPayment.COMPANION,
      choice = subsCodegen.SubscriptionPayment.CHOICE_SubscriptionPayment_Collect,
    )

object SubscriptionPayment_Reject
    extends ExerciseNodeCompanion.Mk(
      template = subsCodegen.SubscriptionPayment.COMPANION,
      choice = subsCodegen.SubscriptionPayment.CHOICE_SubscriptionPayment_Reject,
    )

object SubscriptionPayment_Expire
    extends ExerciseNodeCompanion.Mk(
      template = subsCodegen.SubscriptionPayment.COMPANION,
      choice = subsCodegen.SubscriptionPayment.CHOICE_SubscriptionPayment_Expire,
    )
