package com.daml.network.wallet.store

import com.daml.ledger.javaapi.data.DamlOptional
import com.daml.network.codegen.java.cc.coin as coinCodegen
import com.daml.network.codegen.java.cn.svcrules as svcCodegen
import com.daml.network.codegen.java.cn.wallet.{
  install as installCodegen,
  payment as paymentCodegen,
  subscriptions as subsCodegen,
  transferoffer as transferCodegen,
}
import com.daml.network.codegen.java.cn.wallet.subscriptions.SubscriptionPayment
import com.daml.network.codegen.java.da.types as daTypes
import com.daml.network.util.ExerciseNodeCompanion

// TODO(#3984): This entire file could have been generated by some codegen

object WalletAppInstall_ExecuteBatch extends ExerciseNodeCompanion {
  override type Tpl = installCodegen.WalletAppInstall
  override type Arg = installCodegen.WalletAppInstall_ExecuteBatch
  override type Res = installCodegen.ExecuteBatchResult

  override val templateOrInterface = Left(installCodegen.WalletAppInstall.COMPANION)
  override val choice = installCodegen.WalletAppInstall.CHOICE_WalletAppInstall_ExecuteBatch

  override val argDecoder = installCodegen.WalletAppInstall_ExecuteBatch.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = installCodegen.ExecuteBatchResult.valueDecoder()
  override def resToValue(res: Res) = res.toValue
}

object WalletAppInstall_CreateTransferOffer extends ExerciseNodeCompanion {
  override type Tpl = installCodegen.WalletAppInstall
  override type Arg = installCodegen.WalletAppInstall_CreateTransferOffer
  override type Res = transferCodegen.TransferOffer.ContractId

  override val templateOrInterface = Left(installCodegen.WalletAppInstall.COMPANION)
  override val choice = installCodegen.WalletAppInstall.CHOICE_WalletAppInstall_CreateTransferOffer

  override val argDecoder = installCodegen.WalletAppInstall_CreateTransferOffer.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = result =>
    new transferCodegen.TransferOffer.ContractId(result.asContractId().get.getValue)
  override def resToValue(res: Res) = res.toValue
}

case object TransferOffer_Accept extends ExerciseNodeCompanion {
  override type Tpl = transferCodegen.TransferOffer
  override type Arg = transferCodegen.TransferOffer_Accept
  override type Res = transferCodegen.AcceptedTransferOffer.ContractId

  override val templateOrInterface = Left(transferCodegen.TransferOffer.COMPANION)
  override val choice = transferCodegen.TransferOffer.CHOICE_TransferOffer_Accept

  override val argDecoder = transferCodegen.TransferOffer_Accept.valueDecoder()

  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = result =>
    new transferCodegen.AcceptedTransferOffer.ContractId(result.asContractId().get.getValue)

  override def resToValue(res: Res) = res.toValue
}

case object TransferOffer_Reject extends ExerciseNodeCompanion {
  override type Tpl = transferCodegen.TransferOffer
  override type Arg = transferCodegen.TransferOffer_Reject
  override type Res = transferCodegen.TransferOfferTrackingInfo

  override val templateOrInterface = Left(transferCodegen.TransferOffer.COMPANION)
  override val choice = transferCodegen.TransferOffer.CHOICE_TransferOffer_Reject

  override val argDecoder = transferCodegen.TransferOffer_Reject.valueDecoder()

  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = transferCodegen.TransferOfferTrackingInfo.valueDecoder()
  override def resToValue(res: Res) = res.toValue
}

case object TransferOffer_Withdraw extends ExerciseNodeCompanion {
  override type Tpl = transferCodegen.TransferOffer
  override type Arg = transferCodegen.TransferOffer_Withdraw
  override type Res = transferCodegen.TransferOfferTrackingInfo

  override val templateOrInterface = Left(transferCodegen.TransferOffer.COMPANION)
  override val choice = transferCodegen.TransferOffer.CHOICE_TransferOffer_Withdraw

  override val argDecoder = transferCodegen.TransferOffer_Withdraw.valueDecoder()

  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = transferCodegen.TransferOfferTrackingInfo.valueDecoder()
  override def resToValue(res: Res) = res.toValue
}

case object TransferOffer_Expire extends ExerciseNodeCompanion {
  override type Tpl = transferCodegen.TransferOffer
  override type Arg = transferCodegen.TransferOffer_Expire
  override type Res = transferCodegen.TransferOfferTrackingInfo

  override val templateOrInterface = Left(transferCodegen.TransferOffer.COMPANION)
  override val choice = transferCodegen.TransferOffer.CHOICE_TransferOffer_Expire

  override val argDecoder = transferCodegen.TransferOffer_Expire.valueDecoder()

  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = transferCodegen.TransferOfferTrackingInfo.valueDecoder()
  override def resToValue(res: Res) = res.toValue
}

object AcceptedTransferOffer_Complete extends ExerciseNodeCompanion {
  override type Tpl = transferCodegen.AcceptedTransferOffer
  override type Arg = transferCodegen.AcceptedTransferOffer_Complete
  override type Res = daTypes.Tuple2[
    daTypes.Tuple2[coinCodegen.TransferResult, transferCodegen.TransferOfferTrackingInfo],
    java.util.Optional[
      coinCodegen.Coin.ContractId
    ],
  ]

  override val templateOrInterface = Left(transferCodegen.AcceptedTransferOffer.COMPANION)
  override val choice = transferCodegen.AcceptedTransferOffer.CHOICE_AcceptedTransferOffer_Complete

  override val argDecoder = transferCodegen.AcceptedTransferOffer_Complete.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = daTypes.Tuple2.valueDecoder(
    daTypes.Tuple2.valueDecoder(
      coinCodegen.TransferResult.valueDecoder(),
      transferCodegen.TransferOfferTrackingInfo.valueDecoder(),
    ),
    x =>
      x.asOptional()
        .get
        .getValue
        .map(cid => new coinCodegen.Coin.ContractId(cid.asContractId().get.getValue)),
  )
  override def resToValue(res: Res) =
    res.toValue(_.toValue(_.toValue, _.toValue), x => DamlOptional.of(x.map(_.toValue)))
}

case object AcceptedTransferOffer_Expire extends ExerciseNodeCompanion {
  override type Tpl = transferCodegen.AcceptedTransferOffer
  override type Arg = transferCodegen.AcceptedTransferOffer_Expire
  override type Res = transferCodegen.TransferOfferTrackingInfo

  override val templateOrInterface = Left(transferCodegen.AcceptedTransferOffer.COMPANION)
  override val choice = transferCodegen.AcceptedTransferOffer.CHOICE_AcceptedTransferOffer_Expire

  override val argDecoder = transferCodegen.AcceptedTransferOffer_Expire.valueDecoder()

  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = transferCodegen.TransferOfferTrackingInfo.valueDecoder()
  override def resToValue(res: Res) = res.toValue
}

case object AcceptedTransferOffer_Abort extends ExerciseNodeCompanion {
  override type Tpl = transferCodegen.AcceptedTransferOffer
  override type Arg = transferCodegen.AcceptedTransferOffer_Abort
  override type Res = transferCodegen.TransferOfferTrackingInfo

  override val templateOrInterface = Left(transferCodegen.AcceptedTransferOffer.COMPANION)
  override val choice = transferCodegen.AcceptedTransferOffer.CHOICE_AcceptedTransferOffer_Abort

  override val argDecoder = transferCodegen.AcceptedTransferOffer_Abort.valueDecoder()

  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = transferCodegen.TransferOfferTrackingInfo.valueDecoder()

  override def resToValue(res: Res) = res.toValue
}

case object AcceptedTransferOffer_Withdraw extends ExerciseNodeCompanion {
  override type Tpl = transferCodegen.AcceptedTransferOffer
  override type Arg = transferCodegen.AcceptedTransferOffer_Withdraw
  override type Res = transferCodegen.TransferOfferTrackingInfo

  override val templateOrInterface = Left(transferCodegen.AcceptedTransferOffer.COMPANION)
  override val choice = transferCodegen.AcceptedTransferOffer.CHOICE_AcceptedTransferOffer_Withdraw

  override val argDecoder = transferCodegen.AcceptedTransferOffer_Withdraw.valueDecoder()

  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = transferCodegen.TransferOfferTrackingInfo.valueDecoder()
  override def resToValue(res: Res) = res.toValue
}

object AppPaymentRequest_Accept extends ExerciseNodeCompanion {
  override type Tpl = paymentCodegen.AppPaymentRequest
  override type Arg = paymentCodegen.AppPaymentRequest_Accept
  override type Res =
    daTypes.Tuple2[paymentCodegen.AcceptedAppPayment.ContractId, java.util.Optional[
      coinCodegen.Coin.ContractId
    ]]

  override val templateOrInterface = Left(paymentCodegen.AppPaymentRequest.COMPANION)
  override val choice = paymentCodegen.AppPaymentRequest.CHOICE_AppPaymentRequest_Accept

  override val argDecoder = paymentCodegen.AppPaymentRequest_Accept.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = daTypes.Tuple2.valueDecoder(
    cid => new paymentCodegen.AcceptedAppPayment.ContractId(cid.asContractId().get.getValue),
    x =>
      x.asOptional()
        .get
        .getValue
        .map(cid => new coinCodegen.Coin.ContractId(cid.asContractId().get.getValue)),
  )
  override def resToValue(res: Res) = res.toValue(
    _.toValue,
    x => DamlOptional.of(x.map(_.toValue)),
  )
}

object AcceptedAppPayment_Collect extends ExerciseNodeCompanion {
  override type Tpl = paymentCodegen.AcceptedAppPayment
  override type Arg = paymentCodegen.AcceptedAppPayment_Collect
  override type Res = paymentCodegen.AcceptedAppPayment_Collect_Result

  override val templateOrInterface = Left(paymentCodegen.AcceptedAppPayment.COMPANION)
  override val choice = paymentCodegen.AcceptedAppPayment.CHOICE_AcceptedAppPayment_Collect

  override val argDecoder = paymentCodegen.AcceptedAppPayment_Collect.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = paymentCodegen.AcceptedAppPayment_Collect_Result.valueDecoder()
  override def resToValue(res: Res) = res.toValue
}

object AcceptedAppPayment_Reject extends ExerciseNodeCompanion {
  override type Tpl = paymentCodegen.AcceptedAppPayment
  override type Arg = paymentCodegen.AcceptedAppPayment_Reject
  override type Res = coinCodegen.CoinCreateSummary[coinCodegen.Coin.ContractId]

  override val templateOrInterface = Left(paymentCodegen.AcceptedAppPayment.COMPANION)
  override val choice = paymentCodegen.AcceptedAppPayment.CHOICE_AcceptedAppPayment_Reject

  override val argDecoder = paymentCodegen.AcceptedAppPayment_Reject.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder =
    coinCodegen.CoinCreateSummary.valueDecoder(cid =>
      new coinCodegen.Coin.ContractId(cid.asContractId().get().getValue)
    )
  override def resToValue(res: Res) = res.toValue(_.toValue)
}

object AcceptedAppPayment_Expire extends ExerciseNodeCompanion {
  override type Tpl = paymentCodegen.AcceptedAppPayment
  override type Arg = paymentCodegen.AcceptedAppPayment_Expire
  override type Res = coinCodegen.CoinCreateSummary[coinCodegen.Coin.ContractId]

  override val templateOrInterface = Left(paymentCodegen.AcceptedAppPayment.COMPANION)
  override val choice = paymentCodegen.AcceptedAppPayment.CHOICE_AcceptedAppPayment_Expire

  override val argDecoder = paymentCodegen.AcceptedAppPayment_Expire.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder =
    coinCodegen.CoinCreateSummary.valueDecoder(cid =>
      new coinCodegen.Coin.ContractId(cid.asContractId().get().getValue)
    )
  override def resToValue(res: Res) = res.toValue(_.toValue)
}

object SubscriptionRequest_AcceptAndMakePayment extends ExerciseNodeCompanion {
  override type Tpl = subsCodegen.SubscriptionRequest
  override type Arg = subsCodegen.SubscriptionRequest_AcceptAndMakePayment
  override type Res =
    daTypes.Tuple2[subsCodegen.SubscriptionInitialPayment.ContractId, java.util.Optional[
      coinCodegen.Coin.ContractId
    ]]

  override val templateOrInterface = Left(subsCodegen.SubscriptionRequest.COMPANION)
  override val choice =
    subsCodegen.SubscriptionRequest.CHOICE_SubscriptionRequest_AcceptAndMakePayment

  override val argDecoder = subsCodegen.SubscriptionRequest_AcceptAndMakePayment.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = daTypes.Tuple2.valueDecoder(
    cid => new subsCodegen.SubscriptionInitialPayment.ContractId(cid.asContractId().get.getValue),
    x =>
      x.asOptional()
        .get
        .getValue
        .map(cid => new coinCodegen.Coin.ContractId(cid.asContractId().get.getValue)),
  )
  override def resToValue(res: Res) = res.toValue(_.toValue, x => DamlOptional.of(x.map(_.toValue)))
}

object SubscriptionInitialPayment_Collect extends ExerciseNodeCompanion {
  override type Tpl = subsCodegen.SubscriptionInitialPayment
  override type Arg = subsCodegen.SubscriptionInitialPayment_Collect
  override type Res = daTypes.Tuple3[
    subsCodegen.Subscription.ContractId,
    subsCodegen.SubscriptionIdleState.ContractId,
    coinCodegen.Coin.ContractId,
  ]

  override val templateOrInterface = Left(subsCodegen.SubscriptionInitialPayment.COMPANION)
  override val choice =
    subsCodegen.SubscriptionInitialPayment.CHOICE_SubscriptionInitialPayment_Collect

  override val argDecoder = subsCodegen.SubscriptionInitialPayment_Collect.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = daTypes.Tuple3.valueDecoder(
    cid => new subsCodegen.Subscription.ContractId(cid.asContractId().get().getValue),
    cid => new subsCodegen.SubscriptionIdleState.ContractId(cid.asContractId().get().getValue),
    cid => new coinCodegen.Coin.ContractId(cid.asContractId().get().getValue),
  )

  override def resToValue(res: Res) = res.toValue(
    _.toValue,
    _.toValue,
    _.toValue,
  )
}

object SubscriptionInitialPayment_Reject extends ExerciseNodeCompanion {
  override type Tpl = subsCodegen.SubscriptionInitialPayment
  override type Arg = subsCodegen.SubscriptionInitialPayment_Reject
  override type Res = coinCodegen.CoinCreateSummary[coinCodegen.Coin.ContractId]

  override val templateOrInterface = Left(subsCodegen.SubscriptionInitialPayment.COMPANION)
  override val choice =
    subsCodegen.SubscriptionInitialPayment.CHOICE_SubscriptionInitialPayment_Reject

  override val argDecoder = subsCodegen.SubscriptionInitialPayment_Reject.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder =
    coinCodegen.CoinCreateSummary.valueDecoder(cid =>
      new coinCodegen.Coin.ContractId(cid.asContractId().get().getValue)
    )
  override def resToValue(res: Res) = res.toValue(_.toValue)
}

object SubscriptionInitialPayment_Expire extends ExerciseNodeCompanion {
  override type Tpl = subsCodegen.SubscriptionInitialPayment
  override type Arg = subsCodegen.SubscriptionInitialPayment_Expire
  override type Res = coinCodegen.CoinCreateSummary[coinCodegen.Coin.ContractId]

  override val templateOrInterface = Left(subsCodegen.SubscriptionInitialPayment.COMPANION)
  override val choice =
    subsCodegen.SubscriptionInitialPayment.CHOICE_SubscriptionInitialPayment_Expire

  override val argDecoder = subsCodegen.SubscriptionInitialPayment_Expire.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder =
    coinCodegen.CoinCreateSummary.valueDecoder(cid =>
      new coinCodegen.Coin.ContractId(cid.asContractId().get().getValue)
    )
  override def resToValue(res: Res) = res.toValue(_.toValue)
}

object SubscriptionIdleState_MakePayment extends ExerciseNodeCompanion {
  override type Tpl = subsCodegen.SubscriptionIdleState
  override type Arg = subsCodegen.SubscriptionIdleState_MakePayment
  override type Res = daTypes.Tuple2[subsCodegen.SubscriptionPayment.ContractId, java.util.Optional[
    coinCodegen.Coin.ContractId
  ]]

  override val templateOrInterface = Left(subsCodegen.SubscriptionIdleState.COMPANION)
  override val choice = subsCodegen.SubscriptionIdleState.CHOICE_SubscriptionIdleState_MakePayment

  override val argDecoder = subsCodegen.SubscriptionIdleState_MakePayment.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = daTypes.Tuple2.valueDecoder(
    cid => new SubscriptionPayment.ContractId(cid.asContractId().get.getValue),
    x =>
      x.asOptional()
        .get
        .getValue
        .map(cid => new coinCodegen.Coin.ContractId(cid.asContractId().get.getValue)),
  )
  override def resToValue(res: Res) = res.toValue(_.toValue, x => DamlOptional.of(x.map(_.toValue)))
}

object SubscriptionIdleState_ExpireSubscription extends ExerciseNodeCompanion {
  override type Tpl = subsCodegen.SubscriptionIdleState
  override type Arg = subsCodegen.SubscriptionIdleState_ExpireSubscription
  override type Res = subsCodegen.TerminatedSubscription.ContractId

  override val templateOrInterface = Left(subsCodegen.SubscriptionIdleState.COMPANION)
  override val choice =
    subsCodegen.SubscriptionIdleState.CHOICE_SubscriptionIdleState_ExpireSubscription

  override val argDecoder = subsCodegen.SubscriptionIdleState_ExpireSubscription.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = result =>
    new subsCodegen.TerminatedSubscription.ContractId(result.asContractId().get.getValue)
  override def resToValue(res: Res) = res.toValue
}

object SubscriptionPayment_Collect extends ExerciseNodeCompanion {
  override type Tpl = subsCodegen.SubscriptionPayment
  override type Arg = subsCodegen.SubscriptionPayment_Collect
  override type Res = daTypes.Tuple2[
    subsCodegen.SubscriptionIdleState.ContractId,
    coinCodegen.Coin.ContractId,
  ]

  override val templateOrInterface = Left(subsCodegen.SubscriptionPayment.COMPANION)
  override val choice = subsCodegen.SubscriptionPayment.CHOICE_SubscriptionPayment_Collect

  override val argDecoder = subsCodegen.SubscriptionPayment_Collect.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = daTypes.Tuple2.valueDecoder(
    cid => new subsCodegen.SubscriptionIdleState.ContractId(cid.asContractId().get().getValue),
    cid => new coinCodegen.Coin.ContractId(cid.asContractId().get().getValue),
  )

  override def resToValue(res: Res) = res.toValue(
    _.toValue,
    _.toValue,
  )
}

object SubscriptionPayment_Reject extends ExerciseNodeCompanion {
  override type Tpl = subsCodegen.SubscriptionPayment
  override type Arg = subsCodegen.SubscriptionPayment_Reject
  override type Res = daTypes.Tuple2[
    subsCodegen.SubscriptionIdleState.ContractId,
    coinCodegen.CoinCreateSummary[coinCodegen.Coin.ContractId],
  ]

  override val templateOrInterface = Left(subsCodegen.SubscriptionPayment.COMPANION)
  override val choice = subsCodegen.SubscriptionPayment.CHOICE_SubscriptionPayment_Reject

  override val argDecoder = subsCodegen.SubscriptionPayment_Reject.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = daTypes.Tuple2.valueDecoder(
    cid => new subsCodegen.SubscriptionIdleState.ContractId(cid.asContractId().get().getValue),
    coinCodegen.CoinCreateSummary.valueDecoder(cid =>
      new coinCodegen.Coin.ContractId(cid.asContractId().get().getValue)
    ),
  )

  override def resToValue(res: Res) = res.toValue(
    _.toValue,
    _.toValue(_.toValue),
  )
}

object SubscriptionPayment_Expire extends ExerciseNodeCompanion {
  override type Tpl = subsCodegen.SubscriptionPayment
  override type Arg = subsCodegen.SubscriptionPayment_Expire
  override type Res = daTypes.Tuple2[
    subsCodegen.SubscriptionIdleState.ContractId,
    coinCodegen.CoinCreateSummary[coinCodegen.Coin.ContractId],
  ]

  override val templateOrInterface = Left(subsCodegen.SubscriptionPayment.COMPANION)
  override val choice = subsCodegen.SubscriptionPayment.CHOICE_SubscriptionPayment_Expire

  override val argDecoder = subsCodegen.SubscriptionPayment_Expire.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = daTypes.Tuple2.valueDecoder(
    cid => new subsCodegen.SubscriptionIdleState.ContractId(cid.asContractId().get().getValue),
    coinCodegen.CoinCreateSummary.valueDecoder(cid =>
      new coinCodegen.Coin.ContractId(cid.asContractId().get().getValue)
    ),
  )

  override def resToValue(res: Res) = res.toValue(
    _.toValue,
    _.toValue(_.toValue),
  )
}

object SvcRules_CollectSvReward extends ExerciseNodeCompanion {
  override type Tpl = svcCodegen.SvcRules
  override type Arg = svcCodegen.SvcRules_CollectSvReward
  override type Res = coinCodegen.CoinCreateSummary[coinCodegen.Coin.ContractId]

  override val templateOrInterface = Left(svcCodegen.SvcRules.COMPANION)
  override val choice = svcCodegen.SvcRules.CHOICE_SvcRules_CollectSvReward

  override val argDecoder = svcCodegen.SvcRules_CollectSvReward.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder =
    coinCodegen.CoinCreateSummary.valueDecoder(cid =>
      new coinCodegen.Coin.ContractId(cid.asContractId().get().getValue)
    )
  override def resToValue(res: Res) = res.toValue(_.toValue)
}
