package com.daml.network.wallet.store

import com.daml.network.codegen.java.splice.amulet as amuletCodegen
import com.daml.network.codegen.java.splice.wallet.{
  buytrafficrequest as trafficRequestCodegen,
  install as installCodegen,
  payment as paymentCodegen,
  subscriptions as subsCodegen,
  transferoffer as transferCodegen,
}
import com.daml.network.util.ExerciseNodeCompanion

// TODO(#3984): This entire file could have been generated by some codegen

object WalletAppInstall_ExecuteBatch extends ExerciseNodeCompanion {
  override type Tpl = installCodegen.WalletAppInstall
  override type Arg = installCodegen.WalletAppInstall_ExecuteBatch
  override type Res = installCodegen.ExecuteBatchResult

  override val template = installCodegen.WalletAppInstall.COMPANION
  override val choice = installCodegen.WalletAppInstall.CHOICE_WalletAppInstall_ExecuteBatch

  override val argDecoder = installCodegen.WalletAppInstall_ExecuteBatch.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = installCodegen.ExecuteBatchResult.valueDecoder()
  override def resToValue(res: Res) = res.toValue
}

object WalletAppInstall_CreateTransferOffer extends ExerciseNodeCompanion {
  override type Tpl = installCodegen.WalletAppInstall
  override type Arg = installCodegen.WalletAppInstall_CreateTransferOffer
  override type Res = installCodegen.WalletAppInstall_CreateTransferOfferResult

  override val template = installCodegen.WalletAppInstall.COMPANION
  override val choice = installCodegen.WalletAppInstall.CHOICE_WalletAppInstall_CreateTransferOffer

  override val argDecoder = installCodegen.WalletAppInstall_CreateTransferOffer.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = installCodegen.WalletAppInstall_CreateTransferOfferResult.valueDecoder
  override def resToValue(res: Res) = res.toValue
}

case object TransferOffer_Accept extends ExerciseNodeCompanion {
  override type Tpl = transferCodegen.TransferOffer
  override type Arg = transferCodegen.TransferOffer_Accept
  override type Res = transferCodegen.TransferOffer_AcceptResult

  override val template = transferCodegen.TransferOffer.COMPANION
  override val choice = transferCodegen.TransferOffer.CHOICE_TransferOffer_Accept

  override val argDecoder = transferCodegen.TransferOffer_Accept.valueDecoder()

  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = transferCodegen.TransferOffer_AcceptResult.valueDecoder

  override def resToValue(res: Res) = res.toValue
}

case object TransferOffer_Reject extends ExerciseNodeCompanion {
  override type Tpl = transferCodegen.TransferOffer
  override type Arg = transferCodegen.TransferOffer_Reject
  override type Res = transferCodegen.TransferOffer_RejectResult

  override val template = transferCodegen.TransferOffer.COMPANION
  override val choice = transferCodegen.TransferOffer.CHOICE_TransferOffer_Reject

  override val argDecoder = transferCodegen.TransferOffer_Reject.valueDecoder()

  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = transferCodegen.TransferOffer_RejectResult.valueDecoder()
  override def resToValue(res: Res) = res.toValue
}

case object TransferOffer_Withdraw extends ExerciseNodeCompanion {
  override type Tpl = transferCodegen.TransferOffer
  override type Arg = transferCodegen.TransferOffer_Withdraw
  override type Res = transferCodegen.TransferOffer_WithdrawResult

  override val template = transferCodegen.TransferOffer.COMPANION
  override val choice = transferCodegen.TransferOffer.CHOICE_TransferOffer_Withdraw

  override val argDecoder = transferCodegen.TransferOffer_Withdraw.valueDecoder()

  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = transferCodegen.TransferOffer_WithdrawResult.valueDecoder()
  override def resToValue(res: Res) = res.toValue
}

case object TransferOffer_Expire extends ExerciseNodeCompanion {
  override type Tpl = transferCodegen.TransferOffer
  override type Arg = transferCodegen.TransferOffer_Expire
  override type Res = transferCodegen.TransferOffer_ExpireResult

  override val template = transferCodegen.TransferOffer.COMPANION
  override val choice = transferCodegen.TransferOffer.CHOICE_TransferOffer_Expire

  override val argDecoder = transferCodegen.TransferOffer_Expire.valueDecoder()

  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = transferCodegen.TransferOffer_ExpireResult.valueDecoder()
  override def resToValue(res: Res) = res.toValue
}

object AcceptedTransferOffer_Complete extends ExerciseNodeCompanion {
  override type Tpl = transferCodegen.AcceptedTransferOffer
  override type Arg = transferCodegen.AcceptedTransferOffer_Complete
  override type Res = transferCodegen.AcceptedTransferOffer_CompleteResult

  override val template = transferCodegen.AcceptedTransferOffer.COMPANION
  override val choice = transferCodegen.AcceptedTransferOffer.CHOICE_AcceptedTransferOffer_Complete

  override val argDecoder = transferCodegen.AcceptedTransferOffer_Complete.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = transferCodegen.AcceptedTransferOffer_CompleteResult.valueDecoder()
  override def resToValue(res: Res) = res.toValue
}

case object AcceptedTransferOffer_Expire extends ExerciseNodeCompanion {
  override type Tpl = transferCodegen.AcceptedTransferOffer
  override type Arg = transferCodegen.AcceptedTransferOffer_Expire
  override type Res = transferCodegen.AcceptedTransferOffer_ExpireResult

  override val template = transferCodegen.AcceptedTransferOffer.COMPANION
  override val choice = transferCodegen.AcceptedTransferOffer.CHOICE_AcceptedTransferOffer_Expire

  override val argDecoder = transferCodegen.AcceptedTransferOffer_Expire.valueDecoder()

  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = transferCodegen.AcceptedTransferOffer_ExpireResult.valueDecoder()
  override def resToValue(res: Res) = res.toValue
}

case object AcceptedTransferOffer_Abort extends ExerciseNodeCompanion {
  override type Tpl = transferCodegen.AcceptedTransferOffer
  override type Arg = transferCodegen.AcceptedTransferOffer_Abort
  override type Res = transferCodegen.TransferOfferTrackingInfo

  override val template = transferCodegen.AcceptedTransferOffer.COMPANION
  override val choice = transferCodegen.AcceptedTransferOffer.CHOICE_AcceptedTransferOffer_Abort

  override val argDecoder = transferCodegen.AcceptedTransferOffer_Abort.valueDecoder()

  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = transferCodegen.TransferOfferTrackingInfo.valueDecoder()

  override def resToValue(res: Res) = res.toValue
}

case object AcceptedTransferOffer_Withdraw extends ExerciseNodeCompanion {
  override type Tpl = transferCodegen.AcceptedTransferOffer
  override type Arg = transferCodegen.AcceptedTransferOffer_Withdraw
  override type Res = transferCodegen.AcceptedTransferOffer_WithdrawResult

  override val template = transferCodegen.AcceptedTransferOffer.COMPANION
  override val choice = transferCodegen.AcceptedTransferOffer.CHOICE_AcceptedTransferOffer_Withdraw

  override val argDecoder = transferCodegen.AcceptedTransferOffer_Withdraw.valueDecoder()

  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = transferCodegen.AcceptedTransferOffer_WithdrawResult.valueDecoder()
  override def resToValue(res: Res) = res.toValue
}

object AppPaymentRequest_Accept extends ExerciseNodeCompanion {
  override type Tpl = paymentCodegen.AppPaymentRequest
  override type Arg = paymentCodegen.AppPaymentRequest_Accept
  override type Res = paymentCodegen.AppPaymentRequest_AcceptResult

  override val template = paymentCodegen.AppPaymentRequest.COMPANION
  override val choice = paymentCodegen.AppPaymentRequest.CHOICE_AppPaymentRequest_Accept

  override val argDecoder = paymentCodegen.AppPaymentRequest_Accept.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = paymentCodegen.AppPaymentRequest_AcceptResult.valueDecoder()
  override def resToValue(res: Res) = res.toValue
}

object AcceptedAppPayment_Collect extends ExerciseNodeCompanion {
  override type Tpl = paymentCodegen.AcceptedAppPayment
  override type Arg = paymentCodegen.AcceptedAppPayment_Collect
  override type Res = paymentCodegen.AcceptedAppPayment_Collect_Result

  override val template = paymentCodegen.AcceptedAppPayment.COMPANION
  override val choice = paymentCodegen.AcceptedAppPayment.CHOICE_AcceptedAppPayment_Collect

  override val argDecoder = paymentCodegen.AcceptedAppPayment_Collect.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = paymentCodegen.AcceptedAppPayment_Collect_Result.valueDecoder()
  override def resToValue(res: Res) = res.toValue
}

object AcceptedAppPayment_Reject extends ExerciseNodeCompanion {
  override type Tpl = paymentCodegen.AcceptedAppPayment
  override type Arg = paymentCodegen.AcceptedAppPayment_Reject
  override type Res = paymentCodegen.AcceptedAppPayment_RejectResult

  override val template = paymentCodegen.AcceptedAppPayment.COMPANION
  override val choice = paymentCodegen.AcceptedAppPayment.CHOICE_AcceptedAppPayment_Reject

  override val argDecoder = paymentCodegen.AcceptedAppPayment_Reject.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = paymentCodegen.AcceptedAppPayment_RejectResult.valueDecoder()
  override def resToValue(res: Res) = res.toValue
}

object AcceptedAppPayment_Expire extends ExerciseNodeCompanion {
  override type Tpl = paymentCodegen.AcceptedAppPayment
  override type Arg = paymentCodegen.AcceptedAppPayment_Expire
  override type Res = paymentCodegen.AcceptedAppPayment_ExpireResult

  override val template = paymentCodegen.AcceptedAppPayment.COMPANION
  override val choice = paymentCodegen.AcceptedAppPayment.CHOICE_AcceptedAppPayment_Expire

  override val argDecoder = paymentCodegen.AcceptedAppPayment_Expire.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = paymentCodegen.AcceptedAppPayment_ExpireResult.valueDecoder()
  override def resToValue(res: Res) = res.toValue
}

object WalletAppInstall_CreateBuyTrafficRequest extends ExerciseNodeCompanion {
  override type Tpl = installCodegen.WalletAppInstall
  override type Arg = installCodegen.WalletAppInstall_CreateBuyTrafficRequest
  override type Res = installCodegen.WalletAppInstall_CreateBuyTrafficRequestResult

  override val template = installCodegen.WalletAppInstall.COMPANION
  override val choice =
    installCodegen.WalletAppInstall.CHOICE_WalletAppInstall_CreateBuyTrafficRequest

  override val argDecoder = installCodegen.WalletAppInstall_CreateBuyTrafficRequest.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder =
    installCodegen.WalletAppInstall_CreateBuyTrafficRequestResult.valueDecoder
  override def resToValue(res: Res) = res.toValue
}

object BuyTrafficRequest_Complete extends ExerciseNodeCompanion {
  override type Tpl = trafficRequestCodegen.BuyTrafficRequest
  override type Arg = trafficRequestCodegen.BuyTrafficRequest_Complete
  override type Res = trafficRequestCodegen.BuyTrafficRequest_CompleteResult

  override val template = trafficRequestCodegen.BuyTrafficRequest.COMPANION
  override val choice = trafficRequestCodegen.BuyTrafficRequest.CHOICE_BuyTrafficRequest_Complete

  override val argDecoder = trafficRequestCodegen.BuyTrafficRequest_Complete.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = trafficRequestCodegen.BuyTrafficRequest_CompleteResult.valueDecoder
  override def resToValue(res: Res) = res.toValue
}

case object BuyTrafficRequest_Cancel extends ExerciseNodeCompanion {
  override type Tpl = trafficRequestCodegen.BuyTrafficRequest
  override type Arg = trafficRequestCodegen.BuyTrafficRequest_Cancel
  override type Res = trafficRequestCodegen.BuyTrafficRequest_CancelResult

  override val template = trafficRequestCodegen.BuyTrafficRequest.COMPANION
  override val choice = trafficRequestCodegen.BuyTrafficRequest.CHOICE_BuyTrafficRequest_Cancel

  override val argDecoder = trafficRequestCodegen.BuyTrafficRequest_Cancel.valueDecoder()

  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = trafficRequestCodegen.BuyTrafficRequest_CancelResult.valueDecoder()
  override def resToValue(res: Res) = res.toValue
}

case object BuyTrafficRequest_Expire extends ExerciseNodeCompanion {
  override type Tpl = trafficRequestCodegen.BuyTrafficRequest
  override type Arg = trafficRequestCodegen.BuyTrafficRequest_Expire
  override type Res = trafficRequestCodegen.BuyTrafficRequest_ExpireResult

  override val template = trafficRequestCodegen.BuyTrafficRequest.COMPANION
  override val choice = trafficRequestCodegen.BuyTrafficRequest.CHOICE_BuyTrafficRequest_Expire

  override val argDecoder = trafficRequestCodegen.BuyTrafficRequest_Expire.valueDecoder()

  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = trafficRequestCodegen.BuyTrafficRequest_ExpireResult.valueDecoder()
  override def resToValue(res: Res) = res.toValue
}

object SubscriptionRequest_AcceptAndMakePayment extends ExerciseNodeCompanion {
  override type Tpl = subsCodegen.SubscriptionRequest
  override type Arg = subsCodegen.SubscriptionRequest_AcceptAndMakePayment
  override type Res = subsCodegen.SubscriptionRequest_AcceptAndMakePaymentResult

  override val template = subsCodegen.SubscriptionRequest.COMPANION
  override val choice =
    subsCodegen.SubscriptionRequest.CHOICE_SubscriptionRequest_AcceptAndMakePayment

  override val argDecoder = subsCodegen.SubscriptionRequest_AcceptAndMakePayment.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder =
    subsCodegen.SubscriptionRequest_AcceptAndMakePaymentResult.valueDecoder()
  override def resToValue(res: Res) = res.toValue
}

object SubscriptionInitialPayment_Collect extends ExerciseNodeCompanion {
  override type Tpl = subsCodegen.SubscriptionInitialPayment
  override type Arg = subsCodegen.SubscriptionInitialPayment_Collect
  override type Res = subsCodegen.SubscriptionInitialPayment_CollectResult

  override val template = subsCodegen.SubscriptionInitialPayment.COMPANION
  override val choice =
    subsCodegen.SubscriptionInitialPayment.CHOICE_SubscriptionInitialPayment_Collect

  override val argDecoder = subsCodegen.SubscriptionInitialPayment_Collect.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = subsCodegen.SubscriptionInitialPayment_CollectResult.valueDecoder()

  override def resToValue(res: Res) = res.toValue
}

object SubscriptionInitialPayment_Reject extends ExerciseNodeCompanion {
  override type Tpl = subsCodegen.SubscriptionInitialPayment
  override type Arg = subsCodegen.SubscriptionInitialPayment_Reject
  override type Res = amuletCodegen.AmuletCreateSummary[amuletCodegen.Amulet.ContractId]

  override val template = subsCodegen.SubscriptionInitialPayment.COMPANION
  override val choice =
    subsCodegen.SubscriptionInitialPayment.CHOICE_SubscriptionInitialPayment_Reject

  override val argDecoder = subsCodegen.SubscriptionInitialPayment_Reject.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder =
    amuletCodegen.AmuletCreateSummary.valueDecoder(cid =>
      new amuletCodegen.Amulet.ContractId(cid.asContractId().get().getValue)
    )
  override def resToValue(res: Res) = res.toValue(_.toValue)
}

object SubscriptionInitialPayment_Expire extends ExerciseNodeCompanion {
  override type Tpl = subsCodegen.SubscriptionInitialPayment
  override type Arg = subsCodegen.SubscriptionInitialPayment_Expire
  override type Res = amuletCodegen.AmuletCreateSummary[amuletCodegen.Amulet.ContractId]

  override val template = subsCodegen.SubscriptionInitialPayment.COMPANION
  override val choice =
    subsCodegen.SubscriptionInitialPayment.CHOICE_SubscriptionInitialPayment_Expire

  override val argDecoder = subsCodegen.SubscriptionInitialPayment_Expire.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder =
    amuletCodegen.AmuletCreateSummary.valueDecoder(cid =>
      new amuletCodegen.Amulet.ContractId(cid.asContractId().get().getValue)
    )
  override def resToValue(res: Res) = res.toValue(_.toValue)
}

object SubscriptionIdleState_MakePayment extends ExerciseNodeCompanion {
  override type Tpl = subsCodegen.SubscriptionIdleState
  override type Arg = subsCodegen.SubscriptionIdleState_MakePayment
  override type Res = subsCodegen.SubscriptionIdleState_MakePaymentResult

  override val template = subsCodegen.SubscriptionIdleState.COMPANION
  override val choice = subsCodegen.SubscriptionIdleState.CHOICE_SubscriptionIdleState_MakePayment

  override val argDecoder = subsCodegen.SubscriptionIdleState_MakePayment.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = subsCodegen.SubscriptionIdleState_MakePaymentResult.valueDecoder()
  override def resToValue(res: Res) = res.toValue
}

object SubscriptionIdleState_ExpireSubscription extends ExerciseNodeCompanion {
  override type Tpl = subsCodegen.SubscriptionIdleState
  override type Arg = subsCodegen.SubscriptionIdleState_ExpireSubscription
  override type Res = subsCodegen.SubscriptionIdleState_ExpireSubscriptionResult

  override val template = subsCodegen.SubscriptionIdleState.COMPANION
  override val choice =
    subsCodegen.SubscriptionIdleState.CHOICE_SubscriptionIdleState_ExpireSubscription

  override val argDecoder = subsCodegen.SubscriptionIdleState_ExpireSubscription.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder =
    subsCodegen.SubscriptionIdleState_ExpireSubscriptionResult.valueDecoder()
  override def resToValue(res: Res) = res.toValue
}

object SubscriptionPayment_Collect extends ExerciseNodeCompanion {
  override type Tpl = subsCodegen.SubscriptionPayment
  override type Arg = subsCodegen.SubscriptionPayment_Collect
  override type Res = subsCodegen.SubscriptionPayment_CollectResult

  override val template = subsCodegen.SubscriptionPayment.COMPANION
  override val choice = subsCodegen.SubscriptionPayment.CHOICE_SubscriptionPayment_Collect

  override val argDecoder = subsCodegen.SubscriptionPayment_Collect.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = subsCodegen.SubscriptionPayment_CollectResult.valueDecoder()

  override def resToValue(res: Res) = res.toValue
}

object SubscriptionPayment_Reject extends ExerciseNodeCompanion {
  override type Tpl = subsCodegen.SubscriptionPayment
  override type Arg = subsCodegen.SubscriptionPayment_Reject
  override type Res = subsCodegen.SubscriptionPayment_RejectResult

  override val template = subsCodegen.SubscriptionPayment.COMPANION
  override val choice = subsCodegen.SubscriptionPayment.CHOICE_SubscriptionPayment_Reject

  override val argDecoder = subsCodegen.SubscriptionPayment_Reject.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = subsCodegen.SubscriptionPayment_RejectResult.valueDecoder()

  override def resToValue(res: Res) = res.toValue
}

object SubscriptionPayment_Expire extends ExerciseNodeCompanion {
  override type Tpl = subsCodegen.SubscriptionPayment
  override type Arg = subsCodegen.SubscriptionPayment_Expire
  override type Res = subsCodegen.SubscriptionPayment_ExpireResult

  override val template = subsCodegen.SubscriptionPayment.COMPANION
  override val choice = subsCodegen.SubscriptionPayment.CHOICE_SubscriptionPayment_Expire

  override val argDecoder = subsCodegen.SubscriptionPayment_Expire.valueDecoder()
  override def argToValue(arg: Arg) = arg.toValue

  override val resDecoder = subsCodegen.SubscriptionPayment_ExpireResult.valueDecoder()

  override def resToValue(res: Res) = res.toValue
}
