name: Remind to backport PRs to release branches
on:
  pull_request:
    types: [opened, reopened]
    paths:
      - cluster/deployment/**
      - cluster/configs/**
      - '**/expected.json'

jobs:
  add-backport-reminder:
    runs-on: ubuntu-24.04
    steps:
        - uses: hyperledger-labs/splice-shared-gha/actions/backport_reminder@a3e2e3bb8f5004aa285979ee35701199d6fa97e6
          with:
            pr_number: ${{ github.event.pull_request.number }}
            lookup_prod_cluster_configs: false
