name: Backport a commit or PR across branches
on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'A commit SHA to backport (either commit_sha or pr_number must be provided)'
        required: false
        type: string
      pr_number:
        description: 'A merged PR to backport (either commit_sha or pr_number must be provided)'
        required: false
        type: number
      base_branch:
        description: 'The branch to backport to'
        required: true
        type: string
      reviewer:
        description: 'The GitHub username of a reviewer to request a review from (currently supports only one reviewer)'
        required: false
        type: string
  workflow_call:
    inputs:
      commit_sha:
        description: 'A commit SHA to backport (either commit_sha or pr_number must be provided)'
        required: false
        type: string
      pr_number:
        description: 'A merged PR to backport (either commit_sha or pr_number must be provided)'
        required: false
        type: number
      base_branch:
        description: 'The branch to backport to'
        required: true
        type: string
      reviewer:
        description: 'The GitHub username of a reviewer to request a review from (currently supports only one reviewer)'
        required: false
        type: string

jobs:
  dummy:
    runs-on: ubuntu-24.04
    steps:
      - name: Dummy step
        run: echo 'Hello, world!'
