name: Bundle
on: workflow_call

jobs:
  bundle:
    runs-on: self-hosted-k8s-small
    container:
      image: digitalasset-canton-network-docker.jfrog.io/digitalasset/splice-test-ci:0.3.6-snapshot.20250113.8012.0.v6b097acb

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_READ }}
          submodules: recursive

      - name: Setup
        id: setup
        uses: ./.github/actions/tests/common_test_setup
        with:
          test_name: bundle
          artifactory_user: ${{ vars.ARTIFACTORY_USER }}
          artifactory_password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Bundle
        uses: ./.github/actions/sbt/execute_sbt_command
        with:
          # compile tests, as well as bundle, to make sure the cache that is uploaded here is complete
          cmd: "Test/compile bundle"
          fail_on_error_in_output: false

      - name: Post-SBT job
        uses: ./.github/actions/sbt/post_sbt
        with:
          cache_version: 0
          setup_sbt_cache_hits: ${{ steps.setup.outputs.sbt_cache_hits }}
