name: Build
on: pull_request
# TODO(#15988): also on commits on main and release branches


jobs:
  static_tests:
    uses: ./.github/workflows/build.static_tests.yml
    secrets: inherit

  scala_test_sim_time:
    uses: ./.github/workflows/build.scala_test.yml
    with:
      start_canton_options: -s
    secrets: inherit
