name: Build
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - 'main'
# TODO(#15988): notify on failure when running on commits to main
# TODO(#15988): run also on commits to release branches

# Cancel previously runs of this workflow on the same branch, unless it's main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  static_tests:
    uses: ./.github/workflows/build.static_tests.yml
    secrets: inherit

  scala_test_sim_time:
    uses: ./.github/workflows/build.scala_test.yml
    with:
      # For now, the two tests that we are running here seem to work
      # just fine on the smaller runners
      runs_on: self-hosted-docker
#      runs_on: self-hosted-docker-large
      start_canton_options: -s
    secrets: inherit
