name: Build
on: pull_request
# TODO(#15988): also on commits on main and release branches


jobs:
  static_tests:
    uses: ./.github/workflows/build.static_tests.yml
    secrets: inherit

  scala_test_sim_time:
    uses: ./.github/workflows/build.scala_test.yml
    with:
      # For now, the two tests that we are running here seem to work
      # just fine on the smaller runners
      runs_on: self-hosted-docker
#      runs_on: self-hosted-docker-large
      start_canton_options: -s
    secrets: inherit
