name: Deployment Test
on: workflow_call

jobs:
  deployment_test:
    runs-on: self-hosted-k8s-x-small

    container:
      # TODO(#15988): use a snapshot after this is merged, and a release after it's in a release
      image: digitalasset-canton-network-docker-dev.jfrog.io/digitalasset/splice-test-ci:0.3.7-itai-dirty

    steps:

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_READ }}
          submodules: recursive

      - name: Setup
        uses: ./.github/actions/tests/common_test_setup
        with:
          test_name: deployment_test
          with_sbt: false
          artifactory_user: ${{ vars.ARTIFACTORY_USER }}
          artifactory_password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Deployment test
        uses: ./.github/actions/nix/run_bash_command_in_nix
        with:
          cmd_retry_count: 5 # Retry in case of dependency download errors
          cmd: make cluster/pulumi/test
