name: Docker Images Build
on: workflow_call

jobs:
  docker_images_build:
    runs-on: self-hosted-docker-medium

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_READ }}
          submodules: recursive

      - name: Setup
        id: setup
        uses: ./.github/actions/tests/common_test_setup
        with:
          test_name: docker_images_build
          artifactory_user: ${{ vars.ARTIFACTORY_USER }}
          artifactory_password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Build Docker images
        uses: ./.github/actions/nix/run_bash_command_in_nix
        with:
          cmd: |
            export ARTIFACTORY_USER="${{ vars.artifactory_user }}"
            export ARTIFACTORY_PASSWORD="${{ secrets.artifactory_password }}"
            /usr/bin/sudo mkdir -p ~/.docker/buildx
            /usr/bin/sudo /usr/bin/chown $(whoami):docker ~/.docker/buildx
            make docker-build -j
          cmd_retry_count: 5 # Retry in case of dependency download errors
          additional_nix_args: "--keep DOCKER_CERT_PATH --keep DOCKER_HOST --keep DOCKER_MACHINE_NAME --keep DOCKER_TLS_VERIFY --keep PULUMI_VERSION --keep NO_PROXY"

      - name: Post-SBT job
        uses: ./.github/actions/sbt/post_sbt
        with:
          cache_version: 1
          setup_sbt_cache_hits: ${{ steps.setup.outputs.sbt_cache_hits }}

      - name: Report Failures on Slack & Github
        if: failure() && github.event_name == 'push'
        shell: bash
        env:
          SLACK_ACCESS_TOKEN: ${{ secrets.SLACK_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_ISSUES }}
        run: ./.circleci/notification-scripts/failure_notification.py
