name: Daily store ingestion performance tests
on:
  # allow manual running on PRs that you expect might affect store performance
  workflow_dispatch:
  schedule:
    - cron: '37 3 * * 1-5' # 3:37 AM on workdays

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-perftest
  cancel-in-progress: true

permissions:
  id-token: write # Required for GCP Workload Identity for failure notifications
  contents: read

jobs:
  performance_tests:
    # note that we're loading the entirety of mainnet updates (and in the future, the ACS) so as to make sure that that's not the bottleneck.
    # as of 03.03.2026 that seems to be enough, but we might have to increase it as the activity in mainnet does too.
    runs-on: self-hosted-k8s-medium
    container:
      image: us-central1-docker.pkg.dev/da-cn-shared/ghcr/digital-asset/decentralized-canton-sync-dev/docker/splice-test-ci:0.3.12
    name: Performance Tests
    if: github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ''
          submodules: "recursive"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup
        id: setup
        uses: ./splice-shared-gha/.github/actions/tests/common_test_setup
        with:
          test_name: oss
          target: 'oss'

      - name: Run performance tests
        uses: ./splice-shared-gha/.github/actions/sbt/execute_sbt_command
        env:
          PERFORMANCE_TESTS_DB_PASSWORD: ${{ secrets.PERFORMANCE_TESTS_DB_PASSWORD }}
          PERFORMANCE_TESTS_DB_HOST: ${{ secrets.PERFORMANCE_TESTS_DB_HOST }}
          PERFORMANCE_TESTS_DB_USER: ${{ secrets.PERFORMANCE_TESTS_DB_USER }}
        with:
          additional_nix_args: "--keep PERFORMANCE_TESTS_DB_PASSWORD --keep PERFORMANCE_TESTS_DB_HOST --keep PERFORMANCE_TESTS_DB_USER"
          extra_env_vars: 'POSTGRES_HOST="$PERFORMANCE_TESTS_DB_HOST" POSTGRES_USER="$PERFORMANCE_TESTS_DB_USER" POSTGRES_PASSWORD="$PERFORMANCE_TESTS_DB_PASSWORD"'
          pre_sbt_cmd: |
            echo "Clearing database"
            PGPASSWORD="$PERFORMANCE_TESTS_DB_PASSWORD" psql \
              -h"$PERFORMANCE_TESTS_DB_HOST" \
              -U"$PERFORMANCE_TESTS_DB_USER" \
              -dcantonnet \
              -c 'DROP DATABASE IF EXISTS splice_apps' \
              -c 'CREATE DATABASE splice_apps' || (echo "Connection to DB failed" && exit 1)

            echo "Downloading updates from mainnet for performance tests"
            curl -sSL --fail-with-body "https://storage.googleapis.com/mainnet-history-dumps/mainnetupdates.json" -o /tmp/mainnetupdates.json
            ls -lah /tmp/mainnetupdates.json
          cmd: '"apps-app / Test / runMain org.lfdecentralizedtrust.splice.performance.SplicePerf run -t * -c ./apps/app/src/test/resources/performance/tests.conf -d /tmp/mainnetupdates.json"'

      - name: Push metrics to Prometheus Pushgateway
        if: ${{ always() }} #TBD
        run: |
          python3 apps/app/src/test/resources/performance/push_store_perf_metrics.py

      # sanity check
      - name: Check logs for errors
        uses: ./splice-shared-gha/.github/actions/sbt/execute_sbt_command
        with:
          # we don't care if some integration test happened to make the repo dirty
          pre_sbt_cmd: "export CI_IGNORE_DIRTY_REPO=1"
          cmd: checkErrors

      - name: Upload logs
        # if they're successful we don't care too much about the logs - but note that the ingestion are still logged
        # as part of the GHA run itself (meaning: we use println to stdout)
        if: ${{ !success() }}
        uses: ./splice-shared-gha/.github/actions/sbt/upload_logs
        with:
          name: "logs-performance-tests"

      - name: Report Failures on Slack & Github
        if: failure() && github.event_name == 'schedule'
        uses: ./splice-shared-gha/.github/actions/tests/failure_notifications
        with:
          job_subname: "Daily Store Ingestion Performance Tests"
          workload_identity_provider: "${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.FAILURE_NOTIFICATIONS_INVOKER_SA }}"
          notifications_url: '${{ secrets.FAILURE_NOTIFICATIONS_INVOKER_URL }}'
          slack_channel: '${{ secrets.FAILURE_NOTIFICATIONS_SLACK_CHANNEL }}'

