canton {
  validator-apps {
    splitwellValidatorApp {
      onboarding = {
        # our onboarding sponsor is SV1
        sv-client.admin-api.url = ${NETWORK_APPS_ADDRESS_PROTOCOL}"://sv.sv-1.svc."${NETWORK_APPS_ADDRESS}"/api/v0/sv"
        # secret must be obtained from SV1 first
        secret = "PLACEHOLDER"
      }
    }
  }
}
