canton {
  parameters.non-standard-config = yes
  domains {
    splitwellDomain {
      storage.type = memory
      public-api.port = 5108
      admin-api.port = 5109
      init.domain-parameters {
        unique-contract-keys = false
        protocol-version = dev
      }
    }
  }
}
canton.features.enable-testing-commands = yes
