canton {
  parameters {
    non-standard-config = yes
    dev-version-support = yes
    # Bumping because our topology state can get very large due to
    # a large number of participants.
    timeouts.processing.verify-active = 40.seconds
  }

  # Bumping because our topology state can get very large due to
  # a large number of participants.
  monitoring.delay-logging-threshold = 40.seconds

  participants {
    splitwellParticipant {
      storage.type = memory
      admin-api.port = 5102
      ledger-api.port = 5101
      ledger-api.explicit-disclosure-unsafe = true
      parameters {
        dev-version-support = yes
      }
      init.parameters.unique-contract-keys = false
    }
  }
}
canton.features.enable-testing-commands = yes
