canton {
  parameters {
    non-standard-config = yes
    dev-version-support = yes
  }
  domains {
    splitwellDomain {
      storage.type = memory
      public-api.port = 5708
      admin-api.port = 5709
      init.domain-parameters {
        protocol-version = dev
      }
    }
  }
}
canton.features.enable-testing-commands = yes
