_validator_participant_remote {
  admin-api.port = 5102
  ledger-api.client-config.port = 5101
  ledger-api.auth-config.type = "none"
}

_scan_remote {
  admin-api.port = 5112
  admin-api.address = ${NETWORK_APPS_ADDRESS}
  admin-api.url = ${NETWORK_APPS_ADDRESS_PROTOCOL}"://"${NETWORK_APPS_ADDRESS}":6012"
}

canton {
  splitwell-apps {
    splitwellBackend {
      admin-api.address = 0.0.0.0
      admin-api.port = 5113
      provider-user = "splitwell-service-user"
      remote-participant = ${_validator_participant_remote}
      remote-scan = ${_scan_remote}
      domains {
        global = "global"
        splitwell = "global"
        splitwell = ${?SPLITWELL_APP_DOMAIN}
      }
    }
  }
}
