_validator_participant_remote {
  admin-api.port = 5002
  ledger-api.client-config.port = 5001
  ledger-api.auth-config.type = "none"
}

_scan_remote {
  admin-api.port = 5012
  admin-api.address = ${NETWORK_APPS_ADDRESS}
  admin-api.url = ${NETWORK_APPS_ADDRESS_PROTOCOL}"://"${NETWORK_APPS_ADDRESS}":5012"
}

canton {
  splitwell-app-clients {
    aliceSplitwell {
      admin-api.address = 127.0.0.1
      admin-api.port = 5113
      remote-participant = ${_validator_participant_remote}
      remote-scan = ${_scan_remote}
      ledger-api-user = "alice"
    }
    bobSplitwell {
      admin-api.address = 127.0.0.1
      admin-api.port = 5113
      remote-participant = ${_validator_participant_remote}
      remote-scan = ${_scan_remote}
      ledger-api-user = "bob"
    }
  }
  features.enable-testing-commands = yes
}
