### Directory App

server {
    listen       5010;
    server_name  localhost;

    location / {
       resolver kube-dns.kube-system.svc.cluster.local;
       proxy_pass http://directory-app.svc.svc.cluster.local:5010;
    }
}

server {
    listen       80;
    listen  [::]:80;

    server_name  directory.*;

    location / {
        resolver kube-dns.kube-system.svc.cluster.local;
        proxy_pass http://directory-app.svc.svc.cluster.local:5010;
    }
}
