### Directory App

server {
    listen       80;
    listen  [::]:80;

    server_name  directory.sv-1.svc.*;

    location ~ ^/(api/v0/directory/)(.*)  {
        resolver kube-dns.kube-system.svc.cluster.local;
        proxy_http_version 1.1;
        proxy_pass http://directory-app.sv-1.svc.cluster.local:5010/$2$is_args$args;
    }

}
