### Canton Domain

server {
    listen       5008 http2;
    server_name  localhost;

    location / {
       resolver kube-dns.kube-system.svc.cluster.local;
       grpc_pass grpc://global-domain.sv-1.svc.cluster.local:5008;
    }
}

server {
    listen       5009 http2;
    server_name  localhost;

    location / {
       resolver kube-dns.kube-system.svc.cluster.local;
       grpc_pass grpc://global-domain.sv-1.svc.cluster.local:5009;
    }
}

server {
    listen       10313;
    server_name  localhost;

    location / {
       resolver kube-dns.kube-system.svc.cluster.local;
       proxy_http_version 1.1;
       proxy_pass http://global-domain.sv-1.svc.cluster.local:10013;
    }
}
