### Scan App

server {
    listen       5012;
    server_name  localhost;

    location / {
       resolver kube-dns.kube-system.svc.cluster.local;
       proxy_http_version 1.1;
       proxy_pass http://scan-app.svc.svc.cluster.local:5012;
    }
}

server {
    listen       80;
    listen  [::]:80;

    server_name  scan.*;

    location ~ ^/(api/)(.*) {
        resolver kube-dns.kube-system.svc.cluster.local;
        proxy_http_version 1.1;
        proxy_pass http://scan-app.svc.svc.cluster.local:5012/api/$2$is_args$args;
    }

    location / {
        resolver kube-dns.kube-system.svc.cluster.local;
        proxy_http_version 1.1;
        proxy_pass http://scan-web-ui.svc.svc.cluster.local/;
    }
}
