#### SV 2

server {
    listen       5114;
    server_name  localhost;

    location / {
       resolver kube-dns.kube-system.svc.cluster.local;
       proxy_pass http://sv-app.sv-2.svc.cluster.local:5114;
    }
}
