#### SV 4

server {
    listen       5314;
    server_name  localhost;

    location / {
       resolver kube-dns.kube-system.svc.cluster.local;
       proxy_pass http://sv-app.sv-4.svc.cluster.local:5314;
    }
}
