### Wallet Web UI @ SV2

server {
    listen       80;
    listen  [::]:80;

    server_name  wallet.sv-2.svc.*;

    location ~ ^/(api/v0/validator/)(.*) {
       resolver kube-dns.kube-system.svc.cluster.local;
       proxy_http_version 1.1;
       proxy_pass http://validator-app.sv-2.svc.cluster.local:5003/$2$is_args$args;
    }

    location / {
        resolver kube-dns.kube-system.svc.cluster.local;
        proxy_http_version 1.1;
        proxy_pass http://wallet-web-ui.sv-2.svc.cluster.local;
    }
}
