### Directory Web UI @ SV4

server {
    listen       80;
    listen  [::]:80;

    server_name  directory.sv-4.svc.*;

    location ~ ^/(api/json-api/)(.*) {
       resolver kube-dns.kube-system.svc.cluster.local;
       proxy_http_version 1.1;
       proxy_pass http://participant.sv-4.svc.cluster.local:7575/$2$is_args$args;
    }

    location / {
        resolver kube-dns.kube-system.svc.cluster.local;
        proxy_http_version 1.1;
        proxy_pass http://directory-web-ui.sv-4.svc.cluster.local;
    }
}
