### SVC App

server {
    listen       5005 http2;
    server_name  localhost;

    location / {
       resolver kube-dns.kube-system.svc.cluster.local;
       grpc_pass grpc://svc-app.sv-1.svc.cluster.local:5005;
    }
}
