### Canton Participant

server {
    listen       5002 http2;
    server_name  localhost;

    location / {
       resolver kube-dns.kube-system.svc.cluster.local;
       grpc_pass grpc://participant.svc.svc.cluster.local:5002;
    }
}

server {
    listen       5001 http2;
    server_name  localhost;

    location / {
       resolver kube-dns.kube-system.svc.cluster.local;
       grpc_pass grpc://participant.svc.svc.cluster.local:5001;
    }
}

server {
    listen       10013;
    server_name  localhost;

    location / {
       resolver kube-dns.kube-system.svc.cluster.local;
       proxy_http_version 1.1;
       proxy_pass http://participant.svc.svc.cluster.local:10013;
    }
}
